### PR TITLE
Minor changes in tests

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/142)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/142)* status: 1 of 8 files reviewed, 3 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 286 at r1](https://reviewable.io/reviews/pmem/pmemstream/142#-MxdAHQw62G5_TofZ-6p:-MxdAHQw62G5_TofZ-6q:b-nsqcu9) ([raw file](https://github.com/pmem/pmemstream/blob/d3a1c6b85f116229ef9dd7a828d6bdc53ae3f243/src/libpmemstream.c#L286)):*
> ```C
> 		       struct pmemstream_entry reserved_entry)
> {
> ```

redundant empty line
___
*[src/libpmemstream.c, line 295 at r1](https://reviewable.io/reviews/pmem/pmemstream/142#-Mxd9msk5RdWdDIj9mYa:-Mxd9msk5RdWdDIj9mYb:b-2j7pgm) ([raw file](https://github.com/pmem/pmemstream/blob/d3a1c6b85f116229ef9dd7a828d6bdc53ae3f243/src/libpmemstream.c#L295)):*
> ```C
> 
> 	size_t popcount = 0;
> 	if (data != NULL) {
> ```

perhaps this check should be done inside of the `util_popcount_memory` function...?
___
*[tests/api_c/append_entry.c, line 20 at r1](https://reviewable.io/reviews/pmem/pmemstream/142#-MxfP3-v8c-PG0fhdPwg:-MxfP3-w7lh49iEM2a2a:b-n4jypq) ([raw file](https://github.com/pmem/pmemstream/blob/d3a1c6b85f116229ef9dd7a828d6bdc53ae3f243/tests/api_c/append_entry.c#L20)):*
> ```C
> void valid_input_test(char *path)
> {
> 	pmemstream_test_env env = pmemstream_test_default_prepare(path);
> ```

I'm not sure if I like the name of this helper :wink: perhaps just `prepare_default_pmemstream` or `pmemstream_test_default` or `pmemstream_test_make_default`

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 8 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/142#-:-MxmesNaAMW1OhFPWVXi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

___
*[tests/api_c/append_entry.c, line 20 at r1](https://reviewable.io/reviews/pmem/pmemstream/142#-MxfP3-v8c-PG0fhdPwg:-MxmbcUU3HE5F1CYaGDq:bb7p5eq) ([raw file](https://github.com/pmem/pmemstream/blob/d3a1c6b85f116229ef9dd7a828d6bdc53ae3f243/tests/api_c/append_entry.c#L20)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx!

**Review by KFilipek — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 6 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/142)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by KFilipek — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/142#-:-MxnJb9IBeLtsBy7wiYu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/142)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
