### PR TITLE
Refactor timestamp-based persistency

### PR DESCRIPTION
**Pull request by igchor**
- expose persisted/committed timestamps
- allow issuing multiple concurrent operations from a single thread

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/201)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 11 of 22 files at r1, 1 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/201)* status: 13 of 25 files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[`src/libpmemstream.c` line 121 at r1](https://reviewable.io/reviews/pmem/pmemstream/201#-N3OHN2eBrP-u5kD8dCf:-N3OHN2f4MfP1EJNUbcv:b1j2s8t) ([raw file](https://github.com/pmem/pmemstream/blob/247c912deeb9227a4116cdf4deadab0e275928a3/src/libpmemstream.c#L121)):*
> ```C
> 			stream->data.flush(&span_region->max_valid_timestamp, sizeof(span_region->max_valid_timestamp));
> 		} else {
> 			/* If max_valid_timestamp is equal to a valid timestamp, this means that this regions
> ```

these regions
___
*[`src/libpmemstream.c` line 40 at r5](https://reviewable.io/reviews/pmem/pmemstream/201#-N3QMfIbEJIRkM6OHnLP:-N3QMfIc3S49pfUriNye:b-2klv73) ([raw file](https://github.com/pmem/pmemstream/blob/7df9ce1f0230f02df053878f31a6955fdc9a09a9/src/libpmemstream.c#L40)):*
> ```C
> 	stream->header->stream_size = stream->stream_size;
> 	stream->header->block_size = stream->block_size;
> 	stream->header->persisted_timestamp = 0;
> ```

`PMEMSTREAM_INVALID_TIMESTAMP`
___
*[`src/mpmc_queue.h` line 0 at r5](https://reviewable.io/reviews/pmem/pmemstream/201#-N3QPDbU-TjcEQfrh0nU:-N3QPDbV3363WdySZOYn:b-sosn2j) ([raw file](https://github.com/pmem/pmemstream/blob/7df9ce1f0230f02df053878f31a6955fdc9a09a9/src/mpmc_queue.h#L0)):*
mpmc_queue.c should also be gone

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 6 of 22 files at r1, 2 of 5 files at r4, 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/201)* status: 22 of 25 files reviewed, 14 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/201#-N3UmHyXDEXDwadkAzRB:-N3UmHyXDEXDwadkAzRC:bye6sp6) (no related file):*
I guess you can rebase with the latest master changes :wink: 

___
___
*[`examples/04_basic_async/main.cpp` line 110 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3UhP-R-ZkqtXDGs2JH:-N3UhP-R-ZkqtXDGs2JI:bpzkdji) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/examples/04_basic_async/main.cpp#L110)):*
> ```cpp
> 	}
> 
> 	/* Now, wait until all appends complete. */
> ```

you can add some more explanation here, e.g. `... complete. Wait for the last entry to be persisted - it implies waiting on all previous entries (with lower timestamps).`
___
*[`examples/04_basic_async/main.cpp` line 111 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3Ui73IDTCf7d5cu3VF:-N3Ui73J3zs_-NQgRU3r:b39eld1) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/examples/04_basic_async/main.cpp#L111)):*
> ```cpp
> 
> 	/* Now, wait until all appends complete. */
> 	// XXX: get proper timestamp from async_append (refactor API)
> ```

maybe it's not the best idea to put XXX in the middle of an example :wink: 
___
*[`examples/04_basic_async/main.cpp` line 117 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3UiDIC-J3gg1Fi4tnh:-N3UiDIC-J3gg1Fi4tni:bb7f4eo) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/examples/04_basic_async/main.cpp#L117)):*
> ```cpp
> 	uint64_t committed_timestamp = pmemstream_committed_timestamp(stream);
> 	uint64_t persisted_timestamp = pmemstream_persisted_timestamp(stream);
> 	printf("Timestamp commited: %lu, timestamp persisted: %lu\n", committed_timestamp, persisted_timestamp);
> ```

perhaps add "before" here... or just make this loop a `do...while`
___
*[`examples/04_basic_async/main.cpp` line 132 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3UiX2L8SMkNOtUU1rP:-N3UiX2L8SMkNOtUU1rQ:b-c2mxdw) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/examples/04_basic_async/main.cpp#L132)):*
> ```cpp
> 	committed_timestamp = pmemstream_committed_timestamp(stream);
> 	persisted_timestamp = pmemstream_persisted_timestamp(stream);
> 	printf("Timestamp commited: %lu, timestamp persisted: %lu\n", committed_timestamp, persisted_timestamp);
> ```

\+ "After"
___
*[`src/libpmemstream.c` line 448 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3U_M4cDf_b-0UNfiew:-N3U_M4cDf_b-0UNfiex:b-xquqkf) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/src/libpmemstream.c#L448)):*
> ```C
> 	while (sem_trywait(&stream->async_ops_semaphore) != 0) {
> 		struct pmemstream_async_wait_fut future =
> 			pmemstream_async_wait_committed(stream, pmemstream_committed_timestamp(stream) + 1);
> ```

why `+ 1`? could we potentially wait for something that does not exist yet (meaning, we've got to this function, when everything is already committed) ?
___
*[`src/libpmemstream.c` line 662 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3UaP7p9cw5IO2yo1Y1:-N3UaP7p9cw5IO2yo1Y2:b2ts7q9) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/src/libpmemstream.c#L662)):*
> ```C
> 	assert(data->timestamp < __atomic_load_n(&data->stream->next_timestamp, __ATOMIC_RELAXED));
> 
> 	bool future_complete = false;
> ```

you can move this variable two "ifs" below, where it's needed
___
*[`src/libpmemstream.c` line 713 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3UdZE7AxVRmKZ2AJHP:-N3UdZE7AxVRmKZ2AJHQ:b-o44mc) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/src/libpmemstream.c#L713)):*
> ```C
> 	}
> 
> 	__atomic_store_n(&data->stream->header->persisted_timestamp, data->timestamp, __ATOMIC_RELEASE);
> ```

I'm not sure how we ended up here, while a moment ago we waited only for committed...?
___
*[`src/include/libpmemstream.h` line 113 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3UfzXwDmDWl9i4KNe1:-N3UfzXwDmDWl9i4KNe2:b-cctov) ([raw file](https://github.com/pmem/pmemstream/blob/c3d54a09834b6e40e70764fa608b676f74e0e815/src/include/libpmemstream.h#L113)):*
> ```objc
>  *
>  * *data has to hold the same data as they were written by user (e.g. in custom memcpy).
>  * size of the entry have to match the previous reservation and the actual size of the data written by user. */
> ```

why did you remove this line with `size` description?
___
*[`tests/common/stream_helpers.hpp` line 138 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3UkENK7e-JdI9bjkfx:-N3UkENK7e-JdI9bjkfy:bs2jm8o) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/tests/common/stream_helpers.hpp#L138)):*
> ```cpp
> 		    pmemstream_region_runtime *region_runtime = nullptr)
> 	{
> 		// XXX: remove data, size from API
> ```

perhaps move this XXX into libpmemstream.h/.c ?
___
*[`tests/common/stream_helpers.hpp` line 145 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3UkLPPAvrDAU6FiocL:-N3UkLPPAvrDAU6FiocM:b3kqx) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/tests/common/stream_helpers.hpp#L145)):*
> ```cpp
> 			   struct pmemstream_entry reserved_entry, pmemstream_region_runtime *region_runtime = nullptr)
> 	{
> 		// XXX: remove data, size from API
> ```

.
___
*[`tests/common/stream_helpers.hpp` line 463 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3Ula6m3xFNBF78JlJX:-N3Ula6m3xFNBF78JlJY:b-dze062) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/tests/common/stream_helpers.hpp#L463)):*
> ```cpp
> 			UT_ASSERT(stream.entry_timestamp(entry) <= stream.committed_timestamp());
> 
> 			if (persisted && stream.entry_timestamp(entry) > stream.persisted_timestamp())
> ```

if this entry is not persisted yet, and we require it to be persisted we move to the next entry...? what if this is the last entry?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/201)* status: 22 of 25 files reviewed, 14 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[`src/libpmemstream.c` line 448 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3U_M4cDf_b-0UNfiew:-N3YTOWm80ja5A4hQMYN:b-2u03zj) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/src/libpmemstream.c#L448)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why `+ 1`? could we potentially wait for something that does not exist yet (meaning, we've got to this function, when everything is already committed) ?
</blockquote></details>

We can add such support but right now it will not work I belive.

In this case pmemstream_committed_timestamp() + 1 is a valid offset to wait for (because try_wait failed, it means that there are at least 1024 in-progress timestamps which we can wait on).
___
*[`src/libpmemstream.c` line 713 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3UdZE7AxVRmKZ2AJHP:-N3YTcxc8cAgFpbAf0hB:b-jw7eyv) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/src/libpmemstream.c#L713)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure how we ended up here, while a moment ago we waited only for committed...?
</blockquote></details>

Right now, "persist" future only sets persisted timestamp since the data is already persisted by the append itself. We might experiment with different options in future (e.g. actually persisting data here)/
___
*[`tests/common/stream_helpers.hpp` line 463 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3Ula6m3xFNBF78JlJX:-N3YTr3V91Z8ootztw98:b-6ga0qt) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/tests/common/stream_helpers.hpp#L463)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if this entry is not persisted yet, and we require it to be persisted we move to the next entry...? what if this is the last entry?
</blockquote></details>

I don't understand the question.

The flag specifies if you want to only see persisted entries. If so, and we encounter entry which is not persisted yet (it's timestamp is > persisted_timestamp) we stop iteration.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/201)* status: 20 of 26 files reviewed, 12 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[`src/libpmemstream.c` line 40 at r5](https://reviewable.io/reviews/pmem/pmemstream/201#-N3QMfIbEJIRkM6OHnLP:-N3Yd6IcAJ5yaIOgIWu8:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7df9ce1f0230f02df053878f31a6955fdc9a09a9/src/libpmemstream.c#L40)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`PMEMSTREAM_INVALID_TIMESTAMP`
</blockquote></details>

Done.
___
*[`src/libpmemstream.c` line 662 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3UaP7p9cw5IO2yo1Y1:-N3YdEMx1KtBKrVe5y8B:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/src/libpmemstream.c#L662)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can move this variable two "ifs" below, where it's needed
</blockquote></details>

Done.
___
*[`src/mpmc_queue.h` line  at r5](https://reviewable.io/reviews/pmem/pmemstream/201#-N3QPDbU-TjcEQfrh0nU:-N3Ydb0y1a3zE6BnAxe9:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7df9ce1f0230f02df053878f31a6955fdc9a09a9/src/mpmc_queue.h#L)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

mpmc_queue.c should also be gone
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/201)* status: 20 of 28 files reviewed, 14 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[`tests/unittest/concurrent_async_wait.cpp` line 61 at r10](https://reviewable.io/reviews/pmem/pmemstream/201#-N3_5IrjDWqawUODQjjr:-N3cdxZQ4NwsstZJFNnE:bghzlqj) ([raw file](https://github.com/pmem/pmemstream/blob/3fdbc4a7293fa37c173f88cc8da835d476502389/tests/unittest/concurrent_async_wait.cpp#L61)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I think it's not correct.
`all_extra_data.end()` will be invalidated when reallocation occur.

From: https://en.cppreference.com/w/cpp/container/vector/insert
Causes reallocation if the new size() is greater than the old capacity(). If the new size() is greater than capacity(), all iterators and references are invalidated. Otherwise, only the iterators and references before the insertion point remain valid. ***The past-the-end iterator is also invalidated.***

reserve() should do the job.

</blockquote></details>

Yes, they are invalidaded, but we are not using the iterator after invalidation, we create a new one. This is the as here: https://stackoverflow.com/questions/3177241/what-is-the-best-way-to-concatenate-two-vectors

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/201)* status: 19 of 28 files reviewed, 14 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`examples/04_basic_async/main.cpp` line 110 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3UhP-R-ZkqtXDGs2JH:-N3dDf5fCF7xp9mB34S0:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/examples/04_basic_async/main.cpp#L110)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can add some more explanation here, e.g. `... complete. Wait for the last entry to be persisted - it implies waiting on all previous entries (with lower timestamps).`
</blockquote></details>

Done.
___
*[`examples/04_basic_async/main.cpp` line 111 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3Ui73IDTCf7d5cu3VF:-N3dDqyb9r5ZAN7rzv-g:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/examples/04_basic_async/main.cpp#L111)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe it's not the best idea to put XXX in the middle of an example :wink: 
</blockquote></details>

Done.
___
*[`examples/04_basic_async/main.cpp` line 117 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3UiDIC-J3gg1Fi4tnh:-N3dE41D8zh2ti7a-WtT:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/examples/04_basic_async/main.cpp#L117)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps add "before" here... or just make this loop a `do...while`
</blockquote></details>

Done.
___
*[`examples/04_basic_async/main.cpp` line 132 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3UiX2L8SMkNOtUU1rP:-N3dE4O0DFDdhfsiMpb6:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/examples/04_basic_async/main.cpp#L132)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

\+ "After"
</blockquote></details>

Done.
___
*[`src/libpmemstream.c` line 121 at r1](https://reviewable.io/reviews/pmem/pmemstream/201#-N3OHN2eBrP-u5kD8dCf:-N3dE8IGDTV5kYaHqALd:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/247c912deeb9227a4116cdf4deadab0e275928a3/src/libpmemstream.c#L121)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

these regions
</blockquote></details>

Done.
___
*[`src/include/libpmemstream.h` line 113 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3UfzXwDmDWl9i4KNe1:-N3dERhy-1uctrI-pIw4:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c3d54a09834b6e40e70764fa608b676f74e0e815/src/include/libpmemstream.h#L113)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why did you remove this line with `size` description?
</blockquote></details>

Done.



_Code quote:_
```objc
size of the entry have to match the previous reservation and the actual size of the data written by user
```
___
*[`tests/common/stream_helpers.hpp` line 138 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3UkENK7e-JdI9bjkfx:-N3dEWFF-jE3rXhDMJHO:bkt37li) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/tests/common/stream_helpers.hpp#L138)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps move this XXX into libpmemstream.h/.c ?
</blockquote></details>

This is already removed from the API
___
*[`tests/common/stream_helpers.hpp` line 145 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3UkLPPAvrDAU6FiocL:-N3dE_W3DwXw5CdXKbLa:b3kqx) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/tests/common/stream_helpers.hpp#L145)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[`tests/common/stream_helpers.hpp` line 463 at r6](https://reviewable.io/reviews/pmem/pmemstream/201#-N3Ula6m3xFNBF78JlJX:-N3dEeUJABKGNx1AVo6i:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/df602f996508adcfddf2160f63089238e951f561/tests/common/stream_helpers.hpp#L463)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

yeah, ok, I wanted to write also... `if these are just persisted entries, then perhaps rename this variable to 'persisted_only' :D` that would answer my problem :wink: 
</blockquote></details>

Done.
___
*[`tests/unittest/concurrent_async_wait.cpp` line 59 at r10](https://reviewable.io/reviews/pmem/pmemstream/201#-N3_7lHX1oDQb90pJxy5:-N3dEr1B2oVjDSCVXl6C:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/3fdbc4a7293fa37c173f88cc8da835d476502389/tests/unittest/concurrent_async_wait.cpp#L59)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

add this line after:
`all_extra_data.reserve(concurrency * extra_data.size() + 1);`
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 4 files at r7, 1 of 3 files at r11, 15 of 15 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/201)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[`src/libpmemstream.c` line 289 at r12](https://reviewable.io/reviews/pmem/pmemstream/201#-N3xkJZA10U7VY_8gZow:-N3xkJZA10U7VY_8gZox:b-ttznhv) ([raw file](https://github.com/pmem/pmemstream/blob/816ef3449d04a668c503ff1b14c7700aed4e3f8e/src/libpmemstream.c#L289)):*
> ```C
> uint64_t pmemstream_persisted_timestamp(struct pmemstream *stream)
> {
> 	/* Make sure that persisted_timestamp is actually persisted before retuning. */
> ```

returning

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/201)* status: all files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`src/libpmemstream.c` line 289 at r12](https://reviewable.io/reviews/pmem/pmemstream/201#-N3xkJZA10U7VY_8gZow:-N3zAs-b0ib8BzdWTqhq:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/816ef3449d04a668c503ff1b14c7700aed4e3f8e/src/libpmemstream.c#L289)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

returning
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 8 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/201#-:-N3zQf3GAxqSZq04e0jx:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

**Pull request merged**
