### PR TITLE
Updates related to region runtime and timestamps

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
Mostly a fixes after #183.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/191)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 14 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/191)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/pmem/pmemstream/191#-N2upYRz1rMpH2r0aaXt):*
typo



_Code quote:_
```
introducded
```
___
*[`src/region.c` line 342 at r1](https://reviewable.io/reviews/pmem/pmemstream/191#-N2qyCn5-5zJpYaQ5Lgz:-N2uqJr63N3Xe_eKFgwo:blw2km6) ([raw file](https://github.com/pmem/pmemstream/blob/f66c063e5d583186e4c167ab90c79bf80f2b8bf4/src/region.c#L342)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

yeah, I know I was thinking about removing this... but this way we have it explicitly said it's a case of invalid_entry, so I left it to "comment" the code :)
</blockquote></details>

+1 for Igor: When you have a few ways to exit the function, you explicitly know when it exits.
This is the reason why we wrote:
```cpp
if (!it)
    return -1;
```
instead of:
```cpp
if (!it)
    goto invalid_iterator;
```

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/191)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @igchor and @KFilipek)

___
*[`src/region.c` line 342 at r1](https://reviewable.io/reviews/pmem/pmemstream/191#-N2qyCn5-5zJpYaQ5Lgz:-N2uvw22BZ425xZza33U:b-rc7v0z) ([raw file](https://github.com/pmem/pmemstream/blob/f66c063e5d583186e4c167ab90c79bf80f2b8bf4/src/region.c#L342)):*
> This is the reason why we wrote:

heh, I don't recall a strict rule about it :wink: 

Done.

**Review by karczex — CHANGES_REQUESTED** [review]
> Reviewed 7 of 14 files at r1, 2 of 5 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/191)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`-- commits` line 3 at r4](https://reviewable.io/reviews/pmem/pmemstream/191#-N2vGt27B2bJQ5BCz9DD):*
Please elaborate, why this test is not needed any more.
___
*[`src/region.c` line 5 at r4](https://reviewable.io/reviews/pmem/pmemstream/191#-N2vF7mQ51WkBc_An_nB:-N2vF7mQ51WkBc_An_nC:b-nsqcu9) ([raw file](https://github.com/pmem/pmemstream/blob/839a533b941402ab616f568a7ec2c6d168c751cd/src/region.c#L5)):*
> ```C
> 
> #include "region.h"
> ```

redundant empty line

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/191#-:-N2vYWhMEZvDvyTNsEe7:bnfp4nl)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
