### PR TITLE
Refactor id_manager test to use stateful testing

### PR DESCRIPTION
**Pull request by igchor**
Along with https://github.com/pmem/pmemstream/pull/131
fixes: https://github.com/pmem/pmemstream/issues/92

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/133)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/133#-:-MwakUR87hmsiwNt0_AI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/133)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[tests/unittest/id_manager.cpp, line 38 at r1](https://reviewable.io/reviews/pmem/pmemstream/133#-MxFaUUe8gWOFCJKMpxc:-MxJoDFf79rWud21jjfg:b32v57) ([raw file](https://github.com/pmem/pmemstream/blob/01dc9b01ce2bc31d08a90ee660de43c3edf4fc23/tests/unittest/id_manager.cpp#L38)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It's good for compiler, but totally unreadable ;) 

Maybe give this type some name
```
using id_manager_unique_ptr = decltype(make_id_manager());

id_manager_uniqe_ptr sut;
```


</blockquote></details>

+1

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/133)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[tests/unittest/id_manager.cpp, line 38 at r1](https://reviewable.io/reviews/pmem/pmemstream/133#-MxFaUUe8gWOFCJKMpxc:-MyHdc4JC6QnXke7FJgJ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/01dc9b01ce2bc31d08a90ee660de43c3edf4fc23/tests/unittest/id_manager.cpp#L38)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/133#-:-MyHeNdM1RlK-AJkWX-Q:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @KFilipek and @lukaszstolarczuk)

**Review by lukaszstolarczuk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/133)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
