### PR TITLE
Refactor region iterators

### PR DESCRIPTION
**Pull request by KFilipek**
- [x] initial refactor of region API - next/get/is_valid with test (`ctest --progress -R "region_iterator"`)
- [x] fix all tests
- [x] fix all examples

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/186)

### CODE REVIEW

**Review by igchor — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/186)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[`src/iterator.c` line 81 at r2](https://reviewable.io/reviews/pmem/pmemstream/186#-N2B3Ah7Bgk9lMxK422P:-N2B3Ah7Bgk9lMxK422Q:b-6glbvo) ([raw file](https://github.com/pmem/pmemstream/blob/37a79f7562b47d16e6ad06720b92cebb072b2a4f/src/iterator.c#L81)):*
> ```C
> 
> 	it->region.offset = next_offset;
> 	it->prev_region.offset = SLIST_INVALID_OFFSET;
> ```

1. Where is this prev_region actually used?
2. How will you guarantee that the prev_region points to a valid region? There is nothing preventing user from freeing the prev_region.
___
*[`src/include/libpmemstream.h` line 156 at r2](https://reviewable.io/reviews/pmem/pmemstream/186#-N2B2TE95mL3xFeewdvF:-N2B2TE95mL3xFeewdvG:b-qop4ok) ([raw file](https://github.com/pmem/pmemstream/blob/37a79f7562b47d16e6ad06720b92cebb072b2a4f/src/include/libpmemstream.h#L156)):*
> ```objc
> int pmemstream_region_iterator_is_valid(struct pmemstream_region_iterator *iterator);
> 
> int pmemstream_region_iterator_seek_first(struct pmemstream_region_iterator *iterator);
> ```

Please follow the signature from the design: https://github.com/pmem/pmemstream/issues/182

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/186)* status: 1 of 11 files reviewed, 5 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[`src/iterator.c` line 29 at r3](https://reviewable.io/reviews/pmem/pmemstream/186#-N2jg9MR1RL6AnAt6dPi:-N2jg9MR1RL6AnAt6dPj:b-rvnhph) ([raw file](https://github.com/pmem/pmemstream/blob/b634db07eb3d0cd22867b39b0f2936d4640446ff/src/iterator.c#L29)):*
> ```C
> 	iter->region.offset = SLIST_INVALID_OFFSET;
> 	*iterator = iter;
> ```

can we/should we call `seek_first` here within `_new`? as of right now we don't have any other option to start with iteration
___
*[`src/iterator.c` line 49 at r3](https://reviewable.io/reviews/pmem/pmemstream/186#-N2jf_N4BdGzhB8YoHfM:-N2jf_N4BdGzhB8YoHfN:b7kqafc) ([raw file](https://github.com/pmem/pmemstream/blob/b634db07eb3d0cd22867b39b0f2936d4640446ff/src/iterator.c#L49)):*
> ```C
> {
> 	iterator->region.offset = iterator->stream->header->region_allocator_header.allocated_list.head;
> }
> ```

maybe we could return an error code when the list was empty; this way we wouldn't have to call `_is_valid` after each `seek_first`
___
*[`tests/common/stream_helpers.hpp` line 338 at r3](https://reviewable.io/reviews/pmem/pmemstream/186#-N2jf-8xBuqJNvzBc2U8:-N2jf-8xBuqJNvzBc2U9:b9u2kuq) ([raw file](https://github.com/pmem/pmemstream/blob/b634db07eb3d0cd22867b39b0f2936d4640446ff/tests/common/stream_helpers.hpp#L338)):*
> ```cpp
> 		
> 		pmemstream_region_iterator_seek_first(riter.get());
> 		int ret = pmemstream_region_iterator_is_valid(riter.get());
> ```

you don't have to call `_is_valid` right before `_get` - it's called within `_get`

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 7 of 11 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/186)* status: 9 of 13 files reviewed, 14 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[`examples/02_visual_iterator/main.cpp` line 79 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pMDlSCAyC_dt1wT85:-N2pMDlSCAyC_dt1wT86:bfch6y9) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/examples/02_visual_iterator/main.cpp#L79)):*
> ```cpp
> 		struct pmemstream_entry entry;
> 		struct pmemstream_entry_iterator *eiter;
> 		ret = pmemstream_entry_iterator_new(&eiter, stream, region);
> ```

you never call next & get, so this `region` is not updated in the loop
___
*[`src/libpmemstream.c` line 115 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2p_7_24GJUYmJqOU85:-N2p_7_24GJUYmJqOU86:b3w4f7w) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/src/libpmemstream.c#L115)):*
> ```C
> 	while (pmemstream_region_iterator_is_valid(iterator) == 0) {
> 		struct span_region *span_region =
> 			(struct span_region *)span_offset_to_span_ptr(&stream->data, region.offset);
> ```

you never call get, so this region is not updated within the loop
___
*[`src/libpmemstream.map` line 21 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pNKL02D39RuhKaK4t:-N2pNKL02D39RuhKaK4u:bhfaaca) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/src/libpmemstream.map#L21)):*
> ```
> 		pmemstream_region_iterator_seek_first;
> 		pmemstream_region_iterator_next;
> 		pmemstream_region_iterator_get;
> ```

pls sort A-Z
___
*[`src/include/libpmemstream.h` line 148 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pNT0xEsKjeR2AWsM8:-N2pNT0y0dm9fogtLk9f:b-7ek9x) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/src/include/libpmemstream.h#L148)):*
> ```objc
> size_t pmemstream_entry_length(struct pmemstream *stream, struct pmemstream_entry entry);
> 
> int pmemstream_region_iterator_new(struct pmemstream_region_iterator **iterator, struct pmemstream *stream);
> ```

pls describe these methods here a little (e.g. to inform that a new iterator is now invalid, when created)
___
*[`tests/api_c/region_iterator.c` line 92 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pNtnI8AqRaWXqqhpF:-N2pNtnI8AqRaWXqqhpG:b9cpzcs) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/tests/api_c/region_iterator.c#L92)):*
> ```C
> 	ret = pmemstream_region_iterator_is_valid(NULL);
> 	UT_ASSERTeq(ret, -1);
> ```

we should check NULL in other (new) iter functions, as well
___
*[`tests/api_c/region_iterator.c` line 113 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pO4H-DYsBGZtwClDs:-N2pO4H-DYsBGZtwClDt:b-3n77vm) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/tests/api_c/region_iterator.c#L113)):*
> ```C
> 	invalid_region = pmemstream_region_iterator_get(riter);
> 	UT_ASSERTeq(invalid_region.offset, SLIST_INVALID_OFFSET);
> ```

we could also validate call `next` here
___
*[`tests/common/stream_helpers.hpp` line 368 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pOqpUA_KA3C-wC0Ek:-N2pOqpUA_KA3C-wC0El:b-gmzfkf) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/tests/common/stream_helpers.hpp#L368)):*
> ```cpp
> 			// int ret = pmemstream_region_iterator_get(riter.get(), &region);
> 			region = pmemstream_region_iterator_get(riter.get());
> 			if (region.offset == UINT64_MAX)
> ```

you can break on `is_valid != 0`
___
*[`tests/common/stream_helpers.hpp` line 433 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pPhMb5U0GgusGy_xe:-N2pPhMb5U0GgusGy_xf:bnbxp9q) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/tests/common/stream_helpers.hpp#L433)):*
> ```cpp
> 		struct pmemstream_region region = pmemstream_region_iterator_get(riter.get());
> 		while (region.offset != offset) {
> 			region = pmemstream_region_iterator_get(riter.get());
> ```

you can call `is_valid` here, to ensure (as it was previously) that each region is a valid one
___
*[`tests/unittest/create.cpp` line 80 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2p__jiCLqCq4lOM1cc:-N2p__jiCLqCq4lOM1cd:b-z4k6g9) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/tests/unittest/create.cpp#L80)):*
> ```cpp
> 				UT_ASSERTeq(ret, 0);
> 				struct pmemstream_region r;
> 				r = pmemstream_region_iterator_get(riter.get());
> ```

you can merge these 2 lines above `struct region r = ...`
___
*[`tests/unittest/create.cpp` line 81 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2p_UWOEQzqBPAmw9Sk:-N2p_UWOEQzqBPAmw9Sl:bwd1vvh) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/tests/unittest/create.cpp#L81)):*
> ```cpp
> 				struct pmemstream_region r;
> 				r = pmemstream_region_iterator_get(riter.get());
> 				UT_ASSERTeq(region.offset, r.offset); // ?
> ```

why `// ?` ?
___
*[`tests/unittest/multi_region_state.cpp` line 131 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pa8bn-CgVafH6Jxl_:-N2pa8bn-CgVafH6Jxla:bq3wi0a) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/tests/unittest/multi_region_state.cpp#L131)):*
> ```cpp
> 			/* in each region we expect only 1 entry (storing the unique id) */
> 			region = pmemstream_region_iterator_get(it.get());
> 			RC_ASSERT(region.offset != -1);
> ```

? 
s there any scenario where the offset is equal to `-1`?



_Code quote:_
```cpp
region.offset != -1
```

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 8 of 12 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/186)* status: all files reviewed, 12 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[`-- commits` line 5 at r11](https://reviewable.io/reviews/pmem/pmemstream/186#-N2qH1d8EIvaQBqZYlZ4):*
I think we need a little more information here :wink: and a `ref. #182`
___
*[`src/iterator.c` line 53 at r11](https://reviewable.io/reviews/pmem/pmemstream/186#-N2qPDpf6Dl0FdfuLXve:-N2qPDpg029kckgRej9X:b7v1azb) ([raw file](https://github.com/pmem/pmemstream/blob/f60a9bd804a831d9c13d24c61318e4a6901035ea/src/iterator.c#L53)):*
> ```C
> }
> 
> void pmemstream_region_iterator_next(struct pmemstream_region_iterator *it)
> ```

I believe, for consistency, please rename this param to `iterator`
___
*[`src/iterator.c` line 61 at r11](https://reviewable.io/reviews/pmem/pmemstream/186#-N2qPXsh4YdEIyFZlCs7:-N2qPXsh4YdEIyFZlCs8:b3kqx) ([raw file](https://github.com/pmem/pmemstream/blob/f60a9bd804a831d9c13d24c61318e4a6901035ea/src/iterator.c#L61)):*
> ```C
> }
> 
> struct pmemstream_region pmemstream_region_iterator_get(struct pmemstream_region_iterator *it)
> ```

.
___
*[`src/libpmemstream.map` line 21 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pNKL02D39RuhKaK4t:-N2qQkYv1LUWdWXAWWrw:bb7dx2z) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/src/libpmemstream.map#L21)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls sort A-Z
</blockquote></details>

bump
___
*[`src/include/libpmemstream.h` line 148 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pNT0xEsKjeR2AWsM8:-N2qQoHk9cG-7zTYTRS9:bb7dx2z) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/src/include/libpmemstream.h#L148)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls describe these methods here a little (e.g. to inform that a new iterator is now invalid, when created)
</blockquote></details>

bump
___
*[`tests/api_c/region_iterator.c` line 113 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pO4H-DYsBGZtwClDs:-N2qRASO3c5-QBoO5F7-:b-9qg1u4) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/tests/api_c/region_iterator.c#L113)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done
___
*[`tests/api_c/region_iterator.c` line 42 at r11](https://reviewable.io/reviews/pmem/pmemstream/186#-N2qRCqyDRz5zXGLOj2b:-N2qRCqz4wphAO8YolKi:b-k87zl9) ([raw file](https://github.com/pmem/pmemstream/blob/f60a9bd804a831d9c13d24c61318e4a6901035ea/tests/api_c/region_iterator.c#L42)):*
> ```C
> }
> 
> // void valid_recovery_test(char *path)
> ```

pls add a comment why this is commented out
___
*[`tests/common/stream_helpers.hpp` line 368 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pOqpUA_KA3C-wC0Ek:-N2qS8Ej8ZEyzFLs2QD1:bsv5qop) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/tests/common/stream_helpers.hpp#L368)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

hmm... something went wrong here - now you call `is_valid` twice
___
*[`tests/common/stream_helpers.hpp` line 433 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pPhMb5U0GgusGy_xe:-N2qSc341qHBcEq_wGqt:b-klf07f) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/tests/common/stream_helpers.hpp#L433)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You don't validate the first region here, as well. A do-while loop can be a solution.

Also, we should ut_assert the iterated regions (it's a test helper after all :wink: )
___
*[`tests/common/stream_helpers.hpp` line 339 at r11](https://reviewable.io/reviews/pmem/pmemstream/186#-N2qR_o13o3qmeeCeiRn:-N2qR_o2-AXNikyMpEby:bvmoyah) ([raw file](https://github.com/pmem/pmemstream/blob/f60a9bd804a831d9c13d24c61318e4a6901035ea/tests/common/stream_helpers.hpp#L339)):*
> ```cpp
> 		auto riter = stream.region_iterator();
> 		pmemstream_region_iterator_seek_first(riter.get());
> 		region = pmemstream_region_iterator_get(riter.get());
> ```

you don't ensure that the first region is valid

you may use a do-while loop for validating all iterated regions

**Review by karczex — CHANGES_REQUESTED** [review]
Indeed. I think, we may do it in separate PRs and merge both at once. 

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/186#-:-N2uNcEi5CHsBbjBEgU1:b-6d19dv)* status: all files reviewed, 11 unresolved discussions (waiting on @KFilipek)

___
*[`src/iterator.c` line 65 at r11](https://reviewable.io/reviews/pmem/pmemstream/186#-N2uO6mA282TQcU9Hanx:-N2uO6mA282TQcU9Hany:bhsqvoi) ([raw file](https://github.com/pmem/pmemstream/blob/f60a9bd804a831d9c13d24c61318e4a6901035ea/src/iterator.c#L65)):*
> ```C
> 	int is_valid = pmemstream_region_iterator_is_valid(it);
> 	if (is_valid != 0) {
> 		struct pmemstream_region region = {.offset = SLIST_INVALID_OFFSET};
> ```

Probably we may expose PMEMSTREAM_INVALID_REGION and PMEMSTREAM_INVALID_ENTRY macros in API

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 12 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/186)* status: 8 of 13 files reviewed, 10 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`src/iterator.c` line 53 at r11](https://reviewable.io/reviews/pmem/pmemstream/186#-N2qPDpf6Dl0FdfuLXve:-N2ug0qr3ad7l2HuVtWx:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f60a9bd804a831d9c13d24c61318e4a6901035ea/src/iterator.c#L53)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe, for consistency, please rename this param to `iterator`
</blockquote></details>

Done.
___
*[`src/iterator.c` line 61 at r11](https://reviewable.io/reviews/pmem/pmemstream/186#-N2qPXsh4YdEIyFZlCs7:-N2ugtFa4B6YyzSpWV59:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f60a9bd804a831d9c13d24c61318e4a6901035ea/src/iterator.c#L61)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`src/iterator.c` line 65 at r11](https://reviewable.io/reviews/pmem/pmemstream/186#-N2uO6mA282TQcU9Hanx:-N2uopeO-PLb7_Z1ZMpI:bvo783t) ([raw file](https://github.com/pmem/pmemstream/blob/f60a9bd804a831d9c13d24c61318e4a6901035ea/src/iterator.c#L65)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Probably we may expose PMEMSTREAM_INVALID_REGION and PMEMSTREAM_INVALID_ENTRY macros in API
</blockquote></details>

ofc, I can push it separately, immediately after this PR
___
*[`src/libpmemstream.map` line 21 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pNKL02D39RuhKaK4t:-N2ui2ne27LC0MS0uB3Z:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/src/libpmemstream.map#L21)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

bump
</blockquote></details>

Done.
___
*[`src/include/libpmemstream.h` line 148 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pNT0xEsKjeR2AWsM8:-N2ukZMuDhlMbTphHIIS:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/src/include/libpmemstream.h#L148)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

bump
</blockquote></details>

Done.
___
*[`tests/api_c/region_iterator.c` line 113 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pO4H-DYsBGZtwClDs:-N2umGsK7D9XqPvR07py:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/tests/api_c/region_iterator.c#L113)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not done
</blockquote></details>

Done.
___
*[`tests/api_c/region_iterator.c` line 42 at r11](https://reviewable.io/reviews/pmem/pmemstream/186#-N2qRCqyDRz5zXGLOj2b:-N2ul2Qt32YG8cfSp4c1:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f60a9bd804a831d9c13d24c61318e4a6901035ea/tests/api_c/region_iterator.c#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add a comment why this is commented out
</blockquote></details>

Done.
___
*[`tests/common/stream_helpers.hpp` line 368 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pOqpUA_KA3C-wC0Ek:-N2umO-X0H-l6u2A3Ujp:b-rb9qek) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/tests/common/stream_helpers.hpp#L368)):*
> you don't ensure that the first region is valid
Cringe xD
___
*[`tests/common/stream_helpers.hpp` line 433 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pPhMb5U0GgusGy_xe:-N2uoj5gCq2AGhmfYxbI:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/tests/common/stream_helpers.hpp#L433)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

You don't validate the first region here, as well. A do-while loop can be a solution.

Also, we should ut_assert the iterated regions (it's a test helper after all :wink: )
</blockquote></details>

Done.
___
*[`tests/common/stream_helpers.hpp` line 339 at r11](https://reviewable.io/reviews/pmem/pmemstream/186#-N2qR_o13o3qmeeCeiRn:-N2unh9Y7gAHeVZJ456e:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f60a9bd804a831d9c13d24c61318e4a6901035ea/tests/common/stream_helpers.hpp#L339)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you don't ensure that the first region is valid

you may use a do-while loop for validating all iterated regions
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/186)* status: 8 of 13 files reviewed, 10 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`-- commits` line 5 at r11](https://reviewable.io/reviews/pmem/pmemstream/186#-N2qH1d8EIvaQBqZYlZ4):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think we need a little more information here :wink: and a `ref. #182`
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 5 of 12 files at r10, 3 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/186)* status: 8 of 13 files reviewed, 10 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/186#-:-N2urtYN7ruLIg0noKtN:bnfp4nl)* status: 8 of 13 files reviewed, 10 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 5 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/186)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[`src/libpmemstream.map` line 21 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pNKL02D39RuhKaK4t:-N2upxRC-ILXa9_lylPA:bkf17wq) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/src/libpmemstream.map#L21)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant only yours... but thanks ;-)
___
*[`tests/api_c/region_iterator.c` line 113 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pO4H-DYsBGZtwClDs:-N2uqtHX6rDMKbPFFKeR:bnq3b5d) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/tests/api_c/region_iterator.c#L113)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done :stuck_out_tongue_winking_eye: 

This is not a 'null' test - I was hoping for a test to call `next` on an invalid_region (unless it's UB :wink: )
___
*[`tests/common/stream_helpers.hpp` line 368 at r7](https://reviewable.io/reviews/pmem/pmemstream/186#-N2pOqpUA_KA3C-wC0Ek:-N2usa_u0LJl1HjvulHH:btu250c) ([raw file](https://github.com/pmem/pmemstream/blob/72fd294367154c1021cb4e2a69dfb22b4458b8be/tests/common/stream_helpers.hpp#L368)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> you don't ensure that the first region is valid
Cringe xD
</blockquote></details>

previously there was `while(true)` :roll_eyes:

Now it looks good.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/186#-:-N2v1DHF1owsdr8Yd_y_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
