### PR TITLE
Initial version of timestamp-based persistency

### PR DESCRIPTION
**Pull request by igchor**
Ref: https://github.com/pmem/pmemstream/issues/78

This PR does not add transactions nor timestamps for allocations.

This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/183)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/183)* status: 3 of 13 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/pmem/pmemstream/183#-N1wJqZg0l7h5utWoLGi):*
we may comment out the part with multiple active appends (per thread), do a different/simplified test for now, and re-enable the commented part later on

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/183)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/pmem/pmemstream/183#-N1wJqZg0l7h5utWoLGi):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we may comment out the part with multiple active appends (per thread), do a different/simplified test for now, and re-enable the commented part later on
</blockquote></details>

Fixed - the problem was different. I was clearing the metadata of new entry (`	stream->data.memset(destination + entry_total_size_span_aligned, 0, sizeof(struct span_entry), PMEM2_F_MEM_NOFLUSH);` in pmemstream_publish and since pmemstream_publish calls can be done in arbitrary order valid metadata could be zeroed. I now moved the clearing to pmemstream_reserve.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/183)* status: 2 of 14 files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[`src/region.c` line 226 at r4](https://reviewable.io/reviews/pmem/pmemstream/183#-N2Bkac73DmAxMo46bJm:-N2Bkac73DmAxMo46bJn:bn2yfii) ([raw file](https://github.com/pmem/pmemstream/blob/e7b696503f54542cce22e14fb702cc03517e6c27/src/region.c#L226)):*
> ```C
> 
> 	uint8_t *next_entry_dst = (uint8_t *)pmemstream_offset_to_ptr(region_runtime->data, tail_offset);
> 	region_runtime->data->memset(next_entry_dst, 0, sizeof(struct span_entry), 0);
> ```

you can just create an empty span (it applies in a few places within this review...?)
___
*[`src/span.h` line 44 at r4](https://reviewable.io/reviews/pmem/pmemstream/183#-N2CHUv-0rcjsOrXnTqK:-N2CHUv01ejNMLCpe9_K:b-jb0j2n) ([raw file](https://github.com/pmem/pmemstream/blob/e7b696503f54542cce22e14fb702cc03517e6c27/src/span.h#L44)):*
> ```objc
> 	alignas(CACHELINE_SIZE) struct span_base span_base;
> 	struct allocator_entry_metadata allocator_entry_metadata;
> 	uint64_t max_valid_timestamp;
> ```

you could describe a little this max_valid_timestamp
___
*[`tests/unittest/region_runtime_initialize.cpp` line 54 at r4](https://reviewable.io/reviews/pmem/pmemstream/183#-N2CHmLX13oEa0SJYK_F:-N2CHmLX13oEa0SJYK_G:bdqlxnb) ([raw file](https://github.com/pmem/pmemstream/blob/e7b696503f54542cce22e14fb702cc03517e6c27/tests/unittest/region_runtime_initialize.cpp#L54)):*
> ```cpp
> 			"verify that pmemstream is ready to be written to after region_runtime_initialize_for_write_locked",
> 			[&](pmemstream_with_single_init_region &&stream) {
> 				const auto concurrency = *rc::gen::inRange<std::size_t>(0, max_concurrency);
> ```

0? it works in range `<x, y)`

**Review by karczex — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/183)* status: 3 of 14 files reviewed, 6 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[`src/region.c` line 361 at r5](https://reviewable.io/reviews/pmem/pmemstream/183#-N2HFKYdArHMc59XU-Wi:-N2HFKYdArHMc59XU-Wj:b-ebgdir) ([raw file](https://github.com/pmem/pmemstream/blob/f58dd163b98a5fd4ec419c8321dc93ecda7fa907/src/region.c#L361)):*
> ```C
> 	/* Region is already recovered, and we did not encounter end of the data yet.
> 	 * Span must be a valid entry. */
> 	assert(check_entry_consistency_and_maybe_recover_region(iterator));
> ```

Such assert may cause "it works only on Debug builds" kind of bugs in the future. 
it probably would be better to split `check_entry_consistency_and_maybe_recover_region()` to `check_entry_consistency()`  and `maybe_recover_region()` and call only `check_consistency()` in the `assert`
___
*[`tests/CMakeLists.txt` line 94 at r5](https://reviewable.io/reviews/pmem/pmemstream/183#-N2GpLVsC9PC6_wq69kO:-N2GpLVsC9PC6_wq69kP:b-6vl9rh) ([raw file](https://github.com/pmem/pmemstream/blob/f7c46d402b456305b0c0bc32e21f6a062332474a/tests/CMakeLists.txt#L94)):*
> ```CMake
> add_test_generic(NAME region_create TRACERS none memcheck pmemcheck drd helgrind)
> 
> build_test_ext(NAME region_initialize SRC_FILES unittest/region_initialize.cpp ../src/region.c ../src/critnib/critnib.c ../src/span.c ../src/iterator.c)
> ```

This test should be fixed
___
*[`tests/layout/iterate_validation.cpp` line 43 at r5](https://reviewable.io/reviews/pmem/pmemstream/183#-N2GjxTQ0LryPXPbXKZV:-N2Gjdo2-rt_kw7D33kt:b-a1yk67) ([raw file](https://github.com/pmem/pmemstream/blob/f58dd163b98a5fd4ec419c8321dc93ecda7fa907/tests/layout/iterate_validation.cpp#L43)):*
> ```cpp
> 	if (stype == SPAN_ENTRY) {
> 		/* Always wrong timestamp. */
> 		auto popcount = std::numeric_limits<uint64_t>::max();
> ```

Wrong varaible  name.

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/183#-:-N2LWfbBAG53jomwtOUP:bnfp4nl)* status: 3 of 14 files reviewed, 6 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

**Pull request merged**
