### PR TITLE
Make pmemstream refactor

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/89)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/89)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/pmem/pmemstream/89#-MuGAHTo7kj6CmgLj_1u):*
yyy nope? :stuck_out_tongue_winking_eye: 
___
*[-- commits, line 9 at r1](https://reviewable.io/reviews/pmem/pmemstream/89#-MuGBP4v4CmjEUMSlTMx):*
and actually, why do we need `std::function as deleter type`?
___
*[tests/common/unittest.hpp, line 107 at r1](https://reviewable.io/reviews/pmem/pmemstream/89#-MuGAw409hNsHW0xb_om:-MuGAw409hNsHW0xb_on:bpmcrtm) ([raw file](https://github.com/pmem/pmemstream/blob/cf83660e8f5f23ef645bcd92e999d0c91c222388/tests/common/unittest.hpp#L107)):*
> ```cpp
> 
> /* From: https://stackoverflow.com/a/20846873/5935594
>  * CC BY-SA 3.0 */
> ```

you may write a short sentence why we need this - is it of any use, besides make_pmemstream?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/89)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/pmem/pmemstream/89#-MuGAHTo7kj6CmgLj_1u):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

yyy nope? :stuck_out_tongue_winking_eye: 
</blockquote></details>

Done.
___
*[-- commits, line 9 at r1](https://reviewable.io/reviews/pmem/pmemstream/89#-MuGBP4v4CmjEUMSlTMx):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

and actually, why do we need `std::function as deleter type`?
</blockquote></details>

Done. I just wrote why we need to define return type. 
___
*[tests/common/unittest.hpp, line 107 at r1](https://reviewable.io/reviews/pmem/pmemstream/89#-MuGAw409hNsHW0xb_om:-MuGnbO8DLpmvo2UFBCF:b-kh4vfr) ([raw file](https://github.com/pmem/pmemstream/blob/cf83660e8f5f23ef645bcd92e999d0c91c222388/tests/common/unittest.hpp#L107)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you may write a short sentence why we need this - is it of any use, besides make_pmemstream?
</blockquote></details>

In general, yes. Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/89)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Comment by karczex** [comment]
___
*[tests/common/unittest.hpp, line 111 at r2](https://reviewable.io/reviews/pmem/pmemstream/89#-MuLqfph8bxhPF96R_oQ:-MuLqfph8bxhPF96R_oR:b5f2rts) ([raw file](https://github.com/pmem/pmemstream/blob/70422abb9638d7bc4a3795d5d7f6aeba0342f474/tests/common/unittest.hpp#L111)):*
> ```cpp
>  */
> template <class F>
> auto make_copyable_function(F &&f)
> ```

Please make  names more verbose.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/89)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[tests/common/unittest.hpp, line 111 at r2](https://reviewable.io/reviews/pmem/pmemstream/89#-MuLqfph8bxhPF96R_oQ:-MuLtaOH7ndNHLwDjU-x:ba21ix2) ([raw file](https://github.com/pmem/pmemstream/blob/70422abb9638d7bc4a3795d5d7f6aeba0342f474/tests/common/unittest.hpp#L111)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Please make  names more verbose. 
</blockquote></details>

I actually wanted to not change it if possible (so we don't have to mention it under the license)

**Pull request closed without merging**
