### PR TITLE
Check if new list points to invalid elements (UINT64_MAX)

### PR DESCRIPTION
**Pull request by Karolina002**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/146)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/146)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/146#-MyM5IW4AhFRWYfbX0I2:-MyM5IW4AhFRWYfbX0I3:bumc9tg) (no related file):*
you can rebase to #145, add this test to execution (in CMake) and see if it works :wink: 

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/146#-MyM5ZHh3p7SDVyAhp-D):*
pls extend this with info "what list" - you could write e.g. "add simply test for singly_linked_list" and then details (like your current commit msg)
___
*[tests/unittest/slist_simple_test.cpp, line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/146#-MyM5AEd-ZFMxOdM9HnE:-MyM5AEd-ZFMxOdM9HnF:ber91sd) ([raw file](https://github.com/pmem/pmemstream/blob/744f98a0e4424c0da0d080de35995e3020212715/tests/unittest/slist_simple_test.cpp#L2)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2021-2022, Intel Corporation */
> ```

just 2022
___
*[tests/unittest/slist_simple_test.cpp, line 14 at r1](https://reviewable.io/reviews/pmem/pmemstream/146#-MyM55fV2d6srzgz5vai:-MyM55fV2d6srzgz5vaj:b-ahv4io) ([raw file](https://github.com/pmem/pmemstream/blob/744f98a0e4424c0da0d080de35995e3020212715/tests/unittest/slist_simple_test.cpp#L14)):*
> ```cpp
> 	UT_ASSERTeq((list)->head, UINT64_MAX);
> 	UT_ASSERTeq((list)->tail, UINT64_MAX);
> }
> ```

pls add "enter" at the end

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/146)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @igchor, @Karolina002, and @lukaszstolarczuk)

___
*[tests/unittest/slist_simple_test.cpp, line 7 at r1](https://reviewable.io/reviews/pmem/pmemstream/146#-MyMBRT9AOB1QvZcg9RL:-MyMBRTAAzQy_ANIkIEK:bpazuqt) ([raw file](https://github.com/pmem/pmemstream/blob/744f98a0e4424c0da0d080de35995e3020212715/tests/unittest/slist_simple_test.cpp#L7)):*
> ```cpp
> #include "unittest.hpp"
> 
> int main(int argc, char *argv[])
> ```

Since this is c++ test, please use run_tests function like in other tests. Otherwise, coverity will complain that there are uncaught exceptions (from asserts).

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/146)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/146#-MyM5IW4AhFRWYfbX0I2:-MyOGBS9-avsQwv5PH_8:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can rebase to #145, add this test to execution (in CMake) and see if it works :wink: 
</blockquote></details>

Done.

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/146#-MyM5ZHh3p7SDVyAhp-D):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls extend this with info "what list" - you could write e.g. "add simply test for singly_linked_list" and then details (like your current commit msg)
</blockquote></details>

Done.
___
*[tests/unittest/slist_simple_test.cpp, line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/146#-MyM5AEd-ZFMxOdM9HnE:-MyOGIOzCoa23FoDoIob:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/744f98a0e4424c0da0d080de35995e3020212715/tests/unittest/slist_simple_test.cpp#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

just 2022
</blockquote></details>

Done.
___
*[tests/unittest/slist_simple_test.cpp, line 14 at r1](https://reviewable.io/reviews/pmem/pmemstream/146#-MyM55fV2d6srzgz5vai:-MyOGK3w7zzhIO7sbune:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/744f98a0e4424c0da0d080de35995e3020212715/tests/unittest/slist_simple_test.cpp#L14)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add "enter" at the end
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/146)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor, @Karolina002, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/146#-MyM5IW4AhFRWYfbX0I2:-MyREC-0-BTypws5wU0g:bip5gik) (no related file):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

heh, but now you squashed all changes into one commit :smile: you should have right now all the commits from Krzysiek and your commit on top of that :wink: when we merge Krzysiek's changes you could then easily rebase to master and should be left with just one commit :-)

---

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/146)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @igchor, @Karolina002, and @lukaszstolarczuk)

___
*[tests/unittest/slist_simple_test.cpp, line 13 at r2](https://reviewable.io/reviews/pmem/pmemstream/146#-Myl3LBeAeLBj2cyTR-6:-Myl3LBeAeLBj2cyTR-7:b-n207sg) ([raw file](https://github.com/pmem/pmemstream/blob/6b956513f3c8322ed686ef8067789c8024dfa897/tests/unittest/slist_simple_test.cpp#L13)):*
> ```cpp
> 		SLIST_INIT(&list);
> 
> 		UT_ASSERTeq(list.head, UINT64_MAX);
> ```

we have new DEFINE for this: invalid_offset

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/146)* status: all files reviewed, 3 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 109 at r2](https://reviewable.io/reviews/pmem/pmemstream/146#-MylX9yvCkVcwQGBxNvD:-MylX9yvCkVcwQGBxNvE:bak4710) ([raw file](https://github.com/pmem/pmemstream/blob/6b956513f3c8322ed686ef8067789c8024dfa897/tests/CMakeLists.txt#L109)):*
> ```CMake
> add_test_generic(NAME stream_from_map TRACERS none memcheck pmemcheck drd helgrind)
> 
> build_test_rc(NAME slist SRC_FILES unittest/slist.cpp)
> ```

Please rebase, now this file is renamed to `singly_linked_list.cpp`



_Code quote:_
```CMake
build_test_rc(NAME slist SRC_FILES unittest/slist.cpp)
```
___
*[tests/unittest/slist_simple_test.cpp, line 13 at r2](https://reviewable.io/reviews/pmem/pmemstream/146#-Myl3LBeAeLBj2cyTR-6:-MylXM472OkOLjjk7co6:bgnby38) ([raw file](https://github.com/pmem/pmemstream/blob/6b956513f3c8322ed686ef8067789c8024dfa897/tests/unittest/slist_simple_test.cpp#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we have new DEFINE for this: invalid_offset
</blockquote></details>

Right: `SLIST_INVALID_OFFSET`

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/146)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/146#-MyM5IW4AhFRWYfbX0I2:-MzHBEBz5lSg7rVIU9Gv:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

heh, but now you squashed all changes into one commit :smile: you should have right now all the commits from Krzysiek and your commit on top of that :wink: when we merge Krzysiek's changes you could then easily rebase to master and should be left with just one commit :-)
</blockquote></details>

Done.

---
___
*[tests/CMakeLists.txt, line 109 at r2](https://reviewable.io/reviews/pmem/pmemstream/146#-MylX9yvCkVcwQGBxNvD:-MzHERfe5tjDHetG6kz9:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/6b956513f3c8322ed686ef8067789c8024dfa897/tests/CMakeLists.txt#L109)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Please rebase, now this file is renamed to `singly_linked_list.cpp`
</blockquote></details>

Done.
___
*[tests/unittest/slist_simple_test.cpp, line 13 at r2](https://reviewable.io/reviews/pmem/pmemstream/146#-Myl3LBeAeLBj2cyTR-6:-MzHET087tUQZ7AHCSrU:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/6b956513f3c8322ed686ef8067789c8024dfa897/tests/unittest/slist_simple_test.cpp#L13)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Right: `SLIST_INVALID_OFFSET`
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/146)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @Karolina002 and @KFilipek)

___
*[tests/unittest/slist_simple_test.cpp, line 22 at r4](https://reviewable.io/reviews/pmem/pmemstream/146#-MzJdwvtBYd1z8TM-0zl:-MzJdwvtBYd1z8TM-0zm:b-jcpipk) ([raw file](https://github.com/pmem/pmemstream/blob/c559569c0cf2df5bd09741c9d5ff828e46738ef9/tests/unittest/slist_simple_test.cpp#L22)):*
> ```cpp
> 		SLIST_INIT(&runtime, &list);
> 
> 		UT_ASSERTeq(list.head, SLIST_INVALID_OFFSET);
> ```

please move this test into existing slist's test file

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/146)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[tests/unittest/slist_simple_test.cpp, line 22 at r4](https://reviewable.io/reviews/pmem/pmemstream/146#-MzJdwvtBYd1z8TM-0zl:-MzR70zq7EeGaP-WAKOS:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c559569c0cf2df5bd09741c9d5ff828e46738ef9/tests/unittest/slist_simple_test.cpp#L22)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please move this test into existing slist's test file
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/146)* status: all files reviewed, 2 unresolved discussions (waiting on @Karolina002 and @KFilipek)

___
*[tests/unittest/singly_linked_list.cpp, line 38 at r5](https://reviewable.io/reviews/pmem/pmemstream/146#-MzTrFpnAMLdofeHLZaQ:-MzTrFpnAMLdofeHLZaR:b8r2oeu) ([raw file](https://github.com/pmem/pmemstream/blob/8e8f6ea7d60ca4622fbbf1aefdfe56b3f8b1a599/tests/unittest/singly_linked_list.cpp#L38)):*
> ```cpp
> int main(int argc, char *argv[])
> {
> 	rc::check("Initiate list", [] {
> ```

it doesn't have to be run using RapidCheck - you can just put this test here, like:
```
/* comment with test description */
{
  <test case body here>
}
```

you don't need RC, because you don't generate any data, and by default, RC test is run 100 times, so here it is redundant.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/146)* status: all files reviewed, 3 unresolved discussions (waiting on @Karolina002 and @KFilipek)

___
*[tests/unittest/singly_linked_list.cpp, line 52 at r5](https://reviewable.io/reviews/pmem/pmemstream/146#-MzV6nzz4VV4iGplF0Id:-MzV6nzz4VV4iGplF0Ie:b77rfkp) ([raw file](https://github.com/pmem/pmemstream/blob/8e8f6ea7d60ca4622fbbf1aefdfe56b3f8b1a599/tests/unittest/singly_linked_list.cpp#L52)):*
> ```cpp
> 	});
> 
> 	rc::check("Insert head", [](const std::vector<struct node> &data) {
> ```

I know this is not your change but could you also fix the remaining of this PR? ;d
I see we are missing return checks (https://github.com/pmem/pmemstream/blob/master/tests/unittest/util_common.cpp#L17) and run_test (https://github.com/pmem/pmemstream/blob/master/tests/unittest/util_common.cpp#L14)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/146)* status: all files reviewed, 2 unresolved discussions (waiting on @Karolina002 and @KFilipek)

___
*[tests/unittest/singly_linked_list.cpp, line 52 at r5](https://reviewable.io/reviews/pmem/pmemstream/146#-MzV6nzz4VV4iGplF0Id:-MzVRn8m3uUUwqP58FjY:b-juq0ib) ([raw file](https://github.com/pmem/pmemstream/blob/8e8f6ea7d60ca4622fbbf1aefdfe56b3f8b1a599/tests/unittest/singly_linked_list.cpp#L52)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I know this is not your change but could you also fix the remaining of this PR? ;d
I see we are missing return checks (https://github.com/pmem/pmemstream/blob/master/tests/unittest/util_common.cpp#L17) and run_test (https://github.com/pmem/pmemstream/blob/master/tests/unittest/util_common.cpp#L14) 
</blockquote></details>

I think all these nice updates [and upcoming new tests] for SLIST may be done in the separate PR - e.g. within the refreshed version of #147.

We may quickly finish up and close this PR and keep alive only the other one.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/146#-:-MzZUub9AndQYI1FYidB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/146#-:-MzZWavmBrCVC0dKA6t9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)

**Pull request merged**
