### PR TITLE
Change entry_iterator behavior

### PR DESCRIPTION
**Pull request by Karolina002**
Allow user to get the last entry from the region

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/114)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
Looks good, could you please add some test for this? I think you could implement something similar as here:https://github.com/pmem/pmemstream/issues/105 - to make sure that after the loop, the entry actually points to the last one.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/114#-:-MvPb9uXCM9TN4TyqkMn:b4pn8dh)* status: 0 of 1 files reviewed, all discussions resolved

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/114)* status: all files reviewed, 3 unresolved discussions (waiting on @Karolina002)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/114#-MvYWt030mBK9Op-Wg2B):*
`entry_iterator_next` to be precise
___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/114#-MvYWEz67GhGWY4SPTpM):*
please mention at the end, that this commit fixes https://github.com/pmem/pmemstream/issues/105
see: https://pmem.io/blog/2014/09/git-workflow/

Usually, it's done in the last commit message line:
`Ref: ...` or even better at this case: `Fixes: #105`
___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/114#-MvYWgrQ1wr-iM1emkTm):*
this commit message is not precise, we always allowed user to get the last entry from the region

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/114)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/114#-MvYWt030mBK9Op-Wg2B):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`entry_iterator_next` to be precise
</blockquote></details>

Done.
___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/114#-MvYWEz67GhGWY4SPTpM):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please mention at the end, that this commit fixes https://github.com/pmem/pmemstream/issues/105
see: https://pmem.io/blog/2014/09/git-workflow/

Usually, it's done in the last commit message line:
`Ref: ...` or even better at this case: `Fixes: #105`

</blockquote></details>

Done.
___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/114#-MvYWgrQ1wr-iM1emkTm):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this commit message is not precise, we always allowed user to get the last entry from the region
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/114#-:-MvryrsFCH9Uh4-N4uVs:bnfp4nl)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/114)* status: all files reviewed, 4 unresolved discussions (waiting on @Karolina002)

___
*[tests/CMakeLists.txt, line 90 at r2](https://reviewable.io/reviews/pmem/pmemstream/114#-MvrkdCl1LljmguNqziL:-MvrkdCl1LljmguNqziM:b8bj08r) ([raw file](https://github.com/pmem/pmemstream/blob/33556f8ffe7581aae0bbec27b8cc14b2f00f031d/tests/CMakeLists.txt#L90)):*
> ```CMake
> add_test_generic(NAME entry_iterator TRACERS none memcheck pmemcheck drd helgrind)
> 
> build_test(get_last_entry api_c/get_last_entry.c)
> ```

you can add this test into an existing file - api/entry_iterator.c
___
*[tests/api_c/get_last_entry.c, line 18 at r2](https://reviewable.io/reviews/pmem/pmemstream/114#-MvrgTKp4p9thwTzcDam:-MvrgTKp4p9thwTzcDan:b-ln5dml) ([raw file](https://github.com/pmem/pmemstream/blob/33556f8ffe7581aae0bbec27b8cc14b2f00f031d/tests/api_c/get_last_entry.c#L18)):*
> ```C
> {
> 	int ret;
> 	int n = 5;
> ```

1. `n`? perhaps something more precise - `entries_count`/`repeats`/`iterations`/etc...
2. this var could be `const` actually
___
*[tests/api_c/get_last_entry.c, line 31 at r2](https://reviewable.io/reviews/pmem/pmemstream/114#-MvrjfFnBUrYz8anrgnf:-MvrjfFo3JcooQzFxMLd:b-qtno56) ([raw file](https://github.com/pmem/pmemstream/blob/33556f8ffe7581aae0bbec27b8cc14b2f00f031d/tests/api_c/get_last_entry.c#L31)):*
> ```C
> 	UT_ASSERTeq(ret, 0);
> 
> 	struct entry_data *e = malloc((uint64_t)n * sizeof(struct entry_data));
> ```

can't you just make an array of entry_data's?
___
*[tests/layout/iterate_validation.cpp, line 87 at r2](https://reviewable.io/reviews/pmem/pmemstream/114#-MvrkUiX6aXuucqkDMMV:-MvrkUiX6aXuucqkDMMW:bikcr2e) ([raw file](https://github.com/pmem/pmemstream/blob/33556f8ffe7581aae0bbec27b8cc14b2f00f031d/tests/layout/iterate_validation.cpp#L87)):*
> ```cpp
> 
> 					auto next_entry_offset = ALIGN_UP(
> 						entry.offset + data.back().size() + SPAN_ENTRY_METADATA_SIZE, 8ULL);
> ```

what is this magic `8ULL`?

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/114)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @igchor, @Karolina002, and @lukaszstolarczuk)

___
*[-- commits, line 4 at r4](https://reviewable.io/reviews/pmem/pmemstream/114#-Mw17vKM6xBnfs9PMhIz):*
maybe I'm being too picky, but I wouldn't know what was changed in this commit based on this description. How about something like:
`Output param 'user_entry' is set/updated only on success`

and to be even more precise you could add something like:
`This way user can iterate over all entries and get the last entry after the loop/iteration.`
___
*[tests/CMakeLists.txt, line 90 at r2](https://reviewable.io/reviews/pmem/pmemstream/114#-MvrkdCl1LljmguNqziL:-Mw17lsr84b71rEDTYDr:b-1cb9hi) ([raw file](https://github.com/pmem/pmemstream/blob/33556f8ffe7581aae0bbec27b8cc14b2f00f031d/tests/CMakeLists.txt#L90)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

I think it's more  legible when this test is in the separate file
</blockquote></details>

hmm.. I'm not sure what do you mean - from my perspective it's just another test for `pmemstream_entry_iterator_next`
___
*[tests/layout/iterate_validation.cpp, line 87 at r2](https://reviewable.io/reviews/pmem/pmemstream/114#-MvrkUiX6aXuucqkDMMV:-Mw17QJkEVgDtWgRuycE:bwxl2t5) ([raw file](https://github.com/pmem/pmemstream/blob/33556f8ffe7581aae0bbec27b8cc14b2f00f031d/tests/layout/iterate_validation.cpp#L87)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

This part was changed by @igchor 
</blockquote></details>

what do you mean it was changed by him? I can't see such change on master... :thinking:

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/114)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)

___
*[tests/layout/iterate_validation.cpp, line 87 at r2](https://reviewable.io/reviews/pmem/pmemstream/114#-MvrkUiX6aXuucqkDMMV:-MwW3ijI8pQghzXrsZfi:b-u03qrf) ([raw file](https://github.com/pmem/pmemstream/blob/33556f8ffe7581aae0bbec27b8cc14b2f00f031d/tests/layout/iterate_validation.cpp#L87)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what do you mean it was changed by him? I can't see such change on master... :thinking: 
</blockquote></details>

@igchor, can you help out with this `8ULL` - shouldn't it be `sizeof(span_bytes)`?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/114)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)

___
*[tests/layout/iterate_validation.cpp, line 87 at r2](https://reviewable.io/reviews/pmem/pmemstream/114#-MvrkUiX6aXuucqkDMMV:-MwW6WxC0kRW02VJYc3I:b-gugluv) ([raw file](https://github.com/pmem/pmemstream/blob/33556f8ffe7581aae0bbec27b8cc14b2f00f031d/tests/layout/iterate_validation.cpp#L87)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

@igchor, can you help out with this `8ULL` - shouldn't it be `sizeof(span_bytes)`?
</blockquote></details>

yes, sizeof(span_bytes)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/114#-:-MwWRTpJDSkqN5oT8hy8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)

**Pull request merged**
