### PR TITLE
Add test for append data of size = 0 and invalid address

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/102)

### CODE REVIEW

**Comment by karczex** [comment]
___
*[tests/unittest/append.cpp, line 63 at r1](https://reviewable.io/reviews/pmem/pmemstream/102#-Mup1EQ07COIo2-w4A63:-Mup1EQ07COIo2-w4A64:b-7ilvgp) ([raw file](https://github.com/pmem/pmemstream/blob/c29fa8f2ffc3c40a214f6e0f1102b35666436cf1/tests/unittest/append.cpp#L63)):*
> ```cpp
> 		}
> 
> 		ret += rc::check("verify if appedning entry of size = 0 and invalid address do not cause segfault",
> ```

typo

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/102)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[tests/unittest/append.cpp, line 65 at r1](https://reviewable.io/reviews/pmem/pmemstream/102#-Mup2tEo-KWLL1PZwicJ:-Mup2tEo-KWLL1PZwicK:bmejskm) ([raw file](https://github.com/pmem/pmemstream/blob/c29fa8f2ffc3c40a214f6e0f1102b35666436cf1/tests/unittest/append.cpp#L65)):*
> ```cpp
> 		ret += rc::check("verify if appedning entry of size = 0 and invalid address do not cause segfault",
> 				 [&](const uintptr_t &invalid_data_address) {
> 					 const size_t max_size = 1024UL;
> ```

why do you need this variable, why not use TEST_DEFAULT_... variables?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/102)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/unittest/append.cpp, line 79 at r1](https://reviewable.io/reviews/pmem/pmemstream/102#-Mup4w422HFIRQafmUFy:-Mup4w422HFIRQafmUFz:b8ws94q) ([raw file](https://github.com/pmem/pmemstream/blob/c29fa8f2ffc3c40a214f6e0f1102b35666436cf1/tests/unittest/append.cpp#L79)):*
> ```cpp
> 					 verify(stream.get(), region, {entry}, {});
> 
> 					 UT_ASSERTeq(pmemstream_region_free(stream.get(), region), 0);
> ```

please remove this - we want to make a dedicated test  for region_free and get rid of those from other tests

**Comment by karczex** [comment]
___
*[tests/unittest/append.cpp, line 76 at r1](https://reviewable.io/reviews/pmem/pmemstream/102#-MupsQeHAob4m25F5QZU:-MupsQeHAob4m25F5QZV:bazh7t6) ([raw file](https://github.com/pmem/pmemstream/blob/c29fa8f2ffc3c40a214f6e0f1102b35666436cf1/tests/unittest/append.cpp#L76)):*
> ```cpp
> 					 auto ret = pmemstream_append(stream.get(), region, nullptr, invalid_data_ptr,
> 								      0, nullptr);
> 					 UT_ASSERTeq(ret, 0);
> ```

I should use RC_ASSERT



_Code quote:_
```cpp
UT_ASSERTeq
```

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/102)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/unittest/append.cpp, line 76 at r1](https://reviewable.io/reviews/pmem/pmemstream/102#-MupsQeHAob4m25F5QZU:-MupulDYCg5LD-gJotlr:b-8n8gfh) ([raw file](https://github.com/pmem/pmemstream/blob/c29fa8f2ffc3c40a214f6e0f1102b35666436cf1/tests/unittest/append.cpp#L76)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I should use RC_ASSERT
</blockquote></details>

wait for this change and you won't have to use `RC_` :wink: 
https://github.com/pmem/pmemstream/pull/103

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/102)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/unittest/append.cpp, line 65 at r1](https://reviewable.io/reviews/pmem/pmemstream/102#-Mup2tEo-KWLL1PZwicJ:-MupwCYA1FuqBuBOkYUQ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c29fa8f2ffc3c40a214f6e0f1102b35666436cf1/tests/unittest/append.cpp#L65)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why do you need this variable, why not use TEST_DEFAULT_... variables?
</blockquote></details>

Done.
___
*[tests/unittest/append.cpp, line 79 at r1](https://reviewable.io/reviews/pmem/pmemstream/102#-Mup4w422HFIRQafmUFy:-Mupz-VC3KmnUZ8QpQfk:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c29fa8f2ffc3c40a214f6e0f1102b35666436cf1/tests/unittest/append.cpp#L79)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

please remove this - we want to make a dedicated test  for region_free and get rid of those from other tests
</blockquote></details>

Done.

**Comment by karczex** [comment]
wait for #103

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/102#-:-MvJn2Q_7LUKrwsiaoQn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
