### PR TITLE
Concurrent append

### PR DESCRIPTION
**Pull request by igchor**
TODO:
   - [ ]  more tests for concurrent append
   - [x]  benchmark performance for single thread
   - [ ] benchmark performance for multiple threads vs pmemlog
   - [x] return error if too much threads are active

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/63)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
> Reviewed 6 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/63)* status: 6 of 19 files reviewed, 2 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[-- commits, line 15 at r1](https://reviewable.io/reviews/pmem/pmemstream/63#-MvJquw2CyKBVqhyzUkP):*
typo



_Code quote:_
```
reservae
```
___
*[-- commits, line 16 at r1](https://reviewable.io/reviews/pmem/pmemstream/63#-MvJqzamEnY-v_8pSAiG):*
typo



_Code quote:_
```
exclusibvely
```

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 6 of 19 files at r1, 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/63)* status: 16 of 19 files reviewed, 5 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[src/mpmc_queue.c, line 125 at r3](https://reviewable.io/reviews/pmem/pmemstream/63#-MvOMlom7iewEp2cIz6s:-MvOMlom7iewEp2cIz6t:b-hptgq) ([raw file](https://github.com/pmem/pmemstream/blob/d8da180fc0bdadfab9919cb86b81064d3477c3ae/src/mpmc_queue.c#L125)):*
> ```C
> }
> 
> uint64_t mpmc_queue_consume(struct mpmc_queue *manager, uint64_t max_producer_id, size_t *ready_offset)
> ```

isn't `max_producer_id` equal to `manager->size`?
___
*[src/region.h, line 52 at r3](https://reviewable.io/reviews/pmem/pmemstream/63#-MvOPVTw38fIMsUPLaEh:-MvOPVTw38fIMsUPLaEi:b-qi54sk) ([raw file](https://github.com/pmem/pmemstream/blob/d8da180fc0bdadfab9919cb86b81064d3477c3ae/src/region.h#L52)):*
> ```objc
>  */
> int region_runtimes_map_get_or_create(struct region_runtimes_map *map, struct pmemstream_region region,
> 				      struct span_runtime region_rt,
> ```

just to consider:
- do we need this param? we could get 'stream' as the first param and calculate this region_rt here
- we could rename this param to match our "policy" - `region_srt`
___
*[tests/unittest/mpmc_queue.cpp, line 165 at r3](https://reviewable.io/reviews/pmem/pmemstream/63#-MvOVY2T0MnF4ouLz5bR:-MvOVY2T0MnF4ouLz5bS:b-b6ypdr) ([raw file](https://github.com/pmem/pmemstream/blob/d8da180fc0bdadfab9919cb86b81064d3477c3ae/tests/unittest/mpmc_queue.cpp#L165)):*
> ```cpp
> 
> 		ret += rc::check(
> 			"verify if producer can consume it's own products", [](const std::vector<uint32_t> &sizes) {
> ```

`its` :smile:

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/63)* status: 16 of 19 files reviewed, 5 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/mpmc_queue.c, line 125 at r3](https://reviewable.io/reviews/pmem/pmemstream/63#-MvOMlom7iewEp2cIz6s:-MvPZUv20Oi5N_sza84a:b-ka6pk4) ([raw file](https://github.com/pmem/pmemstream/blob/d8da180fc0bdadfab9919cb86b81064d3477c3ae/src/mpmc_queue.c#L125)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

isn't `max_producer_id` equal to `manager->size`?
</blockquote></details>

No necessarily, max_producer_id must be <= manager->size. In general manager->size is the max amount of producers which can use mpmc_queue. And max_producer_id is the biggest ID we know has used the mpmc_queue.
___
*[src/region.h, line 52 at r3](https://reviewable.io/reviews/pmem/pmemstream/63#-MvOPVTw38fIMsUPLaEh:-MvP_klP8Rj2DijbCBE2:b-4xfrz7) ([raw file](https://github.com/pmem/pmemstream/blob/d8da180fc0bdadfab9919cb86b81064d3477c3ae/src/region.h#L52)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

just to consider:
- do we need this param? we could get 'stream' as the first param and calculate this region_rt here
- we could rename this param to match our "policy" - `region_srt`
</blockquote></details>

1. we could pass stream but it makes it more difficult to unittest - with current code, we can just mock those params. Mocking entire stream is more complicated.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/63)* status: 16 of 19 files reviewed, 5 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/mpmc_queue.c, line 125 at r3](https://reviewable.io/reviews/pmem/pmemstream/63#-MvOMlom7iewEp2cIz6s:-MvPiDj20AaT_cwCTGf6:b-3ghtt7) ([raw file](https://github.com/pmem/pmemstream/blob/d8da180fc0bdadfab9919cb86b81064d3477c3ae/src/mpmc_queue.c#L125)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

No necessarily, max_producer_id must be <= manager->size. In general manager->size is the max amount of producers which can use mpmc_queue. And max_producer_id is the biggest ID we know has used the mpmc_queue.
</blockquote></details>

Edit: I mean manager->num_producers, not manager->size.

manager->size is just maximum possible produce_offset.

**Pull request closed without merging**
