### PR TITLE
All pmemstream_span_create_* functions now provide durability

### PR DESCRIPTION
**Pull request by igchor**
It makes it less error-prone to use - we don't need to remember about
calling persist/drain after span creation.

Those functions might be extended with flags for customizing the
durability guarantees.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/39)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/39#-:-MrRkrjaEBfCP5qzpXkl:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[src/libpmemstream.c, line 25 at r1](https://reviewable.io/reviews/pmem/pmemstream/39#-MrRkgvJCD7X5sCdxFS2:-MrRkgvJCD7X5sCdxFS3:b-f75uk9) ([raw file](https://github.com/pmem/pmemstream/blob/997d427c13ba00a3eaaea5dc99e6701f116d5e47/src/libpmemstream.c#L25)):*
> ```C
> 
> static void pmemstream_span_create_entry(struct pmemstream *stream, pmemstream_span_bytes *span, const void *data,
> 					 size_t data_size, size_t popcount)
> ```

BTW, we could actually use popcount method in here, instead of passing calculated popcount
___
*[src/libpmemstream.c, line 92 at r1](https://reviewable.io/reviews/pmem/pmemstream/39#-MrRkE8f4QAMXO2yE1Ms:-MrRkE8f4QAMXO2yE1Mt:bmypt3r) ([raw file](https://github.com/pmem/pmemstream/blob/997d427c13ba00a3eaaea5dc99e6701f116d5e47/src/libpmemstream.c#L92)):*
> ```C
> static void pmemstream_init(struct pmemstream *stream)
> {
> 	memset(stream->data->header.signature, 0, PMEMSTREAM_SIGNATURE_SIZE);
> ```

btw, shouldn't here be used stream->memset?
___
*[src/libpmemstream.c, line 101 at r1](https://reviewable.io/reviews/pmem/pmemstream/39#-MrRk5yy5hc25c4qpzSD:-MrRk5yy5hc25c4qpzSE:bn4v087) ([raw file](https://github.com/pmem/pmemstream/blob/997d427c13ba00a3eaaea5dc99e6701f116d5e47/src/libpmemstream.c#L101)):*
> ```C
> 	pmemstream_span_create_empty(stream, &stream->data->spans[0], stream->usable_size - metadata_size);
> 
> 	stream->memcpy(stream->data->header.signature, PMEMSTREAM_SIGNATURE, strlen(PMEMSTREAM_SIGNATURE), 0);
> ```

btw, shouldn't this memcpy be nontemporal or something?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/39)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 25 at r1](https://reviewable.io/reviews/pmem/pmemstream/39#-MrRkgvJCD7X5sCdxFS2:-MrRoJim72czYSK7gFp9:b-q9d3gy) ([raw file](https://github.com/pmem/pmemstream/blob/997d427c13ba00a3eaaea5dc99e6701f116d5e47/src/libpmemstream.c#L25)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

BTW, we could actually use popcount method in here, instead of passing calculated popcount
</blockquote></details>

We could, but acutuallly this way it's a bit more generic - we can replace popcount with checksum perhaps in future.
___
*[src/libpmemstream.c, line 92 at r1](https://reviewable.io/reviews/pmem/pmemstream/39#-MrRkE8f4QAMXO2yE1Ms:-MrRq_ChA1cGihV3CpcJ:b-9wzs0d) ([raw file](https://github.com/pmem/pmemstream/blob/997d427c13ba00a3eaaea5dc99e6701f116d5e47/src/libpmemstream.c#L92)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

btw, shouldn't here be used stream->memset?
</blockquote></details>

It should I think, will fix in next PR.
___
*[src/libpmemstream.c, line 101 at r1](https://reviewable.io/reviews/pmem/pmemstream/39#-MrRk5yy5hc25c4qpzSD:-MrRqgOj7Wwf7gzk0rqn:bmwhnfq) ([raw file](https://github.com/pmem/pmemstream/blob/997d427c13ba00a3eaaea5dc99e6701f116d5e47/src/libpmemstream.c#L101)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

btw, shouldn't this memcpy be nontemporal or something?
</blockquote></details>

Yes, will fix it in another PR.

**Review by KFilipek — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/39)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 25 at r1](https://reviewable.io/reviews/pmem/pmemstream/39#-MrRkgvJCD7X5sCdxFS2:-MrRqXPM0b1Qr5YdhGnd:brn05rh) ([raw file](https://github.com/pmem/pmemstream/blob/997d427c13ba00a3eaaea5dc99e6701f116d5e47/src/libpmemstream.c#L25)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

BTW, we could actually use popcount method in here, instead of passing calculated popcount
</blockquote></details>

Good point, we can hide this logic, can you create PR for this?

**Comment by lukaszstolarczuk** [comment]
> > Reviewed 1 of 1 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/39)_ status: all files reviewed, 3 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)
> 
> _[src/libpmemstream.c, line 25 at r1](https://reviewable.io/reviews/pmem/pmemstream/39#-MrRkgvJCD7X5sCdxFS2:-MrRqXPM0b1Qr5YdhGnd:brn05rh) ([raw file](https://github.com/pmem/pmemstream/blob/997d427c13ba00a3eaaea5dc99e6701f116d5e47/src/libpmemstream.c#L25)):_
> 
> Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…
> Good point, we can hide this logic, can you create PR for this?

yeah, I will.

**Pull request merged**
