### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/49)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/49)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 33 at r2](https://reviewable.io/reviews/pmem/pmemstream/49#-MrcFOrW5Qg63aNwtYU7:-MrcFOrW5Qg63aNwtYU8:bl77j8m) ([raw file](https://github.com/pmem/pmemstream/blob/77311abd72873c5d9d0a0a05a4dd0d258444aa39/src/libpmemstream.c#L33)):*
> ```C
> 
> 	void *dest = ((uint8_t *)span) + SPAN_EMPTY_METADATA_SIZE;
> 	stream->memset(dest, 0, data_size, PMEM2_F_MEM_NODRAIN);
> ```

This should actually have both NONREMPORAL and NODRAIN ;d

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/49)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[src/libpmemstream.c, line 33 at r2](https://reviewable.io/reviews/pmem/pmemstream/49#-MrcFOrW5Qg63aNwtYU7:-Ms-Cdyf8k0CdeMgUv0q:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/77311abd72873c5d9d0a0a05a4dd0d258444aa39/src/libpmemstream.c#L33)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This should actually have both NONREMPORAL and NODRAIN ;d
</blockquote></details>

Done.

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/49)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 47 at r4](https://reviewable.io/reviews/pmem/pmemstream/49#-Ms-Oneg9NtxxHy7cFbO:-Ms-OnehE0WzGq98FmpK:b-enc0k7) ([raw file](https://github.com/pmem/pmemstream/blob/4f0ceb0092b437798cef037e220bec26fd7afcc4/src/libpmemstream.c#L47)):*
> ```C
> 	// XXX - use variadic mempcy to store data and metadata at once
> 	void *dest = ((uint8_t *)span) + SPAN_ENTRY_METADATA_SIZE;
> 	stream->memcpy(dest, data, data_size, PMEM2_F_MEM_NODRAIN);
> ```

Probably we should have `PMEM2_F_MEM_NONTEMPORAL | PMEM2_F_MEM_NODRAIN` here as well

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/49)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[src/libpmemstream.c, line 47 at r4](https://reviewable.io/reviews/pmem/pmemstream/49#-Ms-Oneg9NtxxHy7cFbO:-Ms-V-Qt0qBwfBU3MQhC:b-an1zal) ([raw file](https://github.com/pmem/pmemstream/blob/4f0ceb0092b437798cef037e220bec26fd7afcc4/src/libpmemstream.c#L47)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Probably we should have `PMEM2_F_MEM_NONTEMPORAL | PMEM2_F_MEM_NODRAIN` here as well
</blockquote></details>

done aaand done :wink:

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/49#-:-Ms-VUkh4DYnn15GQXJ6:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @igchor)

**Pull request merged**
