### PR TITLE
bump required clang-format to ver. 11

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
apply new (slightly changed) code formatting and add Ubuntu 22.04 to check cpp formatting (clang-format-11 is provided on that OS).

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/178)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/178)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by karczex — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/178)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`utils/docker/images/ubuntu-22.04.Dockerfile` line 33 at r4](https://reviewable.io/reviews/pmem/pmemstream/178#-N1lRd2W1-R4CLEh5Imk:-N1lRd2X8-07wBS1qPRZ:bbxijpm) ([raw file](https://github.com/pmem/pmemstream/blob/78bcb4d046df52458938c5c3e5e876be48e62b7a/utils/docker/images/ubuntu-22.04.Dockerfile#L33)):*
> ```
> 	${CODECOV_DEPS} \
> 	${MISC_DEPS} \
>     clang-13 \
> ```

Is it intended to be not categorized?

**Review by karczex — COMMENTED** [review]
Please also update https://github.com/pmem/pmemstream/blob/bb36bc8c59c398b2633fc1f93872d4bafd07d1f8/INSTALL.md?plain=1#L31

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/178#-:-N1lUOK93U9yc8oWwqYG:b-2ntium)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
good catch, done.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/178#-:-N1lxLt15j7rF8VyvH7I:b1jxzi3)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)

___
*[`utils/docker/images/ubuntu-22.04.Dockerfile` line 33 at r4](https://reviewable.io/reviews/pmem/pmemstream/178#-N1lRd2W1-R4CLEh5Imk:-N1lxO5qCCFOwpHmiA8q:b6uta8z) ([raw file](https://github.com/pmem/pmemstream/blob/78bcb4d046df52458938c5c3e5e876be48e62b7a/utils/docker/images/ubuntu-22.04.Dockerfile#L33)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Is it intended to be not categorized?
</blockquote></details>

yeah, I think this way we'll be reminded to remove it (sooner or later) :wink:

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/178#-:-N1wvAlSDCdwoDZosIyh:bnfp4nl)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)

**Pull request merged**
