### PR TITLE
Fix TESTS_USE_FORCED_PMEM

### PR DESCRIPTION
**Pull request by igchor**
Use PMEM2_FORCE_GRANULARITY variable instead of PMEM_IS_PMEM_FORCE
which was ignored (it only worked for pmem 1.0)

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/155)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/155)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/155#-MzFPQuo3VPuYK5qacv3:-MzFPQuo3VPuYK5qacv4:bgmzqd9) (no related file):*
please update top-level CMake - definition of TESTS_USE_FORCED_PMEM

---
___
*[tests/cmake/exec_functions.cmake, line 213 at r1](https://reviewable.io/reviews/pmem/pmemstream/155#-MzFKrq94sSFrw8oTZml:-MzFKrq94sSFrw8oTZmm:bdd595h) ([raw file](https://github.com/pmem/pmemstream/blob/81d894f581b61bfe44a42343c012f441685798bf/tests/cmake/exec_functions.cmake#L213)):*
> ```CMake
> 
> 	if(TESTS_USE_FORCED_PMEM)
> 		unset(ENV{PMEM2_FORCE_GRANULARITY})
> ```

perhaps we should set the original value (saved beforehand)...?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/155)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/155#-MzFPQuo3VPuYK5qacv3:-MzFYF_L3OGDc2alEzlt:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please update top-level CMake - definition of TESTS_USE_FORCED_PMEM
</blockquote></details>

Done.

---
___
*[tests/cmake/exec_functions.cmake, line 213 at r1](https://reviewable.io/reviews/pmem/pmemstream/155#-MzFKrq94sSFrw8oTZml:-MzFYC007fIYeRKRjaoF:b-fb5zzr) ([raw file](https://github.com/pmem/pmemstream/blob/81d894f581b61bfe44a42343c012f441685798bf/tests/cmake/exec_functions.cmake#L213)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps we should set the original value (saved beforehand)...?
</blockquote></details>

I don';t think this is necessary, ctest runs in separate process anyway

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/155)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @igchor)

___
*[tests/cmake/exec_functions.cmake, line 213 at r1](https://reviewable.io/reviews/pmem/pmemstream/155#-MzFKrq94sSFrw8oTZml:-MzFa5HZ7fbcHfoj1ahR:bfdzbww) ([raw file](https://github.com/pmem/pmemstream/blob/81d894f581b61bfe44a42343c012f441685798bf/tests/cmake/exec_functions.cmake#L213)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I don';t think this is necessary, ctest runs in separate process anyway
</blockquote></details>

if you say so... :smile: :+1: 
___
*[tests/cmake/exec_functions.cmake, line 108 at r2](https://reviewable.io/reviews/pmem/pmemstream/155#-MzFcrX94ss3NT3NFubu:-MzFcrX94ss3NT3NFubv:b-4qbazd) ([raw file](https://github.com/pmem/pmemstream/blob/5e1ba3f01770f854f9ff114b59ecd5563d9e81b1/tests/cmake/exec_functions.cmake#L108)):*
> ```CMake
> 
> 	if(${TRACER} STREQUAL pmemcheck)
> 		if(TESTS_USE_FORCED_PMEM)
> ```

I'm not sure if this is a #goodchange :wink: 

1. in case you want to  setup granularity by your upper layer you will have to set TESTS_USE_FORCED_PMEM to 0 anyway (so these few lines will do nothing)

2. in case you're running a regular build, I guess, you don't want the "PMEM2_FORCE_GRNULARITY" to be set (if this is really a slow down for pmemcheck)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/155)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[tests/cmake/exec_functions.cmake, line 108 at r2](https://reviewable.io/reviews/pmem/pmemstream/155#-MzFcrX94ss3NT3NFubu:-MzFhIX_D9ktQk1ip3d3:b90ijm) ([raw file](https://github.com/pmem/pmemstream/blob/5e1ba3f01770f854f9ff114b59ecd5563d9e81b1/tests/cmake/exec_functions.cmake#L108)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure if this is a #goodchange :wink: 

1. in case you want to  setup granularity by your upper layer you will have to set TESTS_USE_FORCED_PMEM to 0 anyway (so these few lines will do nothing)

2. in case you're running a regular build, I guess, you don't want the "PMEM2_FORCE_GRNULARITY" to be set (if this is really a slow down for pmemcheck)
</blockquote></details>

1. We can extend this change later by allowing different values to TESTS_USE_FORCED_PMEM (e.g. 0 = no change, 1 = CACHE_LINE for compatibility and CACHE_LINE, BYTE and PAGE)
2. Actually, on my machine setting granularity sped up the build (on /dev/shm at least).

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/155#-:-MzJgfnCBbMWowERUqNk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

___
*[tests/cmake/exec_functions.cmake, line 108 at r2](https://reviewable.io/reviews/pmem/pmemstream/155#-MzFcrX94ss3NT3NFubu:-MzJgULd0MwcehmTLE9i:b-5i58g5) ([raw file](https://github.com/pmem/pmemstream/blob/5e1ba3f01770f854f9ff114b59ecd5563d9e81b1/tests/cmake/exec_functions.cmake#L108)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

1. We can extend this change later by allowing different values to TESTS_USE_FORCED_PMEM (e.g. 0 = no change, 1 = CACHE_LINE for compatibility and CACHE_LINE, BYTE and PAGE)
2. Actually, on my machine setting granularity sped up the build (on /dev/shm at least).
</blockquote></details>

ok then :+1: 

as for 0/1 - I'm not sure if we need to support compatibility :wink:

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/155#-:-MzL-OTdC6FWlKf_qERl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
