### PR TITLE
add ChangeLog entry for 0.2.0 release

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/215)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/215)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[`ChangeLog` line 10 at r1](https://reviewable.io/reviews/pmem/pmemstream/215#-N4bPFJNAbh3WCEAZ6kJ:-N4bPFJNAbh3WCEAZ6kK:bwhfw9t) ([raw file](https://github.com/pmem/pmemstream/blob/ebbaa5af57591f00c99841eee84fcb0d2fd8e245/ChangeLog#L10)):*
> ```
> 
> 	New features:
> 	- Asynchronous API using libminiasync (https://github.com/pmem/miniasync)
> ```

which/that uses? but I'm not sure
___
*[`ChangeLog` line 11 at r1](https://reviewable.io/reviews/pmem/pmemstream/215#-N4bO_D4De6yNny82vxR:-N4bO_D4De6yNny82vxS:b-tsfxqn) ([raw file](https://github.com/pmem/pmemstream/blob/ebbaa5af57591f00c99841eee84fcb0d2fd8e245/ChangeLog#L11)):*
> ```
> 	New features:
> 	- Asynchronous API using libminiasync (https://github.com/pmem/miniasync)
> 		for concurrently appending data to the stream (currently, only one thread can append
> ```

"currently, only one thread can append to a single region"

This might be interpreted as "at any point, there can only be one operation - appending from single thread to single region". Maybe something like "currently, multiple threads can append data concurrently to different regions but no two threads can append to the same one". Or something similar?
___
*[`ChangeLog` line 17 at r1](https://reviewable.io/reviews/pmem/pmemstream/215#-N4bPLkcBxRAPQjZXLlx:-N4bPLkcBxRAPQjZXLly:b21nqq4) ([raw file](https://github.com/pmem/pmemstream/blob/ebbaa5af57591f00c99841eee84fcb0d2fd8e245/ChangeLog#L17)):*
> ```
> 		for reading and/or for persistency guarantee.
> 	- Changed region and entry iterators API. It now provides `seek_first`, `next`, and `is_valid`
> 		functions for both types of iterators. It allows better flexibility.
> ```

offers higher flexibility

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/215)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @igchor)

___
*[`ChangeLog` line 10 at r1](https://reviewable.io/reviews/pmem/pmemstream/215#-N4bPFJNAbh3WCEAZ6kJ:-N4bTeMf7ub8hRCzUEHy:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ebbaa5af57591f00c99841eee84fcb0d2fd8e245/ChangeLog#L10)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

which/that uses? but I'm not sure
</blockquote></details>

Done.
___
*[`ChangeLog` line 11 at r1](https://reviewable.io/reviews/pmem/pmemstream/215#-N4bO_D4De6yNny82vxR:-N4bTrnu5sukL0txFHaz:bfpcr7w) ([raw file](https://github.com/pmem/pmemstream/blob/ebbaa5af57591f00c99841eee84fcb0d2fd8e245/ChangeLog#L11)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

"currently, only one thread can append to a single region"

This might be interpreted as "at any point, there can only be one operation - appending from single thread to single region". Maybe something like "currently, multiple threads can append data concurrently to different regions but no two threads can append to the same one". Or something similar?
</blockquote></details>

I think you're right, we should be more verbose - thx!
___
*[`ChangeLog` line 17 at r1](https://reviewable.io/reviews/pmem/pmemstream/215#-N4bPLkcBxRAPQjZXLlx:-N4bTgAx6U2k0lkBW4Qj:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ebbaa5af57591f00c99841eee84fcb0d2fd8e245/ChangeLog#L17)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

offers higher flexibility
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/215#-:-N4bab6J80hEHBNhMujb:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @igchor)

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/215#-:-N5-oM7B6EnrQmvWDhuK:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @igchor)

**Review by KFilipek — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/215)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
