### PR TITLE
Fix: Copy just pmemstream signature text instead of whole block

### PR DESCRIPTION
**Pull request by KFilipek**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/26)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/26)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor and @karczex)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/26)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)

___
*[src/libpmemstream.c, line 98 at r1](https://reviewable.io/reviews/pmem/pmemstream/26#-MqZEUmlC1ENyFQkGC4-:-MqZEUmlC1ENyFQkGC40:b-9t7g8z) ([raw file](https://github.com/pmem/pmemstream/blob/f4ce9f82d35ebed547dc4d2a48273f51a0bb95da/src/libpmemstream.c#L98)):*
> ```C
> 
> struct pmemstream_header {
> 	char signature[PMEMSTREAM_SIGNATURE_LEN];
> ```

nit: you could rename PMEMSTREAM_SIGNATURE_LEN to something like PMEMSTREAM_SIGNATURE_CAPACITY maybe or somrhing similar? LEN is kind of confusing

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/26#-:-MqZFOWz8MU9zuj5-C8V:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/26#-:-MqnSayb-EWASNDrdhkD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
