### PR TITLE
Clang format

### PR DESCRIPTION
**Pull request by karczex**
Dear reader, 
Is such formatting good looking in your IDE? 
Do you want to change any clang-format settings?

TODO:
- [x]  Wait for https://github.com/pmem/pmemstream/pull/7 to be merged
- [x] Wait for https://github.com/pmem/pmemstream/pull/10 to bo merged
- [x] Rebase and reformat

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/13)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> Reviewed 3 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/13)* status: 3 of 12 files reviewed, 2 unresolved discussions (waiting on @igchor and @karczex)

___
*[.clang-format, line 1 at r1](https://reviewable.io/reviews/pmem/pmemstream/13#-MpHG57SC8nrgopu4enK:-MpHG57SC8nrgopu4enL:b7lhtn5) ([raw file](https://github.com/pmem/pmemstream/blob/596aaacd073b2172ccaab76d10d35a346f472f64/.clang-format#L1)):*
> ```YAML
> AccessModifierOffset: -7
> ```

Why it's negative and different than in libpmemobj-cpp?
___
*[src/ravl.h, line 21 at r1](https://reviewable.io/reviews/pmem/pmemstream/13#-MpHGUwK24549nS-lNfJ:-MpHGUwK24549nS-lNfK:b-1896bi) ([raw file](https://github.com/pmem/pmemstream/blob/596aaacd073b2172ccaab76d10d35a346f472f64/src/ravl.h#L21)):*
> ```objc
> 
> enum ravl_predicate {
> 	RAVL_PREDICATE_EQUAL = 1 << 0,
> ```

What do you think about aligning such assignments? There seems to be `AlignConsecutiveAssignments` option

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/13)* status: 3 of 12 files reviewed, 3 unresolved discussions (waiting on @igchor and @karczex)

___
*[.clang-format, line 8 at r1](https://reviewable.io/reviews/pmem/pmemstream/13#-MpHH0cNAy2XxCxJFdMa:-MpHG6tG6HPds5xng0ur:bigqz26) ([raw file](https://github.com/pmem/pmemstream/blob/596aaacd073b2172ccaab76d10d35a346f472f64/.clang-format#L8)):*
> ```YAML
> AlwaysBreakAfterDefinitionReturnType: false
> AlwaysBreakTemplateDeclarations: true
> BasedOnStyle: LLVM
> ```

nit: since you don't follow alphabetical oreder, I'd put this on top

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/13)* status: 3 of 12 files reviewed, 4 unresolved discussions (waiting on @igchor and @karczex)

___
*[.clang-format, line 1 at r1](https://reviewable.io/reviews/pmem/pmemstream/13#-MpHG57SC8nrgopu4enK:-MpHPKIK4jg1fFo8jEQ6:b-v1qw94) ([raw file](https://github.com/pmem/pmemstream/blob/596aaacd073b2172ccaab76d10d35a346f472f64/.clang-format#L1)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Why it's negative and different than in libpmemobj-cpp?
</blockquote></details>

It should be -8 to align access modifier with class keyword (because of  IndentWidth: 8). 
To be honest, I like -7 as it adds 1 space indentation for access modifiers. It gives better encapsulation vibe :) 
___
*[.clang-format, line 26 at r1](https://reviewable.io/reviews/pmem/pmemstream/13#-MpHOIZy3TLd-YRU-NZY:-MpHOIZy3TLd-YRU-NZZ:b-gpgkff) ([raw file](https://github.com/pmem/pmemstream/blob/596aaacd073b2172ccaab76d10d35a346f472f64/.clang-format#L26)):*
> ```YAML
> ConstructorInitializerAllOnOneLineOrOnePerLine: true
> ContinuationIndentWidth: 8
> FixNamespaceComments: false
> ```

What do you think of enabling it? It seems to be cool feature. 
___
*[src/ravl.h, line 21 at r1](https://reviewable.io/reviews/pmem/pmemstream/13#-MpHGUwK24549nS-lNfJ:-MpHMWKlCGM7O7EX7qMg:b-vdjm5q) ([raw file](https://github.com/pmem/pmemstream/blob/596aaacd073b2172ccaab76d10d35a346f472f64/src/ravl.h#L21)):*
> AlignConsecutiveAssignments
It looks good in structs definitions, but it adds also extra whitespaces in the middle of assignments in functions, which looks little bit messy
```C
static struct pmemstream_span_runtime pmemstream_span_get_runtime(struct pmemstream_span *span)               
   79 {                                                                                                             
   80 »       struct pmemstream_span_runtime sr;                                                                                                                                                                                              
   81 »       sr.type»       = span->type_extra & PMEMSTREAM_SPAN_TYPE_MASK;                                        
   82 »       uint64_t extra = span->type_extra & PMEMSTREAM_SPAN_EXTRA_MASK;                                       
   83 »       switch (sr.type) {                                                                                    
   84 »       »       case PMEMSTREAM_SPAN_FREE:                                                                    
   85 »       »       »       sr.free.size  = extra;         
```
 (» is tab character)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/13)* status: 3 of 12 files reviewed, 2 unresolved discussions (waiting on @igchor and @karczex)

___
*[.clang-format, line 26 at r1](https://reviewable.io/reviews/pmem/pmemstream/13#-MpHOIZy3TLd-YRU-NZY:-MpH_NxW4YXUjx7If9Me:bii3zqk) ([raw file](https://github.com/pmem/pmemstream/blob/596aaacd073b2172ccaab76d10d35a346f472f64/.clang-format#L26)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

What do you think of enabling it? It seems to be cool feature. 
</blockquote></details>

It's pretty nice, we just need to be consistent between // and /**/
___
*[src/ravl.h, line 21 at r1](https://reviewable.io/reviews/pmem/pmemstream/13#-MpHGUwK24549nS-lNfJ:-MpHZpp9D8HQ3hxCMRZH:bgnxvmq) ([raw file](https://github.com/pmem/pmemstream/blob/596aaacd073b2172ccaab76d10d35a346f472f64/src/ravl.h#L21)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

> AlignConsecutiveAssignments
It looks good in structs definitions, but it adds also extra whitespaces in the middle of assignments in functions, which looks little bit messy
```C
static struct pmemstream_span_runtime pmemstream_span_get_runtime(struct pmemstream_span *span)               
   79 {                                                                                                             
   80 »       struct pmemstream_span_runtime sr;                                                                                                                                                                                              
   81 »       sr.type»       = span->type_extra & PMEMSTREAM_SPAN_TYPE_MASK;                                        
   82 »       uint64_t extra = span->type_extra & PMEMSTREAM_SPAN_EXTRA_MASK;                                       
   83 »       switch (sr.type) {                                                                                    
   84 »       »       case PMEMSTREAM_SPAN_FREE:                                                                    
   85 »       »       »       sr.free.size  = extra;         
```
 (» is tab character)


</blockquote></details>

Yeah, in that case it's better to not add this

**Review by lukaszstolarczuk — COMMENTED** [review]
it works fine with my clang-format-9 on Ubuntu 21.10

> Reviewed 3 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/13#-:-MpMP1bw0pkvA4Gi9bbV:bfvt0rr)* status: 5 of 12 files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/13#-MpMPoAs4MHjkr49NclX:-MpMPoAs4MHjkr49NclY:b-9jhxz7) (no related file):*
Please update INSTALL.md with the required version (in the CMake I can see we look for `9`)

---
*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/13#-MpMPvh718xIi8WtROQ8:-MpMPvh718xIi8WtROQ9:b-8o9i1t) (no related file):*
Please update CONTRIBUTING.md#code-style

---
___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/pmem/pmemstream/13#-MpMPMQ-B9vyui1X2jfU):*
what do you mean by "silent fails"?
___
*[.clang-format, line 26 at r1](https://reviewable.io/reviews/pmem/pmemstream/13#-MpHOIZy3TLd-YRU-NZY:-MpMPJs3C8Otso_jUVIL:b-8fx2u7) ([raw file](https://github.com/pmem/pmemstream/blob/596aaacd073b2172ccaab76d10d35a346f472f64/.clang-format#L26)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

It's pretty nice, we just need to be consistent between // and /**/
</blockquote></details>

:+1:

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/13)* status: 1 of 18 files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/13#-MpMPvh718xIi8WtROQ8:-MpRbwHJ1lxXWFyYktLO:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Please update CONTRIBUTING.md#code-style
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/13#-MpMPoAs4MHjkr49NclX:-MpRcukG6fpnUP0jAuzL:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Please update INSTALL.md with the required version (in the CMake I can see we look for `9`)
</blockquote></details>

Done.

---
___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/pmem/pmemstream/13#-MpMPMQ-B9vyui1X2jfU):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what do you mean by "silent fails"?
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 4 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/13#-:-MpRfc3l3LSnw9xiu5Id:bnfp4nl)* status: 5 of 18 files reviewed, all discussions resolved (waiting on @igchor and @lukaszstolarczuk)

**Pull request merged**
