### PR TITLE
CI

### PR DESCRIPTION
**Pull request by karczex**
Needs a lot of cleanup, but is green, which is nice

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/4)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
much cleanup ahead, but looks good

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/4#-:-Mo-PpyZE6WrCVfI1qFz:b-veja99)* status: 0 of 13 files reviewed, 7 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 194 at r1](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo-PmbTBAZgRzLEajHs:-Mo-PmbTBAZgRzLEajHt:b-6in6pp) ([raw file](https://github.com/pmem/pmemstream/blob/7fbc45f7331e9747d26b754e8ed6b66f8d1d65ff/CMakeLists.txt#L194)):*
> ```CMake
> if(CHECK_CPP_STYLE)
> 	# XXX: update this, when clang format version is picked, and probably check min. version only
> 	find_program(CLANG_FORMAT NAMES clang-format-9 clang-format-9.0 clang-format) # XXX: add more versions and/or program names?
> ```

comment in this line can now be gone
___
*[.github/workflows/gha.yml, line 1 at r1](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo-Pe2V-FixlffYeQKF:-Mo-Pe2V-FixlffYeQKG:b-lcyj32) ([raw file](https://github.com/pmem/pmemstream/blob/7fbc45f7331e9747d26b754e8ed6b66f8d1d65ff/.github/workflows/gha.yml#L1)):*
> ```YAML
> name: Basic Tests
> ```

I guess we could rename this file as well, what is this "gha.yml" name :smile:  :wink: 
___
*[.github/workflows/gha.yml, line 14 at r1](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo-Nht501V4Nixh2xC-:-Mo-Nht501V4Nixh2xC0:b-kqi314) ([raw file](https://github.com/pmem/pmemstream/blob/7fbc45f7331e9747d26b754e8ed6b66f8d1d65ff/.github/workflows/gha.yml#L14)):*
> ```YAML
> env:
>   REPO:           pmemstream
>   GITHUB_REPO:    ${{ github.repository }}
> ```

there was some issue with using this variable here - I guess we should use old-fashioned `pmem/pmemstream`
___
*[.github/workflows/gha.yml, line 15 at r1](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo-PZ0YDzbcS4ldqF_Q:-Mo-PZ0YDzbcS4ldqF_R:b9hvaai) ([raw file](https://github.com/pmem/pmemstream/blob/7fbc45f7331e9747d26b754e8ed6b66f8d1d65ff/.github/workflows/gha.yml#L15)):*
> ```YAML
>   REPO:           pmemstream
>   GITHUB_REPO:    ${{ github.repository }}
>   CONTAINER_REG:  ghcr.io/pmem/pmemkv
> ```

if you want to leave this for now, then pls leave some comment
___
*[.github/workflows/gha.yml, line 36 at r1](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo-NtPBCZqzaCNg8SuE:-Mo-NtPBCZqzaCNg8SuF:bmfksey) ([raw file](https://github.com/pmem/pmemstream/blob/7fbc45f7331e9747d26b754e8ed6b66f8d1d65ff/.github/workflows/gha.yml#L36)):*
> ```YAML
>                  #"TYPE=release OS=fedora OS_VER=34",
>                  "TYPE=release OS=ubuntu OS_VER=20.04",
>                  #"TYPE=valgrind OS=ubuntu OS_VER=20.04 TESTS_VALGRIND_UNWIND=0",
> ```

these UNWIND vars are redundant here, they won't be useful (see https://github.com/pmem/libpmemobj-cpp/pull/1227 )
___
*[utils/check_whitespace, line 3 at r1](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo-O8xiAN2f8CR5Md1F:-Mo-O8xiAN2f8CR5Md1G:b-8mxykb) ([raw file](https://github.com/pmem/pmemstream/blob/7fbc45f7331e9747d26b754e8ed6b66f8d1d65ff/utils/check_whitespace#L3)):*
> ```
> #!/usr/bin/env perl
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2015-2018, Intel Corporation
> ```

-2021
___
*[utils/docker/build.sh, line 96 at r1](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo-OeB48g5psNpotore:-Mo-OeB48g5psNpotorf:b-7u99kh) ([raw file](https://github.com/pmem/pmemstream/blob/7fbc45f7331e9747d26b754e8ed6b66f8d1d65ff/utils/docker/build.sh#L96)):*
> ```Shell
> echo "COMMAND to execute within Docker container: ${COMMAND}"
> 
> #XXX: Add coverity?
> ```

FYI, coverity =/= coverage :smile: 

both of these can be added separately, this is quite big PR already
___
*[utils/docker/build.sh, line 133 at r1](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo-OuND9zsvdroRtb4I:-Mo-OuND9zsvdroRtb4J:b-igzbe8) ([raw file](https://github.com/pmem/pmemstream/blob/7fbc45f7331e9747d26b754e8ed6b66f8d1d65ff/utils/docker/build.sh#L133)):*
> ```Shell
> 	--env CHECK_CPP_STYLE=${CHECK_CPP_STYLE:-OFF} \
> 	--env DEFAULT_TEST_DIR=/mnt/pmem \
> 	--env TESTS_PACKAGES=${TESTS_PACKAGES:-ON} \
> ```

I'm not sure if we use this var anyhow (it was copied from PMDK, I guess)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 6 of 13 files at r1, 4 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/4)* status: 10 of 14 files reviewed, 8 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[utils/check_whitespace, line 3 at r1](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo-O8xiAN2f8CR5Md1F:-Mo88HHL8oqgGo5ry7EB:b40gcv8) ([raw file](https://github.com/pmem/pmemstream/blob/7fbc45f7331e9747d26b754e8ed6b66f8d1d65ff/utils/check_whitespace#L3)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Are you sure? I didn't change this file.
</blockquote></details>

I'm not 100% sure, but you touched it and committed in 2021, so the dates are incorrect here (that's my understanding and I did similarly in my PR :wink: )
___
*[utils/cppstyle, line 3 at r2](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo89U7i4GXubqWVJgWm:-Mo89U7i4GXubqWVJgWn:b3kqx) ([raw file](https://github.com/pmem/pmemstream/blob/51330adccfc850dd774a9c20f097e76c26ab3763/utils/cppstyle#L3)):*
> ```
> #!/usr/bin/perl -w
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2017, Intel Corporation
> ```

.
___
*[utils/check_license/file-exceptions.sh, line 9 at r2](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo89bOVDTsO4Dkl06x1:-Mo89bOVDTsO4Dkl06x2:blg00p6) ([raw file](https://github.com/pmem/pmemstream/blob/51330adccfc850dd774a9c20f097e76c26ab3763/utils/check_license/file-exceptions.sh#L9)):*
> ```Shell
> 
> grep -v -E -e 'tests/external/libcxx/'
> grep -v -E -e 'include/libpmemobj++/detail/ebr.hpp/'
> ```

:wink: 
___
*[utils/docker/build.sh, line 7 at r2](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo8AEvtAEi2roUydVak:-Mo8AEvtAEi2roUydVal:b18bepj) ([raw file](https://github.com/pmem/pmemstream/blob/51330adccfc850dd774a9c20f097e76c26ab3763/utils/docker/build.sh#L7)):*
> ```Shell
> #
> # build.sh - runs a Docker container from a Docker image with environment
> #		prepared for running libpmemobj-cpp builds and tests. It uses Docker image
> ```

obj-cpp :wink: 
___
*[utils/docker/build.sh, line 28 at r2](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo8AJe0E0p35EZ9_lyF:-Mo8AJe0E0p35EZ9_lyG:b-txk4da) ([raw file](https://github.com/pmem/pmemstream/blob/51330adccfc850dd774a9c20f097e76c26ab3763/utils/docker/build.sh#L28)):*
> ```Shell
> TAG="${OS}-${OS_VER}-${IMG_VER}"
> IMAGE_NAME=${CONTAINER_REG}:${TAG}
> CONTAINER_NAME=pmemkv-${OS}-${OS_VER}
> ```

pls add comment with `XXX` to most likely fix it later
___
*[utils/docker/run-build.sh, line 20 at r2](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo8B-QZ-6M66rYRVHOS:-Mo8B-QZ-6M66rYRVHOT:bb7lgjf) ([raw file](https://github.com/pmem/pmemstream/blob/51330adccfc850dd774a9c20f097e76c26ab3763/utils/docker/run-build.sh#L20)):*
> ```Shell
> CHECK_CPP_STYLE=${CHECK_CPP_STYLE:-ON}
> TESTS_LONG=${TESTS_LONG:-OFF}
> TESTS_TBB=${TESTS_TBB:-ON}
> ```

nope
___
*[utils/docker/run-build.sh, line 22 at r2](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo8B0OL7SGCq8R0A8NJ:-Mo8B0OL7SGCq8R0A8NK:b-cbcvd) ([raw file](https://github.com/pmem/pmemstream/blob/51330adccfc850dd774a9c20f097e76c26ab3763/utils/docker/run-build.sh#L22)):*
> ```Shell
> TESTS_TBB=${TESTS_TBB:-ON}
> TESTS_PMREORDER=${TESTS_PMREORDER:-ON}
> TESTS_PACKAGES=${TESTS_PACKAGES:-ON}
> ```

nope(?)
___
*[utils/docker/run-build.sh, line 26 at r2](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo8B2IsAPXB1ltb0iz5:-Mo8B2IsAPXB1ltb0iz6:bb7lgjf) ([raw file](https://github.com/pmem/pmemstream/blob/51330adccfc850dd774a9c20f097e76c26ab3763/utils/docker/run-build.sh#L26)):*
> ```Shell
> TESTS_ASAN=${TESTS_ASAN:-OFF}
> TESTS_UBSAN=${TESTS_UBSAN:-OFF}
> TESTS_VALGRIND_UNWIND=${TESTS_VALGRIND_UNWIND:-OFF}
> ```

nope

**Comment by karczex** [comment]
___
*[utils/docker/run-build.sh, line 20 at r2](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo8B-QZ-6M66rYRVHOS:-MocFm_b-XtSMOOlLTsB:b8b25vt) ([raw file](https://github.com/pmem/pmemstream/blob/51330adccfc850dd774a9c20f097e76c26ab3763/utils/docker/run-build.sh#L20)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

nope
</blockquote></details>

Why not?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/4)* status: 7 of 16 files reviewed, 8 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[utils/docker/run-build.sh, line 20 at r2](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo8B-QZ-6M66rYRVHOS:-MocGvpyBIQZXN08dkQ4:b-ibmyd1) ([raw file](https://github.com/pmem/pmemstream/blob/51330adccfc850dd774a9c20f097e76c26ab3763/utils/docker/run-build.sh#L20)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Why not?
</blockquote></details>

TBB? on this repo? :wink:

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/4)* status: 3 of 22 files reviewed, 8 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/check_whitespace, line 3 at r1](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo-O8xiAN2f8CR5Md1F:-Mod7duW6xWf0g9H_Qfa:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7fbc45f7331e9747d26b754e8ed6b66f8d1d65ff/utils/check_whitespace#L3)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not 100% sure, but you touched it and committed in 2021, so the dates are incorrect here (that's my understanding and I did similarly in my PR :wink: )
</blockquote></details>

Done.
___
*[utils/cppstyle, line 3 at r2](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo89U7i4GXubqWVJgWm:-Mod7iYa3NHWRWJBmotb:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/51330adccfc850dd774a9c20f097e76c26ab3763/utils/cppstyle#L3)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/check_license/file-exceptions.sh, line 9 at r2](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo89bOVDTsO4Dkl06x1:-Mod7w-B38kRYv8o7-Fq:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/51330adccfc850dd774a9c20f097e76c26ab3763/utils/check_license/file-exceptions.sh#L9)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

:wink: 
</blockquote></details>

Done.
___
*[utils/docker/build.sh, line 7 at r2](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo8AEvtAEi2roUydVak:-ModABLtDLBsNFZQxz8Z:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/51330adccfc850dd774a9c20f097e76c26ab3763/utils/docker/build.sh#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

obj-cpp :wink: 
</blockquote></details>

Done.
___
*[utils/docker/build.sh, line 28 at r2](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo8AJe0E0p35EZ9_lyF:-ModASK73DsepnGp0Jso:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/51330adccfc850dd774a9c20f097e76c26ab3763/utils/docker/build.sh#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add comment with `XXX` to most likely fix it later
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 20 at r2](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo8B-QZ-6M66rYRVHOS:-Mocq1B6AFu95RWoz5i9:bxq5d90) ([raw file](https://github.com/pmem/pmemstream/blob/51330adccfc850dd774a9c20f097e76c26ab3763/utils/docker/run-build.sh#L20)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

TBB? on this repo? :wink: 
</blockquote></details>

That's why I removed it. 
___
*[utils/docker/run-build.sh, line 22 at r2](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo8B0OL7SGCq8R0A8NJ:-ModAd7HEfEcDanBA1Mn:bjfl5oj) ([raw file](https://github.com/pmem/pmemstream/blob/51330adccfc850dd774a9c20f097e76c26ab3763/utils/docker/run-build.sh#L22)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

nope(?)
</blockquote></details>

As I see now, this variable is pointless in general. Why was it introduced in libpmemobj-cpp?
___
*[utils/docker/run-build.sh, line 26 at r2](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo8B2IsAPXB1ltb0iz5:-ModBV2e2aDvR8WFzbmU:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/51330adccfc850dd774a9c20f097e76c26ab3763/utils/docker/run-build.sh#L26)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

nope
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 8 files at r3, 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/4)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex)

___
*[utils/docker/pull-or-rebuild-image.sh, line 110 at r4](https://reviewable.io/reviews/pmem/pmemstream/4#-ModbBGf28wxDNk0Jemv:-ModbBGf28wxDNk0Jemw:bnlnbve) ([raw file](https://github.com/pmem/pmemstream/blob/44aa655fa3b1f57dce17c84992d85a3b1fb2b3fd/utils/docker/pull-or-rebuild-image.sh#L110)):*
> ```Shell
> for file in ${files}; do
> 	# Check if modified files are relevant to the current build
> 	if [[ ${file} =~ ^(${BASE_DIR})\/(${OS})-(${OS_VER}/.Dockerfile)$ ]] \
> ```

is the `.` properly escaped here (`/.Dockerfile`)
___
*[utils/docker/run-build.sh, line 20 at r2](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo8B-QZ-6M66rYRVHOS:-ModbVQvEbfgIPtjbzF9:b-64jklb) ([raw file](https://github.com/pmem/pmemstream/blob/51330adccfc850dd774a9c20f097e76c26ab3763/utils/docker/run-build.sh#L20)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

That's why I removed it. 
</blockquote></details>

maybe my comment was given to the wrong revision, nvm
___
*[utils/docker/run-build.sh, line 22 at r2](https://reviewable.io/reviews/pmem/pmemstream/4#-Mo8B0OL7SGCq8R0A8NJ:-Modbe5i4ZnZhJLdXGAF:b-d3tb2) ([raw file](https://github.com/pmem/pmemstream/blob/51330adccfc850dd774a9c20f097e76c26ab3763/utils/docker/run-build.sh#L22)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

As I see now, this variable is pointless in general. Why was it introduced in libpmemobj-cpp?
</blockquote></details>

probably "shamelessly" copy-pasted :wink: 

there's just too many of them... it will keep happening, I guess
___
*[utils/docker/run-build.sh, line 199 at r4](https://reviewable.io/reviews/pmem/pmemstream/4#-ModcGUtCJAO5ax1QQIF:-ModcGUtCJAO5ax1QQIG:b-10d1ho) ([raw file](https://github.com/pmem/pmemstream/blob/44aa655fa3b1f57dce17c84992d85a3b1fb2b3fd/utils/docker/run-build.sh#L199)):*
> ```Shell
> 		-DTESTS_USE_VALGRIND=0 \
> 		-DTESTS_LONG=OFF \
> 		-DTESTS_PMREORDER=OFF \
> ```

you removed this variable as well
___
*[utils/docker/run-build.sh, line 228 at r4](https://reviewable.io/reviews/pmem/pmemstream/4#-ModcWQZ-rB0fmqaUuEs:-ModcWQZ-rB0fmqaUuEt:b-tqdph7) ([raw file](https://github.com/pmem/pmemstream/blob/44aa655fa3b1f57dce17c84992d85a3b1fb2b3fd/utils/docker/run-build.sh#L228)):*
> ```Shell
> 
> 	# Remove pkg-config and force cmake to use find_package while compiling example
> 	if [ ${PACKAGE_MANAGER} = "deb" ]; then
> ```

yeah, we rather won't use this test, since we don't provide "FindLIBPMEMSTREAM.cmake" - you can remove this block up to the end of this function

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/4)* status: 20 of 22 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/docker/pull-or-rebuild-image.sh, line 110 at r4](https://reviewable.io/reviews/pmem/pmemstream/4#-ModbBGf28wxDNk0Jemv:-ModfE9n2PDRNl-RTo_G:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/44aa655fa3b1f57dce17c84992d85a3b1fb2b3fd/utils/docker/pull-or-rebuild-image.sh#L110)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

is the `.` properly escaped here (`/.Dockerfile`)
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 199 at r4](https://reviewable.io/reviews/pmem/pmemstream/4#-ModcGUtCJAO5ax1QQIF:-ModeNxC-Ks8xSbfIh_x:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/44aa655fa3b1f57dce17c84992d85a3b1fb2b3fd/utils/docker/run-build.sh#L199)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you removed this variable as well
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 228 at r4](https://reviewable.io/reviews/pmem/pmemstream/4#-ModcWQZ-rB0fmqaUuEs:-ModerRR8nIT6hHUh-wr:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/44aa655fa3b1f57dce17c84992d85a3b1fb2b3fd/utils/docker/run-build.sh#L228)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

yeah, we rather won't use this test, since we don't provide "FindLIBPMEMSTREAM.cmake" - you can remove this block up to the end of this function
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/4#-:-ModhdyQ3KuTVZWOEbTQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by KFilipek — APPROVED** [review]
> Reviewed 3 of 13 files at r1, 2 of 8 files at r3, 12 of 15 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
