### PR TITLE
Set TSAN jobs on CI

### PR DESCRIPTION
**Pull request by KFilipek**
## Important notice
Drop commit `c478eccc` when #241 is merged.

## Description
Add following TSAN jobs on GitHub Actions:
- TYPE=debug OS=ubuntu OS_VER=22.04 TESTS_TSAN=1 TESTS_PMREORDER=0
- TYPE=debug OS=fedora OS_VER=35 TESTS_TSAN=1 TESTS_PMREORDER=0

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/238)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/238)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @igchor)

___
*[`utils/docker/run-build.sh` line 26 at r2](https://reviewable.io/reviews/pmem/pmemstream/238#-N6IzBi-5VMB2QpXA_8M:-N6IzBi-5VMB2QpXA_8N:b-m4n8u5) ([raw file](https://github.com/pmem/pmemstream/blob/afd947e701f8b0c3bf4e6b556dfe1fc5226ceda9/utils/docker/run-build.sh#L26)):*
> ```Shell
> TEST_TIMEOUT=${TEST_TIMEOUT:-600}
> TESTS_PMREORDER=${TESTS_PMREORDER:-ON}
> TESTS_LIBUNWIND=${TESTS_LIBUNWIND:-1}
> ```

for consistency: "ON"

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/238)* status: all files reviewed, 3 unresolved discussions (waiting on @KFilipek)

___
*[`-- commits` line 11 at r2](https://reviewable.io/reviews/pmem/pmemstream/238#-N6MVOL63oyZf5isceuu):*
you don't have to copy-paste the content of your commit into the commit msg :wink: 
___
*[`utils/docker/run-build.sh` line 54 at r2](https://reviewable.io/reviews/pmem/pmemstream/238#-N6MXaxnCBhiVEOjvALd:-N6MXaxnCBhiVEOjvALe:b-3xi6oj) ([raw file](https://github.com/pmem/pmemstream/blob/afd947e701f8b0c3bf4e6b556dfe1fc5226ceda9/utils/docker/run-build.sh#L54)):*
> ```Shell
> 		-DUSE_TSAN=${TESTS_TSAN} \
> 		-DUSE_UBSAN=${TESTS_UBSAN} \
> 		-DBUILD_BENCHMARKS=1
> ```

\+ unwind
___
*[`utils/docker/run-build.sh` line 179 at r2](https://reviewable.io/reviews/pmem/pmemstream/238#-N6MXh9y9NXYCZNkjjFc:-N6MXh9y9NXYCZNkjjFd:b3kqx) ([raw file](https://github.com/pmem/pmemstream/blob/afd947e701f8b0c3bf4e6b556dfe1fc5226ceda9/utils/docker/run-build.sh#L179)):*
> ```Shell
> 		-DUSE_TSAN=${TESTS_TSAN} \
> 		-DUSE_UBSAN=${TESTS_UBSAN}
> ```

.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/238)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`-- commits` line 11 at r2](https://reviewable.io/reviews/pmem/pmemstream/238#-N6MVOL63oyZf5isceuu):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you don't have to copy-paste the content of your commit into the commit msg :wink: 
</blockquote></details>

Done.
___
*[`utils/docker/run-build.sh` line 54 at r2](https://reviewable.io/reviews/pmem/pmemstream/238#-N6MXaxnCBhiVEOjvALd:-N6NVCiF3ERT0A3pBX3i:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/afd947e701f8b0c3bf4e6b556dfe1fc5226ceda9/utils/docker/run-build.sh#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

\+ unwind
</blockquote></details>

Done.
___
*[`utils/docker/run-build.sh` line 179 at r2](https://reviewable.io/reviews/pmem/pmemstream/238#-N6MXh9y9NXYCZNkjjFc:-N6NVFow3CyHNglyzbXA:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/afd947e701f8b0c3bf4e6b556dfe1fc5226ceda9/utils/docker/run-build.sh#L179)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/238)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[`-- commits` line 10 at r3](https://reviewable.io/reviews/pmem/pmemstream/238#-N6NWtQl4bcGNtETstTD):*
"degub" :smile: 
___
*[`utils/docker/build.sh` line 132 at r3](https://reviewable.io/reviews/pmem/pmemstream/238#-N6NX86O9WfATyyGImW2:-N6NX86P9oXN5zvWy62A:b-9jkhxr) ([raw file](https://github.com/pmem/pmemstream/blob/8b974a536b8f8c5a16af49606bff8d99407c0fc8/utils/docker/build.sh#L132)):*
> ```Shell
> 	--env COVERAGE \
> 	--env DEFAULT_TEST_DIR=/mnt/pmem \
> 	--env TESTS_LIBUNWIND=${TESTS_LIBUNWIND:-1} \
> ```

"ON" as well :wink:

**Review by KFilipek — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/238)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[`-- commits` line 10 at r3](https://reviewable.io/reviews/pmem/pmemstream/238#-N6NWtQl4bcGNtETstTD):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"degub" :smile: 
</blockquote></details>

xD
___
*[`utils/docker/build.sh` line 132 at r3](https://reviewable.io/reviews/pmem/pmemstream/238#-N6NX86O9WfATyyGImW2:-N6SB4UTBTQSBAWbmG56:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/8b974a536b8f8c5a16af49606bff8d99407c0fc8/utils/docker/build.sh#L132)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"ON" as well :wink: 
</blockquote></details>

Done.

**Comment by lukaszstolarczuk** [comment]
waiting for miniasync fixes, until now we're not going to enable it

**Pull request closed without merging**
