### PR TITLE
get rid of VERSION file for releases

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
fix setting proper SRCVERSION without git and without VERSION file.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/226)

### CODE REVIEW

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/226#-:-N5ZdXn15KNdAvcIcKCq:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/226)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @karczex)

___
*[`CMakeLists.txt` line 16 at r1](https://reviewable.io/reviews/pmem/pmemstream/226#-N5Zl5jM445hgsFC2XRZ:-N5eeLKQ7HtF7qDI_6Bz:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/921cdd8273353fa4f14b5e6f044c3983ee045db1/CMakeLists.txt#L16)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Set to devel after release 
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/226#-:-N5ek0Ye0awwehWrQXbh:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @karczex)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/226#-:-N5ekbYZ-2YFIWSkqmcM:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @igchor and @karczex)

___
*[`cmake/functions.cmake` line 204 at r2](https://reviewable.io/reviews/pmem/pmemstream/226#-N5ekQUa4sNvH7ppPryi:-N5ekQUa4sNvH7ppPryj:bl0edwv) ([raw file](https://github.com/pmem/pmemstream/blob/541f25d18318152223ebe266ae80f1794304a355/cmake/functions.cmake#L204)):*
> ```CMake
> # unless git is not available, then it's set to the recently released VERSION
> function(set_source_ver)
> 	# otherwise take it from git
> ```

drop this comment (there is no `if` now ;d)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/226)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @igchor and @karczex)

___
*[`cmake/functions.cmake` line 204 at r2](https://reviewable.io/reviews/pmem/pmemstream/226#-N5ekQUa4sNvH7ppPryi:-N5elqVw851FfDI8ZwIX:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/541f25d18318152223ebe266ae80f1794304a355/cmake/functions.cmake#L204)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

drop this comment (there is no `if` now ;d)
</blockquote></details>

Done.

**Pull request merged**
