### PR TITLE
Commit/persist batch processing

### PR DESCRIPTION
**Pull request by igchor**
TODO:
- [x] benchmark this for different batch sizes
- [ ] ~~more tests?~~

This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/245)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/245)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/245#-N6vzaiv-o0i1fSTQcqR:-N6x2XjKB0ziHkyHajM_:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can we add a test (without a custom data mover) to test it? E.g., start 1000 async appends and then call wait_* after a various number of entries (quite like your latest benchmark update :wink: )
</blockquote></details>

Done.

___

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/245)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[`tests/unittest/concurrent_async_wait.cpp` line 64 at r4](https://reviewable.io/reviews/pmem/pmemstream/245#-N7-j9sWEj-W96K0uoyj:-N7-j9sWEj-W96K0uoyk:b-i2uhei) ([raw file](https://github.com/pmem/pmemstream/blob/33e71367669392accb29172ba42b73b3a954dcd1/tests/unittest/concurrent_async_wait.cpp#L64)):*
> ```cpp
> 
> 				for (auto &future_sequence : futures) {
> 					std::mt19937_64 g(*rc::gen::arbitrary<size_t>());
> ```

you can use `init_random` from `random_helpers.hpp` instead

// while generating seed with RC is nice, it'd be harder to reproduce an issue...? not sure how shrinking will work with this approach...
___
*[`tests/unittest/concurrent_async_wait.cpp` line 77 at r4](https://reviewable.io/reviews/pmem/pmemstream/245#-N7-k5XY0jK7V8l8ojfz:-N7-k5XY0jK7V8l8ojg-:b-lrqcqk) ([raw file](https://github.com/pmem/pmemstream/blob/33e71367669392accb29172ba42b73b3a954dcd1/tests/unittest/concurrent_async_wait.cpp#L77)):*
> ```cpp
> 				std::vector<std::string> all_extra_data;
> 				all_extra_data.reserve(extra_data_size);
> 				for (auto &entry_sequency : extra_data) {
> ```

`entry_sequency` -> `entry_sequence`

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/245)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/245)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[`tests/unittest/concurrent_async_wait.cpp` line 64 at r4](https://reviewable.io/reviews/pmem/pmemstream/245#-N7-j9sWEj-W96K0uoyj:-N7KUTtl1sko3OJKdaX1:b-8vylls) ([raw file](https://github.com/pmem/pmemstream/blob/33e71367669392accb29172ba42b73b3a954dcd1/tests/unittest/concurrent_async_wait.cpp#L64)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can use `init_random` from `random_helpers.hpp` instead

// while generating seed with RC is nice, it'd be harder to reproduce an issue...? not sure how shrinking will work with this approach...
</blockquote></details>

Why it won't work? RC provides you with it's own seed to reproduce the results.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/245#-:-N8ORzm_-jEUdt4FwF70:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/245#-:-N8OfJkW3h4Y1KB5-H_x:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/245#-:-N8Yf59C9VeL6vVkJA5f:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
