### PR TITLE
Remove region_context from API

### PR DESCRIPTION
**Pull request by igchor**
Instead, use pmemstream_entry to hold information about where to append
new data. Instead of dedicated method for finding that offset we might
just use iterator API. It now guarantees that after reaching end of
the data (pmemstream_iterator_next return -1), pmemstrem_entry->offset will
point to offset which can be provided to pmemstream_append.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/15)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/15)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/15#-MpqeRma7NfwdSuYHy1t:-MpqeRmb7J1Jcfvw44Wb:b-z52q85) (no related file):*
u plan adding some tests along...?

---
___
*[src/libpmemstream.c, line 354 at r1](https://reviewable.io/reviews/pmem/pmemstream/15#-MpqYm6UC0z-XUhPoOP0:-MpqYm6UC0z-XUhPoOP1:b-ntuy95) ([raw file](https://github.com/pmem/pmemstream/blob/60dea33f0cdf9c5a91965b1baa154470239e6105/src/libpmemstream.c#L354)):*
> ```C
> 				   struct pmemstream_entry *entry)
> {
> 	pmemstream_span_bytes *entry_span = pmemstream_get_span_for_offset(iter->stream, iter->offset);
> ```

iter may be null...?
___
*[src/libpmemstream.c, line 368 at r1](https://reviewable.io/reviews/pmem/pmemstream/15#-MpqZP31B6mcfh8arwm7:-MpqZP31B6mcfh8arwm8:bp3wqld) ([raw file](https://github.com/pmem/pmemstream/blob/60dea33f0cdf9c5a91965b1baa154470239e6105/src/libpmemstream.c#L368)):*
> ```C
> 
> 	if (iter->offset >= iter->region.offset + region_rt.total_size) {
> 		return -1;
> ```

pls add a comment, why
___
*[src/libpmemstream.c, line 378 at r1](https://reviewable.io/reviews/pmem/pmemstream/15#-MpqZXxg26P91ovq4IU3:-MpqZXxg26P91ovq4IU4:bcba5y7) ([raw file](https://github.com/pmem/pmemstream/blob/60dea33f0cdf9c5a91965b1baa154470239e6105/src/libpmemstream.c#L378)):*
> ```C
> 	}
> 
> 	return -1;
> ```

here as well, pls - a comment
___
*[src/include/libpmemstream.h, line 42 at r1](https://reviewable.io/reviews/pmem/pmemstream/15#-MpqXF4g-RhJMwieVyj6:-MpqXF4g-RhJMwieVyj7:b9og85k) ([raw file](https://github.com/pmem/pmemstream/blob/60dea33f0cdf9c5a91965b1baa154470239e6105/src/include/libpmemstream.h#L42)):*
> ```objc
> size_t pmemstream_region_size(struct pmemstream *stream, struct pmemstream_region region);
> 
> // synchronously appends data buffer to the end of the transaction log space
> ```

here we say where it will be appended
___
*[src/include/libpmemstream.h, line 44 at r1](https://reviewable.io/reviews/pmem/pmemstream/15#-MpqXIha-1RL7w1j3wqx:-MpqXIha-1RL7w1j3wqy:blqrnwt) ([raw file](https://github.com/pmem/pmemstream/blob/60dea33f0cdf9c5a91965b1baa154470239e6105/src/include/libpmemstream.h#L44)):*
> ```objc
> // synchronously appends data buffer to the end of the transaction log space
> // fails if no space is available
> // 'entry' must provide offset where new entry is appended - it can be obtained from iterator
> ```

...and here we say we must provide 'entry' to know where to append it ;-)

I know, in general, all docs have to be updated, but pls consider straightening it up.
___
*[src/include/libpmemstream.h, line 47 at r1](https://reviewable.io/reviews/pmem/pmemstream/15#-MpqX_Bh-1ChlGoZE4kY:-MpqX_Bh-1ChlGoZE4kZ:b-rkucoy) ([raw file](https://github.com/pmem/pmemstream/blob/60dea33f0cdf9c5a91965b1baa154470239e6105/src/include/libpmemstream.h#L47)):*
> ```objc
> // after function completes, entry->offset is incremented by count + metadata size
> // and new_entry->offset is set to original value of entry->offset
> int pmemstream_append(struct pmemstream *stream, struct pmemstream_region *region, struct pmemstream_entry *entry,
> ```

perhaps we could rename 'entry' into something else...? reading this API, I'm not sure why the append function has "entry" and "new_entry" :wink: 
___
*[src/include/libpmemstream.h, line 48 at r1](https://reviewable.io/reviews/pmem/pmemstream/15#-MpqadIN-CV9HEK8feID:-MpqadIN-CV9HEK8feIE:b-8bkmqz) ([raw file](https://github.com/pmem/pmemstream/blob/60dea33f0cdf9c5a91965b1baa154470239e6105/src/include/libpmemstream.h#L48)):*
> ```objc
> // and new_entry->offset is set to original value of entry->offset
> int pmemstream_append(struct pmemstream *stream, struct pmemstream_region *region, struct pmemstream_entry *entry,
> 		      const void *buf, size_t count, struct pmemstream_entry *new_entry);
> ```

buf and count could also be explained a bit

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/15)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 354 at r1](https://reviewable.io/reviews/pmem/pmemstream/15#-MpqYm6UC0z-XUhPoOP0:-MpvMN8A1Di2KqVSjHaw:bovj9qe) ([raw file](https://github.com/pmem/pmemstream/blob/60dea33f0cdf9c5a91965b1baa154470239e6105/src/libpmemstream.c#L354)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

iter may be null...?
</blockquote></details>

There are quite of lot of places like this in code - where we assume pointer it not null. We need to go though all of them and decide how to handle it (assert vs check).
___
*[src/include/libpmemstream.h, line 47 at r1](https://reviewable.io/reviews/pmem/pmemstream/15#-MpqX_Bh-1ChlGoZE4kY:-MpvMcJU1y04zEhyhRwM:b-m5g513) ([raw file](https://github.com/pmem/pmemstream/blob/60dea33f0cdf9c5a91965b1baa154470239e6105/src/include/libpmemstream.h#L47)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps we could rename 'entry' into something else...? reading this API, I'm not sure why the append function has "entry" and "new_entry" :wink: 
</blockquote></details>

Right, but to what? ;d

**Review by KFilipek — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/15)* status: all files reviewed, 10 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 247 at r1](https://reviewable.io/reviews/pmem/pmemstream/15#-MpvGKPVD5cN2rDhxhUC:-MpvGKPWEfrk6xaRFFdM:b-k8egy4) ([raw file](https://github.com/pmem/pmemstream/blob/60dea33f0cdf9c5a91965b1baa154470239e6105/src/libpmemstream.c#L247)):*
> ```
> region->offset
> ```
Should we add some asserts at the beginning? Dereference of `region` will cause problems.
```cpp
#include <assert.h>
[...]
assert(stream != NULL);
assert(region  != NULL);
assert(entry  != NULL);
```
I think that `new_entry` is optional, right? Generally it looks like new_entry is copy-paste from `entry`
___
*[src/libpmemstream.c, line 363 at r1](https://reviewable.io/reviews/pmem/pmemstream/15#-MpvLICSARPuGQOKh-OA:-MpvLICSARPuGQOKh-OB:b-j6z6xm) ([raw file](https://github.com/pmem/pmemstream/blob/60dea33f0cdf9c5a91965b1baa154470239e6105/src/libpmemstream.c#L363)):*
> ```
> 	if (region) {
> 		*region = iter->region;
> 	}
> ```
Is that for case when we move from last entry in region1 to first entry in region next to the region1?
___
*[src/include/libpmemstream.h, line 47 at r1](https://reviewable.io/reviews/pmem/pmemstream/15#-MpqX_Bh-1ChlGoZE4kY:-MpvNHA8-o_d4xKK7tsu:b-dg3m6y) ([raw file](https://github.com/pmem/pmemstream/blob/60dea33f0cdf9c5a91965b1baa154470239e6105/src/include/libpmemstream.h#L47)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Right, but to what? ;d
</blockquote></details>

record, chunk... There is many `drops` in one stream :)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/15)* status: all files reviewed, 10 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[src/libpmemstream.c, line 354 at r1](https://reviewable.io/reviews/pmem/pmemstream/15#-MpqYm6UC0z-XUhPoOP0:-MpvNShW6UN7Qm0mzei5:b-tgmxuz) ([raw file](https://github.com/pmem/pmemstream/blob/60dea33f0cdf9c5a91965b1baa154470239e6105/src/libpmemstream.c#L354)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

There are quite of lot of places like this in code - where we assume pointer it not null. We need to go though all of them and decide how to handle it (assert vs check).
</blockquote></details>

Make sense, we can squeeze this in along with the incoming API refactor. We may check with some error, like in pmemkv.
___
*[src/include/libpmemstream.h, line 47 at r1](https://reviewable.io/reviews/pmem/pmemstream/15#-MpqX_Bh-1ChlGoZE4kY:-MpvNtgI6wNa56tcg1j3:b-hc2att) ([raw file](https://github.com/pmem/pmemstream/blob/60dea33f0cdf9c5a91965b1baa154470239e6105/src/include/libpmemstream.h#L47)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

record, chunk... There is many `drops` in one stream :) 
</blockquote></details>

from the top of my head - perhaps: entry_point, offset_info, starting_offset, last_entry_pos, ...

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/15)* status: all files reviewed, 11 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[src/include/libpmemstream.h, line 42 at r1](https://reviewable.io/reviews/pmem/pmemstream/15#-MpvSsApC5fuO7y5IbMF:-MpvSsAq92mHDi7srcKA:bxvdzqt) ([raw file](https://github.com/pmem/pmemstream/blob/f3bcee9b19607cd28def5fbd220fd4199263aea4/src/include/libpmemstream.h#L42)):*
> ```objc
> size_t pmemstream_region_size(struct pmemstream *stream, struct pmemstream_region region);
> 
> int pmemstream_region_context_new(struct pmemstream_region_context **rcontext, struct pmemstream *stream,
> ```

pls update linker map file - delete these there

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/15)* status: all files reviewed, 10 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/15#-MpqeRma7NfwdSuYHy1t:-Mq-Mz0Q2xBQeazXAxfV:b-f70950) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

u plan adding some tests along...?
</blockquote></details>

Sure, I will add some simple test

---
___
*[src/libpmemstream.c, line 247 at r1](https://reviewable.io/reviews/pmem/pmemstream/15#-MpvGKPVD5cN2rDhxhUC:-Mq-NLAiBTWbDD_v-pEj:bnn45ym) ([raw file](https://github.com/pmem/pmemstream/blob/60dea33f0cdf9c5a91965b1baa154470239e6105/src/libpmemstream.c#L247)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> region->offset
> ```
Should we add some asserts at the beginning? Dereference of `region` will cause problems.
```cpp
#include <assert.h>
[...]
assert(stream != NULL);
assert(region  != NULL);
assert(entry  != NULL);
```
I think that `new_entry` is optional, right? Generally it looks like new_entry is copy-paste from `entry`
</blockquote></details>

Yes new_entry is optional and as for asserts I agree, but we need to do this for all the functions - I would do this as a next step. Plus, as I wrote below we need to discuss strategy for those checks.
___
*[src/libpmemstream.c, line 354 at r1](https://reviewable.io/reviews/pmem/pmemstream/15#-MpqYm6UC0z-XUhPoOP0:-Mq-NYg63YZn1Qo795_w:b-8ayu6x) ([raw file](https://github.com/pmem/pmemstream/blob/60dea33f0cdf9c5a91965b1baa154470239e6105/src/libpmemstream.c#L354)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Make sense, we can squeeze this in along with the incoming API refactor. We may check with some error, like in pmemkv.
</blockquote></details>

Agree
___
*[src/libpmemstream.c, line 363 at r1](https://reviewable.io/reviews/pmem/pmemstream/15#-MpvLICSARPuGQOKh-OA:-Mq-NhoD-GG9xZrAjhYR:bfyv9n8) ([raw file](https://github.com/pmem/pmemstream/blob/60dea33f0cdf9c5a91965b1baa154470239e6105/src/libpmemstream.c#L363)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> 	if (region) {
> 		*region = iter->region;
> 	}
> ```
Is that for case when we move from last entry in region1 to first entry in region next to the region1?
</blockquote></details>

No, it's just a matter of returning region which the iterator points - this will always set the same region (region1). Once itersator goes out of iterator1 the return value it will be just -1.

I belive we could probably remove the region param - user nows it anyway because it;s needed for pmemstream_entry_iterator_new

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/15)* status: 3 of 7 files reviewed, 13 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[examples/01-iterate/main.c, line 131 at r2](https://reviewable.io/reviews/pmem/pmemstream/15#-Mq03eaQ5tDb5TI9Rq4u:-Mq03eaQ5tDb5TI9Rq4v:boped7r) ([raw file](https://github.com/pmem/pmemstream/blob/4821bd899054283f5edb60ffedcca7b3b29b4042/examples/01-iterate/main.c#L131)):*
> ```C
> 		}
> 
> 		/* Find out offset for the first entry in region */
> ```

you do the same in the test - perhaps we should consider always pointing to the first entry, already with calling "entry_iter_new"? 
or rather we should add another function, something like "iter_first/begin"?
___
*[tests/unittest/append.cpp, line 26 at r2](https://reviewable.io/reviews/pmem/pmemstream/15#-Mq05eMd1Mn1TqsvaRCS:-Mq05eMd1Mn1TqsvaRCT:bnfmwsp) ([raw file](https://github.com/pmem/pmemstream/blob/4821bd899054283f5edb60ffedcca7b3b29b4042/tests/unittest/append.cpp#L26)):*
> ```cpp
> }
> 
> struct pmemstream_region initialize_stream_single_region(struct pmemstream *stream, size_t region_size,
> ```

this function could also be a helper method in UT.hpp :wink: 
___
*[tests/unittest/append.cpp, line 63 at r2](https://reviewable.io/reviews/pmem/pmemstream/15#-Mq06_0DDCdbLhU9TECk:-Mq06_0EBQCObrec9sXn:b-3s8sv1) ([raw file](https://github.com/pmem/pmemstream/blob/4821bd899054283f5edb60ffedcca7b3b29b4042/tests/unittest/append.cpp#L63)):*
> ```cpp
> }
> 
> struct pmemstream_entry get_append_offset(struct pmemstream *stream, struct pmemstream_region *region)
> ```

perhaps rename to 'get next/last offset' ?
___
*[tests/unittest/append.cpp, line 91 at r2](https://reviewable.io/reviews/pmem/pmemstream/15#-Mq06u7O8IxkwVLo4SXr:-Mq06u7O8IxkwVLo4SXs:bki0gx0) ([raw file](https://github.com/pmem/pmemstream/blob/4821bd899054283f5edb60ffedcca7b3b29b4042/tests/unittest/append.cpp#L91)):*
> ```cpp
> 		return_check ret;
> 
> 		ret += rc::check("verify popcount against custom implementation",
> ```

wrong description

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/15)* status: 1 of 7 files reviewed, 13 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[examples/01-iterate/main.c, line 131 at r2](https://reviewable.io/reviews/pmem/pmemstream/15#-Mq03eaQ5tDb5TI9Rq4u:-MqDs8gf1g8KC-dYpiMx:b-kpdvn2) ([raw file](https://github.com/pmem/pmemstream/blob/4821bd899054283f5edb60ffedcca7b3b29b4042/examples/01-iterate/main.c#L131)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you do the same in the test - perhaps we should consider always pointing to the first entry, already with calling "entry_iter_new"? 
or rather we should add another function, something like "iter_first/begin"?
</blockquote></details>

If we would point to the first item we would have to add additional parameter (entry) to the pmemstream_entry_iterator_new function - I think we could add one additional function which would just return the last entry in the region - similar to region_context_create_new but with entry
___
*[tests/unittest/append.cpp, line 91 at r2](https://reviewable.io/reviews/pmem/pmemstream/15#-Mq06u7O8IxkwVLo4SXr:-MqEXPJB-oWb9JeqeFyo:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4821bd899054283f5edb60ffedcca7b3b29b4042/tests/unittest/append.cpp#L91)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

wrong description
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 4 files at r2, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/15)* status: 6 of 7 files reviewed, 11 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[examples/01-iterate/main.c, line 131 at r2](https://reviewable.io/reviews/pmem/pmemstream/15#-Mq03eaQ5tDb5TI9Rq4u:-MqKTU701ZZIK_eTvHy3:bqzill9) ([raw file](https://github.com/pmem/pmemstream/blob/4821bd899054283f5edb60ffedcca7b3b29b4042/examples/01-iterate/main.c#L131)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

If we would point to the first item we would have to add additional parameter (entry) to the pmemstream_entry_iterator_new function - I think we could add one additional function which would just return the last entry in the region - similar to region_context_create_new but with entry
</blockquote></details>

as discussed - pls make it a TODO for now

**Comment by lukaszstolarczuk** [comment]
to be continued in later PR

**Pull request merged**
