### PR TITLE
Define GitHub actions variables

### PR DESCRIPTION
**Pull request by Karolina002**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/189)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/189)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/pmem/pmemstream/189#-N2LkIYeCf6cTtZHjBYJ):*
pls add descruption why do we need them
___
*[`utils/docker/build.sh` line 114 at r4](https://reviewable.io/reviews/pmem/pmemstream/189#-N2Lk38UE8L2yQlBLFLJ:-N2Lk38UE8L2yQlBLFLK:bt7n1eu) ([raw file](https://github.com/pmem/pmemstream/blob/3179d318c2a4a983d9bbaeeb4d120132ebca0f18/utils/docker/build.sh#L114)):*
> ```Shell
> 	--env GITHUB_ACTIONS=${GITHUB_ACTIONS} \
> 	--env "GITHUB_ACTION=${GITHUB_ACTION}" \
> 	--env "GITHUB_REPO=${GITHUB_REPO}" \
> ```

it's supposed to be `--env GITHUB_ACTION="${GITHUB_ACTION}" \` :wink: 
___
*[`utils/docker/build.sh` line 132 at r4](https://reviewable.io/reviews/pmem/pmemstream/189#-N2LkBeuEdysOM5FZTw9:-N2LkBeuEdysOM5FZTwA:bz0j5i4) ([raw file](https://github.com/pmem/pmemstream/blob/3179d318c2a4a983d9bbaeeb4d120132ebca0f18/utils/docker/build.sh#L132)):*
> ```Shell
> 	--env COVERITY_SCAN_TOKEN=${COVERITY_SCAN_TOKEN} \
> 	--env COVERITY_SCAN_NOTIFICATION_EMAIL=${COVERITY_SCAN_NOTIFICATION_EMAIL} \
> 	--env CHECK_CPP_STYLE=${CHECK--env GITHUB_ACTIONS=${GITHUB_ACTIONS} \_CPP_STYLE:-OFF} \
> ```

something is "no yes" here :wink: 
___
*[`utils/docker/set-ci-vars.sh` line 3 at r4](https://reviewable.io/reviews/pmem/pmemstream/189#-N2LkF3Y0fr4UQtHNjie:-N2LkF3Y0fr4UQtHNjif:bva9rt5) ([raw file](https://github.com/pmem/pmemstream/blob/3179d318c2a4a983d9bbaeeb4d120132ebca0f18/utils/docker/set-ci-vars.sh#L3)):*
> ```Shell
> #!/usr/bin/env bash
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2020-2022, Intel Corporation
> ```

no update pls :wink:

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/189)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/pmem/pmemstream/189#-N2LkIYeCf6cTtZHjBYJ):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add descruption why do we need them
</blockquote></details>

Done.
___
*[`utils/docker/build.sh` line 114 at r4](https://reviewable.io/reviews/pmem/pmemstream/189#-N2Lk38UE8L2yQlBLFLJ:-N2MgdBbBjc7IVAOp43v:by1h29) ([raw file](https://github.com/pmem/pmemstream/blob/3179d318c2a4a983d9bbaeeb4d120132ebca0f18/utils/docker/build.sh#L114)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's supposed to be `--env GITHUB_ACTION="${GITHUB_ACTION}" \` :wink: 
</blockquote></details>

I tried it that way and it didn't work, so I found and applied current solution
___
*[`utils/docker/build.sh` line 132 at r4](https://reviewable.io/reviews/pmem/pmemstream/189#-N2LkBeuEdysOM5FZTw9:-N2Mhm-bE6-bWcvQZG19:b-8e5iwh) ([raw file](https://github.com/pmem/pmemstream/blob/3179d318c2a4a983d9bbaeeb4d120132ebca0f18/utils/docker/build.sh#L132)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

something is "no yes" here :wink: 
</blockquote></details>

Sorry, I don't follow, could you elaborate
___
*[`utils/docker/set-ci-vars.sh` line 3 at r4](https://reviewable.io/reviews/pmem/pmemstream/189#-N2LkF3Y0fr4UQtHNjie:-N2MiEGWA1dqZ3V7tqEV:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/3179d318c2a4a983d9bbaeeb4d120132ebca0f18/utils/docker/set-ci-vars.sh#L3)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

no update pls :wink: 
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/189)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/pmem/pmemstream/189#-N2LkIYeCf6cTtZHjBYJ):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

where you adding them? :wink: 

as usual, please, be very precise - if you read that commit message in few months you wouldn't know what was it about
___
*[`utils/docker/build.sh` line 114 at r4](https://reviewable.io/reviews/pmem/pmemstream/189#-N2Lk38UE8L2yQlBLFLJ:-N2Q77HuDZ44LHWJ9gPI:b-ixg030) ([raw file](https://github.com/pmem/pmemstream/blob/3179d318c2a4a983d9bbaeeb4d120132ebca0f18/utils/docker/build.sh#L114)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

I tried it that way and it didn't work, so I found and applied current solution
</blockquote></details>

I'm not sure if that's the same..

in general, when in bash setting a var, e.g.:
`MY_VAR=something`

that "something" may be with spaces and you should do:
`MY_VAR="something something"`

maybe docker's `--env` param is handling it differently, but please double check if that's the case.

Also, what error did you get on the previous try?
___
*[`utils/docker/build.sh` line 132 at r4](https://reviewable.io/reviews/pmem/pmemstream/189#-N2LkBeuEdysOM5FZTw9:-N2Q87UM4qy_XwlTBQMV:b-43nsph) ([raw file](https://github.com/pmem/pmemstream/blob/3179d318c2a4a983d9bbaeeb4d120132ebca0f18/utils/docker/build.sh#L132)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Sorry, I don't follow, could you elaborate
</blockquote></details>

you had something weird here, now it's ok.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/189)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @karczex, @Karolina002, and @lukaszstolarczuk)

___
*[`utils/docker/build.sh` line 114 at r4](https://reviewable.io/reviews/pmem/pmemstream/189#-N2Lk38UE8L2yQlBLFLJ:-N2QWUVW7BSenaCcG3YH:bn81wkf) ([raw file](https://github.com/pmem/pmemstream/blob/3179d318c2a4a983d9bbaeeb4d120132ebca0f18/utils/docker/build.sh#L114)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure if that's the same..

in general, when in bash setting a var, e.g.:
`MY_VAR=something`

that "something" may be with spaces and you should do:
`MY_VAR="something something"`

maybe docker's `--env` param is handling it differently, but please double check if that's the case.

Also, what error did you get on the previous try?
</blockquote></details>

Accordingly to https://docs.docker.com/engine/reference/commandline/run/ you may just forward env variable to docker by  
```
docker run --env GITHUB_ACTION ...
```
IMHO such usage is less error-prone. 

I suggest changing all `--env` lines in this file.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/189)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @karczex, @Karolina002, and @lukaszstolarczuk)

___
*[`utils/docker/build.sh` line 114 at r4](https://reviewable.io/reviews/pmem/pmemstream/189#-N2Lk38UE8L2yQlBLFLJ:-N2QaDix5spB9ALb2jCv:b-gzhj0k) ([raw file](https://github.com/pmem/pmemstream/blob/3179d318c2a4a983d9bbaeeb4d120132ebca0f18/utils/docker/build.sh#L114)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Accordingly to https://docs.docker.com/engine/reference/commandline/run/ you may just forward env variable to docker by  
```
docker run --env GITHUB_ACTION ...
```
IMHO such usage is less error-prone. 

I suggest changing all `--env` lines in this file. 
</blockquote></details>

that's perfect!

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/189)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/pmem/pmemstream/189#-N2LkIYeCf6cTtZHjBYJ):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

where you adding them? :wink: 

as usual, please, be very precise - if you read that commit message in few months you wouldn't know what was it about
</blockquote></details>

Done.
___
*[`utils/docker/build.sh` line 114 at r4](https://reviewable.io/reviews/pmem/pmemstream/189#-N2Lk38UE8L2yQlBLFLJ:-N2ScgEtD2Hcsta1HtJq:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/3179d318c2a4a983d9bbaeeb4d120132ebca0f18/utils/docker/build.sh#L114)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

that's perfect!
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/189)* status: all files reviewed, 1 unresolved discussion (waiting on @Karolina002)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/pmem/pmemstream/189#-N2LkIYeCf6cTtZHjBYJ):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx!
___
*[`utils/docker/build.sh` line 110 at r7](https://reviewable.io/reviews/pmem/pmemstream/189#-N2VW16AEbzwau4aLzgj:-N2VW16B9Q33WZQMZ05h:br0q71m) ([raw file](https://github.com/pmem/pmemstream/blob/e5668081b26c89fe644adf7ed0af63861274c93b/utils/docker/build.sh#L110)):*
> ```Shell
> 	--env https_proxy \
> 	--env TERM=xterm-256color \
> 	--env WORKDIR \
> ```

based on the CI log it seems like there's something wrong with the workdir...? `Permission denied` to create a directory means we're in the wrong place...? something went wrong :wink:

**Review by KFilipek — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/189)* status: all files reviewed, 1 unresolved discussion (waiting on @Karolina002)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/189#-:-N2kAByZAmR03HvAO0zV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)

**Review by KFilipek — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/189)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/189#-:-N2kJpc89OaOokbdA6x_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)

**Pull request merged**
