### PR TITLE
Add initial code for libpmemstream

### PR DESCRIPTION
**Pull request by igchor**
Implemented by @pbalcer

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/5)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/5)* status: all files reviewed, 9 unresolved discussions (waiting on @igchor)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo2jBitDb3NAbi03s4W):*
perhaps split into more commits? e.g. libpmem2 dependency should be added in sep. commit? not sure about that 
___
*[CMakeLists.txt, line 171 at r1](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo2jpYT5TjSfqm3u7fc:-Mo2jpYT5TjSfqm3u7fd:b-v2ud9e) ([raw file](https://github.com/pmem/pmemstream/blob/dde77080f07e0e140961ccb5df5f47ccc78aeffa/CMakeLists.txt#L171)):*
> ```CMake
> # endif()
> 
> if(BUILD_TESTS OR BUILD_EXAMPLES)
> ```

I'm not sure if we need this block
___
*[cmake/FindLIBPMEM2.cmake, line 1 at r1](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo2kojc7-5YYaZkkmNn:-Mo2kojd1gyBq_7uImqF:b-nsn1u0) ([raw file](https://github.com/pmem/pmemstream/blob/dde77080f07e0e140961ccb5df5f47ccc78aeffa/cmake/FindLIBPMEM2.cmake#L1)):*
> ```CMake
> #
> ```

pls drop these 2 empty lines of comment
___
*[examples/CMakeLists.txt, line 15 at r1](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo2lNn6-vC6IyctVs00:-Mo2lNn6-vC6IyctVs01:b-ava1im) ([raw file](https://github.com/pmem/pmemstream/blob/dde77080f07e0e140961ccb5df5f47ccc78aeffa/examples/CMakeLists.txt#L15)):*
> ```CMake
> ## Setup examples
> # ----------------------------------------------------------------- #
> include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../src)
> ```

we could use here `PMEMSTREAM_ROOT_DIR` var
___
*[examples/CMakeLists.txt, line 25 at r1](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo2ljjC5hmUM4BWksIq:-Mo2ljjC5hmUM4BWksIr:b-yov5s2) ([raw file](https://github.com/pmem/pmemstream/blob/dde77080f07e0e140961ccb5df5f47ccc78aeffa/examples/CMakeLists.txt#L25)):*
> ```CMake
> add_check_whitespace(examples ${CMAKE_CURRENT_SOURCE_DIR}/01-iterate/*.*)
> 
> function(add_example name)
> ```

this helper function should be in another section.. e.g. in "Setup examples" above (?)
___
*[examples/CMakeLists.txt, line 37 at r1](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo2n4PE8WI_ndWRTRZC:-Mo2n4PE8WI_ndWRTRZD:b-rss6uu) ([raw file](https://github.com/pmem/pmemstream/blob/dde77080f07e0e140961ccb5df5f47ccc78aeffa/examples/CMakeLists.txt#L37)):*
> ```CMake
> # ----------------------------------------------------------------- #
> add_example(01-iterate 01-iterate/main.c)
> # XXX
> ```

why XXX here?
___
*[src/pmemstream.c, line 706 at r1](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo2o8nfEOi9n7wxx2Vp:-Mo2o8nfEOi9n7wxx2Vq:byu25fn) ([raw file](https://github.com/pmem/pmemstream/blob/dde77080f07e0e140961ccb5df5f47ccc78aeffa/src/pmemstream.c#L706)):*
> ```C
> 	free(iter);
> 	*iterator = NULL;
> }
> ```

EOL missing
___
*[src/ravl.h, line 8 at r1](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo2o6_b8wzFABBJlHt9:-Mo2o6_b8wzFABBJlHtA:bb70pn1) ([raw file](https://github.com/pmem/pmemstream/blob/dde77080f07e0e140961ccb5df5f47ccc78aeffa/src/ravl.h#L8)):*
> ```objc
>  */
> 
> #ifndef LIBPMEMOBJ_RAVL_H
> ```

OBJ?
___
*[src/ravl.c, line 11 at r1](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo2oK3a2PHBonuGmNUE:-Mo2oK3a2PHBonuGmNUF:b-r4zici) ([raw file](https://github.com/pmem/pmemstream/blob/dde77080f07e0e140961ccb5df5f47ccc78aeffa/src/ravl.c#L11)):*
> ```C
> #include <stdlib.h>
> #include <string.h>
> #include <errno.h>
> ```

errno?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/5)* status: 4 of 10 files reviewed, 8 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo2jBitDb3NAbi03s4W):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps split into more commits? e.g. libpmem2 dependency should be added in sep. commit? not sure about that 
</blockquote></details>

Done.
___
*[CMakeLists.txt, line 171 at r1](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo2jpYT5TjSfqm3u7fc:-Mo3jki92tv55xKMvB5o:bss4a2b) ([raw file](https://github.com/pmem/pmemstream/blob/dde77080f07e0e140961ccb5df5f47ccc78aeffa/CMakeLists.txt#L171)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure if we need this block
</blockquote></details>

Removed.
___
*[cmake/FindLIBPMEM2.cmake, line 1 at r1](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo2kojc7-5YYaZkkmNn:-Mo3jrtq9XX_eyrP_DhW:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/dde77080f07e0e140961ccb5df5f47ccc78aeffa/cmake/FindLIBPMEM2.cmake#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls drop these 2 empty lines of comment
</blockquote></details>

Done.
___
*[examples/CMakeLists.txt, line 15 at r1](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo2lNn6-vC6IyctVs00:-Mo3k1xy1ohH89k32JUK:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/dde77080f07e0e140961ccb5df5f47ccc78aeffa/examples/CMakeLists.txt#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we could use here `PMEMSTREAM_ROOT_DIR` var
</blockquote></details>

Done.
___
*[examples/CMakeLists.txt, line 25 at r1](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo2ljjC5hmUM4BWksIq:-Mo3k72KCsueCCpvcfqK:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/dde77080f07e0e140961ccb5df5f47ccc78aeffa/examples/CMakeLists.txt#L25)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this helper function should be in another section.. e.g. in "Setup examples" above (?)
</blockquote></details>

Done.
___
*[examples/CMakeLists.txt, line 37 at r1](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo2n4PE8WI_ndWRTRZC:-Mo3k9SpEUVyIcgGMDlV:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/dde77080f07e0e140961ccb5df5f47ccc78aeffa/examples/CMakeLists.txt#L37)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why XXX here?
</blockquote></details>

Done.
___
*[src/pmemstream.c, line 706 at r1](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo2o8nfEOi9n7wxx2Vp:-Mo3kEKf4aWcMj_CxFU_:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/dde77080f07e0e140961ccb5df5f47ccc78aeffa/src/pmemstream.c#L706)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

EOL missing
</blockquote></details>

Done.
___
*[src/ravl.h, line 8 at r1](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo2o6_b8wzFABBJlHt9:-Mo3kJ7w7qcY2DVSAXqp:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/dde77080f07e0e140961ccb5df5f47ccc78aeffa/src/ravl.h#L8)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

OBJ?
</blockquote></details>

Done.
___
*[src/ravl.c, line 11 at r1](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo2oK3a2PHBonuGmNUE:-Mo3kJuj1Z27aQQ5Tj1M:b-7mz4of) ([raw file](https://github.com/pmem/pmemstream/blob/dde77080f07e0e140961ccb5df5f47ccc78aeffa/src/ravl.c#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

errno?
</blockquote></details>

Yeah, it's used in the code

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/5)* status: 4 of 10 files reviewed, 8 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo2jBitDb3NAbi03s4W):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I split adding source code from the rest but I did not split libpmem2 - it;s most of the change anyway

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/5)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo3tO4C0WMQGl-iS10e:-Mo3tO4C0WMQGl-iS10f:bzhfecc) (no related file):*
pc file should also be updated with dependency - "require" section

---
___
*[examples/01-iterate/main.c, line 4 at r2](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo3toPw2Zrzrid0pduN:-Mo3toPw2Zrzrid0pduO:bc5yxcl) ([raw file](https://github.com/pmem/pmemstream/blob/6da56b20739f4a52b6c141226ec535c55e8d8ed0/examples/01-iterate/main.c#L4)):*
> ```C
> /* Copyright 2021, Intel Corporation */
> 
> #include "pmemstream.h"
> ```

update path here as well
___
*[src/libpmemstream.map, line 4 at r2](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo3sRXA5EEqnVd7MxnY:-Mo3sRXA5EEqnVd7MxnZ:bh43zwn) ([raw file](https://github.com/pmem/pmemstream/blob/6da56b20739f4a52b6c141226ec535c55e8d8ed0/src/libpmemstream.map#L4)):*
> ```
> # Copyright 2021, Intel Corporation
> #
> # src/libpmemstream.map -- linker map file for libpmemstream
> ```

should this be named "libpmemstream.map" or "pmemstream.map"...? should we actually bother about this file and pmemstream's header file name?
___
*[src/ravl.h, line 5 at r2](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo3tDa76X4SjcZZXqNz:-Mo3tDa76X4SjcZZXqO-:bid02oa) ([raw file](https://github.com/pmem/pmemstream/blob/6da56b20739f4a52b6c141226ec535c55e8d8ed0/src/ravl.h#L5)):*
> ```objc
> 
> /*
>  * ravl.h -- internal definitions for ravl tree
> ```

move to "include" dir as well
___
*[src/ravl.c, line 11 at r1](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo2oK3a2PHBonuGmNUE:-Mo3szMpBAc1Y_JGFke4:bj32e3v) ([raw file](https://github.com/pmem/pmemstream/blob/dde77080f07e0e140961ccb5df5f47ccc78aeffa/src/ravl.c#L11)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Yeah, it's used in the code
</blockquote></details>

hah, ok, nevermind, I thought it was from obj

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/5)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo3tO4C0WMQGl-iS10e:-Mo43xA-2mruugBI_Sqw:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pc file should also be updated with dependency - "require" section
</blockquote></details>

Done.

---
___
*[examples/01-iterate/main.c, line 4 at r2](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo3toPw2Zrzrid0pduN:-Mo43hHe1LtGQVNPstAX:bdtlcln) ([raw file](https://github.com/pmem/pmemstream/blob/6da56b20739f4a52b6c141226ec535c55e8d8ed0/examples/01-iterate/main.c#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

update path here as well
</blockquote></details>

Actually it should be other way around, I removed the include from pmemstream.c
___
*[src/libpmemstream.map, line 4 at r2](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo3sRXA5EEqnVd7MxnY:-Mo43oH_Bf7UztjyZLu6:b7ess0q) ([raw file](https://github.com/pmem/pmemstream/blob/6da56b20739f4a52b6c141226ec535c55e8d8ed0/src/libpmemstream.map#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

should this be named "libpmemstream.map" or "pmemstream.map"...? should we actually bother about this file and pmemstream's header file name?
</blockquote></details>

I'd say libpmemstream.map is fine.
___
*[src/ravl.h, line 5 at r2](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo3tDa76X4SjcZZXqNz:-Mo43tEJCr6gi-CZzvfd:b-3ke71m) ([raw file](https://github.com/pmem/pmemstream/blob/6da56b20739f4a52b6c141226ec535c55e8d8ed0/src/ravl.h#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

move to "include" dir as well
</blockquote></details>

Why? This is internal source file

**Review by karczex — APPROVED** [review]
:lgtm:

> Reviewed 1 of 10 files at r1, 3 of 6 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/5#-:-Mo5MFDf1zWdXYkV1s6i:bnfp4nl)* status: 10 of 11 files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/5)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor)

___
*[src/CMakeLists.txt, line 13 at r3](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo8JxTs6ePygXItk2A2:-Mo8JxTs6ePygXItk2A3:byrxqx1) ([raw file](https://github.com/pmem/pmemstream/blob/e7659a6c6c7f9d6a720247bf74e9b0d9befd372c/src/CMakeLists.txt#L13)):*
> ```CMake
> 
> set(SOURCES pmemstream.c
> 	ravl.c)
> ```

should we also include header files in this list?
___
*[src/pmemstream.c, line 4 at r3](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo8LH_J8KEvQtjxLwRF:-Mo8LH_J8KEvQtjxLwRG:b33fu0w) ([raw file](https://github.com/pmem/pmemstream/blob/e7659a6c6c7f9d6a720247bf74e9b0d9befd372c/src/pmemstream.c#L4)):*
> ```C
> /* Copyright 2021, Intel Corporation */
> 
> #include "pmemstream.h"
> ```

I think we should actually rename these to **lib**pmemstream.*
___
*[src/pmemstream.c, line 6 at r3](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo8LgDZ7xSdAGSrQ7x7:-Mo8LgDZ7xSdAGSrQ7x8:b-7pddvf) ([raw file](https://github.com/pmem/pmemstream/blob/e7659a6c6c7f9d6a720247bf74e9b0d9befd372c/src/pmemstream.c#L6)):*
> ```C
> #include "pmemstream.h"
> 
> #include "libpmem2.h"
> ```

`<libpmem2.h>`
___
*[src/pmemstream.c, line 7 at r3](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo8LiY60SyPgL83VI8u:-Mo8LiY792JLx0XktrqV:b-l2cezn) ([raw file](https://github.com/pmem/pmemstream/blob/e7659a6c6c7f9d6a720247bf74e9b0d9befd372c/src/pmemstream.c#L7)):*
> ```C
> 
> #include "libpmem2.h"
> #include "ravl.h"
> ```

this should be above, next to `pmemstream.h`

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/5)* status: 7 of 11 files reviewed, 4 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[src/CMakeLists.txt, line 13 at r3](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo8JxTs6ePygXItk2A2:-Mo8WoM44OZv5lJm8NdN:bqp042l) ([raw file](https://github.com/pmem/pmemstream/blob/e7659a6c6c7f9d6a720247bf74e9b0d9befd372c/src/CMakeLists.txt#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

should we also include header files in this list?
</blockquote></details>

I think not, we had headers in this list in pmemkv but it was not used for anything I believe. 
___
*[src/pmemstream.c, line 4 at r3](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo8LH_J8KEvQtjxLwRF:-Mo8X4AkCMhtfd92ppxw:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e7659a6c6c7f9d6a720247bf74e9b0d9befd372c/src/pmemstream.c#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think we should actually rename these to **lib**pmemstream.*
</blockquote></details>

Done.
___
*[src/pmemstream.c, line 6 at r3](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo8LgDZ7xSdAGSrQ7x7:-Mo8X76UEhByK9VagL1D:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e7659a6c6c7f9d6a720247bf74e9b0d9befd372c/src/pmemstream.c#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`<libpmem2.h>`
</blockquote></details>

Done.
___
*[src/pmemstream.c, line 7 at r3](https://reviewable.io/reviews/pmem/pmemstream/5#-Mo8LiY60SyPgL83VI8u:-Mo8X7LrED0NTsfPymcH:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e7659a6c6c7f9d6a720247bf74e9b0d9befd372c/src/pmemstream.c#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this should be above, next to `pmemstream.h`
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/5#-:-Mo8dm327ia9fI_7vSf6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
