### PR TITLE
Update tests

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/61)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/61#-:-Mt3D66N8NJi4fvgTLiY:bnfp4nl)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @igchor)

**Comment by lukaszstolarczuk** [comment]
I'll update my tests after #60 is merged.

**Review by karczex — COMMENTED** [review]
Please split this test into separate files - i.e append_pbt.cpp and append_basic.cpp

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/61#-:-Mt7uMJoCtCl_8Ebw6rB:b-3cz767)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @igchor)

**Comment by lukaszstolarczuk** [comment]
I've added a few more test cases and run existing examples as tests.


> Please split this test into separate files - i.e append_pbt.cpp and append_basic.cpp
> 
> > _[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/61#-:-Mt7uMJoCtCl_8Ebw6rB:b-3cz767)_ status: 1 of 4 files reviewed, all discussions resolved (waiting on @igchor)

it's not that easy after all 😉 it requires extra work to fix our helpers (not to use RC_ASSERTs), so it'd be done later on

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 4 files at r2, 4 of 6 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/61)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/cmake/run_with_file.cmake, line 11 at r4](https://reviewable.io/reviews/pmem/pmemstream/61#-MtCsBuC4wogPixG-zNw:-MtCsBuC4wogPixG-zNx:bp149jy) ([raw file](https://github.com/pmem/pmemstream/blob/7e3b7ece5f8ba9006c4a961312bb5d8c1ca58d82/tests/cmake/run_with_file.cmake#L11)):*
> ```CMake
> 
> # create 100MiB file
> execute_process(COMMAND dd if=/dev/zero of=${DIR}/testfile bs=1024 count=102400)
> ```

Probably we could get rid of this by just passing O_CREAT in the example...
___
*[tests/common/stream_helpers.hpp, line 26 at r4](https://reviewable.io/reviews/pmem/pmemstream/61#-MtCsbRU-abJy6zWEtN9:-MtCsbRU-abJy6zWEtNA:bb1te9t) ([raw file](https://github.com/pmem/pmemstream/blob/7e3b7ece5f8ba9006c4a961312bb5d8c1ca58d82/tests/common/stream_helpers.hpp#L26)):*
> ```cpp
> 	struct pmemstream_region new_region;
> 	RC_ASSERT(pmemstream_region_allocate(stream, region_size, &new_region) == 0);
> 	RC_ASSERT(pmemstream_region_size(stream, new_region) >= region_size);
> ```

why `>=`?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/61)* status: 3 of 13 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[tests/common/stream_helpers.hpp, line 26 at r4](https://reviewable.io/reviews/pmem/pmemstream/61#-MtCsbRU-abJy6zWEtN9:-MtDFEoO4iDO0cgRTh8i:bjrvqk5) ([raw file](https://github.com/pmem/pmemstream/blob/7e3b7ece5f8ba9006c4a961312bb5d8c1ca58d82/tests/common/stream_helpers.hpp#L26)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why `>=`?
</blockquote></details>

we ALIGN_UP the region_size to block_size - I added a comment, but pls let me know if you think we should be more precise here
___
*[tests/cmake/run_with_file.cmake, line 11 at r4](https://reviewable.io/reviews/pmem/pmemstream/61#-MtCsBuC4wogPixG-zNw:-MtDFmcP9PsD5tIqF-74:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7e3b7ece5f8ba9006c4a961312bb5d8c1ca58d82/tests/cmake/run_with_file.cmake#L11)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Probably we could get rid of this by just passing O_CREAT in the example...
</blockquote></details>

Done.

**Review by karczex — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 4 of 6 files at r3, 1 of 1 files at r4, 1 of 10 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/61)* status: 4 of 13 files reviewed, 2 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/unittest/reserve_publish.cpp, line 54 at r4](https://reviewable.io/reviews/pmem/pmemstream/61#-MtDHriJDEftJ81bJ6wp:-MtDHriJDEftJ81bJ6wq:bhzrme0) ([raw file](https://github.com/pmem/pmemstream/blob/7e3b7ece5f8ba9006c4a961312bb5d8c1ca58d82/tests/unittest/reserve_publish.cpp#L54)):*
> ```cpp
> 
> 		ret += rc::check(
> 			"verify if reserve and publish by hand will behave as regular append",
> ```

I would say, such property would be tested more accurately if you create two streams. append to first, reserve+publish to second and compare content of such streams. 


Separate test, may be: 
"verify if mixing reserve+publish with append behave as regular append", but it may be done on separate PR

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/61)* status: 2 of 13 files reviewed, 2 unresolved discussions (waiting on @igchor and @karczex)

___
*[tests/unittest/reserve_publish.cpp, line 54 at r4](https://reviewable.io/reviews/pmem/pmemstream/61#-MtDHriJDEftJ81bJ6wp:-MtDjov45RYC6yBiQ2Is:b-21w2pp) ([raw file](https://github.com/pmem/pmemstream/blob/7e3b7ece5f8ba9006c4a961312bb5d8c1ca58d82/tests/unittest/reserve_publish.cpp#L54)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I would say, such property would be tested more accurately if you create two streams. append to first, reserve+publish to second and compare content of such streams. 


Separate test, may be: 
"verify if mixing reserve+publish with append behave as regular append", but it may be done on separate PR

</blockquote></details>

good idea, done.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 5 of 10 files at r6, 1 of 1 files at r7, 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/61#-:-MtHsjHT8zVcn6ru6joz:bnfp4nl)* status: 9 of 13 files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)

**Comment by karczex** [comment]
___
*[tests/unittest/reserve_publish.cpp, line 80 at r8](https://reviewable.io/reviews/pmem/pmemstream/61#-MtHvPRqBDSxJnVBfk0q:-MtHvPRqBDSxJnVBfk0r:b-jzwnan) ([raw file](https://github.com/pmem/pmemstream/blob/92f28dda46b00d058ac604e6b9a3f5f8e2ea6688/tests/unittest/reserve_publish.cpp#L80)):*
> ```cpp
> 			});
> 
> 		ret += rc::check("verify if reserve+publish by hand will behave the same as regular append",
> ```

You probably should use two separate files.

**Review by karczex — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/61)* status: 9 of 13 files reviewed, 2 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/unittest/reserve_publish.cpp, line 54 at r4](https://reviewable.io/reviews/pmem/pmemstream/61#-MtDHriJDEftJ81bJ6wp:-MtHuBR45i0TWqXYE3yY:b-jdrt7g) ([raw file](https://github.com/pmem/pmemstream/blob/7e3b7ece5f8ba9006c4a961312bb5d8c1ca58d82/tests/unittest/reserve_publish.cpp#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

good idea, done.
</blockquote></details>

I'm big fun of such defined property :)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/61)* status: 8 of 13 files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)

___
*[tests/unittest/reserve_publish.cpp, line 54 at r4](https://reviewable.io/reviews/pmem/pmemstream/61#-MtDHriJDEftJ81bJ6wp:-MtI-_G3DXhzJCH5YK6d:b-ve3yvb) ([raw file](https://github.com/pmem/pmemstream/blob/7e3b7ece5f8ba9006c4a961312bb5d8c1ca58d82/tests/unittest/reserve_publish.cpp#L54)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I'm big fun of such defined property :) 
</blockquote></details>

:smile: 
___
*[tests/unittest/reserve_publish.cpp, line 80 at r8](https://reviewable.io/reviews/pmem/pmemstream/61#-MtHvPRqBDSxJnVBfk0q:-MtI-aYB6296-iBZyxLN:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/92f28dda46b00d058ac604e6b9a3f5f8e2ea6688/tests/unittest/reserve_publish.cpp#L80)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

You probably should use two separate files.
</blockquote></details>

Done.

**Review by karczex — APPROVED** [review]
:lgtm:

> Reviewed 2 of 10 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/61#-:-MtIIHP6BFoPy9lFw6tl:bnfp4nl)* status: 9 of 13 files reviewed, all discussions resolved (waiting on @igchor and @karczex)

**Pull request merged**
