### PR TITLE
Enable prefault at open/create time

### PR DESCRIPTION
**Pull request by Karolina002**
at open/create time

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/263)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/263)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/263#-NA98kpYEDOCghZ3_uWB:-NA98kpYEDOCghZ3_uWC:by0ovw4) (no related file):*
you can try and run some benchmark with and without this prefault set to see if there's any difference

___
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/pmem/pmemstream/263#-NA950TYAyQBaRldYIuf):*
1. adding a new variable is just a way to accomplish your goal, which is to enable prefaulting :wink:  pls re-write
2. if you want to add a second line of the commit message, pls add an empty line between them (see git workflow blog on pmem.io and its commit message description)
___
*[`src/libpmemstream.c` line 151 at r2](https://reviewable.io/reviews/pmem/pmemstream/263#-NA96sACAbw5y_S8G3el:-NA96sAD9U7iGyu_1FAF:b8thp3k) ([raw file](https://github.com/pmem/pmemstream/blob/f4b2579cc2033041348cfe3987a54dac5b442080/src/libpmemstream.c#L151)):*
> ```C
> 	volatile char *cur_addr = pmem2_map_get_address(map);
> 	char *addr_end = (char *)cur_addr + pmem2_map_get_size(map);
> 	unsigned long long pagesize = (unsigned long)sysconf(_SC_PAGESIZE);
> ```

1. static cast
2. unsigned long long != unsigned long :wink:

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/263)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/pmem/pmemstream/263#-NA950TYAyQBaRldYIuf):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. adding a new variable is just a way to accomplish your goal, which is to enable prefaulting :wink:  pls re-write
2. if you want to add a second line of the commit message, pls add an empty line between them (see git workflow blog on pmem.io and its commit message description)
</blockquote></details>

Done.
___
*[`src/libpmemstream.c` line 151 at r2](https://reviewable.io/reviews/pmem/pmemstream/263#-NA96sACAbw5y_S8G3el:-NAJUOu5D8nZLPJcQUDP:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f4b2579cc2033041348cfe3987a54dac5b442080/src/libpmemstream.c#L151)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. static cast
2. unsigned long long != unsigned long :wink: 
</blockquote></details>

Done.

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/263)* status: all files reviewed, 1 unresolved discussion (waiting on @Karolina002)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/263#-NA98kpYEDOCghZ3_uWB:-NAJm-Kn16ca8TsDuXAa:b30g13l) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can try and run some benchmark with and without this prefault set to see if there's any difference
</blockquote></details>

@karolina002 did you manage to check this?

___

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/263)* status: all files reviewed, 1 unresolved discussion (waiting on @Karolina002)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/263#-NA98kpYEDOCghZ3_uWB:-NAJmZt210SGyDvJi8TZ:bdik7eg) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

@karolina002 did you manage to check this?
</blockquote></details>

working on it

___

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/263)* status: all files reviewed, 1 unresolved discussion (waiting on @Karolina002)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/263#-NA98kpYEDOCghZ3_uWB:-NAOJ_J38CLceKQBqiz0:bosd7b2) (no related file):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

working on it
</blockquote></details>

standard deviation visibly dropped, mean stayed approximately the same

___

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/263)* status: all files reviewed, 3 unresolved discussions (waiting on @Karolina002)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/263#-NA98kpYEDOCghZ3_uWB:-NAOK4pd-_3S595rrjwi:b-8fx2u7) (no related file):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

standard deviation visibly dropped, mean stayed approximately the same
</blockquote></details>

:+1: 

___
___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/pmem/pmemstream/263#-NAOKCwc1Q86SAaIUjwT):*
pls update with `PMEMSTREAM_` prefix
___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/pmem/pmemstream/263#-NAOKGxN23fG6Zx95BFj):*
to be precise prefault is not enabled just `by adding` an env variable :smile: :wink:

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/263)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/pmem/pmemstream/263#-NAOKCwc1Q86SAaIUjwT):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls update with `PMEMSTREAM_` prefix
</blockquote></details>

Done.



_Code quote:_
```
PREFAULT_AT_OPEN
```
___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/pmem/pmemstream/263#-NAOKGxN23fG6Zx95BFj):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

to be precise prefault is not enabled just `by adding` an env variable :smile: :wink: 
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/263#-:-NAd48bk8Am3cJm-ex11:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Karolina002)

___
*[`doc/libpmemstream.3.md` line 132 at r4](https://reviewable.io/reviews/pmem/pmemstream/263#-NAd44Xe2wjPQdrL01F3:-NAd44Xe2wjPQdrL01F4:b64p8ee) ([raw file](https://github.com/pmem/pmemstream/blob/c28d820a67e6e0e6a523473e7e3dd4aa85a25bb9/doc/libpmemstream.3.md#L132)):*
> ```Markdown
> 	If a mapping points to a previously existing pmemstream instance, it re-opens it and reads persisted header's data.
> 	In any other case, it's undefined behavior.
> 	To force prefault at create/open time set env varibale PMEMSTREAM_PREFAULT_AT_OPEN.
> ```

`varibale` misspell

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/263)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @karczex and @lukaszstolarczuk)

___
*[`doc/libpmemstream.3.md` line 132 at r4](https://reviewable.io/reviews/pmem/pmemstream/263#-NAd44Xe2wjPQdrL01F3:-NAdH6Oq4E5A-rq7KGIK:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c28d820a67e6e0e6a523473e7e3dd4aa85a25bb9/doc/libpmemstream.3.md#L132)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`varibale` misspell
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/263#-:-NAnQ-bG3aXY6aCftq4D:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)

**Pull request merged**
