### PR TITLE
Implement basic functionality

### PR DESCRIPTION
**Pull request by igchor**
Remove tx-related API and implement single region-support.

Consistency of the data is guaranteed by storing popcount.
TODO: make sure stream is initially zeroed.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/7)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/7)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[examples/01-iterate/main.c, line 3 at r1](https://reviewable.io/reviews/pmem/pmemstream/7#-Mosh4SuDQLmIImz97Z0:-Mosh4SuDQLmIImz97Z1:b-31b43a) ([raw file](https://github.com/pmem/pmemstream/blob/3214352d0a33acac992e91b7fbde3dcdee93036b/examples/01-iterate/main.c#L3)):*
> ```C
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2021, Intel Corporation */
> ```

a short desc. here, perhaps
___
*[examples/01-iterate/main.c, line 54 at r1](https://reviewable.io/reviews/pmem/pmemstream/7#-MosfzD_Eb7hN6dLDi9R:-MosfzD_Eb7hN6dLDi9S:b-52fic8) ([raw file](https://github.com/pmem/pmemstream/blob/3214352d0a33acac992e91b7fbde3dcdee93036b/examples/01-iterate/main.c#L54)):*
> ```C
> {
> 	if (argc != 2) {
> 		printf("Wrong number of arguments\n");
> ```

perhaps, print usage instead
___
*[examples/01-iterate/main.c, line 96 at r1](https://reviewable.io/reviews/pmem/pmemstream/7#-Mosgx0AE0pCIH45ZroA:-Mosgx0AE0pCIH45ZroB:bv1o066) ([raw file](https://github.com/pmem/pmemstream/blob/3214352d0a33acac992e91b7fbde3dcdee93036b/examples/01-iterate/main.c#L96)):*
> ```C
> 	pmemstream_region_iterator_delete(&riter);
> 
> 	struct pmemstream_region new_region;
> ```

pls add a short comment, or two for the main parts of this example

**Review by karczex — COMMENTED** [review]
> Reviewed 4 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/7)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[examples/01-iterate/main.c, line 54 at r1](https://reviewable.io/reviews/pmem/pmemstream/7#-MosfzD_Eb7hN6dLDi9R:-MosmP0b3wuAtKQUvG-M:b-iexmme) ([raw file](https://github.com/pmem/pmemstream/blob/3214352d0a33acac992e91b7fbde3dcdee93036b/examples/01-iterate/main.c#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps, print usage instead
</blockquote></details>

And please describe, how to create this file. 
___
*[src/include/libpmemstream.h, line 35 at r1](https://reviewable.io/reviews/pmem/pmemstream/7#-MosriaLBcJITtDDCMiM:-MosriaLBcJITtDDCMiN:b-gpn70l) ([raw file](https://github.com/pmem/pmemstream/blob/3214352d0a33acac992e91b7fbde3dcdee93036b/src/include/libpmemstream.h#L35)):*
> ```
> int pmemstream_region_allocate(struct pmemstream *stream, size_t size, struct pmemstream_region *region);
> int pmemstream_region_free(struct pmemstream *stream, struct pmemstream_region region);
> ```

It seems to be little bit messy around whole API. Why in allocate is passed pointer to region, but in free is passed structure? 
___
*[src/include/libpmemstream.h, line 39 at r1](https://reviewable.io/reviews/pmem/pmemstream/7#-MossaUg24w-bBoxUAtp:-MossaUg24w-bBoxUAtq:b-lqj1yb) ([raw file](https://github.com/pmem/pmemstream/blob/3214352d0a33acac992e91b7fbde3dcdee93036b/src/include/libpmemstream.h#L39)):*
> ```objc
> size_t pmemstream_region_size(struct pmemstream *stream, struct pmemstream_region region);
> 
> int pmemstream_region_context_new(struct pmemstream_region_context **rcontext,
> ```

This is similar situation, but even more tricky, as you pass **rcontext. I find APIs where you have to check every parameter if it's object, ptr or ptr ptr hard to use. Honestly, the example is hard to read due to this issue.

In general we should figure out some calling convention. I suggest to just pass ptrs to structures virtually everywhere.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/7)* status: 6 of 7 files reviewed, 8 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 19 at r1](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp6XqJDChS5pslx-Kgu:-Mp6XqJDChS5pslx-Kgv:bihq48v) ([raw file](https://github.com/pmem/pmemstream/blob/3214352d0a33acac992e91b7fbde3dcdee93036b/src/libpmemstream.c#L19)):*
> ```C
> #define util_popcount64(value) ((unsigned char)__builtin_popcountll(value))
> 
> enum pmemstream_span_type {
> ```

For the long run, the approach with bit masks is harf to maintain - [like in libpmemobj-cpp ringbuf](https://github.com/pmem/libpmemobj-cpp/blob/9fd40dfd69b2f8202db24cf19add1c02f5802d20/include/libpmemobj%2B%2B/detail/ringbuf.hpp#L74) 

Instead of this, we may try approach with bitfields: 

```C
#include <stdio.h>
#include <stdint.h>

union data_with_flags{
	struct {
		uint64_t data  : 61;
		uint64_t flag1 : 1;
		uint64_t flag2 : 2;
	} manage;
	uint64_t data;
};

int main()
{
	union data_with_flags x;
	x.manage.flag1 = 1;
	x.manage.flag2 = 1;

	x.manage.data = 0xBEEF;

	printf("data: %llx \n", x.manage.data);
	printf("data_with_flags: %llx \n", x.data);
}

```

In this approach you can easily memcpy whole data structure and compiler will prevent  you from shooting in the foot with with overriding your data with flags by mistake with pretty good warning (gcc): 

```
 warning: conversion from ‘uint64_t’ {aka ‘long unsigned int’} to ‘long unsigned int:61’ changes value from ‘4611686018427387904’ to ‘0’ 
```
___
*[src/libpmemstream.c, line 69 at r1](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp6FtLu4huy3ww4mRHb:-Mp6FtLu4huy3ww4mRHc:b6l9ls9) ([raw file](https://github.com/pmem/pmemstream/blob/3214352d0a33acac992e91b7fbde3dcdee93036b/src/libpmemstream.c#L69)):*
> ```C
> 
> static struct pmemstream_span_runtime
> pmemstream_span_get_runtime(uint64_t *span)
> ```

Why uint64_t instead of pmemstream_span? If it's not important  now, you may just 
```C 
typedef pmemstream_span uint64_t;
```
___
*[src/libpmemstream.c, line 271 at r1](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp6i5DcDRBKXWh1k8cd:-Mp6i5DdDG5XyZBzI4B6:bdady33) ([raw file](https://github.com/pmem/pmemstream/blob/3214352d0a33acac992e91b7fbde3dcdee93036b/src/libpmemstream.c#L271)):*
> ```C
> 			      struct pmemstream_region region)
> {
> 	// todo: the only reason context exists is to store the offset of the
> ```

Why we cannot store this offset in region structure?

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/7)* status: 6 of 7 files reviewed, 8 unresolved discussions (waiting on @igchor, @karczex, @lukaszstolarczuk, and @pbalcer)

___
*[src/libpmemstream.c, line 19 at r1](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp6XqJDChS5pslx-Kgu:-Mp6vvxA1sb6Ebm9xKG9:b-ttu4rx) ([raw file](https://github.com/pmem/pmemstream/blob/3214352d0a33acac992e91b7fbde3dcdee93036b/src/libpmemstream.c#L19)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

For the long run, the approach with bit masks is harf to maintain - [like in libpmemobj-cpp ringbuf](https://github.com/pmem/libpmemobj-cpp/blob/9fd40dfd69b2f8202db24cf19add1c02f5802d20/include/libpmemobj%2B%2B/detail/ringbuf.hpp#L74) 

Instead of this, we may try approach with bitfields: 

```C
#include <stdio.h>
#include <stdint.h>

union data_with_flags{
	struct {
		uint64_t data  : 61;
		uint64_t flag1 : 1;
		uint64_t flag2 : 2;
	} manage;
	uint64_t data;
};

int main()
{
	union data_with_flags x;
	x.manage.flag1 = 1;
	x.manage.flag2 = 1;

	x.manage.data = 0xBEEF;

	printf("data: %llx \n", x.manage.data);
	printf("data_with_flags: %llx \n", x.data);
}

```

In this approach you can easily memcpy whole data structure and compiler will prevent  you from shooting in the foot with with overriding your data with flags by mistake with pretty good warning (gcc): 

```
 warning: conversion from ‘uint64_t’ {aka ‘long unsigned int’} to ‘long unsigned int:61’ changes value from ‘4611686018427387904’ to ‘0’ 
```

</blockquote></details>

bitfields are not really portable:
https://stackoverflow.com/questions/18652148/clarification-about-bit-field-ordering-semantics-in-c
https://lwn.net/Articles/478657/

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/7)* status: 6 of 7 files reviewed, 8 unresolved discussions (waiting on @igchor, @karczex, @lukaszstolarczuk, and @pbalcer)

___
*[src/libpmemstream.c, line 19 at r1](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp6XqJDChS5pslx-Kgu:-Mp74EdN5QzfuRiaqTy0:bho9hsq) ([raw file](https://github.com/pmem/pmemstream/blob/3214352d0a33acac992e91b7fbde3dcdee93036b/src/libpmemstream.c#L19)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

bitfields are not really portable:
https://stackoverflow.com/questions/18652148/clarification-about-bit-field-ordering-semantics-in-c
https://lwn.net/Articles/478657/
</blockquote></details>

That's really unfortunate.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 5 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/7)* status: all files reviewed, 13 unresolved discussions (waiting on @igchor, @karczex, @lukaszstolarczuk, and @pbalcer)

___
*[src/libpmemstream.c, line 15 at r2](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp7IL93184W8IHkCixh:-Mp7IL93184W8IHkCixi:beodseo) ([raw file](https://github.com/pmem/pmemstream/blob/19bfced47a3b072a3e84d6914763dca47d60738a/src/libpmemstream.c#L15)):*
> ```
> MEMBER_SIZE(type, member) sizeof(((struct type*)NULL)->member)
> ```
Why not function?
___
*[src/libpmemstream.c, line 17 at r2](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp7FSh17f9qd5W0Zvns:-Mp7FSh24O-SoMXbKBKP:biqmtoy) ([raw file](https://github.com/pmem/pmemstream/blob/19bfced47a3b072a3e84d6914763dca47d60738a/src/libpmemstream.c#L17)):*
> ```C
> #define MEMBER_SIZE(type, member) sizeof(((struct type*)NULL)->member)
> 
> #define util_popcount64(value) ((unsigned char)__builtin_popcountll(value))
> ```

Upper case or c-function
___
*[src/libpmemstream.c, line 35 at r2](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp7GJcnBU1Kz4C4s9di:-Mp7GJcnBU1Kz4C4s9dj:b-flufj9) ([raw file](https://github.com/pmem/pmemstream/blob/19bfced47a3b072a3e84d6914763dca47d60738a/src/libpmemstream.c#L35)):*
> ```
> free
> ```
We should change it to different name I think, below we have pointers to functions: `pmem2_memcpy_fn memcpy`, `pmem2_memset_fn memset`, but `free` is a just structure.
___
*[src/libpmemstream.c, line 78 at r2](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp7I5cF-8VnWosQiMX-:-Mp7I5cF-8VnWosQiMX0:b4p6gpl) ([raw file](https://github.com/pmem/pmemstream/blob/19bfced47a3b072a3e84d6914763dca47d60738a/src/libpmemstream.c#L78)):*
> ```
> free
> ```
looks very similar to `free()` and we can change the name to something different
___
*[src/libpmemstream.c, line 83 at r2](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp7PZEI7XOXAL6tZIsZ:-Mp7PZEI7XOXAL6tZIs_:bvoicr3) ([raw file](https://github.com/pmem/pmemstream/blob/19bfced47a3b072a3e84d6914763dca47d60738a/src/libpmemstream.c#L83)):*
> ```
> (uint8_t *)&span[2]
> ```

```
(uint8_t *)(span + 2)
```
___
*[src/include/libpmemstream.h, line 39 at r1](https://reviewable.io/reviews/pmem/pmemstream/7#-MossaUg24w-bBoxUAtp:-Mp7dRdi-1sSRmrH4phE:b32v57) ([raw file](https://github.com/pmem/pmemstream/blob/3214352d0a33acac992e91b7fbde3dcdee93036b/src/include/libpmemstream.h#L39)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

This is similar situation, but even more tricky, as you pass **rcontext. I find APIs where you have to check every parameter if it's object, ptr or ptr ptr hard to use. Honestly, the example is hard to read due to this issue.

In general we should figure out some calling convention. I suggest to just pass ptrs to structures virtually everywhere. 
</blockquote></details>

+1

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/7)* status: all files reviewed, 12 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 271 at r1](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp6i5DcDRBKXWh1k8cd:-MpGBYbx85eZcoiWE0WH:b-xrtua3) ([raw file](https://github.com/pmem/pmemstream/blob/3214352d0a33acac992e91b7fbde3dcdee93036b/src/libpmemstream.c#L271)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Why we cannot store this offset in region structure?
</blockquote></details>

Because you don't need to know this offset for some cases (and it's pretty expensive to compute). For example, `pmemstream_region` can be obtained from iterator - we do not have to know this max offset because we will iterate over this region anyway.

We could have offset field in region and only initialize this when needed but that seems more error prone.
___
*[src/libpmemstream.c, line 35 at r2](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp7GJcnBU1Kz4C4s9di:-MpGAxpoEuZbhAEjXo_k:b6mofr8) ([raw file](https://github.com/pmem/pmemstream/blob/19bfced47a3b072a3e84d6914763dca47d60738a/src/libpmemstream.c#L35)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> free
> ```
We should change it to different name I think, below we have pointers to functions: `pmem2_memcpy_fn memcpy`, `pmem2_memset_fn memset`, but `free` is a just structure.
</blockquote></details>

any suggestions for a better name?
___
*[src/libpmemstream.c, line 78 at r2](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp7I5cF-8VnWosQiMX-:-MpGB1EY8QjSJ5e9mOkP:b3kqx) ([raw file](https://github.com/pmem/pmemstream/blob/19bfced47a3b072a3e84d6914763dca47d60738a/src/libpmemstream.c#L78)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> free
> ```
looks very similar to `free()` and we can change the name to something different
</blockquote></details>

.
___
*[src/libpmemstream.c, line 83 at r2](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp7PZEI7XOXAL6tZIsZ:-MpGB3VNDxXOMca5jy3S:bb6p4xv) ([raw file](https://github.com/pmem/pmemstream/blob/19bfced47a3b072a3e84d6914763dca47d60738a/src/libpmemstream.c#L83)):*
> .
___
*[src/include/libpmemstream.h, line 35 at r1](https://reviewable.io/reviews/pmem/pmemstream/7#-MosriaLBcJITtDDCMiM:-MpGBHgD9tsUypSk_dK4:bp0nz1d) ([raw file](https://github.com/pmem/pmemstream/blob/3214352d0a33acac992e91b7fbde3dcdee93036b/src/include/libpmemstream.h#L35)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

> ```
> int pmemstream_region_allocate(struct pmemstream *stream, size_t size, struct pmemstream_region *region);
> int pmemstream_region_free(struct pmemstream *stream, struct pmemstream_region region);
> ```

It seems to be little bit messy around whole API. Why in allocate is passed pointer to region, but in free is passed structure? 
</blockquote></details>

Agree, we can refactor this later
___
*[src/include/libpmemstream.h, line 39 at r1](https://reviewable.io/reviews/pmem/pmemstream/7#-MossaUg24w-bBoxUAtp:-MpGBLsx84X8513ZDumb:b-8ayu6x) ([raw file](https://github.com/pmem/pmemstream/blob/3214352d0a33acac992e91b7fbde3dcdee93036b/src/include/libpmemstream.h#L39)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Agree

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/7)* status: 5 of 7 files reviewed, 12 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[examples/01-iterate/main.c, line 3 at r1](https://reviewable.io/reviews/pmem/pmemstream/7#-Mosh4SuDQLmIImz97Z0:-MpGNeur3yX7GxsTFg8U:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/3214352d0a33acac992e91b7fbde3dcdee93036b/examples/01-iterate/main.c#L3)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

a short desc. here, perhaps
</blockquote></details>

Done.
___
*[examples/01-iterate/main.c, line 54 at r1](https://reviewable.io/reviews/pmem/pmemstream/7#-MosfzD_Eb7hN6dLDi9R:-MpGLpgo5xtKZb5tL2I1:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/3214352d0a33acac992e91b7fbde3dcdee93036b/examples/01-iterate/main.c#L54)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

And please describe, how to create this file. 
</blockquote></details>

Done.
___
*[examples/01-iterate/main.c, line 96 at r1](https://reviewable.io/reviews/pmem/pmemstream/7#-Mosgx0AE0pCIH45ZroA:-MpGLoaD5oQtVEhftTdm:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/3214352d0a33acac992e91b7fbde3dcdee93036b/examples/01-iterate/main.c#L96)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add a short comment, or two for the main parts of this example
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 69 at r1](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp6FtLu4huy3ww4mRHb:-MpGFrEX12ZY7tyGztDG:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/3214352d0a33acac992e91b7fbde3dcdee93036b/src/libpmemstream.c#L69)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Why uint64_t instead of pmemstream_span? If it's not important  now, you may just 
```C 
typedef pmemstream_span uint64_t;
```
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 271 at r1](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp6i5DcDRBKXWh1k8cd:-MpGNgMY40KEMQlEOLvN:b-9sirhx) ([raw file](https://github.com/pmem/pmemstream/blob/3214352d0a33acac992e91b7fbde3dcdee93036b/src/libpmemstream.c#L271)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Because you don't need to know this offset for some cases (and it's pretty expensive to compute). For example, `pmemstream_region` can be obtained from iterator - we do not have to know this max offset because we will iterate over this region anyway.

We could have offset field in region and only initialize this when needed but that seems more error prone.
</blockquote></details>

But, the current API does not work well with iterators anyway. Look at the example, there we first iterate over all entries in a region and the create a context to append new entry at the end (this means second iteration). I think that, if we want to keep context, we should somehow integrate it with iterators.
___
*[src/libpmemstream.c, line 15 at r2](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp7IL93184W8IHkCixh:-MpGDSol1jQ-IRxf7uRK:b2wrunk) ([raw file](https://github.com/pmem/pmemstream/blob/19bfced47a3b072a3e84d6914763dca47d60738a/src/libpmemstream.c#L15)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> MEMBER_SIZE(type, member) sizeof(((struct type*)NULL)->member)
> ```
Why not function?
</blockquote></details>

Because you cannot pass type as a parameter
___
*[src/libpmemstream.c, line 17 at r2](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp7FSh17f9qd5W0Zvns:-MpGDaLJ1HpJa-vgGHLm:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/19bfced47a3b072a3e84d6914763dca47d60738a/src/libpmemstream.c#L17)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Upper case or c-function
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/7)* status: 4 of 7 files reviewed, 8 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 15 at r2](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp7IL93184W8IHkCixh:-MpGSNXoEDNmOHP0QU3Y:b-s8c7l9) ([raw file](https://github.com/pmem/pmemstream/blob/19bfced47a3b072a3e84d6914763dca47d60738a/src/libpmemstream.c#L15)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Because you cannot pass type as a parameter
</blockquote></details>

@kfilipek 
Poor man's template :) 
___
*[src/libpmemstream.c, line 35 at r2](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp7GJcnBU1Kz4C4s9di:-MpGRJhL2Nn22NOFutMC:bnvft8r) ([raw file](https://github.com/pmem/pmemstream/blob/19bfced47a3b072a3e84d6914763dca47d60738a/src/libpmemstream.c#L35)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

any suggestions for a better name?
</blockquote></details>

I agree, free may be little bit confusing. `empty` maybe?

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/7)* status: 6 of 7 files reviewed, 7 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[examples/01-iterate/main.c, line 51 at r3](https://reviewable.io/reviews/pmem/pmemstream/7#-MpGREYq3Gw-AuGjRY8h:-MpGREYq3Gw-AuGjRY8i:bkj12d7) ([raw file](https://github.com/pmem/pmemstream/blob/99daaf5e673e3a69c97fd3a88fe048830907dc84/examples/01-iterate/main.c#L51)):*
> ```C
> 
> /**
>  * This example creates a stream from map2 source, prints it's content and appends monotonically
> ```

`it's` -> `its`
___
*[examples/01-iterate/main.c, line 55 at r3](https://reviewable.io/reviews/pmem/pmemstream/7#-MpGRRNQ0vy6QI0-DBQi:-MpGRRNQ0vy6QI0-DBQj:bkdws56) ([raw file](https://github.com/pmem/pmemstream/blob/99daaf5e673e3a69c97fd3a88fe048830907dc84/examples/01-iterate/main.c#L55)):*
> ```C
>  *
>  * It accepts a path to already existing, zeroed out file.
>  * (File can be create for example by dd: dd if=/dev/zero of=file bs=1024 count=1024)
> ```

1. `be created`
2. perhaps `for example` = `e.g.`
___
*[src/libpmemstream.c, line 35 at r2](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp7GJcnBU1Kz4C4s9di:-MpGTu4q6gTHbqh-eNPX:b1rrpze) ([raw file](https://github.com/pmem/pmemstream/blob/19bfced47a3b072a3e84d6914763dca47d60738a/src/libpmemstream.c#L35)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I agree, free may be little bit confusing. `empty` maybe?
</blockquote></details>

yep, I also thought about `empty`

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/7)* status: 6 of 7 files reviewed, 7 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[examples/01-iterate/main.c, line 51 at r3](https://reviewable.io/reviews/pmem/pmemstream/7#-MpGREYq3Gw-AuGjRY8h:-MpHBmWYEjlWSirb3JTB:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/99daaf5e673e3a69c97fd3a88fe048830907dc84/examples/01-iterate/main.c#L51)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`it's` -> `its`
</blockquote></details>

Done.
___
*[examples/01-iterate/main.c, line 55 at r3](https://reviewable.io/reviews/pmem/pmemstream/7#-MpGRRNQ0vy6QI0-DBQi:-MpHBoVf0AcXOO0-j0L6:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/99daaf5e673e3a69c97fd3a88fe048830907dc84/examples/01-iterate/main.c#L55)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. `be created`
2. perhaps `for example` = `e.g.`
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 15 at r2](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp7IL93184W8IHkCixh:-MpHBv9y68R7aCbWQrrJ:b7u03hh) ([raw file](https://github.com/pmem/pmemstream/blob/19bfced47a3b072a3e84d6914763dca47d60738a/src/libpmemstream.c#L15)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

@kfilipek 
Poor man's template :) 
</blockquote></details>

Correct
___
*[src/libpmemstream.c, line 35 at r2](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp7GJcnBU1Kz4C4s9di:-MpHCEjhEJDwT8Vvz_yT:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/19bfced47a3b072a3e84d6914763dca47d60738a/src/libpmemstream.c#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

yep, I also thought about `empty`
</blockquote></details>

Done.

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/7)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[examples/01-iterate/main.c, line 145 at r3](https://reviewable.io/reviews/pmem/pmemstream/7#-MpH7sxs8Ri_JlC5CnCC:-MpH7sxu3LJRPHdK0lhU:bbz8pb7) ([raw file](https://github.com/pmem/pmemstream/blob/99daaf5e673e3a69c97fd3a88fe048830907dc84/examples/01-iterate/main.c#L145)):*
> ```
> return -1;
> ```

```
return ret;
```
But it's not a must have.
___
*[src/libpmemstream.c, line 35 at r2](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp7GJcnBU1Kz4C4s9di:-MpGjOivEXO3Yymo4D01:b-8ayu6x) ([raw file](https://github.com/pmem/pmemstream/blob/19bfced47a3b072a3e84d6914763dca47d60738a/src/libpmemstream.c#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

yep, I also thought about `empty`
</blockquote></details>

Agree
___
*[src/libpmemstream.c, line 280 at r3](https://reviewable.io/reviews/pmem/pmemstream/7#-MpHJQPV6vYFJpWpzFUH:-MpHJQPV6vYFJpWpzFUI:bmv0tns) ([raw file](https://github.com/pmem/pmemstream/blob/99daaf5e673e3a69c97fd3a88fe048830907dc84/src/libpmemstream.c#L280)):*
> ```
> struct pmemstream_region_context *c = malloc(sizeof(*c))
> ```
nit: `sizeof(*c)` -> `sizeof *c`

It's a (2) case:
```
sizeof( type ) 	(1) 	
sizeof expression 	 (2) 	
```
https://en.cppreference.com/w/cpp/language/sizeof

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/7)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[examples/01-iterate/main.c, line 145 at r3](https://reviewable.io/reviews/pmem/pmemstream/7#-MpH7sxs8Ri_JlC5CnCC:-MpHM0gy0p_6DviFym_3:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/99daaf5e673e3a69c97fd3a88fe048830907dc84/examples/01-iterate/main.c#L145)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> return -1;
> ```

```
return ret;
```
But it's not a must have.
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 35 at r2](https://reviewable.io/reviews/pmem/pmemstream/7#-Mp7GJcnBU1Kz4C4s9di:-MpHKL6f8jOhv9PohRFO:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/19bfced47a3b072a3e84d6914763dca47d60738a/src/libpmemstream.c#L35)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Agree
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/7#-:-MpHdn9UBjgiduthhJkU:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/7#-:-MpHeYIH3Giysm9qKtxS:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

**Pull request merged**
