### PR TITLE
Add docs

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/222)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/222)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[`doc/libpmemstream.7.md` line 43 at r1](https://reviewable.io/reviews/pmem/pmemstream/222#-N5AFv2u3dypsWM7niK8:-N5AFv2u3dypsWM7niK9:b-vw50e0) ([raw file](https://github.com/pmem/pmemstream/blob/897d7f6626c082208aa7526a3d5b0238ee4af17d/doc/libpmemstream.7.md#L43)):*
> ```Markdown
> solutions. It delivers a generic, easy-to-use set of functions.
> 
> It uses underneath **libpmem2** and **libminiasync** libraries. The latter one
> ```

I think `underneath` should be at the end of the sentence.
___
*[`doc/libpmemstream.7.md` line 49 at r1](https://reviewable.io/reviews/pmem/pmemstream/222#-N5AFo5MBE_UP9KyeVUc:-N5AFo5MBE_UP9KyeVUd:b-76b06g) ([raw file](https://github.com/pmem/pmemstream/blob/897d7f6626c082208aa7526a3d5b0238ee4af17d/doc/libpmemstream.7.md#L49)):*
> ```Markdown
> [GitHub repository](https://github.com/pmem/pmemstream)
> 
> Core features in libpmemstream are:
> ```

`Core features of libpmemstream`:
___
*[`doc/libpmemstream.7.md` line 72 at r1](https://reviewable.io/reviews/pmem/pmemstream/222#-N5AF_Y42d_uBGJFeyVG:-N5AF_Y42d_uBGJFeyVH:b3kre) ([raw file](https://github.com/pmem/pmemstream/blob/897d7f6626c082208aa7526a3d5b0238ee4af17d/doc/libpmemstream.7.md#L72)):*
> ```Markdown
>     defines the size for other regions within one stream,
> - no entry modification allowed,
> - appends can be spawned concurrently only to ,
> ```

?

**Review by igchor — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/222)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[`src/include/libpmemstream.h` line 83 at r2](https://reviewable.io/reviews/pmem/pmemstream/222#-N5F5uVq302Xv0O8s8rT:-N5F5uVq302Xv0O8s8rU:b3kre) ([raw file](https://github.com/pmem/pmemstream/blob/13c075f6b50db2cae34a2fd0a30065ee01f8cf16/src/include/libpmemstream.h#L83)):*
> ```objc
> size_t pmemstream_region_usable_size(struct pmemstream *stream, struct pmemstream_region region);
> 
> /* XXX
> ```

?
___
*[`src/include/libpmemstream.h` line 120 at r2](https://reviewable.io/reviews/pmem/pmemstream/222#-N5F61icE8BBlF1VURAo:-N5F61icE8BBlF1VURAp:b-yqqcfm) ([raw file](https://github.com/pmem/pmemstream/blob/13c075f6b50db2cae34a2fd0a30065ee01f8cf16/src/include/libpmemstream.h#L120)):*
> ```objc
> 		       struct pmemstream_region_runtime *region_runtime, struct pmemstream_entry entry, size_t size);
> 
> /* Synchronously appends data buffer to a given region, at offset pointed by region_runtime.
> ```

hm, maybe "at offset determined by region_runtime" would be better?
___
*[`src/include/libpmemstream.h` line 126 at r2](https://reviewable.io/reviews/pmem/pmemstream/222#-N5F6DqT4Rruj2J86T2k:-N5F6DqT4Rruj2J86T2l:b-i1pqo6) ([raw file](https://github.com/pmem/pmemstream/blob/13c075f6b50db2cae34a2fd0a30065ee01f8cf16/src/include/libpmemstream.h#L126)):*
> ```objc
>  * If it's NULL, it will be obtained from its internal structures (which might incur overhead).
>  *
>  * data is a pointer to the buffer data, to be appended.
> ```

`data buffer`?
___
*[`src/include/libpmemstream.h` line 177 at r2](https://reviewable.io/reviews/pmem/pmemstream/222#-N5F6Mtc65Zkzm0A77HV:-N5F6Mtc65Zkzm0A77HW:b3ntans) ([raw file](https://github.com/pmem/pmemstream/blob/13c075f6b50db2cae34a2fd0a30065ee01f8cf16/src/include/libpmemstream.h#L177)):*
> ```objc
>  * To get "persisted" guarantee for given timestamp, the returned future must be polled until completion.
>  *
>  * Persisted data is guaranteed to be safely reachable after application's restart.
> ```

drop `safely` - reachable is enough.

You could also mention that if entry is persisted it is also commited.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/222)* status: 3 of 8 files reviewed, all discussions resolved (waiting on @igchor)

___
*[`doc/libpmemstream.3.md` line 117 at r3](https://reviewable.io/reviews/pmem/pmemstream/222#-N5F6fVz4bKdnVt5h-VH:-N5F6fVz4bKdnVt5h-VI:b-q86xjt) ([raw file](https://github.com/pmem/pmemstream/blob/246d4a1f630ceaadda53a314c5f0a213a3947898/doc/libpmemstream.3.md#L117)):*
> ```Markdown
> 	It returns 0 on success, error code otherwise.
> 
> ...
> ```

when all comments in the header file will look ok, I'll just copy-paste the content here
___
*[`doc/libpmemstream.7.md` line 43 at r1](https://reviewable.io/reviews/pmem/pmemstream/222#-N5AFv2u3dypsWM7niK8:-N5F6pjyDGnIqWyYq9_E:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/897d7f6626c082208aa7526a3d5b0238ee4af17d/doc/libpmemstream.7.md#L43)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think `underneath` should be at the end of the sentence.
</blockquote></details>

Done.
___
*[`doc/libpmemstream.7.md` line 49 at r1](https://reviewable.io/reviews/pmem/pmemstream/222#-N5AFo5MBE_UP9KyeVUc:-N5F6qfJ-U1TCzmL0eQ0:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/897d7f6626c082208aa7526a3d5b0238ee4af17d/doc/libpmemstream.7.md#L49)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

`Core features of libpmemstream`:
</blockquote></details>

Done.
___
*[`doc/libpmemstream.7.md` line 72 at r1](https://reviewable.io/reviews/pmem/pmemstream/222#-N5AF_Y42d_uBGJFeyVG:-N5F6tcY3vBLzuJKfyXm:b-4mjani) ([raw file](https://github.com/pmem/pmemstream/blob/897d7f6626c082208aa7526a3d5b0238ee4af17d/doc/libpmemstream.7.md#L72)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

?
</blockquote></details>

heh, done.
___
*[`src/include/libpmemstream.h` line 83 at r2](https://reviewable.io/reviews/pmem/pmemstream/222#-N5F5uVq302Xv0O8s8rT:-N5F73Zy1fGFcc1poI2Q:bmpb8v3) ([raw file](https://github.com/pmem/pmemstream/blob/13c075f6b50db2cae34a2fd0a30065ee01f8cf16/src/include/libpmemstream.h#L83)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

?
</blockquote></details>

I just couldn't find proper words yesterday :wink:
Done.
___
*[`src/include/libpmemstream.h` line 120 at r2](https://reviewable.io/reviews/pmem/pmemstream/222#-N5F61icE8BBlF1VURAo:-N5F7HSi6WZSyN6l-mgp:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/13c075f6b50db2cae34a2fd0a30065ee01f8cf16/src/include/libpmemstream.h#L120)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

hm, maybe "at offset determined by region_runtime" would be better?
</blockquote></details>

Done.
___
*[`src/include/libpmemstream.h` line 126 at r2](https://reviewable.io/reviews/pmem/pmemstream/222#-N5F6DqT4Rruj2J86T2k:-N5F7RmNDU8G3dGllyNJ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/13c075f6b50db2cae34a2fd0a30065ee01f8cf16/src/include/libpmemstream.h#L126)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

`data buffer`?
</blockquote></details>

Done.
___
*[`src/include/libpmemstream.h` line 177 at r2](https://reviewable.io/reviews/pmem/pmemstream/222#-N5F6Mtc65Zkzm0A77HV:-N5F8Gjz44VXDJ34Xcxl:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/13c075f6b50db2cae34a2fd0a30065ee01f8cf16/src/include/libpmemstream.h#L177)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

drop `safely` - reachable is enough.

You could also mention that if entry is persisted it is also commited.
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 3 of 4 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/222)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @lukaszstolarczuk)

___
*[`doc/libpmemstream.3.md` line 128 at r5](https://reviewable.io/reviews/pmem/pmemstream/222#-N5FOI5I0Djct-N4wa9I:-N5FOI5JAl6t9aiRx402:bysb6po) ([raw file](https://github.com/pmem/pmemstream/blob/7fa76b58b8ce8c3b2f3f3ee58f937416cbb87ef1/doc/libpmemstream.3.md#L128)):*
> ```Markdown
> 	`block_size` defines alignment of regions - must be a power of 2 and multiple of CACHELINE size.
> 	See **libpmem2**(7) for details on creating pmem2 mapping.
> 	If this function is called with an empty mapping the new pmemstream instance will be initialized,
> ```

What does `empty mapping` mean here? You mean mapping representing an empty file or something else?
___
*[`src/include/libpmemstream.h` line 59 at r5](https://reviewable.io/reviews/pmem/pmemstream/222#-N5FU7fKEt1yIOaCK42d:-N5FU7fKEt1yIOaCK42e:b3kqx) ([raw file](https://github.com/pmem/pmemstream/blob/7fa76b58b8ce8c3b2f3f3ee58f937416cbb87ef1/src/include/libpmemstream.h#L59)):*
> ```objc
>  * See **libpmem2**(7) for details on creating pmem2 mapping.
>  *
>  * If this function is called with an empty mapping the new pmemstream instance will be initialized,
> ```

.
___
*[`src/include/libpmemstream.h` line 214 at r5](https://reviewable.io/reviews/pmem/pmemstream/222#-N5FUJix55-Rp4XDe5pY:-N5FUJix55-Rp4XDe5pZ:b-curh29) ([raw file](https://github.com/pmem/pmemstream/blob/7fa76b58b8ce8c3b2f3f3ee58f937416cbb87ef1/src/include/libpmemstream.h#L214)):*
> ```objc
>  *
>  * Persisted data is guaranteed to be reachable after application's restart.
>  * If data is persisted is also guaranteed committed.
> ```

there's something missing in this sentence ;d "If entry is persisted, it is also guaranteed to be committed"?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/222)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @igchor)

___
*[`doc/libpmemstream.3.md` line 128 at r5](https://reviewable.io/reviews/pmem/pmemstream/222#-N5FOI5I0Djct-N4wa9I:-N5Fbyns-hYMAf3j79Fv:bqjbq6r) ([raw file](https://github.com/pmem/pmemstream/blob/7fa76b58b8ce8c3b2f3f3ee58f937416cbb87ef1/doc/libpmemstream.3.md#L128)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

What does `empty mapping` mean here? You mean mapping representing an empty file or something else?
</blockquote></details>

good catch, thx
___
*[`src/include/libpmemstream.h` line 59 at r5](https://reviewable.io/reviews/pmem/pmemstream/222#-N5FU7fKEt1yIOaCK42d:-N5Fc4u98y-_cg3kgOeZ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7fa76b58b8ce8c3b2f3f3ee58f937416cbb87ef1/src/include/libpmemstream.h#L59)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`src/include/libpmemstream.h` line 214 at r5](https://reviewable.io/reviews/pmem/pmemstream/222#-N5FUJix55-Rp4XDe5pY:-N5Fc5uk2bUZ21uUtA9I:baz56k6) ([raw file](https://github.com/pmem/pmemstream/blob/7fa76b58b8ce8c3b2f3f3ee58f937416cbb87ef1/src/include/libpmemstream.h#L214)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

there's something missing in this sentence ;d "If entry is persisted, it is also guaranteed to be committed"?
</blockquote></details>

lol, yes, I've missed something, thx!

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2, 1 of 3 files at r3, 3 of 4 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/222)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[`doc/libpmemstream.3.md` line 112 at r5](https://reviewable.io/reviews/pmem/pmemstream/222#-N5Fqpbu7GPMY-4oPl2Y:-N5Fqpbu7GPMY-4oPl2Z:b-11lsh7) ([raw file](https://github.com/pmem/pmemstream/blob/7fa76b58b8ce8c3b2f3f3ee58f937416cbb87ef1/doc/libpmemstream.3.md#L112)):*
> ```Markdown
> Most of API functions are called with `struct pmemstream *stream` as a first argument. It is a structure
> representing runtime state of a single *pmemstream* instance. It has to be a pointer to a valid
> *pmemstream* instance, created/open using `pmemstream_from_map` call.
> ```

`created/opened`



_Code quote:_
```Markdown
open
```
___
*[`doc/libpmemstream.3.md` line 114 at r5](https://reviewable.io/reviews/pmem/pmemstream/222#-N5FrGId-RiFzdlffPk7:-N5FrGIe8K8HNPAt2xsk:b-nnfn3i) ([raw file](https://github.com/pmem/pmemstream/blob/7fa76b58b8ce8c3b2f3f3ee58f937416cbb87ef1/doc/libpmemstream.3.md#L114)):*
> ```Markdown
> *pmemstream* instance, created/open using `pmemstream_from_map` call.
> 
> Exception is the part of API related to iterators - first parameter in these functions is usually
> ```

I'd prefer something like: `Exception to that rule is the part of API related to iterators`.
Marked statement sounds like you starts describing class or exception mechanism.



_Code quote:_
```Markdown
Exception is the part of API related to iterators
```
___
*[`doc/libpmemstream.3.md` line 130 at r5](https://reviewable.io/reviews/pmem/pmemstream/222#-N5FxT6-6T-3iDNtnfDN:-N5FxT6-6T-3iDNtnfDO:b32wof) ([raw file](https://github.com/pmem/pmemstream/blob/7fa76b58b8ce8c3b2f3f3ee58f937416cbb87ef1/doc/libpmemstream.3.md#L130)):*
> ```Markdown
> 	If this function is called with an empty mapping the new pmemstream instance will be initialized,
> 	if mapping points to a previously existing pmemstream instance it re-opens it and reads persisted header's data,
> 	any other case it's undefined behavior.
> ```

is



_Code quote:_
```Markdown
it's
```

**Review by karczex — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/222)* status: 6 of 8 files reviewed, 6 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[`src/include/libpmemstream.h` line 92 at r6](https://reviewable.io/reviews/pmem/pmemstream/222#-N5J7By4AiaZSNpDsfw-:-N5J7By4AiaZSNpDsfw0:bxld12r) ([raw file](https://github.com/pmem/pmemstream/blob/4f71ad69a019babba491ac637fb0c89823efa18c/src/include/libpmemstream.h#L92)):*
> ```objc
> size_t pmemstream_region_size(struct pmemstream *stream, struct pmemstream_region region);
> 
> /* Returns current usable (free) size of the given 'region'.
> ```

You may add: 
```
 As entries contain metadata, the usable size would be bigger then sum of entries sizes which may fit into region
```
___
*[`src/include/libpmemstream.h` line 114 at r6](https://reviewable.io/reviews/pmem/pmemstream/222#-N5J8W0y2ZLLERPsP1Yq:-N5J8W0y2ZLLERPsP1Yr:bzaq3hj) ([raw file](https://github.com/pmem/pmemstream/blob/4f71ad69a019babba491ac637fb0c89823efa18c/src/include/libpmemstream.h#L114)):*
> ```objc
> /* Reserves space (for a future, custom write) of the given 'size', in a 'region' at offset determined
>  * by 'region_runtime'. Entry's data have to be copied into reserved space by the user and then published
>  * using pmemstream_publish. For regular usage, pmemstream_append should be simpler and safer to use
> ```

... is  simpler and safer...

It would be worth to answer question: 

If append is simpler, safer and provide better performance, what's the point of this function in API? 



_Code quote:_
```objc
For regular usage, pmemstream_append should be simpler and safer
```
___
*[`src/include/libpmemstream.h` line 257 at r6](https://reviewable.io/reviews/pmem/pmemstream/222#-N5JCH3m1vLTHNG9kJ1N:-N5JCH3m1vLTHNG9kJ1O:b-9io4y) ([raw file](https://github.com/pmem/pmemstream/blob/4f71ad69a019babba491ac637fb0c89823efa18c/src/include/libpmemstream.h#L257)):*
> ```objc
>  *
>  * Moves to next region (if any more exists), or sets iterator to invalid region.
>  * Regions are accessed in the order of allocations.
> ```

Calling this function on invalid region is undefined behaviour,                                                                                                                                      
so it should always be called after `pmemstream_region_iterator_is_valid()`.                                
```                                                                                                        
    if(pmemstream_region_iterator_is_valid(it) == 0)                                                       
                        pmemstream_region_iterator_next(it);                             
```

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/222)* status: 4 of 13 files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[`doc/libpmemstream.3.md` line 112 at r5](https://reviewable.io/reviews/pmem/pmemstream/222#-N5Fqpbu7GPMY-4oPl2Y:-N5JncNC3XOWFrCHsjmT:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7fa76b58b8ce8c3b2f3f3ee58f937416cbb87ef1/doc/libpmemstream.3.md#L112)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

`created/opened`
</blockquote></details>

Done.
___
*[`doc/libpmemstream.3.md` line 114 at r5](https://reviewable.io/reviews/pmem/pmemstream/222#-N5FrGId-RiFzdlffPk7:-N5JnsMUBwXno_XsV4dH:bupls90) ([raw file](https://github.com/pmem/pmemstream/blob/7fa76b58b8ce8c3b2f3f3ee58f937416cbb87ef1/doc/libpmemstream.3.md#L114)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I'd prefer something like: `Exception to that rule is the part of API related to iterators`.
Marked statement sounds like you starts describing class or exception mechanism.
</blockquote></details>

Done. Re-phrased.
___
*[`doc/libpmemstream.3.md` line 130 at r5](https://reviewable.io/reviews/pmem/pmemstream/222#-N5FxT6-6T-3iDNtnfDN:-N5JoGDo8yP6cAAqS-XL:bqrotz7) ([raw file](https://github.com/pmem/pmemstream/blob/7fa76b58b8ce8c3b2f3f3ee58f937416cbb87ef1/doc/libpmemstream.3.md#L130)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

is
</blockquote></details>

Done. Re-phrased a little.



_Code quote:_
```Markdown
	If this function is called with a map representing an empty file, the new pmemstream instance will be initialized,
	if a mapping points to a previously existing pmemstream instance, it re-opens it and reads persisted header's data,
	any other case it's undefined behavior.
```
___
*[`src/include/libpmemstream.h` line 92 at r6](https://reviewable.io/reviews/pmem/pmemstream/222#-N5J7By4AiaZSNpDsfw-:-N5Jpk4I2AnaiPmKyckb:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4f71ad69a019babba491ac637fb0c89823efa18c/src/include/libpmemstream.h#L92)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

You may add: 
```
 As entries contain metadata, the usable size would be bigger then sum of entries sizes which may fit into region
```
</blockquote></details>

Done.
___
*[`src/include/libpmemstream.h` line 114 at r6](https://reviewable.io/reviews/pmem/pmemstream/222#-N5J8W0y2ZLLERPsP1Yq:-N5JrHYK7KDiUpTRNf9o:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4f71ad69a019babba491ac637fb0c89823efa18c/src/include/libpmemstream.h#L114)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

... is  simpler and safer...

It would be worth to answer question: 

If append is simpler, safer and provide better performance, what's the point of this function in API? 

</blockquote></details>

Done.
___
*[`src/include/libpmemstream.h` line 257 at r6](https://reviewable.io/reviews/pmem/pmemstream/222#-N5JCH3m1vLTHNG9kJ1N:-N5Jsubo1rM1q5h6bnP6:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4f71ad69a019babba491ac637fb0c89823efa18c/src/include/libpmemstream.h#L257)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Calling this function on invalid region is undefined behaviour,                                                                                                                                      
so it should always be called after `pmemstream_region_iterator_is_valid()`.                                
```                                                                                                        
    if(pmemstream_region_iterator_is_valid(it) == 0)                                                       
                        pmemstream_region_iterator_next(it);                             
```
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/222)* status: 4 of 13 files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[`doc/libpmemstream.3.md` line 258 at r7](https://reviewable.io/reviews/pmem/pmemstream/222#-N5KkNpa3n0sh1dRcxvD:-N5KkNpbAKlvWaud1P5o:b-ttsdgv) ([raw file](https://github.com/pmem/pmemstream/blob/22edf77f97c3efefa0e056b3f02028887af9ce3f/doc/libpmemstream.3.md#L258)):*
> ```Markdown
> `const void *pmemstream_entry_data(struct pmemstream *stream, struct pmemstream_entry entry);`
> 
> :	Returns the size of the data of given 'entry'.
> ```

size? it returns a pointer to the data

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/222)* status: 4 of 13 files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[`doc/libpmemstream.3.md` line 265 at r7](https://reviewable.io/reviews/pmem/pmemstream/222#-N5KkUNaEYanbTZY3F1U:-N5KkUNaEYanbTZY3F1V:b-fdz0xx) ([raw file](https://github.com/pmem/pmemstream/blob/22edf77f97c3efefa0e056b3f02028887af9ce3f/doc/libpmemstream.3.md#L265)):*
> ```Markdown
> `size_t pmemstream_entry_size(struct pmemstream *stream, struct pmemstream_entry entry);`
> 
> :	Returns the size of the given 'entry' (if it points to a valid entry).
> ```

You can write that it's the same value as was passed to pmemstream_append, etc.

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/222)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[`doc/libpmemstream.3.md` line 286 at r7](https://reviewable.io/reviews/pmem/pmemstream/222#-N5Kmd2t4-4VEOzxL4Mf:-N5Kmd2t4-4VEOzxL4Mg:b-1bl9rx) ([raw file](https://github.com/pmem/pmemstream/blob/22edf77f97c3efefa0e056b3f02028887af9ce3f/doc/libpmemstream.3.md#L286)):*
> ```Markdown
> 
> `void pmemstream_region_iterator_seek_first(struct pmemstream_region_iterator *iterator);`
> ```

one extra line
___
*[`doc/libpmemstream.3.md` line 289 at r7](https://reviewable.io/reviews/pmem/pmemstream/222#-N5Kmp_UB30vtSVBY7xN:-N5Kmp_UB30vtSVBY7xO:b-73cfn6) ([raw file](https://github.com/pmem/pmemstream/blob/22edf77f97c3efefa0e056b3f02028887af9ce3f/doc/libpmemstream.3.md#L289)):*
> ```Markdown
> 
> :	Sets region 'iterator' to the first region.
> 	Function sets iterator to the first region, or sets iterator to invalid region.
> ```

It should be the only one statement here (like in `pmemstream_region_iterator_delete`)



_Code quote:_
```Markdown
Function sets iterator to the first region, or sets iterator to invalid region.
```
___
*[`doc/libpmemstream.3.md` line 318 at r7](https://reviewable.io/reviews/pmem/pmemstream/222#-N5KnSd69KeMow-1UFLr:-N5KnSd69KeMow-1UFLs:b2jgq8a) ([raw file](https://github.com/pmem/pmemstream/blob/22edf77f97c3efefa0e056b3f02028887af9ce3f/doc/libpmemstream.3.md#L318)):*
> ```Markdown
> 	The entry iterator is bound to the given 'stream' and 'region'.
> 	Default state is undefined: every new iterator should be moved (e.g.) to first element in the region.
> 	Returns -1 if there is an error.
> ```

error code



_Code quote:_
```Markdown
Returns -1 if there is an error.
```

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/222)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[`doc/libpmemstream.3.md` line 258 at r7](https://reviewable.io/reviews/pmem/pmemstream/222#-N5KkNpa3n0sh1dRcxvD:-N5Ko8DI3whrcmKvxkWF:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/22edf77f97c3efefa0e056b3f02028887af9ce3f/doc/libpmemstream.3.md#L258)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

size? it returns a pointer to the data
</blockquote></details>

Done.
___
*[`doc/libpmemstream.3.md` line 265 at r7](https://reviewable.io/reviews/pmem/pmemstream/222#-N5KkUNaEYanbTZY3F1U:-N5Ko8nfCL_pwLGrVZLW:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/22edf77f97c3efefa0e056b3f02028887af9ce3f/doc/libpmemstream.3.md#L265)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You can write that it's the same value as was passed to pmemstream_append, etc.
</blockquote></details>

Done.
___
*[`doc/libpmemstream.3.md` line 286 at r7](https://reviewable.io/reviews/pmem/pmemstream/222#-N5Kmd2t4-4VEOzxL4Mf:-N5KoJM-5SjfgfKZEOtU:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/22edf77f97c3efefa0e056b3f02028887af9ce3f/doc/libpmemstream.3.md#L286)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

one extra line
</blockquote></details>

Done.



_Code quote:_
```Markdown
ion_iterator_seek_firs
```
___
*[`doc/libpmemstream.3.md` line 289 at r7](https://reviewable.io/reviews/pmem/pmemstream/222#-N5Kmp_UB30vtSVBY7xN:-N5KoYX6Bxy_FdqhExrb:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/22edf77f97c3efefa0e056b3f02028887af9ce3f/doc/libpmemstream.3.md#L289)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

It should be the only one statement here (like in `pmemstream_region_iterator_delete`)
</blockquote></details>

Done.
___
*[`doc/libpmemstream.3.md` line 318 at r7](https://reviewable.io/reviews/pmem/pmemstream/222#-N5KnSd69KeMow-1UFLr:-N5KoZoq4ZXur03-meJ7:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/22edf77f97c3efefa0e056b3f02028887af9ce3f/doc/libpmemstream.3.md#L318)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

error code
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/222)* status: 10 of 13 files reviewed, 5 unresolved discussions (waiting on @karczex and @KFilipek)

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/222#-:-N5KwBzOEzEqOOTfGhYP:bnfp4nl)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @KFilipek)

**Pull request merged**
