### PR TITLE
Add test framework

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
with functions for finding dependencies and setting up tests (e.g. helpers for `ctest`).

It's based on the framework(s) we have in libpmemobj-cpp and pmemkv, with just a pinch of rpma's tweaks and fixes.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/6)

### CODE REVIEW

**Comment by karczex** [comment]
___
*[CMakeLists.txt, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/6#-Mo8Ij7N7XV_-dDoTMSC:-Mo8Ij7N7XV_-dDoTMSD:b-gsi72t) ([raw file](https://github.com/pmem/pmemstream/blob/c0357aea8456c32eda1ce6fc46489726982e4c9d/CMakeLists.txt#L4)):*
> ```CMake
> # Copyright 2018-2021, Intel Corporation
> 
> cmake_minimum_required(VERSION 3.8)
> ```

Cmake 3.8 Is preatty ancient, and we probably cannot reliably guarantee our code will work on it. (Did you test that? I bet we use some newer feature/parameter somewhere) 

Ubuntu20.04 (LTS) uses 3.16.
Debian 9(LTS) uses  cmake3.7, but with 3.16 available in backports repo. 
Fedora, as always supports latest greatest 

So we probably switch to 3.16.

**Review by igchor — COMMENTED** [review]
> Reviewed 21 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/6)* status: 21 of 22 files reviewed, 2 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 36 at r1](https://reviewable.io/reviews/pmem/pmemstream/6#-Mo8ojYE7IZVDqeAjDXR:-Mo8ojYE7IZVDqeAjDXS:b3n3gkh) ([raw file](https://github.com/pmem/pmemstream/blob/c0357aea8456c32eda1ce6fc46489726982e4c9d/tests/CMakeLists.txt#L36)):*
> ```CMake
> endif()
> 
> # XXX: libpmem2
> ```

Not necessary, after my PR
___
*[tests/CMakeLists.txt, line 62 at r1](https://reviewable.io/reviews/pmem/pmemstream/6#-Mo8opBo1fx2ewNcpgli:-Mo8opBo1fx2ewNcpglj:b-df0co2) ([raw file](https://github.com/pmem/pmemstream/blob/c0357aea8456c32eda1ce6fc46489726982e4c9d/tests/CMakeLists.txt#L62)):*
> ```CMake
> endif()
> 
> # XXX: add libpmem dependency
> ```

Hm, we could rewrite this check to use libpmem2 but it would probably be easier to just require libpmem and libpmem2
___
*[tests/cmake/functions.cmake, line 13 at r1](https://reviewable.io/reviews/pmem/pmemstream/6#-Mo8pmvE34DBvoElANDR:-Mo8pmvE34DBvoElANDS:btfnbud) ([raw file](https://github.com/pmem/pmemstream/blob/c0357aea8456c32eda1ce6fc46489726982e4c9d/tests/cmake/functions.cmake#L13)):*
> ```CMake
> 
> # XXX: add for libpmem2 (?):
> # -DLIBPMEMOBJ++_LIBRARY_DIRS=${LIBPMEMOBJ++_LIBRARY_DIRS}
> ```

I think we don't need this for now, it was used for some special tests which did build in cmake script I think.
___
*[tests/cmake/functions.cmake, line 34 at r1](https://reviewable.io/reviews/pmem/pmemstream/6#-Mo8qMPY425iPKUExSTU:-Mo8qMPY425iPKUExSTV:bjyh5nh) ([raw file](https://github.com/pmem/pmemstream/blob/c0357aea8456c32eda1ce6fc46489726982e4c9d/tests/cmake/functions.cmake#L34)):*
> ```CMake
> # XXX: libpmem2? ${LIBPMEMOBJ++_INCLUDE_DIRS}
> set(INCLUDE_DIRS ../common/ ../../src)
> # set(LIBS_DIRS ${LIBPMEMOBJ++_LIBRARY_DIRS})
> ```

Yeah, we could add this for libpmem2
___
*[tests/cmake/functions.cmake, line 223 at r1](https://reviewable.io/reviews/pmem/pmemstream/6#-Mo8qXEU8cDMJWhJwyI5:-Mo8qXEU8cDMJWhJwyI6:b-ij8lk) ([raw file](https://github.com/pmem/pmemstream/blob/c0357aea8456c32eda1ce6fc46489726982e4c9d/tests/cmake/functions.cmake#L223)):*
> ```CMake
> 	endif()
> 
> 	# XXX: do we use this "COST" anyhow?
> ```

it's used to execute pmemcheck tests first as far as I remember

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/6)* status: 17 of 22 files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)

___
*[CMakeLists.txt, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/6#-Mo8Ij7N7XV_-dDoTMSC:-Mo8yB0Z5dYspBCpeOV3:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c0357aea8456c32eda1ce6fc46489726982e4c9d/CMakeLists.txt#L4)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Cmake 3.8 Is preatty ancient, and we probably cannot reliably guarantee our code will work on it. (Did you test that? I bet we use some newer feature/parameter somewhere) 

Ubuntu20.04 (LTS) uses 3.16.
Debian 9(LTS) uses  cmake3.7, but with 3.16 available in backports repo. 
Fedora, as always supports latest greatest 

So we probably switch to 3.16. 
</blockquote></details>

Done.
___
*[tests/CMakeLists.txt, line 36 at r1](https://reviewable.io/reviews/pmem/pmemstream/6#-Mo8ojYE7IZVDqeAjDXR:-Mo8yR-yCPdgGXq9L30Y:bi9lr5l) ([raw file](https://github.com/pmem/pmemstream/blob/c0357aea8456c32eda1ce6fc46489726982e4c9d/tests/CMakeLists.txt#L36)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Not necessary, after my PR
</blockquote></details>

true, removed
___
*[tests/CMakeLists.txt, line 62 at r1](https://reviewable.io/reviews/pmem/pmemstream/6#-Mo8opBo1fx2ewNcpgli:-Mo8yEi996vcBUNsZQ05:b-wmrcvb) ([raw file](https://github.com/pmem/pmemstream/blob/c0357aea8456c32eda1ce6fc46489726982e4c9d/tests/CMakeLists.txt#L62)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, we could rewrite this check to use libpmem2 but it would probably be easier to just require libpmem and libpmem2
</blockquote></details>

yeah, I had a similar idea; for now, I only left a comment
___
*[tests/cmake/functions.cmake, line 13 at r1](https://reviewable.io/reviews/pmem/pmemstream/6#-Mo8pmvE34DBvoElANDR:-Mo8yoQ8377vNj-DZeCk:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c0357aea8456c32eda1ce6fc46489726982e4c9d/tests/cmake/functions.cmake#L13)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think we don't need this for now, it was used for some special tests which did build in cmake script I think.
</blockquote></details>

Done.
___
*[tests/cmake/functions.cmake, line 34 at r1](https://reviewable.io/reviews/pmem/pmemstream/6#-Mo8qMPY425iPKUExSTU:-Mo8z-rK43bbkCbJwa0_:baynd63) ([raw file](https://github.com/pmem/pmemstream/blob/c0357aea8456c32eda1ce6fc46489726982e4c9d/tests/cmake/functions.cmake#L34)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Yeah, we could add this for libpmem2
</blockquote></details>

I guess we'll add it with a first test requiring this
___
*[tests/cmake/functions.cmake, line 223 at r1](https://reviewable.io/reviews/pmem/pmemstream/6#-Mo8qXEU8cDMJWhJwyI5:-Mo8zECq2ersprYgEmBy:b-q01y5z) ([raw file](https://github.com/pmem/pmemstream/blob/c0357aea8456c32eda1ce6fc46489726982e4c9d/tests/cmake/functions.cmake#L223)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

it's used to execute pmemcheck tests first as far as I remember
</blockquote></details>

Done, thx

**Review by karczex — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/6)* status: 17 of 22 files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/cmake/exec_functions.cmake, line 98 at r1](https://reviewable.io/reviews/pmem/pmemstream/6#-Mo8s4VG3r8GM999Apfd:-Mo8s4VG3r8GM999Apfe:b-aahid6) ([raw file](https://github.com/pmem/pmemstream/blob/c0357aea8456c32eda1ce6fc46489726982e4c9d/tests/cmake/exec_functions.cmake#L98)):*
> ```CMake
> endfunction()
> 
> function(execute_common expect_success output_file name)
> ```

This function is little bit too long and deserve some refactoring :) 
___
*[tests/cmake/functions.cmake, line 5 at r1](https://reviewable.io/reviews/pmem/pmemstream/6#-Mo8t_h0BmfSudvB5V-t:-Mo8t_h0BmfSudvB5V-u:b34zksv) ([raw file](https://github.com/pmem/pmemstream/blob/c0357aea8456c32eda1ce6fc46489726982e4c9d/tests/cmake/functions.cmake#L5)):*
> ```
>  helper functions for tests/CMakeLists.txt:
> ```
This is file with helper functions, however it set some variables on import. Is it as intended? 
___
*[tests/cmake/functions.cmake, line 43 at r1](https://reviewable.io/reviews/pmem/pmemstream/6#-Mo8vA7H6GsgYyJJRKMb:-Mo8vA7H6GsgYyJJRKMc:b-rwz193) ([raw file](https://github.com/pmem/pmemstream/blob/c0357aea8456c32eda1ce6fc46489726982e4c9d/tests/cmake/functions.cmake#L43)):*
> ```CMake
> # ----------------------------------------------------------------- #
> function(find_gdb)
> 	execute_process(COMMAND gdb --help
> ```

Should use `find_program()` like in `find_pmempool()` this s
___
*[tests/cmake/functions.cmake, line 129 at r1](https://reviewable.io/reviews/pmem/pmemstream/6#-Mo8vVcj80CJ18TjtwNs:-Mo8vVcj80CJ18TjtwNt:b-5i0lf5) ([raw file](https://github.com/pmem/pmemstream/blob/c0357aea8456c32eda1ce6fc46489726982e4c9d/tests/cmake/functions.cmake#L129)):*
> ```
> ${LIBPMEMOBJ_PREFIX}
> ```
Should it be like that? If not, please fix all over this file.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/6#-:-Mo9Aghy1a3GeeMOk14M:bnfp4nl)* status: 17 of 22 files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/6)* status: 17 of 22 files reviewed, 3 unresolved discussions (waiting on @igchor and @karczex)

___
*[tests/cmake/exec_functions.cmake, line 98 at r1](https://reviewable.io/reviews/pmem/pmemstream/6#-Mo8s4VG3r8GM999Apfd:-Mo94JfM74tx56IdY2YS:b-m6m0ht) ([raw file](https://github.com/pmem/pmemstream/blob/c0357aea8456c32eda1ce6fc46489726982e4c9d/tests/cmake/exec_functions.cmake#L98)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

This function is little bit too long and deserve some refactoring :) 
</blockquote></details>

I've added a comment for refactoring this - I'd be the best to check if it works when we have any test
___
*[tests/cmake/functions.cmake, line 5 at r1](https://reviewable.io/reviews/pmem/pmemstream/6#-Mo8t_h0BmfSudvB5V-t:-Mo952zj7h7fyRDBjAW0:b3s7vph) ([raw file](https://github.com/pmem/pmemstream/blob/c0357aea8456c32eda1ce6fc46489726982e4c9d/tests/cmake/functions.cmake#L5)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

> ```
>  helper functions for tests/CMakeLists.txt:
> ```
This is file with helper functions, however it set some variables on import. Is it as intended? 
</blockquote></details>

yeah, I've updated the comment

also, they are not global_scope, so it shouldn't impact anything else, just tests
___
*[tests/cmake/functions.cmake, line 43 at r1](https://reviewable.io/reviews/pmem/pmemstream/6#-Mo8vA7H6GsgYyJJRKMb:-Mo9K-4eBSUtNIHFCJ_c:b-pvl3rq) ([raw file](https://github.com/pmem/pmemstream/blob/c0357aea8456c32eda1ce6fc46489726982e4c9d/tests/cmake/functions.cmake#L43)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Should use `find_program()` like in `find_pmempool()` this s
</blockquote></details>

haha, I don't know why it was done this way. Good catch.
___
*[tests/cmake/functions.cmake, line 129 at r1](https://reviewable.io/reviews/pmem/pmemstream/6#-Mo8vVcj80CJ18TjtwNs:-Mo94gpY621IEKcUZYcM:b-285f2k) ([raw file](https://github.com/pmem/pmemstream/blob/c0357aea8456c32eda1ce6fc46489726982e4c9d/tests/cmake/functions.cmake#L129)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

> ```
> ${LIBPMEMOBJ_PREFIX}
> ```
Should it be like that? If not, please fix all over this file.
</blockquote></details>

I believe it was done in the meantime of your review.

**Review by lukaszstolarczuk — COMMENTED** [review]
I've renamed some CMake variables and simplified little CMake workflows, and added the very first, basic test.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/6#-:-MoZDc8Y7JGSzZ3ncJPG:bjgxy12)* status: 14 of 25 files reviewed, 3 unresolved discussions (waiting on @igchor and @karczex)

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/6#-:-MocIkde4zHkJRNLy-1_:bnfp4nl)* status: 14 of 25 files reviewed, all discussions resolved (waiting on @igchor and @karczex)

**Review by igchor — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/6#-:-Moc_GwQ6LCe99CwMUfO:bnfp4nl)* status: 14 of 25 files reviewed, 3 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 111 at r3](https://reviewable.io/reviews/pmem/pmemstream/6#-MocYvO06sJsvQexgs36:-MocYvO06sJsvQexgs37:b-fnln0k) ([raw file](https://github.com/pmem/pmemstream/blob/aa57bbfe2345def6a97e0fa70bb5710081b8975f/CMakeLists.txt#L111)):*
> ```CMake
> endif()
> # XXX: should it be here? or it's only req. in 'src'?
> include_directories(${LIBPMEM2_INCLUDE_DIRS})
> ```

nit: This one is not needed probably, we have target_include_directories in src and examples. Perhaps we could also use target_link_directories in the same way?
___
*[tests/cmake/exec_functions.cmake, line 325 at r3](https://reviewable.io/reviews/pmem/pmemstream/6#-MocZMoZBTB499mnxJED:-MocZMoZBTB499mnxJEE:bl7ejdp) ([raw file](https://github.com/pmem/pmemstream/blob/aa57bbfe2345def6a97e0fa70bb5710081b8975f/tests/cmake/exec_functions.cmake#L325)):*
> ```CMake
> 
> function(pmempool_execute)
> 	# XXX: do we need this function? if so we need to set proper lib dirs
> ```

nit: I don't think we will need this
___
*[tests/common/unittest.h, line 23 at r3](https://reviewable.io/reviews/pmem/pmemstream/6#-MocZfXzBEat0c73WwYw:-MocZfXzBEat0c73WwYx:b-ac5y9o) ([raw file](https://github.com/pmem/pmemstream/blob/aa57bbfe2345def6a97e0fa70bb5710081b8975f/tests/common/unittest.h#L23)):*
> ```objc
> 
> /* XXX: refactor to use __start (https://stackoverflow.com/questions/15919356/c-program-start) */
> #define START() test_register_sighandlers()
> ```

why do you want to use __start?
___
*[tests/common/unittest.h, line 84 at r3](https://reviewable.io/reviews/pmem/pmemstream/6#-MocZn6TAGCk4kdoXmSx:-MocZn6TAGCk4kdoXmSy:b-23cix0) ([raw file](https://github.com/pmem/pmemstream/blob/aa57bbfe2345def6a97e0fa70bb5710081b8975f/tests/common/unittest.h#L84)):*
> ```objc
> 		 0)))
> 
> /* helper function for creating a pmem2_map from a file path */
> ```

probably it should also accept granularity as parameter

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/6)* status: 12 of 25 files reviewed, all discussions resolved (waiting on @igchor and @karczex)

___
*[CMakeLists.txt, line 111 at r3](https://reviewable.io/reviews/pmem/pmemstream/6#-MocYvO06sJsvQexgs36:-Mocfd0jDsG1LN55NyNq:bp0gkm7) ([raw file](https://github.com/pmem/pmemstream/blob/aa57bbfe2345def6a97e0fa70bb5710081b8975f/CMakeLists.txt#L111)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

nit: This one is not needed probably, we have target_include_directories in src and examples. Perhaps we could also use target_link_directories in the same way?
</blockquote></details>

Actually, it's the other way around - all our components require this now (tests use libpmem2 functions e.g. to prep. a mapping), so I believe it's better to set it up here.
___
*[tests/common/unittest.h, line 23 at r3](https://reviewable.io/reviews/pmem/pmemstream/6#-MocZfXzBEat0c73WwYw:-MocbL060oym3dOXCrrL:b-3sb7fl) ([raw file](https://github.com/pmem/pmemstream/blob/aa57bbfe2345def6a97e0fa70bb5710081b8975f/tests/common/unittest.h#L23)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why do you want to use __start?
</blockquote></details>

I just had a glimpse at this solution, but I believe Paweł suggested this to avoid writing `START()` in every test - this `__start` could be loaded automagically before any tests' `main()` function.

anyway, to be checked later
___
*[tests/common/unittest.h, line 84 at r3](https://reviewable.io/reviews/pmem/pmemstream/6#-MocZn6TAGCk4kdoXmSx:-MocbGv2BPlioGYkAYsX:b-697pd9) ([raw file](https://github.com/pmem/pmemstream/blob/aa57bbfe2345def6a97e0fa70bb5710081b8975f/tests/common/unittest.h#L84)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

probably it should also accept granularity as parameter
</blockquote></details>

added XXX

**Review by igchor — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/6#-:-MocgWP44rRBsfEJv7jU:bnfp4nl)* status: 12 of 25 files reviewed, all discussions resolved (waiting on @igchor and @karczex)

**Pull request merged**
