### PR TITLE
Add testing SLIST_REMOVE macro in pmreorder test

### PR DESCRIPTION
**Pull request by KFilipek**
- add testing remove in pmreorder test
- refactor generating commands

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/167)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/167)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 86 at r1](https://reviewable.io/reviews/pmem/pmemstream/167#-N-YaDpt-0mFaDx_hfYq:-N-YaDpt-0mFaDx_hfYr:b-q3mkzd) ([raw file](https://github.com/pmem/pmemstream/blob/531bf040d7641192c30c15223f05c4023d62f3e7/tests/integrity/singly_linked_list_pmreorder.cpp#L86)):*
> ```cpp
> 
> template <typename T>
> T get_one_of(std::list<T> elements) {
> ```

why not vector/deque or anything with random access? 

Also, you should take it by const ref or ref.
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 135 at r1](https://reviewable.io/reviews/pmem/pmemstream/167#-N-YaY8M9fi12GTMl9D1:-N-YaY8M9fi12GTMl9D2:brl946k) ([raw file](https://github.com/pmem/pmemstream/blob/531bf040d7641192c30c15223f05c4023d62f3e7/tests/integrity/singly_linked_list_pmreorder.cpp#L135)):*
> ```cpp
> 	{
> 		used_offsets.push_front(offsets[index]); 
> 		return [=]() { SLIST_INSERT_HEAD(struct node, runtime, list, offsets[index], next); };
> ```

Right now, the commands can only be executed once, in the same order they were generated. Otherwise, the offset on which that command operates might be invalid.

How about putting this `used_offsets.push_front(...)` and other offset-tracking code in the remaining function into the lambda? Then you don't even need to have this switch in generate_commands. You can just do:

```
std::vector<std::function<void>> commands = {slist_insert_head(_rt, _list, i), slist_insert_tail(_rt, _list, i), slist_remove_head(_rt, _list, i), ... };
return sample_with_replacements(commands, number_of_commands);
```

You only need to implement sample_with_replacements (std::sample requires N to be smaller than the population).

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/167)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 135 at r1](https://reviewable.io/reviews/pmem/pmemstream/167#-N-YaY8M9fi12GTMl9D1:-N0WCKW1AofGR2ppkBSn:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/531bf040d7641192c30c15223f05c4023d62f3e7/tests/integrity/singly_linked_list_pmreorder.cpp#L135)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Right now, the commands can only be executed once, in the same order they were generated. Otherwise, the offset on which that command operates might be invalid.

How about putting this `used_offsets.push_front(...)` and other offset-tracking code in the remaining function into the lambda? Then you don't even need to have this switch in generate_commands. You can just do:

```
std::vector<std::function<void>> commands = {slist_insert_head(_rt, _list, i), slist_insert_tail(_rt, _list, i), slist_remove_head(_rt, _list, i), ... };
return sample_with_replacements(commands, number_of_commands);
```

You only need to implement sample_with_replacements (std::sample requires N to be smaller than the population).
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/167)* status: all files reviewed, 11 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[`-- commits` line 4 at r7](https://reviewable.io/reviews/pmem/pmemstream/167#-N0ZjFbX8youlsAO9yop):*
this line is pretty much copy-paste of the above line
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 11 at r7](https://reviewable.io/reviews/pmem/pmemstream/167#-N0Zjcbm9p2WhRwXtME2:-N0Zjcbn3p5AkJF0EEhR:b-rt6yho) ([raw file](https://github.com/pmem/pmemstream/blob/4a66da933666529411c40fbb822317bf3e4c9999/tests/integrity/singly_linked_list_pmreorder.cpp#L11)):*
> ```cpp
> #include <algorithm>
> #include <cstdlib>
> #include <deque>
> ```

deque?
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 15 at r7](https://reviewable.io/reviews/pmem/pmemstream/167#-N0ZjaBeCE0LClAsa8BK:-N0ZjaBeCE0LClAsa8BL:bb7og4i) ([raw file](https://github.com/pmem/pmemstream/blob/4a66da933666529411c40fbb822317bf3e4c9999/tests/integrity/singly_linked_list_pmreorder.cpp#L15)):*
> ```cpp
> #include <iostream>
> #include <list>
> #include <set>
> ```

set?
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 62 at r7](https://reviewable.io/reviews/pmem/pmemstream/167#-N0ZmXqs7HvzKTPIV7Yv:-N0ZmXqs7HvzKTPIV7Yw:btfvlc4) ([raw file](https://github.com/pmem/pmemstream/blob/4a66da933666529411c40fbb822317bf3e4c9999/tests/integrity/singly_linked_list_pmreorder.cpp#L62)):*
> ```cpp
> 
> template <typename Node>
> std::vector<size_t> generate_offsets(size_t number_of_values)
> ```

dead code
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 91 at r7](https://reviewable.io/reviews/pmem/pmemstream/167#-N0ZjpT54regotEaHCmr:-N0ZjpT54regotEaHCms:b-g8ojx8) ([raw file](https://github.com/pmem/pmemstream/blob/4a66da933666529411c40fbb822317bf3e4c9999/tests/integrity/singly_linked_list_pmreorder.cpp#L91)):*
> ```cpp
> {
> 	auto it = elements.begin();
> 	size_t max_elem = rnd_generator() % elements.size();
> ```

`max_elem`?
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 92 at r7](https://reviewable.io/reviews/pmem/pmemstream/167#-N0Zjr2M3zKOU7rSCM4k:-N0Zjr2M3zKOU7rSCM4l:b-r41g58) ([raw file](https://github.com/pmem/pmemstream/blob/4a66da933666529411c40fbb822317bf3e4c9999/tests/integrity/singly_linked_list_pmreorder.cpp#L92)):*
> ```cpp
> 	auto it = elements.begin();
> 	size_t max_elem = rnd_generator() % elements.size();
> 	for (size_t i = 0; i < max_elem; i++) {
> ```

std::advance
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 109 at r7](https://reviewable.io/reviews/pmem/pmemstream/167#-N0ZnEVZ8JjVV36lBBkC:-N0ZnEVZ8JjVV36lBBkD:b-rvuyv8) ([raw file](https://github.com/pmem/pmemstream/blob/4a66da933666529411c40fbb822317bf3e4c9999/tests/integrity/singly_linked_list_pmreorder.cpp#L109)):*
> ```cpp
> 			slist_remove_head(rt, list, st), slist_remove(rt, list, st)};
> 
> 		for (size_t i = 0; i < number_of_commands; i++) {
> ```

you can use helper function `generate_commands` from `random_helpers.hpp`
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 112 at r7](https://reviewable.io/reviews/pmem/pmemstream/167#-N0ZoueK4LxjZguMZqJ4:-N0ZoueK4LxjZguMZqJ5:b-fi28kl) ([raw file](https://github.com/pmem/pmemstream/blob/4a66da933666529411c40fbb822317bf3e4c9999/tests/integrity/singly_linked_list_pmreorder.cpp#L112)):*
> ```cpp
> 			std::sample(funcs.begin(), funcs.end(), std::back_inserter(commands), 1, rnd_generator);
> 		}
> 		return commands;
> ```

as discussed commands could be shuffled
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 125 at r7](https://reviewable.io/reviews/pmem/pmemstream/167#-N0ZnUhp-kcMFeomVbvl:-N0ZnUhp-kcMFeomVbvm:b-avo0ub) ([raw file](https://github.com/pmem/pmemstream/blob/4a66da933666529411c40fbb822317bf3e4c9999/tests/integrity/singly_linked_list_pmreorder.cpp#L125)):*
> ```cpp
> 		size_t lazy_offset_generator()
> 		{
> 			return used_offsets.emplace_back(++generated * sizeof(T));
> ```

`++generated` -> you'll never generate offset `0`
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 175 at r7](https://reviewable.io/reviews/pmem/pmemstream/167#-N0ZoeWE4HRCUP2aiESs:-N0ZoeWE4HRCUP2aiESt:b-kip7bc) ([raw file](https://github.com/pmem/pmemstream/blob/4a66da933666529411c40fbb822317bf3e4c9999/tests/integrity/singly_linked_list_pmreorder.cpp#L175)):*
> ```cpp
> 								 std::end(st->used_offsets), offset_to_del));
> 			} else {
> 				offset_to_del = st->lazy_offset_generator<node>();
> ```

is this correct? using this function you'll add that generated offset to the `used_offsets`

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/167)* status: all files reviewed, 11 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[`-- commits` line 4 at r7](https://reviewable.io/reviews/pmem/pmemstream/167#-N0ZjFbX8youlsAO9yop):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this line is pretty much copy-paste of the above line
</blockquote></details>

Done.
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 11 at r7](https://reviewable.io/reviews/pmem/pmemstream/167#-N0Zjcbm9p2WhRwXtME2:-N0_owZU5kwh_BC-wknA:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4a66da933666529411c40fbb822317bf3e4c9999/tests/integrity/singly_linked_list_pmreorder.cpp#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

deque?
</blockquote></details>

Done.
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 15 at r7](https://reviewable.io/reviews/pmem/pmemstream/167#-N0ZjaBeCE0LClAsa8BK:-N0_ox0L-1eugo9xhono:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4a66da933666529411c40fbb822317bf3e4c9999/tests/integrity/singly_linked_list_pmreorder.cpp#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

set?
</blockquote></details>

Done.
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 62 at r7](https://reviewable.io/reviews/pmem/pmemstream/167#-N0ZmXqs7HvzKTPIV7Yv:-N0_p1y00VXiVlGXw4_w:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4a66da933666529411c40fbb822317bf3e4c9999/tests/integrity/singly_linked_list_pmreorder.cpp#L62)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

dead code
</blockquote></details>

Done.
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 91 at r7](https://reviewable.io/reviews/pmem/pmemstream/167#-N0ZjpT54regotEaHCmr:-N0_qeMD6Jn1erRl-Ry0:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4a66da933666529411c40fbb822317bf3e4c9999/tests/integrity/singly_linked_list_pmreorder.cpp#L91)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`max_elem`?
</blockquote></details>

Done.
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 92 at r7](https://reviewable.io/reviews/pmem/pmemstream/167#-N0Zjr2M3zKOU7rSCM4k:-N0_qeka7tcbpPjc5cyB:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4a66da933666529411c40fbb822317bf3e4c9999/tests/integrity/singly_linked_list_pmreorder.cpp#L92)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

std::advance
</blockquote></details>

Done.
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 109 at r7](https://reviewable.io/reviews/pmem/pmemstream/167#-N0ZnEVZ8JjVV36lBBkC:-N0_s8V1E9K6dr3H4non:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4a66da933666529411c40fbb822317bf3e4c9999/tests/integrity/singly_linked_list_pmreorder.cpp#L109)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can use helper function `generate_commands` from `random_helpers.hpp`
</blockquote></details>

Done.
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 112 at r7](https://reviewable.io/reviews/pmem/pmemstream/167#-N0ZoueK4LxjZguMZqJ4:-N0_qlmDCzY8EQx61Nfm:bjw0cci) ([raw file](https://github.com/pmem/pmemstream/blob/4a66da933666529411c40fbb822317bf3e4c9999/tests/integrity/singly_linked_list_pmreorder.cpp#L112)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

as discussed commands could be shuffled
</blockquote></details>

It's done here. Also offsets are random.
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 125 at r7](https://reviewable.io/reviews/pmem/pmemstream/167#-N0ZnUhp-kcMFeomVbvl:-N0_s96f1jjWJ2uw_yUY:b3ix4xu) ([raw file](https://github.com/pmem/pmemstream/blob/4a66da933666529411c40fbb822317bf3e4c9999/tests/integrity/singly_linked_list_pmreorder.cpp#L125)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`++generated` -> you'll never generate offset `0`
</blockquote></details>

Done. I know, but we can start from `0`.
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 175 at r7](https://reviewable.io/reviews/pmem/pmemstream/167#-N0ZoeWE4HRCUP2aiESs:-N0_sKMl3y0IgbyvRBIF:b-k2ztxf) ([raw file](https://github.com/pmem/pmemstream/blob/4a66da933666529411c40fbb822317bf3e4c9999/tests/integrity/singly_linked_list_pmreorder.cpp#L175)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

is this correct? using this function you'll add that generated offset to the `used_offsets`
</blockquote></details>

Done. Not in the newest revision.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/167)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 100 at r9](https://reviewable.io/reviews/pmem/pmemstream/167#-N0aZSm70aRj3xCBmmZn:-N0aZSm70aRj3xCBmmZo:b-wx1zzz) ([raw file](https://github.com/pmem/pmemstream/blob/dfda84144b7ccf1af24bbf93a2000fd9997eb372/tests/integrity/singly_linked_list_pmreorder.cpp#L100)):*
> ```cpp
> 			std::iota(possible_offsets.begin(), possible_offsets.end(), 0);
> 			for (auto &val : possible_offsets) {
> 				val = val * sizeof(size_t);
> ```

why `size_t`? not `struct node`?
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 105 at r9](https://reviewable.io/reviews/pmem/pmemstream/167#-N0dqE4w1Gj7kxWJbMVG:-N0dqE4x7BX4DlWoKmzs:b-le6u2) ([raw file](https://github.com/pmem/pmemstream/blob/dfda84144b7ccf1af24bbf93a2000fd9997eb372/tests/integrity/singly_linked_list_pmreorder.cpp#L105)):*
> ```cpp
> 		}
> 
> 		size_t lazy_offset_generator()
> ```

is it still "lazy"? :wink: 
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 120 at r9](https://reviewable.io/reviews/pmem/pmemstream/167#-N0aSYCJ71RCgExmBtcJ:-N0aSYCJ71RCgExmBtcK:b-nsqcu9) ([raw file](https://github.com/pmem/pmemstream/blob/dfda84144b7ccf1af24bbf93a2000fd9997eb372/tests/integrity/singly_linked_list_pmreorder.cpp#L120)):*
> ```cpp
> 						       std::shared_ptr<state> st)
> 	{
> ```

redundant empty line

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/167)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 100 at r9](https://reviewable.io/reviews/pmem/pmemstream/167#-N0aZSm70aRj3xCBmmZn:-N0eb0NyEXRF9Oc9iN9N:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/dfda84144b7ccf1af24bbf93a2000fd9997eb372/tests/integrity/singly_linked_list_pmreorder.cpp#L100)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why `size_t`? not `struct node`?
</blockquote></details>

Done.
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 105 at r9](https://reviewable.io/reviews/pmem/pmemstream/167#-N0dqE4w1Gj7kxWJbMVG:-N0eb0w62T4HSLO5HU9f:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/dfda84144b7ccf1af24bbf93a2000fd9997eb372/tests/integrity/singly_linked_list_pmreorder.cpp#L105)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

is it still "lazy"? :wink: 
</blockquote></details>

Done.
___
*[`tests/integrity/singly_linked_list_pmreorder.cpp` line 120 at r9](https://reviewable.io/reviews/pmem/pmemstream/167#-N0aSYCJ71RCgExmBtcJ:-N0eb1i77F5s-rzAPFOf:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/dfda84144b7ccf1af24bbf93a2000fd9997eb372/tests/integrity/singly_linked_list_pmreorder.cpp#L120)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/167#-:-N0efxGi9nvDto0gnc20:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/167#-:-N0egy5K0v6FOVqSXPMS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/167#-:-N0esNPK6f3gtyhF5TP_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
