### PR TITLE
Add shadow value to pmemstream_persisted_timestamp

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/249)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/249)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @karczex)

___
*[`src/libpmemstream.c` line 249 at r1](https://reviewable.io/reviews/pmem/pmemstream/249#-N6wAB2s485WH2rITfj0:-N6wAB2s485WH2rITfj1:b-kxu7v0) ([raw file](https://github.com/pmem/pmemstream/blob/f289e9d326b3cb480f01f1c4cf98bde45d53cd09/src/libpmemstream.c#L249)):*
> ```C
> 	}
> 
> 	/* Make sure that persisted_timestamp is actually persisted before returning. */
> ```

Remove this comment
___
*[`src/libpmemstream.c` line 251 at r1](https://reviewable.io/reviews/pmem/pmemstream/249#-N6wAiKfAlERP5lodNed:-N6wAiKfAlERP5lodNee:bmzt7ns) ([raw file](https://github.com/pmem/pmemstream/blob/f289e9d326b3cb480f01f1c4cf98bde45d53cd09/src/libpmemstream.c#L251)):*
> ```C
> 	/* Make sure that persisted_timestamp is actually persisted before returning. */
> 	uint64_t timestamp;
> 	atomic_load_acquire(&stream->persisted_timestamp, &timestamp);
> ```

please add extra assert
```
uint64_t timestamp;
atomic_load_acquire(&stream->persisted_timestamp, &timestamp);

#ifndef NDEBUG
uint64_t timestamp_on_pmem;
atomic_load_acquire(&stream->header->persisted_timestamp, &timestamp_on_pmem);
assert(timestamp <= timestamp_on_pmem);
#endif
```
___
*[`src/libpmemstream.c` line 784 at r1](https://reviewable.io/reviews/pmem/pmemstream/249#-N6wAEZL5icaWSc8Lx38:-N6wAEZL5icaWSc8Lx39:bygjycs) ([raw file](https://github.com/pmem/pmemstream/blob/f289e9d326b3cb480f01f1c4cf98bde45d53cd09/src/libpmemstream.c#L784)):*
> ```C
> 	if (success) {
> 		data->stream->data.persist(&data->stream->header->persisted_timestamp, sizeof(uint64_t));
> 		/* XXX: This compare exchange may fail only if data->stream->persisted_timestamp is already bigger, so
> ```

why "XXX"? You can actually replace the comment with an assert:

```
if (!success) assert(persisted_timestamp > data->timestamp);
```
___
*[`src/libpmemstream_internal.h` line 43 at r1](https://reviewable.io/reviews/pmem/pmemstream/249#-N6wAbqx9OVXVkf9wPJh:-N6wAbqx9OVXVkf9wPJi:b-mudy0v) ([raw file](https://github.com/pmem/pmemstream/blob/f289e9d326b3cb480f01f1c4cf98bde45d53cd09/src/libpmemstream_internal.h#L43)):*
> ```objc
> 	uint64_t block_size;
> 
> 	/* XXX: investigate if it makes sense to store 'shadow' value in DRAM (for reads) */
> ```

remove this XXX.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/249)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @igchor)

___
*[`src/libpmemstream.c` line 249 at r1](https://reviewable.io/reviews/pmem/pmemstream/249#-N6wAB2s485WH2rITfj0:-N6wZkCO1Weotl8KEJ7k:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f289e9d326b3cb480f01f1c4cf98bde45d53cd09/src/libpmemstream.c#L249)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Remove this comment
</blockquote></details>

Done.
___
*[`src/libpmemstream.c` line 251 at r1](https://reviewable.io/reviews/pmem/pmemstream/249#-N6wAiKfAlERP5lodNed:-N6wZv-R2Q6Qf4hCXLbh:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f289e9d326b3cb480f01f1c4cf98bde45d53cd09/src/libpmemstream.c#L251)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

please add extra assert
```
uint64_t timestamp;
atomic_load_acquire(&stream->persisted_timestamp, &timestamp);

#ifndef NDEBUG
uint64_t timestamp_on_pmem;
atomic_load_acquire(&stream->header->persisted_timestamp, &timestamp_on_pmem);
assert(timestamp <= timestamp_on_pmem);
#endif
```
</blockquote></details>

Done.
___
*[`src/libpmemstream.c` line 784 at r1](https://reviewable.io/reviews/pmem/pmemstream/249#-N6wAEZL5icaWSc8Lx38:-N6wZKR855cLW0il__81:b-4lnxbr) ([raw file](https://github.com/pmem/pmemstream/blob/f289e9d326b3cb480f01f1c4cf98bde45d53cd09/src/libpmemstream.c#L784)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why "XXX"? You can actually replace the comment with an assert:

```
if (!success) assert(persisted_timestamp > data->timestamp);
```
</blockquote></details>

It's WIP, so XXX is for me:) 

Assert is really good idea, thx.
___
*[`src/libpmemstream_internal.h` line 43 at r1](https://reviewable.io/reviews/pmem/pmemstream/249#-N6wAbqx9OVXVkf9wPJh:-N6w_0J73_yQXpbf43O-:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f289e9d326b3cb480f01f1c4cf98bde45d53cd09/src/libpmemstream_internal.h#L43)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

remove this XXX.
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
:lgtm: but we should try to run some benchmarks (https://github.com/pmem/pmemstream/pull/244) to see if this patch improves (or at least, does not decrease performance).

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/249#-:-N6wb2Pr7zgMNGENwv4-:b-vilvnp)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @igchor)

**Review by lukaszstolarczuk — COMMENTED** [review]
:+1: 

do we need some new gdb/pmreorder test for that or is/will this be covered by some other integrity check?

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/249#-:-N6xPVfw1uveAh9y39Km:b-wq1do8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by igchor — COMMENTED** [review]
I think it would be good to add something but it might be quite tricky (need to use multiple thread).
One idea could be to implement this "shadow value" as standalone module / structure. Then we can just unittest that.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/249#-:-N6xd0QeBK4txYrejNdM:b-g9t89m)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by KFilipek — DISMISSED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/249)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[`src/libpmemstream.c` line 254 at r2](https://reviewable.io/reviews/pmem/pmemstream/249#-N7KaD8r16aBd_Y_WWC3:-N7KaD8r16aBd_Y_WWC4:b-worpl9) ([raw file](https://github.com/pmem/pmemstream/blob/d0ab2bd4b99bda341bdd5f84aa0d41a8f46227a9/src/libpmemstream.c#L254)):*
> ```C
> #ifndef NDEBUG
> 	uint64_t timestamp_on_pmem;
> 	atomic_load_acquire(&stream->header->persisted_timestamp, &timestamp_on_pmem);
> ```

https://github.com/pmem/pmemstream/pull/236/files 
I suppose that we should use macros from Igor to avoid problems with TSAN.



_Code quote:_
```C
atomic_load_acquire(&stream->header->persisted_timestamp, &timestamp_on_pmem);
```

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/249)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[`src/libpmemstream.c` line 254 at r2](https://reviewable.io/reviews/pmem/pmemstream/249#-N7KaD8r16aBd_Y_WWC3:-N7QP0XwCRTpN-6p-onJ:b-vni5qn) ([raw file](https://github.com/pmem/pmemstream/blob/d0ab2bd4b99bda341bdd5f84aa0d41a8f46227a9/src/libpmemstream.c#L254)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

https://github.com/pmem/pmemstream/pull/236/files 
I suppose that we should use macros from Igor to avoid problems with TSAN.
</blockquote></details>

I think this is exactly the macro I introduced

**Comment by igchor** [comment]
Ref: https://pmem.io/blog/2021/09/concurrency-considerations-in-libpmemobj-cpp/

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/249)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[`src/libpmemstream.c` line 254 at r2](https://reviewable.io/reviews/pmem/pmemstream/249#-N7KaD8r16aBd_Y_WWC3:-N7piJRP1yRG4sNRmjBu:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d0ab2bd4b99bda341bdd5f84aa0d41a8f46227a9/src/libpmemstream.c#L254)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think this is exactly the macro I introduced
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/249#-:-N7qD3jnCiL2EnPuU9xc:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Pull request merged**
