### PR TITLE
Add first gdb test - integrity of an append

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- [x] wait for PR with entry clear-up when inconsistency is discovered (right now the test will fail)

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/23)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/23)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @igchor)

___
*[tests/integrity/append_break.gdb, line 11 at r1](https://reviewable.io/reviews/pmem/pmemstream/23#-MqUk76t6_JCdSe-i3ta:-MqUk76t6_JCdSe-i3tb:b-vt8uzm) ([raw file](https://github.com/pmem/pmemstream/blob/b19c62ec28a9115794df8bb0258736bffd294c0f/tests/integrity/append_break.gdb#L11)):*
> ```GDB
> r
> info break 1
> b pmemstream_span_get_runtime
> ```

probabky the best aproach would be move the memcpy in pmemstream_append to pmemstream_span_create_entry - that way we could just set breakpoint on that function

**Comment by lukaszstolarczuk** [comment]
> [ @lukaszstolarczuk ](/lukaszstolarczuk)
> ` [tests](/pmem/pmemstream/pull/23/commits/b19c62ec28a9115794df8bb0258736bffd294c0f)`

actually, this will change when we split reserve and write in append 😉 so, yeah

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/23)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @igchor)

___
*[tests/integrity/append_break.cpp, line 150 at r1](https://reviewable.io/reviews/pmem/pmemstream/23#-MqtWvBc-RPvFFDlKuJk:-MqtWvBc-RPvFFDlKuJl:b8hplfs) ([raw file](https://github.com/pmem/pmemstream/blob/b19c62ec28a9115794df8bb0258736bffd294c0f/tests/integrity/append_break.cpp#L150)):*
> ```cpp
> 				UT_ASSERT(init_data[i] == read_elements[i]);
> 
> 				printf("%s\n", read_elements[i].c_str());
> ```

This is probably not needed.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 5 of 8 files at r1, 1 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/23#-:-MrSQdE9-py1RXMyrgiB:bnfp4nl)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/integrity/append_break.cpp, line 116 at r3](https://reviewable.io/reviews/pmem/pmemstream/23#-MrSQNtlA2pKOB_gE8oP:-MrSQNtlA2pKOB_gE8oQ:byjfake) ([raw file](https://github.com/pmem/pmemstream/blob/d2e5d5a21bd47cf6bc81fa3c935dbd970b3871ec/tests/integrity/append_break.cpp#L116)):*
> ```cpp
> 	init_data.emplace_back("mydata");
> 
> 	try {
> ```

nit: you don't need try - all exceptions are caught by run_test()

**Review by lukaszstolarczuk — COMMENTED** [review]
I had to adjust the gdb script after the latest changes, the rest stayed as before :wink: 

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/23#-:-MrSme9g2zieT_jd_IS_:b-fylcr2)* status: 5 of 9 files reviewed, all discussions resolved (waiting on @igchor)

___
*[tests/integrity/append_break.cpp, line 116 at r3](https://reviewable.io/reviews/pmem/pmemstream/23#-MrSQNtlA2pKOB_gE8oP:-MrSm_JRAHNiJm9Fn4SU:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d2e5d5a21bd47cf6bc81fa3c935dbd970b3871ec/tests/integrity/append_break.cpp#L116)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

nit: you don't need try - all exceptions are caught by run_test()
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/23#-:-MrSv9aY1SrGMqPsou27:bnfp4nl)* status: 6 of 9 files reviewed, all discussions resolved (waiting on @igchor)

**Comment by lukaszstolarczuk** [comment]
it turns out it doesn't work on our CI (older gdb than on my machine...?). I applied some workaround, but the test is still failing in "package" build (https://github.com/lukaszstolarczuk/pmemstream/runs/4597765465?check_suite_focus=true) 😄 

I will update the test soon-ish.

**Review by igchor — COMMENTED** [review]
@lukaszstolarczuk maybe it's failing on Release (due to some optimizations)? The test should be enabled only for Debug

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/23#-:-MrWqCGV5XAzBN9aXrkc:b5vzkfb)* status: 6 of 9 files reviewed, all discussions resolved (waiting on @igchor)

**Comment by lukaszstolarczuk** [comment]
On different test setups there were multiple weird gdb behavior:
- *stream->memcpy wasn't a proper breakpoint,
- memcpy was too short...? and memcpy watchpoint wasn't caught.

I added also minor updates, and it should work just fine now.

**Review by igchor — COMMENTED** [review]
___
*[src/libpmemstream.c, line 28 at r5](https://reviewable.io/reviews/pmem/pmemstream/23#-Mrb_dt02-P-i2FD0a1g:-Mrb_dt02-P-i2FD0a1h:b-950011) ([raw file](https://github.com/pmem/pmemstream/blob/308f2c299585687f3924ca981a180213cb8c11d7/src/libpmemstream.c#L28)):*
>> ```C
>> 
>> 	void *dest = ((uint8_t *)span) + SPAN_EMPTY_METADATA_SIZE;
>> 	stream->memset(dest, 0, data_size, PMEM2_F_MEM_NONTEMPORAL);
>> ```
>
>unrelated, but shouldn't this have NO_DRAIN flag?

fixed in  #49

**Pull request merged**
