### PR TITLE
Add stress test for pmemstream_get_region_context

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/53)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/53)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/unittest/concurrent_iterate.cpp, line 40 at r1](https://reviewable.io/reviews/pmem/pmemstream/53#-MsU2DNG3FACQX__YwP3:-MsU2DNH58TBzQRmUKA4:b-iacs84) ([raw file](https://github.com/pmem/pmemstream/blob/535f377356b54c04c2e0e80356393ff76ab04656/tests/unittest/concurrent_iterate.cpp#L40)):*
> ```cpp
> 					 });
> 
> 					 RC_ASSERT(all_equal(threads_data));
> ```

I'm not sure if these 2 are good use cases for `all_equal` - you were comparing threads_data with data, and now you're comparing only threads_data with each other

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/53)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor)

___
*[tests/common/unittest.hpp, line 46 at r1](https://reviewable.io/reviews/pmem/pmemstream/53#-MsUOQ5v1PflCgZiqHZ4:-MsUOQ5wAWwI7JWToRey:b-njrixk) ([raw file](https://github.com/pmem/pmemstream/blob/535f377356b54c04c2e0e80356393ff76ab04656/tests/common/unittest.hpp#L46)):*
> ```cpp
> bool all_equal(const T &t)
> {
> 	return t.empty() ? true : std::equal(t.begin() + 1, t.end(), t.begin());
> ```

braces around



_Code quote:_
```cpp
t.empty() ? true : std::equal(t.begin() + 1, t.end(), t.begin())
```
___
*[tests/unittest/get_region_context.cpp, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/53#-MsUOZ5O3wACOw1V_TSH:-MsUOZ5O3wACOw1V_TSI:b-i30rji) ([raw file](https://github.com/pmem/pmemstream/blob/535f377356b54c04c2e0e80356393ff76ab04656/tests/unittest/get_region_context.cpp#L4)):*
> ```cpp
> /* Copyright 2021, Intel Corporation */
> 
> #include <rapidcheck.h>
> ```

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes 

```
group 5

group 7

group 9
```
so:
```
#include <vector>

#include <rapidcheck.h>

#include "common/util.h"
#include "stream_helpers.hpp"
#include "thread_helpers.hpp"
#include "unittest.hpp"
```



_Code quote:_
```cpp
#include <rapidcheck.h>
#include <vector>

#include "common/util.h"
#include "stream_helpers.hpp"
#include "thread_helpers.hpp"
#include "unittest.hpp"
```
___
*[tests/unittest/get_region_context.cpp, line 22 at r1](https://reviewable.io/reviews/pmem/pmemstream/53#-MsUnCuaD2zYh4OoNDZH:-MsUnCuaD2zYh4OoNDZI:b9zdewq) ([raw file](https://github.com/pmem/pmemstream/blob/535f377356b54c04c2e0e80356393ff76ab04656/tests/unittest/get_region_context.cpp#L22)):*
> ```cpp
> 	}
> 
> 	auto file = std::string(argv[1]);
> ```

it's not a file representation or handler, just a filename



_Code quote:_
```cpp
file
```
___
*[tests/unittest/get_region_context.cpp, line 28 at r1](https://reviewable.io/reviews/pmem/pmemstream/53#-MsUpE7c4heUGdzM5I6w:-MsUpE7c4heUGdzM5I6x:bt3d6re) ([raw file](https://github.com/pmem/pmemstream/blob/535f377356b54c04c2e0e80356393ff76ab04656/tests/unittest/get_region_context.cpp#L28)):*
> ```cpp
> 
> 		ret += rc::check("verify pmemstream_get_region_context return the same value for all threads", [&]() {
> 			static constexpr size_t region_size = stream_size - 16 * 1024;
> ```

why static here?



_Code quote:_
```cpp
			static constexpr size_t region_size = stream_size - 16 * 1024;
			static constexpr size_t block_size = 4096;
```

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/53)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[tests/common/unittest.hpp, line 46 at r1](https://reviewable.io/reviews/pmem/pmemstream/53#-MsUOQ5v1PflCgZiqHZ4:-MsVLjsL3Z1cx_lfIMt3:bb7r2f0) ([raw file](https://github.com/pmem/pmemstream/blob/535f377356b54c04c2e0e80356393ff76ab04656/tests/common/unittest.hpp#L46)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

braces around
</blockquote></details>

why?
___
*[tests/unittest/concurrent_iterate.cpp, line 40 at r1](https://reviewable.io/reviews/pmem/pmemstream/53#-MsU2DNG3FACQX__YwP3:-MsVM9W90Oe5M-YGgP20:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/535f377356b54c04c2e0e80356393ff76ab04656/tests/unittest/concurrent_iterate.cpp#L40)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure if these 2 are good use cases for `all_equal` - you were comparing threads_data with data, and now you're comparing only threads_data with each other
</blockquote></details>

Done.
___
*[tests/unittest/get_region_context.cpp, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/53#-MsUOZ5O3wACOw1V_TSH:-MsVMJXHBgzhJoTTfStO:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/535f377356b54c04c2e0e80356393ff76ab04656/tests/unittest/get_region_context.cpp#L4)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes 

```
group 5

group 7

group 9
```
so:
```
#include <vector>

#include <rapidcheck.h>

#include "common/util.h"
#include "stream_helpers.hpp"
#include "thread_helpers.hpp"
#include "unittest.hpp"
```

</blockquote></details>

Done.
___
*[tests/unittest/get_region_context.cpp, line 22 at r1](https://reviewable.io/reviews/pmem/pmemstream/53#-MsUnCuaD2zYh4OoNDZH:-MsVMKYbDalXnXPfdaJl:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/535f377356b54c04c2e0e80356393ff76ab04656/tests/unittest/get_region_context.cpp#L22)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

it's not a file representation or handler, just a filename
</blockquote></details>

Done.
___
*[tests/unittest/get_region_context.cpp, line 28 at r1](https://reviewable.io/reviews/pmem/pmemstream/53#-MsUpE7c4heUGdzM5I6w:-MsVMPJv57CSYrBcjx6E:b-qfopb3) ([raw file](https://github.com/pmem/pmemstream/blob/535f377356b54c04c2e0e80356393ff76ab04656/tests/unittest/get_region_context.cpp#L28)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

why static here?
</blockquote></details>

constexpr must be static

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/53)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[tests/unittest/concurrent_iterate.cpp, line 40 at r1](https://reviewable.io/reviews/pmem/pmemstream/53#-MsU2DNG3FACQX__YwP3:-MsVSohXAIooECYWNHP7:b2hp9q0) ([raw file](https://github.com/pmem/pmemstream/blob/535f377356b54c04c2e0e80356393ff76ab04656/tests/unittest/concurrent_iterate.cpp#L40)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

much better :) thanks
___
*[tests/unittest/get_region_context.cpp, line 4 at r2](https://reviewable.io/reviews/pmem/pmemstream/53#-MsVTAKxBGvhxcjhQCs3:-MsVTAKxBGvhxcjhQCs4:bibjlnl) ([raw file](https://github.com/pmem/pmemstream/blob/0a32334419a910bfda687fed068171b66e5b6c7c/tests/unittest/get_region_context.cpp#L4)):*
> ```cpp
> /* Copyright 2021, Intel Corporation */
> 
> #include <algorithm>
> ```

no need for algorithm, I believe

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/53)* status: all files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[tests/unittest/get_region_context.cpp, line 4 at r2](https://reviewable.io/reviews/pmem/pmemstream/53#-MsVTAKxBGvhxcjhQCs3:-MsVUnloB1J9nC_pvvEQ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0a32334419a910bfda687fed068171b66e5b6c7c/tests/unittest/get_region_context.cpp#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

no need for algorithm, I believe
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/53#-:-MsVZ3qq9DHaIC1TzqoP:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @KFilipek)

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/53)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[tests/common/unittest.hpp, line 46 at r1](https://reviewable.io/reviews/pmem/pmemstream/53#-MsUOQ5v1PflCgZiqHZ4:-MsZ9x2-2f8WKOqq6eGI:buz0f5s) ([raw file](https://github.com/pmem/pmemstream/blob/535f377356b54c04c2e0e80356393ff76ab04656/tests/common/unittest.hpp#L46)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why?
</blockquote></details>

I thought that `()` for ternary operator ease reading and group whole statement, but it's not a must
___
*[tests/unittest/get_region_context.cpp, line 28 at r1](https://reviewable.io/reviews/pmem/pmemstream/53#-MsUpE7c4heUGdzM5I6w:-MsZ8rfk54DrTpa_zoSF:buf9z8k) ([raw file](https://github.com/pmem/pmemstream/blob/535f377356b54c04c2e0e80356393ff76ab04656/tests/unittest/get_region_context.cpp#L28)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

constexpr must be static
</blockquote></details>

That's make sense
___
*[tests/unittest/get_region_context.cpp, line 38 at r3](https://reviewable.io/reviews/pmem/pmemstream/53#-MsZ9KqX2jRSQkN-NSFr:-MsZ9KqX2jRSQkN-NSFs:b31ddu9) ([raw file](https://github.com/pmem/pmemstream/blob/46f6ef05f65faab289fb8421124f19568bea34b0/tests/unittest/get_region_context.cpp#L38)):*
> ```cpp
> 			std::vector<pmemstream_region_context *> threads_data(concurrency);
> 			parallel_exec(concurrency, [&](size_t tid) {
> 				RC_ASSERT(pmemstream_get_region_context(stream.get(), region, &threads_data[tid]) == 0);
> ```

Should we check that `tid` is less than `threads_data.size()`?
Or use `threads_data.at(tid)` for bounce checking.



_Code quote:_
```cpp
tid
```

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/53)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[tests/unittest/get_region_context.cpp, line 38 at r3](https://reviewable.io/reviews/pmem/pmemstream/53#-MsZ9KqX2jRSQkN-NSFr:-MsZfqPk7VUU36-n3F_e:b-flugza) ([raw file](https://github.com/pmem/pmemstream/blob/46f6ef05f65faab289fb8421124f19568bea34b0/tests/unittest/get_region_context.cpp#L38)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Should we check that `tid` is less than `threads_data.size()`?
Or use `threads_data.at(tid)` for bounce checking.
</blockquote></details>

I don't think it's necessary, tid is always bounded by bounded `concurrency`.

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/53#-:-Ms_BFxi6A6ia81uVWfU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

___
*[tests/unittest/get_region_context.cpp, line 38 at r3](https://reviewable.io/reviews/pmem/pmemstream/53#-MsZ9KqX2jRSQkN-NSFr:-Ms_BCSY4sNl9GV4IXAF:b-apqntg) ([raw file](https://github.com/pmem/pmemstream/blob/46f6ef05f65faab289fb8421124f19568bea34b0/tests/unittest/get_region_context.cpp#L38)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I don't think it's necessary, tid is always bounded by bounded `concurrency`.
</blockquote></details>

If so, then I'm okey with it :)

**Pull request merged**
