### PR TITLE
Add ThreadSanitizer option to CMake

### PR DESCRIPTION
**Pull request by KFilipek**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/234)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
it looks good, why not enable it in CI (in a separate job), like for ASAN/UBSAN...?

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/234#-:-N5pJRc6AkxjN2TRgxMn:bk7toxe)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @KFilipek)

**Comment by KFilipek** [comment]
> it looks good, why not enable it in CI (in a separate job), like for ASAN/UBSAN...?
> 
> > Reviewed 2 of 2 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/234#-:-N5pJRc6AkxjN2TRgxMn:bk7toxe)_ status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @KFilipek)

ofc, I can enable it in CI, if it's needed :)

**Review by karczex — COMMENTED** [review]
"Typical slowdown introduced by ThreadSanitizer is about 5x-15x" so  I would suggest to run it on CI as nightly builds. 

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/234#-:-N5sULVJ657h9eDNMZhY:b-1ix2dc)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @KFilipek)

**Review by karczex — COMMENTED** [review]
I also suggest to play around also with MemorySanitizer (-fsanitize=memory). I'm not sure if it would work properly with pmemstream/libpmem2, but it's worth to check.  

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/234#-:-N5sWm6-E6kj10PGvC1F:bqyj9i6)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @KFilipek)

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/234#-:-N67amV79sCwIf9dAkrp:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @KFilipek)

**Pull request merged**
