### PR TITLE
Test API functions

### PR DESCRIPTION
**Pull request by Karolina002**
Pass only valid arguments

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/87)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
The tests look good! 

Please just make sure that the files are actually being compiled (are they added to the CMakeLists.txt?) and fix the few issues below.

> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/87#-:-MtxYBPO0rmSVbqrSy_D:b-8jggzx)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @igchor and @Karolina002)

___
*[tests/api_c/entry_iterator.c, line 19 at r1](https://reviewable.io/reviews/pmem/pmemstream/87#-MtxX8AB5Dn-gfaUXNMz:-MtxX8ACBXGdcqSuYnGY:b-yxw80a) ([raw file](https://github.com/pmem/pmemstream/blob/c09f41b8db3b65888e1f6abbfda73b893d4413dd/tests/api_c/entry_iterator.c#L19)):*
> ```C
> 	struct pmem2_map *map = map_open(path, TEST_DEFAULT_STREAM_SIZE, true);
> 	struct pmemstream *stream;
> 	pmemstream_from_map(&stream, TEST_DEFAULT_BLOCK_SIZE, map);	
> ```

The return value could be asserted here.
___
*[tests/api_c/entry_iterator.c, line 32 at r1](https://reviewable.io/reviews/pmem/pmemstream/87#-MtxXhjG7wF2IP2fij6a:-MtxXhjG7wF2IP2fij6b:b-kpd3vq) ([raw file](https://github.com/pmem/pmemstream/blob/c09f41b8db3b65888e1f6abbfda73b893d4413dd/tests/api_c/entry_iterator.c#L32)):*
> ```C
> 	do
> 	{
> 		UT_ASSERTeq(ret, 0);
> ```

I'm not sure if this checks anything. in the first iteration, it will just check if the previous operation succeeded (pmemstream_entry_iterator_new) which is already checked. If pmemstream_entry_iterator_next will fail we won't have more iterations anyway (because of the loop condition).

If you know there are no elements in the region, you can just assert that first call to pmemstream_entry_iterator_next will return -1.
___
*[tests/api_c/region_create.c, line 15 at r1](https://reviewable.io/reviews/pmem/pmemstream/87#-MtxXJXaBhYhJySEfyvU:-MtxXJXaBhYhJySEfyvV:b-yxw80a) ([raw file](https://github.com/pmem/pmemstream/blob/c09f41b8db3b65888e1f6abbfda73b893d4413dd/tests/api_c/region_create.c#L15)):*
> ```C
> 	struct pmem2_map *map = map_open(path, TEST_DEFAULT_STREAM_SIZE, true);
> 	struct pmemstream *stream;
> 	pmemstream_from_map(&stream, TEST_DEFAULT_BLOCK_SIZE, map);
> ```

The return value could be asserted here.
___
*[tests/api_c/region_iterator.c, line 18 at r1](https://reviewable.io/reviews/pmem/pmemstream/87#-MtxXRHd4V9AF_Sp5i9J:-MtxXRHd4V9AF_Sp5i9K:b-yxw80a) ([raw file](https://github.com/pmem/pmemstream/blob/c09f41b8db3b65888e1f6abbfda73b893d4413dd/tests/api_c/region_iterator.c#L18)):*
> ```C
> 	struct pmem2_map *map = map_open(path, TEST_DEFAULT_STREAM_SIZE, true);
> 	struct pmemstream *stream;
> 	pmemstream_from_map(&stream, TEST_DEFAULT_BLOCK_SIZE, map);
> ```

The return value could be asserted here.
___
*[tests/api_c/region_iterator.c, line 31 at r1](https://reviewable.io/reviews/pmem/pmemstream/87#-MtxXWSwE_Cw4lqC5Jgv:-MtxXWSwE_Cw4lqC5Jgw:b-gtb6y2) ([raw file](https://github.com/pmem/pmemstream/blob/c09f41b8db3b65888e1f6abbfda73b893d4413dd/tests/api_c/region_iterator.c#L31)):*
> ```C
> 	ret = pmemstream_region_iterator_next(riter, &region);
> 	UT_ASSERTeq(ret, 0);
> ```

You could also check that next call to pmemstream_region_iterator_next will return -1 (because there is no more regions).
___
*[tests/api_c/Testing/Temporary/LastTest.log, line 1 at r1](https://reviewable.io/reviews/pmem/pmemstream/87#-MtxY7Lf0VIC6hkPKtfs:-MtxY7Lg0Yov8WiKL4cZ:buzftmj) ([raw file](https://github.com/pmem/pmemstream/blob/c09f41b8db3b65888e1f6abbfda73b893d4413dd/tests/api_c/Testing/Temporary/LastTest.log#L1)):*
> ```
> Start testing: Jan 21 14:36 CET
> ```

Please remove this file.

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/87)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @igchor)

___
*[tests/api_c/entry_iterator.c, line 19 at r1](https://reviewable.io/reviews/pmem/pmemstream/87#-MtxX8AB5Dn-gfaUXNMz:-MtxiBt9AcydOXj3Waus:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c09f41b8db3b65888e1f6abbfda73b893d4413dd/tests/api_c/entry_iterator.c#L19)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

The return value could be asserted here.
</blockquote></details>

Done.
___
*[tests/api_c/entry_iterator.c, line 32 at r1](https://reviewable.io/reviews/pmem/pmemstream/87#-MtxXhjG7wF2IP2fij6a:-MtxiCvE1TlVV_7BUdT0:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c09f41b8db3b65888e1f6abbfda73b893d4413dd/tests/api_c/entry_iterator.c#L32)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I'm not sure if this checks anything. in the first iteration, it will just check if the previous operation succeeded (pmemstream_entry_iterator_new) which is already checked. If pmemstream_entry_iterator_next will fail we won't have more iterations anyway (because of the loop condition).

If you know there are no elements in the region, you can just assert that first call to pmemstream_entry_iterator_next will return -1.
</blockquote></details>

Done.
___
*[tests/api_c/region_create.c, line 15 at r1](https://reviewable.io/reviews/pmem/pmemstream/87#-MtxXJXaBhYhJySEfyvU:-MtxiDiJ8qmkWus_su7Z:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c09f41b8db3b65888e1f6abbfda73b893d4413dd/tests/api_c/region_create.c#L15)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

The return value could be asserted here.
</blockquote></details>

Done.
___
*[tests/api_c/region_iterator.c, line 18 at r1](https://reviewable.io/reviews/pmem/pmemstream/87#-MtxXRHd4V9AF_Sp5i9J:-MtxiEoH6Z1JvAz7L-VA:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c09f41b8db3b65888e1f6abbfda73b893d4413dd/tests/api_c/region_iterator.c#L18)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

The return value could be asserted here.
</blockquote></details>

Done.
___
*[tests/api_c/region_iterator.c, line 31 at r1](https://reviewable.io/reviews/pmem/pmemstream/87#-MtxXWSwE_Cw4lqC5Jgv:-MtxiGf0CxIgXXdDM6aM:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c09f41b8db3b65888e1f6abbfda73b893d4413dd/tests/api_c/region_iterator.c#L31)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You could also check that next call to pmemstream_region_iterator_next will return -1 (because there is no more regions).
</blockquote></details>

Done.
___
*[tests/api_c/Testing/Temporary/LastTest.log, line 1 at r1](https://reviewable.io/reviews/pmem/pmemstream/87#-MtxY7Lf0VIC6hkPKtfs:-MtxiLU-13wE7qE2S3RI:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c09f41b8db3b65888e1f6abbfda73b893d4413dd/tests/api_c/Testing/Temporary/LastTest.log#L1)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please remove this file.
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/87)* status: all files reviewed, 9 unresolved discussions (waiting on @igchor and @Karolina002)

___
*[tests/api_c/entry_iterator.c, line 34 at r3](https://reviewable.io/reviews/pmem/pmemstream/87#-MuAcLHh6SaY7PinOLY6:-MuAcLHh6SaY7PinOLY7:b-y0yeki) ([raw file](https://github.com/pmem/pmemstream/blob/3db3c4215c513c4a917e2f2b977b628733dc2cc4/tests/api_c/entry_iterator.c#L34)):*
> ```C
> 	UT_ASSERTeq(ret, -1);
> 
> 	pmemstream_entry_iterator_delete(&eiter);
> ```

you could check after this call if `eiter` is null
___
*[tests/api_c/region_create.c, line 26 at r3](https://reviewable.io/reviews/pmem/pmemstream/87#-MuAaoPq0zkPbrtKCior:-MuAaoPq0zkPbrtKCios:b-fry45v) ([raw file](https://github.com/pmem/pmemstream/blob/3db3c4215c513c4a917e2f2b977b628733dc2cc4/tests/api_c/region_create.c#L26)):*
> ```C
> 	size_t region_size;
> 	region_size = pmemstream_region_size(stream, region);
> 	UT_ASSERTne(region_size, 0);
> ```

`region_size >= TEST_DEFAULT_REGION_SIZE`
___
*[tests/api_c/region_iterator.c, line 36 at r3](https://reviewable.io/reviews/pmem/pmemstream/87#-MuAdM1t9kPxK476dOeP:-MuAdM1t9kPxK476dOeQ:b-dlkmfs) ([raw file](https://github.com/pmem/pmemstream/blob/3db3c4215c513c4a917e2f2b977b628733dc2cc4/tests/api_c/region_iterator.c#L36)):*
> ```C
> 	UT_ASSERTeq(ret, -1);
> 
> 	pmemstream_region_iterator_delete(&riter);
> ```

riter should be null now

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/87)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, and @lukaszstolarczuk)

___
*[tests/api_c/append_entry.c, line 41 at r4](https://reviewable.io/reviews/pmem/pmemstream/87#-MuErqtY1bAf3Yl9cMSL:-MuErqtY1bAf3Yl9cMSM:bmjalj) ([raw file](https://github.com/pmem/pmemstream/blob/3ce46b8ef6eaeccb85c8c4c3064c7ff14bf5293d/tests/api_c/append_entry.c#L41)):*
> ```C
> 
> 	entry_size = pmemstream_entry_length(stream, entry);
> 	UT_ASSERTne(entry_size, 0);
> ```

nit. For the better check, you may 
```
UT_ASSERTeq(pmemstream_entry_length(stream, entry), sizeof(data));
```

**Review by karczex — COMMENTED** [review]
> Reviewed 1 of 4 files at r3, 4 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/87)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @igchor, @karczex, @Karolina002, and @lukaszstolarczuk)

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/87)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/api_c/entry_iterator.c, line 34 at r3](https://reviewable.io/reviews/pmem/pmemstream/87#-MuAcLHh6SaY7PinOLY6:-MuFfgBQ97DjFKqEPaig:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/3db3c4215c513c4a917e2f2b977b628733dc2cc4/tests/api_c/entry_iterator.c#L34)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you could check after this call if `eiter` is null
</blockquote></details>

Done.
___
*[tests/api_c/region_create.c, line 26 at r3](https://reviewable.io/reviews/pmem/pmemstream/87#-MuAaoPq0zkPbrtKCior:-MuFfhZP3-S4BRD7KIJS:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/3db3c4215c513c4a917e2f2b977b628733dc2cc4/tests/api_c/region_create.c#L26)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`region_size >= TEST_DEFAULT_REGION_SIZE`
</blockquote></details>

Done.
___
*[tests/api_c/region_iterator.c, line 36 at r3](https://reviewable.io/reviews/pmem/pmemstream/87#-MuAdM1t9kPxK476dOeP:-MuFfiPn1ZUsQadn1rZA:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/3db3c4215c513c4a917e2f2b977b628733dc2cc4/tests/api_c/region_iterator.c#L36)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

riter should be null now
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 5 files at r4, 2 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/87)* status: all files reviewed, 10 unresolved discussions (waiting on @Karolina002)

___
*[-- commits, line 10 at r6](https://reviewable.io/reviews/pmem/pmemstream/87#-MuFjgrJ4qns2_X5nOTH):*
I believe we can squash all these commits into the first one
___
*[tests/api_c/append_entry.c, line 36 at r6](https://reviewable.io/reviews/pmem/pmemstream/87#-MuFmLXD81zGh7beQq5O:-MuFmLXEAbkw8ehYc8wi:b722jlq) ([raw file](https://github.com/pmem/pmemstream/blob/2ef5abced4c18075d159a7a74cbf25fcc715864e/tests/api_c/append_entry.c#L36)):*
> ```C
>     UT_ASSERTne(&entry, NULL);
> 
> 	entry_data = pmemstream_entry_data(stream, entry);
> ```

don't we have to explicitly cast `void *` into `const struct entry_data`...?
___
*[tests/api_c/append_entry.c, line 37 at r6](https://reviewable.io/reviews/pmem/pmemstream/87#-MuFmkBTB4uORhqEU7L6:-MuFmkBTB4uORhqEU7L7:b68kmr3) ([raw file](https://github.com/pmem/pmemstream/blob/2ef5abced4c18075d159a7a74cbf25fcc715864e/tests/api_c/append_entry.c#L37)):*
> ```C
> 
> 	entry_data = pmemstream_entry_data(stream, entry);
> 	UT_ASSERTne(entry_data, NULL);
> ```

what's more, we should set some value into data and check here if the value match
___
*[tests/api_c/reserve_and_publish.c, line 14 at r6](https://reviewable.io/reviews/pmem/pmemstream/87#-MuFoQ4f96AGbMQjB_rd:-MuFoQ4f96AGbMQjB_re:bogv9wl) ([raw file](https://github.com/pmem/pmemstream/blob/2ef5abced4c18075d159a7a74cbf25fcc715864e/tests/api_c/reserve_and_publish.c#L14)):*
> ```C
> };
> 
> void test_reserve_and_publish (char *path)
> ```

not sure if you can have space between `..._publish` and `(char ...`

please run `make cppformat`
___
*[tests/api_c/reserve_and_publish.c, line 14 at r6](https://reviewable.io/reviews/pmem/pmemstream/87#-MuFocVMBGOzRujDC1kB:-MuFocVMBGOzRujDC1kC:b-gdzxvf) ([raw file](https://github.com/pmem/pmemstream/blob/2ef5abced4c18075d159a7a74cbf25fcc715864e/tests/api_c/reserve_and_publish.c#L14)):*
> ```C
> };
> 
> void test_reserve_and_publish (char *path)
> ```

as discussed - please double this function with extra memcpy
___
*[tests/api_c/reserve_and_publish.c, line 17 at r6](https://reviewable.io/reviews/pmem/pmemstream/87#-MuFov-p5942AOY0AWI1:-MuFov-p5942AOY0AWI2:b-wj0zs9) ([raw file](https://github.com/pmem/pmemstream/blob/2ef5abced4c18075d159a7a74cbf25fcc715864e/tests/api_c/reserve_and_publish.c#L17)):*
> ```C
> {
> 	int ret;
>     void* data;
> ```

perhaps better name - `data_address` (?)
___
*[tests/api_c/reserve_and_publish.c, line 18 at r6](https://reviewable.io/reviews/pmem/pmemstream/87#-MuFn29--Js8Zg8HjIfB:-MuFn29--Js8Zg8HjIfC:b-7aij4t) ([raw file](https://github.com/pmem/pmemstream/blob/2ef5abced4c18075d159a7a74cbf25fcc715864e/tests/api_c/reserve_and_publish.c#L18)):*
> ```C
> 	int ret;
>     void* data;
>     struct entry_data e; 
> ```

pls remove whitespaces at the end of the line
___
*[tests/api_c/reserve_and_publish.c, line 18 at r6](https://reviewable.io/reviews/pmem/pmemstream/87#-MuFp1kp0sbDYG4wDuSp:-MuFp1kp0sbDYG4wDuSq:b-rukpvk) ([raw file](https://github.com/pmem/pmemstream/blob/2ef5abced4c18075d159a7a74cbf25fcc715864e/tests/api_c/reserve_and_publish.c#L18)):*
> ```C
> 	int ret;
>     void* data;
>     struct entry_data e; 
> ```

... then here we could have name `data`
___
*[tests/api_c/reserve_and_publish.c, line 30 at r6](https://reviewable.io/reviews/pmem/pmemstream/87#-MuFpMUA-SpMA-9KQHQU:-MuFpMUA-SpMA-9KQHQV:bppdo5t) ([raw file](https://github.com/pmem/pmemstream/blob/2ef5abced4c18075d159a7a74cbf25fcc715864e/tests/api_c/reserve_and_publish.c#L30)):*
> ```C
> 	UT_ASSERTne(&region, NULL);
> 
>     ret = pmemstream_reserve(stream, region, NULL, sizeof(e), &entry, &data);
> ```

data (address) can be initialized at the beginning with null, and after the call to this function it should be null no more :wink:
___
*[tests/api_c/reserve_and_publish.c, line 33 at r6](https://reviewable.io/reviews/pmem/pmemstream/87#-MuFuI3I-66pZ4GpfP43:-MuFuI3I-66pZ4GpfP44:b-bj7uwd) ([raw file](https://github.com/pmem/pmemstream/blob/2ef5abced4c18075d159a7a74cbf25fcc715864e/tests/api_c/reserve_and_publish.c#L33)):*
> ```C
>     UT_ASSERTeq(ret, 0);
> 
>     ret = pmemstream_publish(stream, region, data, sizeof(e), &entry);
> ```

your current `data` is not the data you want to pass into `pmemstream_publish`. With current names, I believe, the third param should be `e`. That's why the names should be accurate :smile:

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/87)* status: 4 of 7 files reviewed, 7 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[-- commits, line 10 at r6](https://reviewable.io/reviews/pmem/pmemstream/87#-MuFjgrJ4qns2_X5nOTH):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe we can squash all these commits into the first one
</blockquote></details>

Done.
___
*[tests/api_c/append_entry.c, line 36 at r6](https://reviewable.io/reviews/pmem/pmemstream/87#-MuFmLXD81zGh7beQq5O:-MuPwXYq0gb1FPAC8_9A:b-mcgh5r) ([raw file](https://github.com/pmem/pmemstream/blob/2ef5abced4c18075d159a7a74cbf25fcc715864e/tests/api_c/append_entry.c#L36)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

don't we have to explicitly cast `void *` into `const struct entry_data`...?
</blockquote></details>

cast to type "struct entry_data" is not allowed C/C++(119)
___
*[tests/api_c/append_entry.c, line 37 at r6](https://reviewable.io/reviews/pmem/pmemstream/87#-MuFmkBTB4uORhqEU7L6:-MuRShJ02Y0S0hMvAgkI:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/2ef5abced4c18075d159a7a74cbf25fcc715864e/tests/api_c/append_entry.c#L37)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what's more, we should set some value into data and check here if the value match
</blockquote></details>

Done.
___
*[tests/api_c/reserve_and_publish.c, line 14 at r6](https://reviewable.io/reviews/pmem/pmemstream/87#-MuFoQ4f96AGbMQjB_rd:-MuRSibK9uclDceHE39y:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/2ef5abced4c18075d159a7a74cbf25fcc715864e/tests/api_c/reserve_and_publish.c#L14)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not sure if you can have space between `..._publish` and `(char ...`

please run `make cppformat`
</blockquote></details>

Done.
___
*[tests/api_c/reserve_and_publish.c, line 14 at r6](https://reviewable.io/reviews/pmem/pmemstream/87#-MuFocVMBGOzRujDC1kB:-MuRSjpNBDjx1WfEVgu4:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/2ef5abced4c18075d159a7a74cbf25fcc715864e/tests/api_c/reserve_and_publish.c#L14)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

as discussed - please double this function with extra memcpy
</blockquote></details>

Done.
___
*[tests/api_c/reserve_and_publish.c, line 18 at r6](https://reviewable.io/reviews/pmem/pmemstream/87#-MuFn29--Js8Zg8HjIfB:-MuRSmG2-zap6qkzb5yU:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/2ef5abced4c18075d159a7a74cbf25fcc715864e/tests/api_c/reserve_and_publish.c#L18)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls remove whitespaces at the end of the line
</blockquote></details>

Done.
___
*[tests/api_c/reserve_and_publish.c, line 30 at r6](https://reviewable.io/reviews/pmem/pmemstream/87#-MuFpMUA-SpMA-9KQHQU:-MuRSobu-Bo-bZy0WYad:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/2ef5abced4c18075d159a7a74cbf25fcc715864e/tests/api_c/reserve_and_publish.c#L30)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

data (address) can be initialized at the beginning with null, and after the call to this function it should be null no more :wink:
</blockquote></details>

Done.
___
*[tests/api_c/reserve_and_publish.c, line 33 at r6](https://reviewable.io/reviews/pmem/pmemstream/87#-MuFuI3I-66pZ4GpfP43:-MuRSqlU3CZNr2TbcJYp:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/2ef5abced4c18075d159a7a74cbf25fcc715864e/tests/api_c/reserve_and_publish.c#L33)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

your current `data` is not the data you want to pass into `pmemstream_publish`. With current names, I believe, the third param should be `e`. That's why the names should be accurate :smile: 
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/87)* status: all files reviewed, 1 unresolved discussion (waiting on @Karolina002)

___
*[tests/api_c/reserve_and_publish.c, line 63 at r7](https://reviewable.io/reviews/pmem/pmemstream/87#-MuRgcK72MSez2rGlW-U:-MuRgcK72MSez2rGlW-V:bf7dwup) ([raw file](https://github.com/pmem/pmemstream/blob/fc332c348b7c9ef2f5b8f7eeee11cba692d104b9/tests/api_c/reserve_and_publish.c#L63)):*
> ```C
> 	UT_ASSERTne(data_address, NULL);
> 
> 	memcpy(&data_address, &data_mcpy, sizeof(data));
> ```

you don't need a separate variable - `data_mcpy`. You want to store the same `data` you reserved space for.

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/87)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[tests/api_c/reserve_and_publish.c, line 63 at r7](https://reviewable.io/reviews/pmem/pmemstream/87#-MuRgcK72MSez2rGlW-U:-MuVg1LC0iOJN5-2jmV4:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/fc332c348b7c9ef2f5b8f7eeee11cba692d104b9/tests/api_c/reserve_and_publish.c#L63)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you don't need a separate variable - `data_mcpy`. You want to store the same `data` you reserved space for.
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/87#-:-MuVjuDs63JG3HM9EOrh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)

**Review by karczex — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/87#-:-MuVn5X12QCqmRzf99X3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)

**Review by igchor — COMMENTED** [review]
> Reviewed 1 of 3 files at r5, 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/87)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)

___
*[tests/api_c/append_entry.c, line 31 at r8](https://reviewable.io/reviews/pmem/pmemstream/87#-MuVpAWP7-EPvRMy0jx5:-MuVpAWP7-EPvRMy0jx6:b4x6nhw) ([raw file](https://github.com/pmem/pmemstream/blob/90743a12a8e1ad8a7bdc656facf1653b0116b1ec/tests/api_c/append_entry.c#L31)):*
> ```C
> 	ret = pmemstream_region_allocate(stream, TEST_DEFAULT_REGION_SIZE, &region);
> 	UT_ASSERTeq(ret, 0);
> 	UT_ASSERTne(&region, NULL);
> ```

this is not necessary, pointer to stack is never NULL
___
*[tests/api_c/append_entry.c, line 35 at r8](https://reviewable.io/reviews/pmem/pmemstream/87#-MuVpD_UA5bXGs1YVdMU:-MuVpD_UA5bXGs1YVdMV:b4x6nhw) ([raw file](https://github.com/pmem/pmemstream/blob/90743a12a8e1ad8a7bdc656facf1653b0116b1ec/tests/api_c/append_entry.c#L35)):*
> ```C
> 	ret = pmemstream_append(stream, region, NULL, &data, sizeof(data), &entry);
> 	UT_ASSERTeq(ret, 0);
> 	UT_ASSERTne(&entry, NULL);
> ```

this is not necessary, pointer to stack is never NULL
___
*[tests/api_c/entry_iterator.c, line 25 at r8](https://reviewable.io/reviews/pmem/pmemstream/87#-MuVpKoe1B8S4bz2K2-L:-MuVpKofDk_ayWrj3FRj:b4x6nhw) ([raw file](https://github.com/pmem/pmemstream/blob/90743a12a8e1ad8a7bdc656facf1653b0116b1ec/tests/api_c/entry_iterator.c#L25)):*
> ```C
> 	ret = pmemstream_region_allocate(stream, TEST_DEFAULT_REGION_SIZE, &region);
> 	UT_ASSERTeq(ret, 0);
> 	UT_ASSERTne(&region, NULL);
> ```

this is not necessary, pointer to stack is never NULL
___
*[tests/api_c/region_create.c, line 22 at r8](https://reviewable.io/reviews/pmem/pmemstream/87#-MuVpRbV6rEfVQJNYtqD:-MuVpRbV6rEfVQJNYtqE:b4x6nhw) ([raw file](https://github.com/pmem/pmemstream/blob/90743a12a8e1ad8a7bdc656facf1653b0116b1ec/tests/api_c/region_create.c#L22)):*
> ```C
> 	ret = pmemstream_region_allocate(stream, TEST_DEFAULT_REGION_SIZE, &region);
> 	UT_ASSERTeq(ret, 0);
> 	UT_ASSERTne(&region, NULL);
> ```

this is not necessary, pointer to stack is never NULL
___
*[tests/api_c/region_iterator.c, line 24 at r8](https://reviewable.io/reviews/pmem/pmemstream/87#-MuVpUgbDsHgTd-ZsRVB:-MuVpUgbDsHgTd-ZsRVC:b4x6nhw) ([raw file](https://github.com/pmem/pmemstream/blob/90743a12a8e1ad8a7bdc656facf1653b0116b1ec/tests/api_c/region_iterator.c#L24)):*
> ```C
> 	ret = pmemstream_region_allocate(stream, TEST_DEFAULT_REGION_SIZE, &region);
> 	UT_ASSERTeq(ret, 0);
> 	UT_ASSERTne(&region, NULL);
> ```

this is not necessary, pointer to stack is never NULL
___
*[tests/api_c/reserve_and_publish.c, line 29 at r8](https://reviewable.io/reviews/pmem/pmemstream/87#-MuVpZpVDg05mf7nck6p:-MuVpZpVDg05mf7nck6q:b4x6nhw) ([raw file](https://github.com/pmem/pmemstream/blob/90743a12a8e1ad8a7bdc656facf1653b0116b1ec/tests/api_c/reserve_and_publish.c#L29)):*
> ```C
> 	ret = pmemstream_region_allocate(stream, TEST_DEFAULT_REGION_SIZE, &region);
> 	UT_ASSERTeq(ret, 0);
> 	UT_ASSERTne(&region, NULL);
> ```

this is not necessary, pointer to stack is never NULL
___
*[tests/api_c/reserve_and_publish.c, line 57 at r8](https://reviewable.io/reviews/pmem/pmemstream/87#-MuVpbe2CESkjBjTvwrE:-MuVpbe2CESkjBjTvwrF:b4x6nhw) ([raw file](https://github.com/pmem/pmemstream/blob/90743a12a8e1ad8a7bdc656facf1653b0116b1ec/tests/api_c/reserve_and_publish.c#L57)):*
> ```C
> 	ret = pmemstream_region_allocate(stream, TEST_DEFAULT_REGION_SIZE, &region);
> 	UT_ASSERTeq(ret, 0);
> 	UT_ASSERTne(&region, NULL);
> ```

this is not necessary, pointer to stack is never NULL

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/87)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/87#-:-MuW9pAd-cCv_xI2bok6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)

**Pull request merged**
