### PR TITLE
Add utils and property based tests for popcount

### PR DESCRIPTION
**Pull request by igchor**
TODO: 
- [x] add rapidcheck to docker image
- [ ] figure out if we can suppress warning from rapidcheck during compile time. Right now, if rapidcheck is installed in non-standard location and we link to it, compiling the test results in a few warnings. There are some solutions like this one: https://stackoverflow.com/questions/42728518/cmake-supress-warnings-on-external-library but in our case we do not provide include dirs directly, it's done automatically by target_link_libraries in tests/common/functions.cmake:build_test_ext

This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/12)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
in general, it looks okay

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/12#-:-MpH4Vhh0de-uLSbSoRc:b-wlmok1)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 69 at r1](https://reviewable.io/reviews/pmem/pmemstream/12#-MpH4xUk31c6MvfH1Dfk:-MpH4xUk31c6MvfH1Dfl:bsqhlkk) ([raw file](https://github.com/pmem/pmemstream/blob/c124d5bda3caa50b6e404f63bb40266c6ad29b7a/tests/CMakeLists.txt#L69)):*
> ```CMake
> build_test(util_popcount popcount.cpp)
> add_test_generic(NAME util_popcount TRACERS none)
> target_link_libraries(util_popcount rapidcheck)
> ```

we'll probably add this link into `build_test_ext` function or even as a basic req. into `build_test`
___
*[tests/popcount.cpp, line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/12#-MpH3XSS-I0hrZS65CXJ:-MpH3XSS-I0hrZS65CXK:b-ufpiwd) ([raw file](https://github.com/pmem/pmemstream/blob/c124d5bda3caa50b6e404f63bb40266c6ad29b7a/tests/popcount.cpp#L2)):*
> ```cpp
> #include <rapidcheck.h>
> ```

if we want to merge it (later on) this should go into some (new) directory

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/12)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 69 at r1](https://reviewable.io/reviews/pmem/pmemstream/12#-MpH4xUk31c6MvfH1Dfk:-MpHCSUJCBAarcZe77Gt:br2xike) ([raw file](https://github.com/pmem/pmemstream/blob/c124d5bda3caa50b6e404f63bb40266c6ad29b7a/tests/CMakeLists.txt#L69)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we'll probably add this link into `build_test_ext` function or even as a basic req. into `build_test`
</blockquote></details>

Yeah, I think build_test_ext is the right way, we probably still want some non-rc tests and it would be best if they can be run without rc lib.
___
*[tests/popcount.cpp, line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/12#-MpH3XSS-I0hrZS65CXJ:-MpHCZfe7Lcz2HMIXECq:b31jyut) ([raw file](https://github.com/pmem/pmemstream/blob/c124d5bda3caa50b6e404f63bb40266c6ad29b7a/tests/popcount.cpp#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if we want to merge it (later on) this should go into some (new) directory
</blockquote></details>

You mean separate dir for rc-based tests?

**Comment by igchor** [comment]
The ourput from rc is quite nice, here is example for a failure:

```

**Comment by igchor** [comment]
TODO: figure out if we can suppress warning from rapidcheck during compile time. Right now, if rapidcheck is installed in non-standard location and we link to it, compiling the test results in a few warnings.

There are some solutions like this one: https://stackoverflow.com/questions/42728518/cmake-supress-warnings-on-external-library but in our case we do not provide include dirs directly, it's done automatically by target_link_libraries in tests/common/functions.cmake:build_test_ext

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/12)* status: 6 of 7 files reviewed, 8 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[-- commits, line 6 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpMQchg4zSOMZy6r-rT):*
misspell in `util_popcpount_memory`
___
*[CMakeLists.txt, line 177 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpMQp6T6u6eWrWP-HG3:-MpMQp6T6u6eWrWP-HG4:b72gx3c) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/CMakeLists.txt#L177)):*
> ```CMake
> 
> if(TESTS_RAPIDCHECK)
> 	find_package(rapidcheck REQUIRED)
> ```

please move this into `tests/CMakeLists.txt`
___
*[tests/CMakeLists.txt, line 69 at r1](https://reviewable.io/reviews/pmem/pmemstream/12#-MpH4xUk31c6MvfH1Dfk:-MpMSG8p5gHyYEYUpxbY:b-7tdf7d) ([raw file](https://github.com/pmem/pmemstream/blob/c124d5bda3caa50b6e404f63bb40266c6ad29b7a/tests/CMakeLists.txt#L69)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Yeah, I think build_test_ext is the right way, we probably still want some non-rc tests and it would be best if they can be run without rc lib.
</blockquote></details>

agree
___
*[tests/CMakeLists.txt, line 67 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpMS9f40lYbi34nH1MJ:-MpMS9f40lYbi34nH1MK:b197fsx) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/CMakeLists.txt#L67)):*
> ```CMake
> add_test_generic(NAME stream_from_map TRACERS none)
> 
> if(TESTS_RAPIDCHECK)
> ```

we should most likely check here for `RAPIDCHECK_FOUND`
___
*[tests/cmake/functions.cmake, line 151 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpMRKMG2pIIT9vwlwID:-MpMRKMG2pIIT9vwlwIE:bcygh7z) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/cmake/functions.cmake#L151)):*
> ```CMake
> 
> 	foreach(lib ${TEST_LIBS})
> 		list(APPEND LIBS_TO_LINK ${lib})
> ```

I guess TEST_LIBS is already a list.. sot this append is not needed (?)
___
*[tests/common/unittest.hpp, line 61 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpMRhAPDrEoTuZmejpy:-MpMRhAPDrEoTuZmejpz:b2iksa8) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/common/unittest.hpp#L61)):*
> ```cpp
> }
> 
> static inline int run_rc_test(std::vector<bool> results)
> ```

a short comment here pls
___
*[tests/unittest/popcount.cpp, line 15 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpMRkKwCu8p6mdmmQRb:-MpMRkKwCu8p6mdmmQRc:b-kkte12) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/unittest/popcount.cpp#L15)):*
> ```cpp
> {
> 	return run_rc_test({
> 		rc::check("verify popcount agains custom implementation", [](const std::vector<uint64_t> &data){
> ```

`against`
___
*[tests/unittest/popcount.cpp, line 28 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpMRr-O6VnyTr5LGLmT:-MpMRr-O6VnyTr5LGLmU:b4kw907) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/unittest/popcount.cpp#L28)):*
> ```cpp
> 			RC_ASSERT(count == expected);
> 		}),
> 		rc::check("verify if popcount handles sizes which is not multiple of 8", [](std::vector<uint64_t>&& data){
> ```

`which are not`
___
*[tests/unittest/popcount.cpp, line 40 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpMRvi-4tQM-IiYEhQm:-MpMRvi-4tQM-IiYEhQn:b-if0db8) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/unittest/popcount.cpp#L40)):*
> ```cpp
> 			RC_ASSERT(to_middle_count + (size - middle) == all_count);
> 		}),
> 		rc::check("verify if popcount works after flipping random bytes", [](std::vector<uint64_t> &&data){
> ```

this test seems a bit tricky, you could add some comment with an explanation (for developers :wink: )

**Review by karczex — COMMENTED** [review]
It's really nice :). Did you check if RC_PARAMS is passed through all cmake layers to the test?  

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/12#-:-MpevXIZBjU-jGXtNa94:bcvjo2a)* status: 6 of 7 files reviewed, 8 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/12)* status: all files reviewed, 13 unresolved discussions (waiting on @igchor)

___
*[src/common/util.h, line 22 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-Mpet1B62CtFk_JMyAiC:-Mpet1B62CtFk_JMyAiD:bfevbbu) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/src/common/util.h#L22)):*
> ```
> 	uint64_t count = 0;
> 	size_t i = 0;
> ```

->
```
size_t count = 0, i = 0;
```
___
*[tests/common/unittest.hpp, line 61 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpLu2st0TQRHI1-pYvf:-MpLu2st0TQRHI1-pYvg:bd7vhvq) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/common/unittest.hpp#L61)):*
> ```
> std::vector<bool> results
> ```
`const std::vector<bool> &results` we don't need to do a copy
___
*[tests/unittest/popcount.cpp, line 5 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpevHJU5_zdTE0EyOLs:-MpevHJU5_zdTE0EyOLt:b-tdfjah) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/unittest/popcount.cpp#L5)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> #include <vector>
> #include <cstring>
> #include <bitset>
> #include <algorithm>
> #include <numeric>
> ```
</details>

reorder please
___
*[tests/unittest/popcount.cpp, line 9 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpevSZg7Cb0n3rw3bsV:-MpevSZg7Cb0n3rw3bsW:b-qlcac1) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/unittest/popcount.cpp#L9)):*
> ```
> #include "unittest.hpp"
> 
> #include "common/util.h"
> ```

1. `#include "common/unittest.hpp"`?
2. remove empty line, it's the same header group
3. reorder
___
*[tests/unittest/popcount.cpp, line 54 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-Mpey6J05Mi-KXix2-uu:-Mpey6J1965SEnQEte5u:b-uiiyom) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/unittest/popcount.cpp#L54)):*
> ```cpp
> 
> 				for (size_t i = 0; i < 64; i++) {
> 					ones_diff += newByte[i] - byte[i];
> ```

what's the idea behind this?

**Review by igchor — COMMENTED** [review]
Yeah, it works.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/12#-:-MpfWkZvB5yMie__IvpB:b-o11363)* status: all files reviewed, 13 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[-- commits, line 6 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpMQchg4zSOMZy6r-rT):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

misspell in `util_popcpount_memory`
</blockquote></details>

Done.
___
*[CMakeLists.txt, line 177 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpMQp6T6u6eWrWP-HG3:-MpfWcOY7_DLeicLFAM7:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/CMakeLists.txt#L177)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please move this into `tests/CMakeLists.txt`
</blockquote></details>

Done.
___
*[src/common/util.h, line 22 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-Mpet1B62CtFk_JMyAiC:-MpfCm0m9T2FjhtSpPaw:b28ubob) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/src/common/util.h#L22)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> 	uint64_t count = 0;
> 	size_t i = 0;
> ```

->
```
size_t count = 0, i = 0;
```
</blockquote></details>

I actually prefer to have each decalaration in a separate line - this is much more readable, e.g. if you have pointers. @karczex @kfilipek @lukaszstolarczuk do you have any preference? 
___
*[tests/CMakeLists.txt, line 67 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpMS9f40lYbi34nH1MJ:-MpfWd6cBA6ggetR10RC:beu6rqb) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/CMakeLists.txt#L67)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we should most likely check here for `RAPIDCHECK_FOUND`
</blockquote></details>

Not necessary, if TESTS_RAPIDCHECK if set we just fail if find_package fails (it's searched as REQUIRED package)
___
*[tests/cmake/functions.cmake, line 151 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpMRKMG2pIIT9vwlwID:-MpfWIlP-MCZPloVFNQk:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/cmake/functions.cmake#L151)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess TEST_LIBS is already a list.. sot this append is not needed (?)
</blockquote></details>

Done.
___
*[tests/common/unittest.hpp, line 61 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpLu2st0TQRHI1-pYvf:-MpfUWMTDVAUCBiRX4sk:b-orj68) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/common/unittest.hpp#L61)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> std::vector<bool> results
> ```
`const std::vector<bool> &results` we don't need to do a copy
</blockquote></details>

Done. I replaced this.
___
*[tests/common/unittest.hpp, line 61 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpMRhAPDrEoTuZmejpy:-MpfUzmj0kvZefhKTy6r:b-bjk4lz) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/common/unittest.hpp#L61)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

a short comment here pls
</blockquote></details>

Done - although I changes the approach to veryfing return values from rc. It's a bit hacky but I didn't come up with anything better.
The previous approach was faulty because rc::check were executed BEFORE the run_tests so before sighandlers were registered.
___
*[tests/unittest/popcount.cpp, line 5 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpevHJU5_zdTE0EyOLs:-MpfVG_o1oj0cVUIyspi:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/unittest/popcount.cpp#L5)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> #include <vector>
> #include <cstring>
> #include <bitset>
> #include <algorithm>
> #include <numeric>
> ```
reorder please
</blockquote></details>

Done.
___
*[tests/unittest/popcount.cpp, line 9 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpevSZg7Cb0n3rw3bsV:-MpfVKHKAt2Y2nrlVE-U:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/unittest/popcount.cpp#L9)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> #include "unittest.hpp"
> 
> #include "common/util.h"
> ```

1. `#include "common/unittest.hpp"`?
2. remove empty line, it's the same header group
3. reorder

</blockquote></details>

Done.
___
*[tests/unittest/popcount.cpp, line 15 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpMRkKwCu8p6mdmmQRb:-MpfVOJV2e8yXLeCip8i:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/unittest/popcount.cpp#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`against`
</blockquote></details>

Done.
___
*[tests/unittest/popcount.cpp, line 28 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpMRr-O6VnyTr5LGLmT:-MpfVP8nDitJSswMQ72z:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/unittest/popcount.cpp#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`which are not`
</blockquote></details>

Done.
___
*[tests/unittest/popcount.cpp, line 40 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpMRvi-4tQM-IiYEhQm:-MpfEUG214EkLpVCK8IP:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/unittest/popcount.cpp#L40)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this test seems a bit tricky, you could add some comment with an explanation (for developers :wink: )
</blockquote></details>

Done.
___
*[tests/unittest/popcount.cpp, line 54 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-Mpey6J05Mi-KXix2-uu:-MpfEUwc6TzKERROo6XW:b-up7zr0) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/unittest/popcount.cpp#L54)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

what's the idea behind this?
</blockquote></details>

I added a comment

**Review by lukaszstolarczuk — COMMENTED** [review]
beside minor issues, lgtm

> Reviewed 9 of 10 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/12#-:-MpflCQBEFxHNSBMxs82:b4gx77y)* status: all files reviewed, 7 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[src/common/util.h, line 22 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-Mpet1B62CtFk_JMyAiC:-MpfeIx971htrgTzy8Mi:bel0lku) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/src/common/util.h#L22)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I actually prefer to have each decalaration in a separate line - this is much more readable, e.g. if you have pointers. @karczex @kfilipek @lukaszstolarczuk do you have any preference? 
</blockquote></details>

looks good in sep. lines :+1: 
___
*[tests/CMakeLists.txt, line 67 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-MpMS9f40lYbi34nH1MJ:-MpfecTp6LQb5rdAJhkx:b-tigh4r) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/tests/CMakeLists.txt#L67)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Not necessary, if TESTS_RAPIDCHECK if set we just fail if find_package fails (it's searched as REQUIRED package)
</blockquote></details>

och, yeah - then this is more "smooth" to use, then `*_FOUND` - I agree
___
*[tests/common/unittest.hpp, line 64 at r5](https://reviewable.io/reviews/pmem/pmemstream/12#-MpffCSL9ykW4QJT6Sdz:-MpffCSL9ykW4QJT6Se-:b-vimsrb) ([raw file](https://github.com/pmem/pmemstream/blob/0fe94d96ecfda45c5cfaa965811d2c26a244f26a/tests/common/unittest.hpp#L64)):*
> ```cpp
>  *     check += f();
>  *     check += g();
>  * } // if f or g returned false, return_check will fire and assert in it's dtor
> ```

1. `will fire`? did you mean `will fail`?
2. `it's dtor` -> `its dtor`
___
*[utils/docker/images/install-rapidcheck.sh, line 31 at r5](https://reviewable.io/reviews/pmem/pmemstream/12#-Mpfl5TQBp8Bwk58XV3d:-Mpfl5TQBp8Bwk58XV3e:bl513hm) ([raw file](https://github.com/pmem/pmemstream/blob/0fe94d96ecfda45c5cfaa965811d2c26a244f26a/utils/docker/images/install-rapidcheck.sh#L31)):*
> ```Shell
> 
> mkdir build
> cd build
> ```

pushd perhaps, as well

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/12#-:-MpfwnlA3HztmZv3p1PA:bnfp4nl)* status: 1 of 11 files reviewed, 13 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 8 of 10 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/12#-:-MpfwucR67mNBi2YSNA9:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[src/common/util.h, line 22 at r3](https://reviewable.io/reviews/pmem/pmemstream/12#-Mpet1B62CtFk_JMyAiC:-Mpfmi63-btbbohm12dM:bbcd14b) ([raw file](https://github.com/pmem/pmemstream/blob/5dfb9ab06b0299f4e532eaaff7ae738dd634d11c/src/common/util.h#L22)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I actually prefer to have each decalaration in a separate line - this is much more readable, e.g. if you have pointers. @karczex @kfilipek @lukaszstolarczuk do you have any preference? 
</blockquote></details>

As we discussed, for now it looks legit.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm: 

> Reviewed 9 of 10 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/12#-:-MpflCQBEFxHNSBMxs82:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
