### PR TITLE
Nontemporal memcpy simple

### PR DESCRIPTION
**Pull request by karczex**
- [ ] actually use pmemstream_memcpy in pmemstream

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/96)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/96)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)

___
*[src/memcpy.c, line 20 at r1](https://reviewable.io/reviews/pmem/pmemstream/96#-MuRQXhh7sk2oaUEczKR:-MuRQXhh7sk2oaUEczKS:bbdtnha) ([raw file](https://github.com/pmem/pmemstream/blob/aece92338f5edb2631a07e83710bb5fd1c8ad2b3/src/memcpy.c#L20)):*
> ```C
> 	if (dest_missalignment > 0) {
> 		size_t to_align = (dest_missalignment > count) ? count : dest_missalignment;
> 		pmem2_memcpy(dest, src, to_align, 0);
> ```

NOFLUSH

**Comment by karczex** [comment]
___
*[src/memcpy.c, line 20 at r1](https://reviewable.io/reviews/pmem/pmemstream/96#-MuRQXhh7sk2oaUEczKR:-MuVvVHK3gYgqvOGlVdJ:b-3du9sl) ([raw file](https://github.com/pmem/pmemstream/blob/aece92338f5edb2631a07e83710bb5fd1c8ad2b3/src/memcpy.c#L20)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

NOFLUSH
</blockquote></details>

How do you think, here also should be NOFLUSH ?
https://github.com/pmem/pmdk/blob/43aa506db217c7dd2d98090a525306c3ab45f9cf/src/examples/libpmem2/ringbuf/ringbuf.c#L107

**Comment by karczex** [comment]
___
*[src/memcpy.c, line 20 at r1](https://reviewable.io/reviews/pmem/pmemstream/96#-MuRQXhh7sk2oaUEczKR:-MuVxoVrEUF9-2BtHEhH:b4nlwcg) ([raw file](https://github.com/pmem/pmemstream/blob/aece92338f5edb2631a07e83710bb5fd1c8ad2b3/src/memcpy.c#L20)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

How do you think, here also should be NOFLUSH ?
https://github.com/pmem/pmdk/blob/43aa506db217c7dd2d98090a525306c3ab45f9cf/src/examples/libpmem2/ringbuf/ringbuf.c#L107
</blockquote></details>

I checked, with 0 libpmem2 will try to guess the best strategy based on the data size, so in mentioned example 0 is OK.

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/96)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)

___
*[src/memcpy.c, line 20 at r1](https://reviewable.io/reviews/pmem/pmemstream/96#-MuRQXhh7sk2oaUEczKR:-MujVgMZ2tCUZgQt8CTF:buuxh0v) ([raw file](https://github.com/pmem/pmemstream/blob/aece92338f5edb2631a07e83710bb5fd1c8ad2b3/src/memcpy.c#L20)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I checked, with 0 libpmem2 will try to guess the best strategy based on the data size, so in mentioned example 0 is OK. 
</blockquote></details>

My mistake, it should be NO_DRAIN actually.

**Pull request closed without merging**
