### PR TITLE
examples: clean up and update examples

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- add more comments,
- remove stale code,
- make printed messages more verbose.

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/261)

### CODE REVIEW

**Review by karczex — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/261)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[`examples/01_basic_iterate/main.c` line 10 at r1](https://reviewable.io/reviews/pmem/pmemstream/261#-N9GwurN54Ki3rWk-Wsm:-N9GwurN54Ki3rWk-Wsn:b-ly3nfd) ([raw file](https://github.com/pmem/pmemstream/blob/85bb0bcac90b43219826e1cdb760801b19b5ee07/examples/01_basic_iterate/main.c#L10)):*
> ```C
> #include <stdio.h>
> 
> /* A simple wrapper for integer value - simulates an arbitrary stream entry. */
> ```

This IS arbitrary stream entry :) it doesn't simulate anything. 
___
*[`examples/01_basic_iterate/main.c` line 21 at r1](https://reviewable.io/reviews/pmem/pmemstream/261#-N9Gx_bg1ULE_07M62tj:-N9Gx_bg1ULE_07M62tk:bksxxh9) ([raw file](https://github.com/pmem/pmemstream/blob/85bb0bcac90b43219826e1cdb760801b19b5ee07/examples/01_basic_iterate/main.c#L21)):*
> ```C
>  * It creates a file at given path, with size = EXAMPLE_STREAM_SIZE.
>  *
>  * Possible usage:
> ```

It's only one possible usage, so "Usage" would be enough.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/261)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[`examples/01_basic_iterate/main.c` line 10 at r1](https://reviewable.io/reviews/pmem/pmemstream/261#-N9GwurN54Ki3rWk-Wsm:-N9H8aqz3OEu3u75a7Mh:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/85bb0bcac90b43219826e1cdb760801b19b5ee07/examples/01_basic_iterate/main.c#L10)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

This IS arbitrary stream entry :) it doesn't simulate anything. 
</blockquote></details>

Done.
___
*[`examples/01_basic_iterate/main.c` line 21 at r1](https://reviewable.io/reviews/pmem/pmemstream/261#-N9Gx_bg1ULE_07M62tj:-N9H8b2M0oXu0hCrDyey:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/85bb0bcac90b43219826e1cdb760801b19b5ee07/examples/01_basic_iterate/main.c#L21)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It's only one possible usage, so "Usage" would be enough.
</blockquote></details>

Done.

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/261#-:-N9HF1eq96KTmEfz98fX:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @karczex)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/261#-:-N9aTnheB9A_Dmr5PFYM:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
