### PR TITLE
Add test for linker map file

### PR DESCRIPTION
**Pull request by karczex**
Check if all symbols defined in linker map file are exposed in compiled library

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/55)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/55)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)

___
*[tests/CMakeLists.txt, line 93 at r1](https://reviewable.io/reviews/pmem/pmemstream/55#-MsdhV4a5v_pyEmF8BKC:-MsdhV4a5v_pyEmF8BKD:bb915td) ([raw file](https://github.com/pmem/pmemstream/blob/97e5237e63a69aa2a14f92878844e1bf17205d8a/tests/CMakeLists.txt#L93)):*
> ```CMake
> add_test_generic(NAME reserve_publish TRACERS none memcheck pmemcheck)
> 
> add_test(NAME symbols COMMAND bash ${TESTS_ROOT_DIR}/check_symbols.sh
> ```

don't we need to check if awk/objdump is available in the system?
___
*[tests/check_symbols.sh, line 17 at r1](https://reviewable.io/reviews/pmem/pmemstream/55#-MsdgaW03SK4Z0q5HErl:-MsdgaW03SK4Z0q5HErm:bnrydvy) ([raw file](https://github.com/pmem/pmemstream/blob/97e5237e63a69aa2a14f92878844e1bf17205d8a/tests/check_symbols.sh#L17)):*
> ```Shell
> for symbol in ${symbols}; do
> 	echo "checking symbol: ${symbol}"
> 	objdump -t ${so_file}  | grep "g.*F.*${symbol}"
> ```

You might consider using `nm` instead of `objdump` - it's easier to parse I think: https://github.com/pmem/pmdk/blob/master/src/test/scope/TESTS.py#L47

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/55)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 93 at r1](https://reviewable.io/reviews/pmem/pmemstream/55#-MsdgqsI4HRTIhSZXLh-:-MsdgqsJ97A6irE0ilaP:b-jlva9c) ([raw file](https://github.com/pmem/pmemstream/blob/97e5237e63a69aa2a14f92878844e1bf17205d8a/tests/CMakeLists.txt#L93)):*
> ```CMake
> add_test_generic(NAME reserve_publish TRACERS none memcheck pmemcheck)
> 
> add_test(NAME symbols COMMAND bash ${TESTS_ROOT_DIR}/check_symbols.sh
> ```

I'm really not sure if this is something we want to run in ctest ... Did you consider running this just as sub-test e.g. in TYPE=package (in CI)?
___
*[tests/check_symbols.sh, line 5 at r1](https://reviewable.io/reviews/pmem/pmemstream/55#-Msdh5SB2y0Gk_k6Rsjl:-Msdh5SB2y0Gk_k6Rsjm:b-rfaos6) ([raw file](https://github.com/pmem/pmemstream/blob/97e5237e63a69aa2a14f92878844e1bf17205d8a/tests/check_symbols.sh#L5)):*
> ```Shell
> # Copyright 2022, Intel Corporation
> 
> # check_symbols.sh - Check if all symbols defined in linker map file are exposed in compiled library
> ```

now I'm thinking - can we do this also the other way around? To check if everything we wanted to make public is public indeed?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/55)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 93 at r1](https://reviewable.io/reviews/pmem/pmemstream/55#-MsdhV4a5v_pyEmF8BKC:-MsdiEZr61Qj5Idm1thS:b-48m8s2) ([raw file](https://github.com/pmem/pmemstream/blob/97e5237e63a69aa2a14f92878844e1bf17205d8a/tests/CMakeLists.txt#L93)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

don't we need to check if awk/objdump is available in the system?
</blockquote></details>

potentially even bash can be missing... :smile: 

I say, this is another reason to move this into CI :stuck_out_tongue_winking_eye: 
___
*[tests/check_symbols.sh, line 17 at r1](https://reviewable.io/reviews/pmem/pmemstream/55#-MsdgaW03SK4Z0q5HErl:-Msdi7ub-F0VNEW1JA2q:b-qubb37) ([raw file](https://github.com/pmem/pmemstream/blob/97e5237e63a69aa2a14f92878844e1bf17205d8a/tests/check_symbols.sh#L17)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You might consider using `nm` instead of `objdump` - it's easier to parse I think: https://github.com/pmem/pmdk/blob/master/src/test/scope/TESTS.py#L47
</blockquote></details>

it looks pretty cool, but since it works...? :wink:

**Comment by karczex** [comment]
___
*[tests/check_symbols.sh, line 17 at r1](https://reviewable.io/reviews/pmem/pmemstream/55#-MsdgaW03SK4Z0q5HErl:-MsdlQoX4LrqyHJxbtBJ:b63osl2) ([raw file](https://github.com/pmem/pmemstream/blob/97e5237e63a69aa2a14f92878844e1bf17205d8a/tests/check_symbols.sh#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it looks pretty cool, but since it works...? :wink: 
</blockquote></details>

objdump and nm have almost the same format

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/55)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 93 at r1](https://reviewable.io/reviews/pmem/pmemstream/55#-MsdhV4a5v_pyEmF8BKC:-Mse6Wbp3bulIFwOnyCb:b-w4a5ch) ([raw file](https://github.com/pmem/pmemstream/blob/97e5237e63a69aa2a14f92878844e1bf17205d8a/tests/CMakeLists.txt#L93)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

potentially even bash can be missing... :smile: 

I say, this is another reason to move this into CI :stuck_out_tongue_winking_eye: 
</blockquote></details>

ok, so I believe, we agreed to keep it here - please then check all required commands (and extend readme)
___
*[tests/check_symbols.sh, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/55#-Mse6g7oBpI9jzC13sXd:-Mse6g7oBpI9jzC13sXe:b-wy5co0) ([raw file](https://github.com/pmem/pmemstream/blob/97e5237e63a69aa2a14f92878844e1bf17205d8a/tests/check_symbols.sh#L4)):*
> ```Shell
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2022, Intel Corporation
> ```

pls consider moving this file into a (new?) tests' sub-directory
___
*[tests/check_symbols.sh, line 8 at r1](https://reviewable.io/reviews/pmem/pmemstream/55#-Mse6pmf9opeMzjYyPZc:-Mse6pmf9opeMzjYyPZd:b5oq99s) ([raw file](https://github.com/pmem/pmemstream/blob/97e5237e63a69aa2a14f92878844e1bf17205d8a/tests/check_symbols.sh#L8)):*
> ```Shell
> 
> set -e
> set -x
> ```

`-x` is required?

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/55)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 93 at r1](https://reviewable.io/reviews/pmem/pmemstream/55#-MsdgqsI4HRTIhSZXLh-:-MseHGv86t0TsfN-jxNB:b-bb5csq) ([raw file](https://github.com/pmem/pmemstream/blob/97e5237e63a69aa2a14f92878844e1bf17205d8a/tests/CMakeLists.txt#L93)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm really not sure if this is something we want to run in ctest ... Did you consider running this just as sub-test e.g. in TYPE=package (in CI)?
</blockquote></details>

I don't like this approach if may be avoided. Obviously, sometimes tests need to call cmake, or may affect system, so shouldn't be run from ctest, but it's not the case here.  
___
*[tests/check_symbols.sh, line 5 at r1](https://reviewable.io/reviews/pmem/pmemstream/55#-Msdh5SB2y0Gk_k6Rsjl:-MseGdh_-9znGXcEvVdW:b-gbia3n) ([raw file](https://github.com/pmem/pmemstream/blob/97e5237e63a69aa2a14f92878844e1bf17205d8a/tests/check_symbols.sh#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

now I'm thinking - can we do this also the other way around? To check if everything we wanted to make public is public indeed?
</blockquote></details>

Maybe I'm not aware of sth, but linker map file is the place, where we define "everything we wanted to make public". 
___
*[tests/check_symbols.sh, line 8 at r1](https://reviewable.io/reviews/pmem/pmemstream/55#-Mse6pmf9opeMzjYyPZc:-MseFdXdDybbQ70dEJmk:b-b9ci3z) ([raw file](https://github.com/pmem/pmemstream/blob/97e5237e63a69aa2a14f92878844e1bf17205d8a/tests/check_symbols.sh#L8)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`-x` is required?
</blockquote></details>

yes. It would make verbose log if test fail (listed all symbols, and stuff like that). If test pass, output is hidden by ctest.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/55)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 93 at r1](https://reviewable.io/reviews/pmem/pmemstream/55#-MsdhV4a5v_pyEmF8BKC:-Msepo0m5UBHwNH0V4rf:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/97e5237e63a69aa2a14f92878844e1bf17205d8a/tests/CMakeLists.txt#L93)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

ok, so I believe, we agreed to keep it here - please then check all required commands (and extend readme)
</blockquote></details>

Done.
___
*[tests/check_symbols.sh, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/55#-Mse6g7oBpI9jzC13sXd:-Msepq6yCgm5Z9592axb:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/97e5237e63a69aa2a14f92878844e1bf17205d8a/tests/check_symbols.sh#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls consider moving this file into a (new?) tests' sub-directory
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/55)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor and @karczex)

___
*[INSTALL.md, line 26 at r2](https://reviewable.io/reviews/pmem/pmemstream/55#-Mt1uTfg1hIJX4jNTJy8:-Mt1uTfg1hIJX4jNTJy9:b-nfmmo6) ([raw file](https://github.com/pmem/pmemstream/blob/ddccb3b7f4c3a4ad787dfd6919a16a7554db5acf/INSTALL.md#L26)):*
> ```Markdown
> 	* **gdb**
> 	* **bash**, **awk**, **grep** - some tests require basic scripting tools.
> 	* [GNU Binutils](https://www.gnu.org/software/binutils/) - some tests require this for testing generated binaries.
> ```

should we install any of these explicitly in the Docker files?
___
*[tests/CMakeLists.txt, line 112 at r2](https://reviewable.io/reviews/pmem/pmemstream/55#-Mt1vToD0kKKNl8zxiN0:-Mt1vToD0kKKNl8zxiN1:b156ilt) ([raw file](https://github.com/pmem/pmemstream/blob/ddccb3b7f4c3a4ad787dfd6919a16a7554db5acf/tests/CMakeLists.txt#L112)):*
> ```CMake
> endif()
> 
> check_test_dependecies(NAME script_dependencies DEPENDENCIES bash awk grep objdump)
> ```

perhaps instead `script_dependencies` use the same name as the test has - `symbols`
___
*[tests/cmake/functions.cmake, line 132 at r2](https://reviewable.io/reviews/pmem/pmemstream/55#-Mt1v6ROAHFshuWgNbIw:-Mt1v6ROAHFshuWgNbIx:bg3qgpq) ([raw file](https://github.com/pmem/pmemstream/blob/ddccb3b7f4c3a4ad787dfd6919a16a7554db5acf/tests/cmake/functions.cmake#L132)):*
> ```CMake
> 	foreach(dependency ${TEST_DEPENDENCIES})
> 		find_program(${dependency}_PROGRAM ${dependency})
> 		if( NOT ${dependency}_PROGRAM)
> ```

remove space within `if( NOT..`

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/55)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 112 at r2](https://reviewable.io/reviews/pmem/pmemstream/55#-Mt1vToD0kKKNl8zxiN0:-Mt2G7vO0L33v5vPY4kj:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ddccb3b7f4c3a4ad787dfd6919a16a7554db5acf/tests/CMakeLists.txt#L112)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps instead `script_dependencies` use the same name as the test has - `symbols`
</blockquote></details>

Done.
___
*[tests/cmake/functions.cmake, line 132 at r2](https://reviewable.io/reviews/pmem/pmemstream/55#-Mt1v6ROAHFshuWgNbIw:-Mt2G8oz7phpQOiW8Cmy:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ddccb3b7f4c3a4ad787dfd6919a16a7554db5acf/tests/cmake/functions.cmake#L132)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

remove space within `if( NOT..`
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/55#-:-Mt2J0Tf17tRbdG8cjLi:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Review by lukaszstolarczuk — COMMENTED** [review]
since you added a new sub-dir within tests, pls extend `tests/README.md` with that dir's description

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/55#-:-Mt2PxCJCoJ54Ot_Eec6:b-yqfj8l)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/55#-:-Mt2WrLa4MIn6PE3DO9n:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @igchor and @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
thx

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/55#-:-Mt2ZmTi91NtFPqNo1j9:b2nid0f)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
