### PR TITLE
Make libpmemstream linkable with c++

### PR DESCRIPTION
**Pull request by karczex**
As it's hard to create simpler test than stream_form_map I just copied
it and included unittest.hpp in it.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/10)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/10)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[tests/CMakeLists.txt, line 67 at r1](https://reviewable.io/reviews/pmem/pmemstream/10#-MpBtX2v5nxB3N7mSzQR:-MpBtX2v5nxB3N7mSzQS:bar6h96) ([raw file](https://github.com/pmem/pmemstream/blob/a5b7951c0148318bd936868e4ce461a68fe14ae0/tests/CMakeLists.txt#L67)):*
> ```CMake
> add_test_generic(NAME stream_from_map TRACERS none)
> 
> build_test(cpp_linkage api_c/stream_from_map.cpp)
> ```

perhaps add something like `# XXX: remove or re-write this test, when real TC comes up` 
___
*[tests/api_c/stream_from_map.cpp, line 7 at r1](https://reviewable.io/reviews/pmem/pmemstream/10#-MpBtmOg3mkSJ-GsAo-n:-MpBtmOg3mkSJ-GsAo-o:bu482vk) ([raw file](https://github.com/pmem/pmemstream/blob/a5b7951c0148318bd936868e4ce461a68fe14ae0/tests/api_c/stream_from_map.cpp#L7)):*
> ```cpp
> 
> /**
>  * stream_from_map - unit test for pmemstream_from_map
> ```

perhaps add short info it's a cpp test - someone may miss that info and try to remove the duplicate(?)

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/10)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/10#-MpCTVyV-u20h00GjSbe:-MpCTVyV-u20h00GjSbf:bi73u1n) (no related file):*
I think you have to solve this comment:
https://github.com/pmem/pmemstream/blob/master/CMakeLists.txt#L133

right now CI is failing this PR

---
___
*[tests/CMakeLists.txt, line 67 at r1](https://reviewable.io/reviews/pmem/pmemstream/10#-MpBtX2v5nxB3N7mSzQR:-MpCTS35633UhwuqbSWF:b2nid0f) ([raw file](https://github.com/pmem/pmemstream/blob/a5b7951c0148318bd936868e4ce461a68fe14ae0/tests/CMakeLists.txt#L67)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/10)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[tests/api_c/stream_from_map.cpp, line 31 at r2](https://reviewable.io/reviews/pmem/pmemstream/10#-MpG8qY0B0zCYPKRGUn0:-MpG8qY0B0zCYPKRGUn1:b-b7chxc) ([raw file](https://github.com/pmem/pmemstream/blob/09e38d59387b00d78c67ca4451bd02eb7cd007b7/tests/api_c/stream_from_map.cpp#L31)):*
> ```cpp
> 	}
> 
> 	START();
> ```

in c++, the preffered way is to call run_tests(...) - this will make sure that if we introduce some exceptions in tests it will work fine.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/10)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/api_c/stream_from_map.cpp, line 31 at r2](https://reviewable.io/reviews/pmem/pmemstream/10#-MpG8qY0B0zCYPKRGUn0:-MpGIWtOE-Z1sV79lvut:b-ew56bk) ([raw file](https://github.com/pmem/pmemstream/blob/09e38d59387b00d78c67ca4451bd02eb7cd007b7/tests/api_c/stream_from_map.cpp#L31)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

in c++, the preffered way is to call run_tests(...) - this will make sure that if we introduce some exceptions in tests it will work fine.
</blockquote></details>

That's really good point. Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/10#-:-MpGOsAZ5VLGY4HfczaZ:bnfp4nl)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/api_c/stream_from_map.cpp, line 34 at r3](https://reviewable.io/reviews/pmem/pmemstream/10#-MpGOvcuDqA3DWGzPjCM:-MpGOvcuDqA3DWGzPjCN:bqdqsht) ([raw file](https://github.com/pmem/pmemstream/blob/6343d73ce50aee8284192b579b436c3d0203ccc6/tests/api_c/stream_from_map.cpp#L34)):*
> ```cpp
> 
> 	return run_test([&] {
> 		test_stream_from_map(path, 10240, 64);
> ```

did you remove this second test case on purpose?

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/10)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/api_c/stream_from_map.cpp, line 34 at r3](https://reviewable.io/reviews/pmem/pmemstream/10#-MpGOvcuDqA3DWGzPjCM:-MpGQQgPAP5kTUE97zI-:b-4hhtfx) ([raw file](https://github.com/pmem/pmemstream/blob/6343d73ce50aee8284192b579b436c3d0203ccc6/tests/api_c/stream_from_map.cpp#L34)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

did you remove this second test case on purpose?
</blockquote></details>

yes, it's not needed here, as whole point of this test is to check compilation and linkage.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/10)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/10#-MpCTVyV-u20h00GjSbe:-MpGR2OG-cZnmiKQPQga:b-4hhjwr) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think you have to solve this comment:
https://github.com/pmem/pmemstream/blob/master/CMakeLists.txt#L133

right now CI is failing this PR
</blockquote></details>

and another issue to solve for CI passing:

`'Version' field value 'd6c5d91': version number does not start with digit`

---

**Comment by karczex** [comment]
*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/10#-MpCTVyV-u20h00GjSbe:-MpH7qwu3147EPFuuIip:b-msvjjh) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

and another issue to solve for CI passing:

`'Version' field value 'd6c5d91': version number does not start with digit`
</blockquote></details>

I may change sha of last commit if you really want :)

---

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/10)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/10#-MpCTVyV-u20h00GjSbe:-MpHLTXNDw7p7o0K4-_W:b-tpzci3) (no related file):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I may change sha of last commit if you really want :)
</blockquote></details>

the second comment in this discussion is, of course, random; but the first comment is a real issue. 

---

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/10)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @karczex)

___
*[src/include/libpmemstream.h, line 5 at r3](https://reviewable.io/reviews/pmem/pmemstream/10#-MpLj1G7749JVvH12T9M:-MpLj1G7749JVvH12T9N:b-zf6bd1) ([raw file](https://github.com/pmem/pmemstream/blob/6343d73ce50aee8284192b579b436c3d0203ccc6/src/include/libpmemstream.h#L5)):*
> ```
> 1
> ```
Why? :D
___
*[src/include/libpmemstream.h, line 111 at r3](https://reviewable.io/reviews/pmem/pmemstream/10#-MpLj5_Q920KY1JWlyeP:-MpLj5_Q920KY1JWlyeQ:bnmbovy) ([raw file](https://github.com/pmem/pmemstream/blob/6343d73ce50aee8284192b579b436c3d0203ccc6/src/include/libpmemstream.h#L111)):*
> ```objc
> } /* end extern "C" */
> #endif
> ```

double line

**Comment by karczex** [comment]
___
*[src/include/libpmemstream.h, line 5 at r3](https://reviewable.io/reviews/pmem/pmemstream/10#-MpLj1G7749JVvH12T9M:-MpQUnuM1rzX8-_e7BKv:btqnkle) ([raw file](https://github.com/pmem/pmemstream/blob/6343d73ce50aee8284192b579b436c3d0203ccc6/src/include/libpmemstream.h#L5)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> 1
> ```
Why? :D
</blockquote></details>

Please use option `git blame` for such questions :) 

Anyhow it's not related to this PR.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/10)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/10#-MpCTVyV-u20h00GjSbe:-MpQj-RB0u37Cv0m8WzP:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

the second comment in this discussion is, of course, random; but the first comment is a real issue. 
</blockquote></details>

Done.

---

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/10#-:-MpQtHnO4LDa5MPXZCyr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Review by KFilipek — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by karczex — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/10#-:-MpRH1TQAmwxISS6Slf9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/10#-:-MpRHODs333WJBBdvNzu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
