### PR TITLE
Fix segmentation fault in pmemstream_reserve and pmestream_publish

### PR DESCRIPTION
**Pull request by Karolina002**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/120)

### CODE REVIEW

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/120)* status: all files reviewed, 1 unresolved discussion (waiting on @Karolina002)

___
*[tests/api_c/reserve_and_publish.c, line 190 at r1](https://reviewable.io/reviews/pmem/pmemstream/120#-MvrxTAR5E6m1pGFoiHP:-MvrxTAR5E6m1pGFoiHQ:b5axb16) ([raw file](https://github.com/pmem/pmemstream/blob/d599d54afa93e5c94ba3ccb00bdfd7ed0adbd3b0/tests/api_c/reserve_and_publish.c#L190)):*
> ```C
> 	null_data_test(path);
> 	zero_size_test(path);
> 	// https://github.com/pmem/pmemstream/issues/101
> ```

You don't need this if your PR fixes this bug :)



_Code quote:_
```C
	// https://github.com/pmem/pmemstream/issues/101
```

**Review by karczex — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/120)* status: all files reviewed, 2 unresolved discussions (waiting on @Karolina002)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/120#-Mvs51547EFwd5ZJ-hJK):*
Don't be so shy  and please describe problem, you are fixing.  
It's really inconvenient when you type `git blame` and only information is issue number.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/120)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex and @Karolina002)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/120#-Mvs51547EFwd5ZJ-hJK):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Don't be so shy  and please describe problem, you are fixing.  
It's really inconvenient when you type `git blame` and only information is issue number.

</blockquote></details>

yeah, as I pointed out in another review - this "fixes" or "ref" with an issue should be the very last line of your commit message :wink: 
___
*[tests/api_c/reserve_and_publish.c, line 72 at r1](https://reviewable.io/reviews/pmem/pmemstream/120#-Mvs755u3OZuxzziHQRI:-Mvs755u3OZuxzziHQRJ:bnsjhf4) ([raw file](https://github.com/pmem/pmemstream/blob/d599d54afa93e5c94ba3ccb00bdfd7ed0adbd3b0/tests/api_c/reserve_and_publish.c#L72)):*
> ```C
> }
> 
> void invalid_region_test(char *path)
> ```

I believe this test is duplicated from https://github.com/pmem/pmemstream/pull/67 - please include only new changes here

we may merge one or another PR first, if it would be easier for you, just please let us know

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/120)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @karczex, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/120#-Mvs51547EFwd5ZJ-hJK):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

yeah, as I pointed out in another review - this "fixes" or "ref" with an issue should be the very last line of your commit message :wink: 
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/120)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex and @Karolina002)

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/120)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[tests/api_c/reserve_and_publish.c, line 72 at r1](https://reviewable.io/reviews/pmem/pmemstream/120#-Mvs755u3OZuxzziHQRI:-Mw0vN1n8NHa7AEBJdNJ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d599d54afa93e5c94ba3ccb00bdfd7ed0adbd3b0/tests/api_c/reserve_and_publish.c#L72)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe this test is duplicated from https://github.com/pmem/pmemstream/pull/67 - please include only new changes here

we may merge one or another PR first, if it would be easier for you, just please let us know
</blockquote></details>

Done.
___
*[tests/api_c/reserve_and_publish.c, line 190 at r1](https://reviewable.io/reviews/pmem/pmemstream/120#-MvrxTAR5E6m1pGFoiHP:-Mw0vSg5AlGvATtmnkH2:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d599d54afa93e5c94ba3ccb00bdfd7ed0adbd3b0/tests/api_c/reserve_and_publish.c#L190)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

You don't need this if your PR fixes this bug :)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/120)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex, @Karolina002, and @KFilipek)

___
*[tests/api_c/reserve_and_publish.c, line 72 at r1](https://reviewable.io/reviews/pmem/pmemstream/120#-Mvs755u3OZuxzziHQRI:-Mw1A7yI5MoJmTUm27xc:ba0x12v) ([raw file](https://github.com/pmem/pmemstream/blob/d599d54afa93e5c94ba3ccb00bdfd7ed0adbd3b0/tests/api_c/reserve_and_publish.c#L72)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

actually, all these tests (and renames of the above functions) are duplicated from https://github.com/pmem/pmemstream/pull/67 - why are you including them here?

If you want to add some tests, they should relate to this PR, meaning, they should test the `return -1` path of the code.

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/120)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[tests/api_c/reserve_and_publish.c, line 72 at r1](https://reviewable.io/reviews/pmem/pmemstream/120#-Mvs755u3OZuxzziHQRI:-Mx17bi71D5I53OZYSD_:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d599d54afa93e5c94ba3ccb00bdfd7ed0adbd3b0/tests/api_c/reserve_and_publish.c#L72)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

actually, all these tests (and renames of the above functions) are duplicated from https://github.com/pmem/pmemstream/pull/67 - why are you including them here?

If you want to add some tests, they should relate to this PR, meaning, they should test the `return -1` path of the code.
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/120)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex, @Karolina002, and @KFilipek)

___
*[src/libpmemstream.c, line 286 at r4](https://reviewable.io/reviews/pmem/pmemstream/120#-Mx3rbrs0AQMB-PlHICn:-Mx3rbrs0AQMB-PlHICo:b-pdrf6l) ([raw file](https://github.com/pmem/pmemstream/blob/40b23883abf5721e933f03d4810265bce0942706/src/libpmemstream.c#L286)):*
> ```C
> 		       struct pmemstream_entry reserved_entry)
> {
> ```

you've left this empty line - it's redundant - pls remove 
___
*[tests/api_c/reserve_and_publish.c, line 4 at r4](https://reviewable.io/reviews/pmem/pmemstream/120#-Mx3uGwQ06VkC0uBIkUC:-Mx3uGwQ06VkC0uBIkUD:b60o8g6) ([raw file](https://github.com/pmem/pmemstream/blob/40b23883abf5721e933f03d4810265bce0942706/tests/api_c/reserve_and_publish.c#L4)):*
> ```C
> /* Copyright 2021-2022, Intel Corporation */
> 
> #include "span.h"
> ```

I believe you don't need this incldue...?

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/120)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 286 at r4](https://reviewable.io/reviews/pmem/pmemstream/120#-Mx3rbrs0AQMB-PlHICn:-MxBNMshE8zL-Jqff9a9:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/40b23883abf5721e933f03d4810265bce0942706/src/libpmemstream.c#L286)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you've left this empty line - it's redundant - pls remove 
</blockquote></details>

Done.
___
*[tests/api_c/reserve_and_publish.c, line 4 at r4](https://reviewable.io/reviews/pmem/pmemstream/120#-Mx3uGwQ06VkC0uBIkUC:-MxBNNfi8zGDasT1ug-H:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/40b23883abf5721e933f03d4810265bce0942706/tests/api_c/reserve_and_publish.c#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe you don't need this incldue...?
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/120#-:-MxDqyENBp1OTBc0eVF0:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex and @KFilipek)

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/120#-:-MxFZf9wA2_6sHfPjOIC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Review by KFilipek — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/120)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/120)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)

**Pull request merged**
