### PR TITLE
Use memset() from pmem2 with proper flags for stream initialization

### PR DESCRIPTION
**Pull request by KFilipek**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/43)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/43)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[src/libpmemstream.c, line 80 at r2](https://reviewable.io/reviews/pmem/pmemstream/43#-MrSIdeX9V53UVy5_lay:-MrSIdeX9V53UVy5_laz:b1h5rol) ([raw file](https://github.com/pmem/pmemstream/blob/3823e0da9423a7c855b51e0820cc2b0cbeb33320/src/libpmemstream.c#L80)):*
> ```C
> static void pmemstream_init(struct pmemstream *stream)
> {
> 	stream->memset(stream->data->header.signature, 0, PMEMSTREAM_SIGNATURE_SIZE, PMEM2_F_MEM_NONTEMPORAL);
> ```

NODRAIN here? we do a persist  right away
___
*[src/libpmemstream.c, line 87 at r2](https://reviewable.io/reviews/pmem/pmemstream/43#-MrSITX59F-kgdMO-HhP:-MrSITX59F-kgdMO-HhQ:blicn7a) ([raw file](https://github.com/pmem/pmemstream/blob/e6e5a963777d6be9064513469f165e3628868062/src/libpmemstream.c#L87)):*
> ```C
> 
> 	size_t metadata_size = MEMBER_SIZE(pmemstream_span_runtime, empty);
> 	pmemstream_span_create_empty(stream, &stream->data->spans[0], stream->usable_size - metadata_size);
> ```

why these changes? I think it's more verbose/explicit to have it like it was before

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/43)* status: all files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 80 at r2](https://reviewable.io/reviews/pmem/pmemstream/43#-MrSIdeX9V53UVy5_lay:-MrSU2Qu-Xmel3IsTPS7:b-cjuyia) ([raw file](https://github.com/pmem/pmemstream/blob/3823e0da9423a7c855b51e0820cc2b0cbeb33320/src/libpmemstream.c#L80)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

NODRAIN here? we do a persist  right away
</blockquote></details>

Right, there should be NODRAIN here because we do persist for whole data block later (ordering is not important here).
___
*[src/libpmemstream.c, line 87 at r2](https://reviewable.io/reviews/pmem/pmemstream/43#-MrSITX59F-kgdMO-HhP:-MrSULqmB41vkyTzqgc9:b-yvgblu) ([raw file](https://github.com/pmem/pmemstream/blob/e6e5a963777d6be9064513469f165e3628868062/src/libpmemstream.c#L87)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why these changes? I think it's more verbose/explicit to have it like it was before
</blockquote></details>

imho the new version is better but I guess it's subjective  ;d
___
*[src/libpmemstream.c, line 88 at r2](https://reviewable.io/reviews/pmem/pmemstream/43#-MrSUYKb9VAwKFdqE7Pr:-MrSUYKb9VAwKFdqE7Ps:b7vesmp) ([raw file](https://github.com/pmem/pmemstream/blob/3823e0da9423a7c855b51e0820cc2b0cbeb33320/src/libpmemstream.c#L88)):*
> ```C
> 	size_t metadata_size = MEMBER_SIZE(pmemstream_span_runtime, empty);
> 	pmemstream_span_create_empty(stream, stream->data->spans, stream->usable_size - metadata_size);
> 	stream->persist(stream->data->spans, metadata_size);
> ```

Please rebase, this will not be needed anymore

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/43)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 87 at r2](https://reviewable.io/reviews/pmem/pmemstream/43#-MrSITX59F-kgdMO-HhP:-MrSV854DVcF27zjzzk4:bmev0gs) ([raw file](https://github.com/pmem/pmemstream/blob/e6e5a963777d6be9064513469f165e3628868062/src/libpmemstream.c#L87)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

imho the new version is better but I guess it's subjective  ;d
</blockquote></details>

hah, ok, so perhaps toss a coin :smile:

**Comment by lukaszstolarczuk** [comment]
continued on new master in https://github.com/pmem/pmemstream/pull/49

**Pull request closed without merging**
