### PR TITLE
Benchmark fixes

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/111)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/111)* status: all files reviewed, 6 unresolved discussions (waiting on @karczex)

___
*[benchmarks/measure.hpp, line 24 at r1](https://reviewable.io/reviews/pmem/pmemstream/111#-Mv3P2Xv1GVhfnt3YUXr:-Mv3P2Xv1GVhfnt3YUXs:b-bzzg9v) ([raw file](https://github.com/pmem/pmemstream/blob/3cc7949ab84d8a6f0a4fe04068df33e6a187ade1/benchmarks/measure.hpp#L24)):*
> ```cpp
> }
> 
> /* Measure time of execution of run_workload funcion. init() and clean()
> ```

function
___
*[benchmarks/measure.hpp, line 27 at r1](https://reviewable.io/reviews/pmem/pmemstream/111#-Mv3TyBKDg2FN_4yfGKv:-Mv3TyBKDg2FN_4yfGKw:bh77ozo) ([raw file](https://github.com/pmem/pmemstream/blob/3cc7949ab84d8a6f0a4fe04068df33e6a187ade1/benchmarks/measure.hpp#L27)):*
> ```cpp
>  * functions are executed respectively before and after each iterarion */
> template <typename TimeUnit, typename InitFunc, typename WorkloadFunc, typename CleanupFunc>
> auto measure(size_t iterations, InitFunc &&init, WorkloadFunc &&run_workload, CleanupFunc clean)
> ```

not `&&clean` ?
___
*[benchmarks/append/main.cpp, line 209 at r1](https://reviewable.io/reviews/pmem/pmemstream/111#-Mv3T2Jk81FffWj-E9rq:-Mv3T2Jk81FffWj-E9rr:b-nqgpos) ([raw file](https://github.com/pmem/pmemstream/blob/3cc7949ab84d8a6f0a4fe04068df33e6a187ade1/benchmarks/append/main.cpp#L209)):*
> ```cpp
> 		for (size_t i = 0; i < data.size() * sizeof(uint64_t); i += cfg.element_size) {
> 			if (pmemlog_append(plp.get(), data_chunks + i, cfg.element_size) < 0) {
> 				throw std::runtime_error("Error while appending new entry! Errno: " +
> ```

perhaps do the same change here: `new` -> `'<the actual data>'`
___
*[benchmarks/append/main.cpp, line 252 at r1](https://reviewable.io/reviews/pmem/pmemstream/111#-Mv3QWwM4znAeq231z9d:-Mv3QWwM4znAeq231z9e:bqo1cg7) ([raw file](https://github.com/pmem/pmemstream/blob/3cc7949ab84d8a6f0a4fe04068df33e6a187ade1/benchmarks/append/main.cpp#L252)):*
> ```cpp
> 			if (pmemstream_append(stream.get(), region, region_runtime_ptr, data_chunks + i,
> 					      cfg.element_size, NULL) < 0) {
> 				throw std::runtime_error("Error while appending " + std::to_string(i) + " entry!");
> ```

pls surround this string with `'...'`
___
*[benchmarks/append/main.cpp, line 292 at r1](https://reviewable.io/reviews/pmem/pmemstream/111#-Mv3TSIO65tFZURorhS7:-Mv3TSIO65tFZURorhS8:bx4yn7r) ([raw file](https://github.com/pmem/pmemstream/blob/3cc7949ab84d8a6f0a4fe04068df33e6a187ade1/benchmarks/append/main.cpp#L292)):*
> ```cpp
> 	}
> 
> 	/* XXX: Add initialization phase whith separate measurement */
> ```

isn't this comment done already? do we want to measure the init phase?
___
*[benchmarks/append/main.cpp, line 297 at r1](https://reviewable.io/reviews/pmem/pmemstream/111#-Mv3REN02FsW1KNk1RbY:-Mv3REN02FsW1KNk1RbZ:b-9jhd6l) ([raw file](https://github.com/pmem/pmemstream/blob/3cc7949ab84d8a6f0a4fe04068df33e6a187ade1/benchmarks/append/main.cpp#L297)):*
> ```cpp
> 		results = benchmark::measure<std::chrono::nanoseconds>(
> 			cfg.iterations, [&] { workload->initialize(); },
> 			[interface = workload.get()] { interface->perform(); }, [&] { workload->clean(); });
> ```

can't you just call `workload.get()->perform`? 

and I'm not sure - why do we need `.get()` here and not for clean and init?

**Comment by karczex** [comment]
___
*[benchmarks/append/main.cpp, line 297 at r1](https://reviewable.io/reviews/pmem/pmemstream/111#-Mv3REN02FsW1KNk1RbY:-Mv3bcx7-PWLVjd3HMT5:b-2bmyfs) ([raw file](https://github.com/pmem/pmemstream/blob/3cc7949ab84d8a6f0a4fe04068df33e6a187ade1/benchmarks/append/main.cpp#L297)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can't you just call `workload.get()->perform`? 

and I'm not sure - why do we need `.get()` here and not for clean and init?
</blockquote></details>

It's tight loop, where we measure time in nanoseconds. It's micro optimization - here we get  raw function pointer at the moment of capturing of lambda expression, so eliminate unique_ptr overhead.  I admit, it may be over engineered  :)

And I would like to announce contest for better name of `interface` variable.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/111)* status: all files reviewed, 6 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[benchmarks/append/main.cpp, line 292 at r1](https://reviewable.io/reviews/pmem/pmemstream/111#-Mv3TSIO65tFZURorhS7:-Mv3bD7hE442-7tbEXCf:b-85zgdd) ([raw file](https://github.com/pmem/pmemstream/blob/3cc7949ab84d8a6f0a4fe04068df33e6a187ade1/benchmarks/append/main.cpp#L292)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

isn't this comment done already? do we want to measure the init phase?
</blockquote></details>

No, especially, the region initialization is now done in every iteration.

**Review by igchor — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/111#-:-Mv3gEcG6ZqfRVeI9s2L:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[benchmarks/measure.hpp, line 27 at r1](https://reviewable.io/reviews/pmem/pmemstream/111#-Mv3flmSDicOHxzxA3c6:-Mv3flmSDicOHxzxA3c7:b-pd0jey) ([raw file](https://github.com/pmem/pmemstream/blob/3cc7949ab84d8a6f0a4fe04068df33e6a187ade1/benchmarks/measure.hpp#L27)):*
> ```cpp
>  * functions are executed respectively before and after each iterarion */
> template <typename TimeUnit, typename InitFunc, typename WorkloadFunc, typename CleanupFunc>
> auto measure(size_t iterations, InitFunc &&init, WorkloadFunc &&run_workload, CleanupFunc clean)
> ```

woulnd't it be easier to just move `class workload_base` to this file and accept pointer to `workload_base*` instead of passing those 3 functions?

In that case, I would remove the prepare_data and get_data_chunks from workload_base. Those function can be implemented for stream and log_workload or using a second base class.

**Comment by karczex** [comment]
___
*[benchmarks/measure.hpp, line 27 at r1](https://reviewable.io/reviews/pmem/pmemstream/111#-Mv3flmSDicOHxzxA3c6:-Mv3iyVg8YBE9Vhf2Dtb:b-3342r2) ([raw file](https://github.com/pmem/pmemstream/blob/3cc7949ab84d8a6f0a4fe04068df33e6a187ade1/benchmarks/measure.hpp#L27)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

woulnd't it be easier to just move `class workload_base` to this file and accept pointer to `workload_base*` instead of passing those 3 functions?

In that case, I would remove the prepare_data and get_data_chunks from workload_base. Those function can be implemented for stream and log_workload or using a second base class.
</blockquote></details>

That's good point :) I would do it in separate PR, as it's version, we already use for measuremets.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/111)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[benchmarks/measure.hpp, line 24 at r1](https://reviewable.io/reviews/pmem/pmemstream/111#-Mv3P2Xv1GVhfnt3YUXr:-Mv3iJmH5tFbGkE-mh7S:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/3cc7949ab84d8a6f0a4fe04068df33e6a187ade1/benchmarks/measure.hpp#L24)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

function
</blockquote></details>

Done.
___
*[benchmarks/append/main.cpp, line 209 at r1](https://reviewable.io/reviews/pmem/pmemstream/111#-Mv3T2Jk81FffWj-E9rq:-Mv3kOHRAn8UtKRJafq3:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/3cc7949ab84d8a6f0a4fe04068df33e6a187ade1/benchmarks/append/main.cpp#L209)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps do the same change here: `new` -> `'<the actual data>'`
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/111#-:-Mv3rTYrEkAt6pecxFTz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

___
*[benchmarks/append/main.cpp, line 297 at r1](https://reviewable.io/reviews/pmem/pmemstream/111#-Mv3REN02FsW1KNk1RbY:-Mv3rLg307wgMT6JAEvL:bu7gcx9) ([raw file](https://github.com/pmem/pmemstream/blob/3cc7949ab84d8a6f0a4fe04068df33e6a187ade1/benchmarks/append/main.cpp#L297)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It's tight loop, where we measure time in nanoseconds. It's micro optimization - here we get  raw function pointer at the moment of capturing of lambda expression, so eliminate unique_ptr overhead.  I admit, it may be over engineered  :)

And I would like to announce contest for better name of `interface` variable.
</blockquote></details>

och, damn, I didn't think of this as optimization, nice

**Pull request merged**
