### PR TITLE
Slist pmreorder test

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/157)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/157)* status: 5 of 7 files reviewed, 9 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 168 at r1](https://reviewable.io/reviews/pmem/pmemstream/157#-MzKiKQy9QMHY-1mmfT5:-MzKiKQz-UwmdXCk_PlR:b-nsqcu9) ([raw file](https://github.com/pmem/pmemstream/blob/597ce6cd0e9dc3c62415e5ebba7bdfb3a2d5dd18/tests/CMakeLists.txt#L168)):*
> ```CMake
> 	add_test_generic(NAME append_break SCRIPT integrity/append_break.cmake TRACERS none)
> endif()
> ```

redundant empty line
___
*[tests/integrity/pmreorder.conf, line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/157#-MzKiaglDW5VkgGOsNnU:-MzKiaglDW5VkgGOsNnV:b27xl4i) ([raw file](https://github.com/pmem/pmemstream/blob/597ce6cd0e9dc3c62415e5ebba7bdfb3a2d5dd18/tests/integrity/pmreorder.conf#L2)):*
> ```
> {
> 	"pmemobj_open" : "NoReorderNoCheck",
> ```

heh, I'm not sure if we use any of these obj's functions :wink: 

FYI, in general, this configuration file is useful to "not do any reorders" in functions which are executed underneath our code and do not bother us in any way... so here, if anything, should be libpmem2 funcs (you'd have to look into store log and see what's redundant for us)
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 80 at r1](https://reviewable.io/reviews/pmem/pmemstream/157#-MzKzv5r6I9JJn0tU-FX:-MzKzv5r6I9JJn0tU-FY:b7go4fo) ([raw file](https://github.com/pmem/pmemstream/blob/597ce6cd0e9dc3c62415e5ebba7bdfb3a2d5dd18/tests/integrity/singly_linked_list_pmreorder.cpp#L80)):*
> ```cpp
> 	{
> 
> 		static std::vector<callable> possible_values{slist_insert_head, slist_insert_tail, slist_remove_head};
> ```

possible_cmds (?)
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 82 at r1](https://reviewable.io/reviews/pmem/pmemstream/157#-MzL-H8E0YMvGbVxkiCW:-MzL-H8E0YMvGbVxkiCX:b-a2vsux) ([raw file](https://github.com/pmem/pmemstream/blob/597ce6cd0e9dc3c62415e5ebba7bdfb3a2d5dd18/tests/integrity/singly_linked_list_pmreorder.cpp#L82)):*
> ```cpp
> 		static std::vector<callable> possible_values{slist_insert_head, slist_insert_tail, slist_remove_head};
> 
> 		constexpr size_t test_memory_size = TEST_DEFAULT_STREAM_SIZE - sizeof(struct node);
> ```

`- sizeof(struct node)`? not `sizeof(singly_linked_list)`?
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 88 at r1](https://reviewable.io/reviews/pmem/pmemstream/157#-MzKze4H9BSty_2S1GJK:-MzKze4I7OWgGfneOFDP:b-i6ihmd) ([raw file](https://github.com/pmem/pmemstream/blob/597ce6cd0e9dc3c62415e5ebba7bdfb3a2d5dd18/tests/integrity/singly_linked_list_pmreorder.cpp#L88)):*
> ```cpp
> 			gen::set(&funcWrapper::func, gen::elementOf(possible_values)),
> 			gen::set(&funcWrapper::offset,
> 				 gen::suchThat(gen::inRange<size_t>(8, test_memory_size), offset_predicate)));
> ```

`8`? :wink: 
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 140 at r1](https://reviewable.io/reviews/pmem/pmemstream/157#-MzL0xDOC-7QBgYMilvU:-MzL0xDOC-7QBgYMilvV:byvdl7b) ([raw file](https://github.com/pmem/pmemstream/blob/597ce6cd0e9dc3c62415e5ebba7bdfb3a2d5dd18/tests/integrity/singly_linked_list_pmreorder.cpp#L140)):*
> ```cpp
> 	auto map = make_pmem2_map(copy_path.c_str(), TEST_DEFAULT_STREAM_SIZE, truncate);
> 	auto runtime = get_runtime(map.get());
> 	singly_linked_list *list = get_list(map.get());
> ```

suddenly not `auto` ? ;-)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/157)* status: 2 of 7 files reviewed, 8 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 168 at r1](https://reviewable.io/reviews/pmem/pmemstream/157#-MzKiKQy9QMHY-1mmfT5:-MzZ8EVJC1i2g-4ZKGwK:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/597ce6cd0e9dc3c62415e5ebba7bdfb3a2d5dd18/tests/CMakeLists.txt#L168)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done.
___
*[tests/integrity/pmreorder.conf, line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/157#-MzKiaglDW5VkgGOsNnU:-MzZ8qtF6Qg7IND5a80c:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/597ce6cd0e9dc3c62415e5ebba7bdfb3a2d5dd18/tests/integrity/pmreorder.conf#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

heh, I'm not sure if we use any of these obj's functions :wink: 

FYI, in general, this configuration file is useful to "not do any reorders" in functions which are executed underneath our code and do not bother us in any way... so here, if anything, should be libpmem2 funcs (you'd have to look into store log and see what's redundant for us)
</blockquote></details>

Done.
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 80 at r1](https://reviewable.io/reviews/pmem/pmemstream/157#-MzKzv5r6I9JJn0tU-FX:-MzZ8rbpBCLYnUB-wnQJ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/597ce6cd0e9dc3c62415e5ebba7bdfb3a2d5dd18/tests/integrity/singly_linked_list_pmreorder.cpp#L80)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

possible_cmds (?)
</blockquote></details>

Done.
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 82 at r1](https://reviewable.io/reviews/pmem/pmemstream/157#-MzL-H8E0YMvGbVxkiCW:-MzOZWFTAiXZcaT8qvJO:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/597ce6cd0e9dc3c62415e5ebba7bdfb3a2d5dd18/tests/integrity/singly_linked_list_pmreorder.cpp#L82)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`- sizeof(struct node)`? not `sizeof(singly_linked_list)`?
</blockquote></details>

Done.
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 88 at r1](https://reviewable.io/reviews/pmem/pmemstream/157#-MzKr4uE2m-s9r81Apsj:-MzZ97NrCc0Af72bcFTE:bjzi383) ([raw file](https://github.com/pmem/pmemstream/blob/597ce6cd0e9dc3c62415e5ebba7bdfb3a2d5dd18/tests/integrity/singly_linked_list_pmreorder.cpp#L88)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This offset generation is wrong is this is possible the case why some tests are going into inifite loop. Right now, there is nothing preventing rapidcheck from generating multiple offset with the same value. This means that you are inserting/removing the same element multiple times (which is wrong).

That's why it would be better to use stateful testing - there you have some state (model) which you can use to generate unique offsets.
</blockquote></details>

Using rapidcheck in this test was tricky, so I removed it. 
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 88 at r1](https://reviewable.io/reviews/pmem/pmemstream/157#-MzKze4H9BSty_2S1GJK:-MzZ9GSEDXwOaeUd6pBi:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/597ce6cd0e9dc3c62415e5ebba7bdfb3a2d5dd18/tests/integrity/singly_linked_list_pmreorder.cpp#L88)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`8`? :wink: 
</blockquote></details>

Done.
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 119 at r1](https://reviewable.io/reviews/pmem/pmemstream/157#-MzKr_9L7CppiDIPMyu_:-MzZ9JMA93xn089v2alp:bs7wumx) ([raw file](https://github.com/pmem/pmemstream/blob/597ce6cd0e9dc3c62415e5ebba7bdfb3a2d5dd18/tests/integrity/singly_linked_list_pmreorder.cpp#L119)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think you should initialize the list at the beginning of this lambda and clear it at the end. Otherwise you will be inserting/removing elements from already initialized list.
</blockquote></details>

Done. 
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 140 at r1](https://reviewable.io/reviews/pmem/pmemstream/157#-MzL0xDOC-7QBgYMilvU:-MzZ9Qw14oXX_KP7Ns0h:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/597ce6cd0e9dc3c62415e5ebba7bdfb3a2d5dd18/tests/integrity/singly_linked_list_pmreorder.cpp#L140)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

suddenly not `auto` ? ;-)
</blockquote></details>

Done.

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/157)* status: 2 of 7 files reviewed, 10 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 99 at r2](https://reviewable.io/reviews/pmem/pmemstream/157#-MzZIMeUEvMS8eKw0zVM:-MzZIMeUEvMS8eKw0zVN:b-wzross) ([raw file](https://github.com/pmem/pmemstream/blob/4bd944560f83065e89a3d406d6c330cb084e8966/tests/integrity/singly_linked_list_pmreorder.cpp#L99)):*
> ```cpp
> }
> 
> template <typename OffsetOf>
> ```

What does OffsetOf mean?
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 103 at r2](https://reviewable.io/reviews/pmem/pmemstream/157#-MzZIdXm4bD0B0cpWNag:-MzZIdXm4bD0B0cpWNah:b6iyrav) ([raw file](https://github.com/pmem/pmemstream/blob/4bd944560f83065e89a3d406d6c330cb084e8966/tests/integrity/singly_linked_list_pmreorder.cpp#L103)):*
> ```cpp
> {
> 	std::vector<size_t> numbers;
> 	std::vector<size_t> mixed_numbers;
> ```

offsets/mixed_offsets?
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 111 at r2](https://reviewable.io/reviews/pmem/pmemstream/157#-MzZJ2cSDJTXH1b2epg8:-MzZJ2cSDJTXH1b2epg9:b-uhslo6) ([raw file](https://github.com/pmem/pmemstream/blob/4bd944560f83065e89a3d406d6c330cb084e8966/tests/integrity/singly_linked_list_pmreorder.cpp#L111)):*
> ```cpp
> 	}
> 
> 	std::sample(numbers.begin(), numbers.end(), std::back_inserter(mixed_numbers), numbers.size(), rnd_generator);
> ```

why not use std::shuffle? it will be faster (no extra allocations)
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 139 at r2](https://reviewable.io/reviews/pmem/pmemstream/157#-MzZJJ3_6xf1vbI1KLEs:-MzZJJ3_6xf1vbI1KLEt:b-wgvixa) ([raw file](https://github.com/pmem/pmemstream/blob/4bd944560f83065e89a3d406d6c330cb084e8966/tests/integrity/singly_linked_list_pmreorder.cpp#L139)):*
> ```cpp
> 
> 	slist_runtime_init(&runtime, list);
> 	const size_t number_of_commands = 100;
> ```

make it a gobal test constant perhaps? It will be easier to modify in future (easier to spot at the top of the file). 
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 142 at r2](https://reviewable.io/reviews/pmem/pmemstream/157#-MzZJUdT7G9bUs9u64ZN:-MzZJUdT7G9bUs9u64ZO:b9d3o7x) ([raw file](https://github.com/pmem/pmemstream/blob/4bd944560f83065e89a3d406d6c330cb084e8966/tests/integrity/singly_linked_list_pmreorder.cpp#L142)):*
> ```cpp
> 
> 	const auto commands = generate_commands(number_of_commands);
> 	const auto offsets = generate_offsets<node>(number_of_commands);
> ```

Shouldn't offset generation depend on command to which is relates? I mean for removes, we are (mostly) interested in whether removing exiting elements works fine. In  your approach we will never remove any element (all offsets you are generating are unique).
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 170 at r2](https://reviewable.io/reviews/pmem/pmemstream/157#-MzZJwq5DY4H8k6xzEoI:-MzZJwq68AKDy0qTpL8c:b-69ioxs) ([raw file](https://github.com/pmem/pmemstream/blob/4bd944560f83065e89a3d406d6c330cb084e8966/tests/integrity/singly_linked_list_pmreorder.cpp#L170)):*
> ```cpp
> 
> 	uint64_t last_accessed = SLIST_INVALID_OFFSET;
> 	slist_foreach(&runtime, list, [&](uint64_t offset) { last_accessed = offset; });
> ```

Can you came up with some additional properties we can check? E.g. all nodes in the list have increasing offsets? Or they contain data which is increasing, or something similar?

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/157)* status: 8 of 9 files reviewed, 9 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 168 at r1](https://reviewable.io/reviews/pmem/pmemstream/157#-MzKiKQy9QMHY-1mmfT5:-MzZK6LO4Aq0ZqKkaVMw:b-pnqbnr) ([raw file](https://github.com/pmem/pmemstream/blob/597ce6cd0e9dc3c62415e5ebba7bdfb3a2d5dd18/tests/CMakeLists.txt#L168)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nope :stuck_out_tongue_winking_eye: 
___
*[tests/integrity/singly_linked_list_pmreorder.cmake, line 18 at r2](https://reviewable.io/reviews/pmem/pmemstream/157#-MzZTMa14JdXmgRsmXxr:-MzZTMa14JdXmgRsmXxs:bnjzwiw) ([raw file](https://github.com/pmem/pmemstream/blob/4bd944560f83065e89a3d406d6c330cb084e8966/tests/integrity/singly_linked_list_pmreorder.cmake#L18)):*
> ```CMake
> pmreorder_execute(${EXPECT_SUCCESS} ReorderAccumulative ${SRC_DIR}/pmreorder.conf ${EXECUTABLE} check)
> 
> pmreorder_execute(${EXPECT_FAILURE} ReorderAccumulative ${SRC_DIR}/pmreorder.conf ${EXECUTABLE} check_without_recovery)
> ```

perhaps, rather, move this into a separate CMake file
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 115 at r2](https://reviewable.io/reviews/pmem/pmemstream/157#-MzZaS0p1w0mLbh0Vjbv:-MzZaS0p1w0mLbh0Vjbw:b8hewj0) ([raw file](https://github.com/pmem/pmemstream/blob/4bd944560f83065e89a3d406d6c330cb084e8966/tests/integrity/singly_linked_list_pmreorder.cpp#L115)):*
> ```cpp
> }
> 
> void slist_init(pmemstream_runtime *runtime, singly_linked_list *list)
> ```

pls move this `slist_` function above, to other `slist_` functions
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 139 at r2](https://reviewable.io/reviews/pmem/pmemstream/157#-MzZJJ3_6xf1vbI1KLEs:-MzZbw2_DA-CBc6YxfV1:b-8fx2u7) ([raw file](https://github.com/pmem/pmemstream/blob/4bd944560f83065e89a3d406d6c330cb084e8966/tests/integrity/singly_linked_list_pmreorder.cpp#L139)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

make it a gobal test constant perhaps? It will be easier to modify in future (easier to spot at the top of the file). 
</blockquote></details>

:+1: 
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 177 at r2](https://reviewable.io/reviews/pmem/pmemstream/157#-MzZacFH3wfSoV-Z5oZa:-MzZacFH3wfSoV-Z5oZb:b7bn7ny) ([raw file](https://github.com/pmem/pmemstream/blob/4bd944560f83065e89a3d406d6c330cb084e8966/tests/integrity/singly_linked_list_pmreorder.cpp#L177)):*
> ```cpp
> int main(int argc, char *argv[])
> {
> ```

redundant empty line :wink: 
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 183 at r2](https://reviewable.io/reviews/pmem/pmemstream/157#-MzZbMeS5-owmb-Ouzxw:-MzZbMeS5-owmb-Ouzxx:b-78b1dz) ([raw file](https://github.com/pmem/pmemstream/blob/4bd944560f83065e89a3d406d6c330cb084e8966/tests/integrity/singly_linked_list_pmreorder.cpp#L183)):*
> ```cpp
> 	std::string mode = argv[1];
> 	std::filesystem::path path(argv[2]);
> ```

shouldn't we run this with `run_test` and make use of `test_config_type` (including stream size, instead of explicitly using `TEST_DEFAULT_STREAM_SIZE` in the code)?

**Comment by karczex** [comment]
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 142 at r2](https://reviewable.io/reviews/pmem/pmemstream/157#-MzZJUdT7G9bUs9u64ZN:-MzZvzJW49lSH2nuiq5g:b-txx5dt) ([raw file](https://github.com/pmem/pmemstream/blob/4bd944560f83065e89a3d406d6c330cb084e8966/tests/integrity/singly_linked_list_pmreorder.cpp#L142)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Shouldn't offset generation depend on command to which is relates? I mean for removes, we are (mostly) interested in whether removing exiting elements works fine. In  your approach we will never remove any element (all offsets you are generating are unique).
</blockquote></details>

Currently I'm testing only remove_head, and I would like to leave it as is. It should be extended in the future  - with additional tests for remove. Especially when SLIST_REMOVE would properly work with not-present nodes.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/157)* status: 0 of 29 files reviewed, 5 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 168 at r1](https://reviewable.io/reviews/pmem/pmemstream/157#-MzKiKQy9QMHY-1mmfT5:-MzZquvc6dwvkvowBXYa:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/597ce6cd0e9dc3c62415e5ebba7bdfb3a2d5dd18/tests/CMakeLists.txt#L168)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

nope :stuck_out_tongue_winking_eye: 
</blockquote></details>

Done.
___
*[tests/integrity/singly_linked_list_pmreorder.cmake, line 18 at r2](https://reviewable.io/reviews/pmem/pmemstream/157#-MzZTMa14JdXmgRsmXxr:-MzZqtDsDuetabiiOrLL:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4bd944560f83065e89a3d406d6c330cb084e8966/tests/integrity/singly_linked_list_pmreorder.cmake#L18)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps, rather, move this into a separate CMake file
</blockquote></details>

Done.
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 115 at r2](https://reviewable.io/reviews/pmem/pmemstream/157#-MzZaS0p1w0mLbh0Vjbv:-MzZt4aHBfLXEtYZUkul:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4bd944560f83065e89a3d406d6c330cb084e8966/tests/integrity/singly_linked_list_pmreorder.cpp#L115)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls move this `slist_` function above, to other `slist_` functions
</blockquote></details>

Done.
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 177 at r2](https://reviewable.io/reviews/pmem/pmemstream/157#-MzZacFH3wfSoV-Z5oZa:-MzZtZU_B8ZCYfM5vBe0:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4bd944560f83065e89a3d406d6c330cb084e8966/tests/integrity/singly_linked_list_pmreorder.cpp#L177)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant empty line :wink: 
</blockquote></details>

Done.
___
*[tests/integrity/singly_linked_list_pmreorder.cpp, line 183 at r2](https://reviewable.io/reviews/pmem/pmemstream/157#-MzZbMeS5-owmb-Ouzxw:-Mz_HeiP5NalCHokjzHh:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4bd944560f83065e89a3d406d6c330cb084e8966/tests/integrity/singly_linked_list_pmreorder.cpp#L183)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

shouldn't we run this with `run_test` and make use of `test_config_type` (including stream size, instead of explicitly using `TEST_DEFAULT_STREAM_SIZE` in the code)?
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r9, 10 of 10 files at r10, 18 of 18 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/157#-:-Mz_OtldDKDPfKHv0bBD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/157#-:-Mz_Pr7e2lyoA7UFMmck:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
