### PR TITLE
Validate passed values in api_c functions

### PR DESCRIPTION
**Pull request by Karolina002**
in libpmemstream.c and iterator.c

Fixes: #98 #99 #100

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/140)

### CODE REVIEW

**Review by karczex — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/140)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @karczex and @Karolina002)

___
*[src/libpmemstream.c, line 102 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-Mx928f1AesrdtMUPsDA:-Mx928f1AesrdtMUPsDB:b-4wwh4q) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/src/libpmemstream.c#L102)):*
> ```C
> }
> 
> static int pmemstream_validate_stream_and_offset(struct pmemstream *stream, uint64_t offset)
> ```

To avoid duplication it would be better to move this function to `libpmemstream_internal.h' 
___
*[src/libpmemstream.c, line 167 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-Mx92zXa9Bh0FodbJk8q:-Mx92zXa9Bh0FodbJk8r:bim5m3j) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/src/libpmemstream.c#L167)):*
> ```C
> int pmemstream_region_allocate(struct pmemstream *stream, size_t size, struct pmemstream_region *region)
> {
> 	if (!stream || !region) {
> ```

It should be possible to pass NULL *region. It would be very useful in scenario, where user wants to preallocate some number of regions before using it later (i.e. accessing via iterators).

**Review by karczex — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/140)* status: 0 of 7 files reviewed, 8 unresolved discussions (waiting on @karczex and @Karolina002)

___
*[tests/api_c/append_entry.c, line 17 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-Mx9RSIm0qSriTBBr0j1:-Mx9RSIm0qSriTBBr0j2:b-ogtrkh) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/tests/api_c/append_entry.c#L17)):*
> ```C
> };
> 
> void valid_input_test(char *path)
> ```

what happened with this test, that it is no more test for entry_iterator?
___
*[tests/api_c/append_entry.c, line 60 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-Mx9RxjC2kCUEjEuT1Tl:-Mx9RxjC2kCUEjEuT1Tm:btwfgmw) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/tests/api_c/append_entry.c#L60)):*
> ```C
> 	UT_ASSERTeq(ret, 0);
> 
> 	struct pmemstream_region region = {.offset = ALIGN_DOWN(UINT64_MAX, sizeof(span_bytes))};
> ```

maybe change the name of this variable to `to_large_region` or something like that.



_Code quote:_
```C
region
```
___
*[tests/api_c/append_entry.c, line 73 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-Mx9TdB11tGr5xvJQ78v:-Mx9TdB11tGr5xvJQ78w:birjs2j) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/tests/api_c/append_entry.c#L73)):*
> ```C
> {
> 	int ret;
> 	struct entry_data e;
> ```

Except traditional i,j,k in for loop, you should virtually never create one letter variable names.



_Code quote:_
```C
e
```
___
*[tests/api_c/append_entry.c, line 74 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-Mx9V7fsBS9fxxprHPsX:-Mx9V7fsBS9fxxprHPsY:b-i2ei7m) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/tests/api_c/append_entry.c#L74)):*
> ```C
> 	int ret;
> 	struct entry_data e;
> 	e.data = PTRDIFF_MAX;
> ```

You may initialize e with Designated Initializer in previous line.
___
*[tests/api_c/append_entry.c, line 75 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-Mx9URlzAooZ8cnD6RT5:-Mx9U8bF4nEqD8qDGAEV:b-ialyf5) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/tests/api_c/append_entry.c#L75)):*
> ```C
> 	struct entry_data e;
> 	e.data = PTRDIFF_MAX;
> 	const struct entry_data *entry_data = &e;
> ```

Here entry_data is structure name and variable name. It's valid c code, but it's little bit hard to figure out what's going on. 



_Code quote:_
```C
const struct entry_data *entry_data = &e;
```
___
*[tests/api_c/append_entry.c, line 76 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-Mx9SPQODhsDe5_nZCeX:-Mx9SPQODhsDe5_nZCeY:b-xrmcms) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/tests/api_c/append_entry.c#L76)):*
> ```C
> 	e.data = PTRDIFF_MAX;
> 	const struct entry_data *entry_data = &e;
> 	struct pmemstream_entry entry = {.offset = ALIGN_DOWN(UINT64_MAX, sizeof(span_bytes))};
> ```

`to_large_entry` or something.

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/140)* status: 2 of 7 files reviewed, 14 unresolved discussions (waiting on @karczex, @Karolina002, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/140#-MxB-Gjn3WCSFf91Y-Hz:-MxB-Gjn3WCSFf91Y-I-:b-kzikce) (no related file):*
I believe we should firstly merge #67 - it'd be easier to continue/review this change.

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-MxAf3ca3tp9oCo8UPrD):*
1. this line is too long
2. as described in our blog post - the first line should be short and rather not detailed (but descriptive) and the next lines should describe in detail if needed
___
*[src/iterator.c, line 96 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-MxAvtW69A8njoDRwGw6:-MxAvtW69A8njoDRwGw7:b-nsqcu9) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/src/iterator.c#L96)):*
> ```C
> 				  struct pmemstream_region region)
> {
> ```

redundant empty line
___
*[src/libpmemstream.c, line 265 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-MxAyTeAECY3h3APH_i-:-MxAyTeAECY3h3APH_i0:behqqnu) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/src/libpmemstream.c#L265)):*
> ```C
> 					 struct pmemstream_region_runtime **region_runtime)
> {
> 	int ret = pmemstream_validate_stream_and_offset(stream, region.offset);
> ```

I think this check may be redundant - pls check, but I believe it's always called after the very same check was already done
___
*[src/libpmemstream.c, line 325 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-MxAysyL-C4301Rfd9Sr:-MxAysyL-C4301Rfd9Ss:b-okr3jb) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/src/libpmemstream.c#L325)):*
> ```C
> 		       struct pmemstream_entry reserved_entry)
> {
> 	int ret = pmemstream_validate_stream_and_offset(stream, region.offset);
> ```

hmm... wouldn't it be better to check here the entry's offset (instead of region's offset)...? or perhaps we should check both offsets...?
___
*[src/libpmemstream.c, line 360 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-MxAzYxm33MRqV1aOKKX:-MxAzYxm33MRqV1aOKKY:bmiohrf) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/src/libpmemstream.c#L360)):*
> ```C
> 	}
> 
> 	if (!region_runtime) {
> ```

we call `pmemstream_reserve` right away, so I think this and the above calls are actually redundant in `_append` ...?
___
*[tests/api_c/append_entry.c, line 17 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-Mx9RSIm0qSriTBBr0j1:-MxAzpMMB6EEQaEzws74:b-4xejrf) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/tests/api_c/append_entry.c#L17)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

what happened with this test, that it is no more test for entry_iterator?
</blockquote></details>

this change is left out from another branch (where we order the names of the tests)... so it's a good change, but it shouldn't be in this PR :wink:

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/140)* status: 0 of 8 files reviewed, 9 unresolved discussions (waiting on @karczex, @Karolina002, and @lukaszstolarczuk)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-MxAf3ca3tp9oCo8UPrD):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. this line is too long
2. as described in our blog post - the first line should be short and rather not detailed (but descriptive) and the next lines should describe in detail if needed
</blockquote></details>

Done.
___
*[src/iterator.c, line 96 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-MxAvtW69A8njoDRwGw6:-MxF6mzm8b9pWivraMRi:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/src/iterator.c#L96)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 102 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-Mx928f1AesrdtMUPsDA:-MxF6oDY50Hspgje_-ac:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/src/libpmemstream.c#L102)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

To avoid duplication it would be better to move this function to `libpmemstream_internal.h' 
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 167 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-Mx92zXa9Bh0FodbJk8q:-MxF6pbzC3iU6uCxY1jd:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/src/libpmemstream.c#L167)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It should be possible to pass NULL *region. It would be very useful in scenario, where user wants to preallocate some number of regions before using it later (i.e. accessing via iterators).
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 265 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-MxAyTeAECY3h3APH_i-:-MxBU4J56bgUfpxGiV8h:b-j8ng7y) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/src/libpmemstream.c#L265)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think this check may be redundant - pls check, but I believe it's always called after the very same check was already done
</blockquote></details>

As far as I'm concerned this function can also be called independently.
___
*[tests/api_c/append_entry.c, line 17 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-Mx9RSIm0qSriTBBr0j1:-MxF6xfz-gbOH9B5fZT3:b-zdeczy) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/tests/api_c/append_entry.c#L17)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

hmmm... so probably should be in mentioned PR :)
</blockquote></details>

I retracted to the previous functions names
___
*[tests/api_c/append_entry.c, line 74 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-Mx9V7fsBS9fxxprHPsX:-MxF7d0cBnem9wpsW5nr:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/tests/api_c/append_entry.c#L74)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

You may initialize e with Designated Initializer in previous line.
</blockquote></details>

Done.
___
*[tests/api_c/append_entry.c, line 75 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-Mx9URlzAooZ8cnD6RT5:-MxF7fjl0zt9lgMrwp20:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/tests/api_c/append_entry.c#L75)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Here entry_data is structure name and variable name. It's valid c code, but it's little bit hard to figure out what's going on. 
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/140)* status: 3 of 8 files reviewed, 11 unresolved discussions (waiting on @karczex, @Karolina002, and @lukaszstolarczuk)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/pmemstream/140#-MxFKLOtEwFl-HpvRxfx):*
"api_c" is just a dir name in our tests :wink: 

I'd re-write this e.g. like this: "Validate passed values to public/API functions"
___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/pmem/pmemstream/140#-MxFKTSc3U__ZCXWDcZ5):*
the line is still too long
___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/pmem/pmemstream/140#-MxFKq9d9tkFVVNEXk-0):*
this is just an internal function, so you can drop the part "Add function" - just "Check if ..."
___
*[src/iterator.c, line 13 at r2](https://reviewable.io/reviews/pmem/pmemstream/140#-MxFOyhM9tB_P_VopNWc:-MxFOyhM9tB_P_VopNWd:b-dyfrsa) ([raw file](https://github.com/pmem/pmemstream/blob/315914cdccb5188bbdadb1817ecd4b96323cb255/src/iterator.c#L13)):*
> ```C
> #include <string.h>
> 
> int pmemstream_region_iterator_new(struct pmemstream_region_iterator **iterator, struct pmemstream *stream)
> ```

Please check for null here as well

and please make sure we check for null-ed stream in all public functions :)
___
*[src/libpmemstream.c, line 265 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-MxAyTeAECY3h3APH_i-:-MxFLp_29DALf_i4W9I1:b7dvv9p) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/src/libpmemstream.c#L265)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

As far as I'm concerned this function can also be called independently.
</blockquote></details>

och, ok, mea culpa, this is a public function :smile: 
___
*[src/libpmemstream.c, line 183 at r2](https://reviewable.io/reviews/pmem/pmemstream/140#-MxFJwRp01na8MQDNfG2:-MxFJwRp01na8MQDNfG3:b-atwhet) ([raw file](https://github.com/pmem/pmemstream/blob/315914cdccb5188bbdadb1817ecd4b96323cb255/src/libpmemstream.c#L183)):*
> ```C
> 	stream->data.memcpy((void *)span_base, &span_region, sizeof(struct span_region), 0);
> 
> 	if (!region) {
> ```

I think, what @karczex suggested is to just avoid setting this var when is not delivered by the user - meaning - check if not null and only then assign the offset
___
*[tests/api_c/append_entry.c, line 17 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-Mx9RSIm0qSriTBBr0j1:-MxFNAfVCkTZRIaRj9xB:bsv4yq8) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/tests/api_c/append_entry.c#L17)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

I retracted to the previous functions names
</blockquote></details>

hmm nope...? the name is still changed

**Review by karczex — COMMENTED** [review]
> Reviewed 1 of 8 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/140)* status: all files reviewed, 8 unresolved discussions (waiting on @karczex and @Karolina002)

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/140)* status: 4 of 8 files reviewed, 8 unresolved discussions (waiting on @karczex, @Karolina002, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/140#-MxB-Gjn3WCSFf91Y-Hz:-MxfQInSBuYwdCezq84c:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe we should firstly merge #67 - it'd be easier to continue/review this change.
</blockquote></details>

Done.

---
___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/pmemstream/140#-MxFKLOtEwFl-HpvRxfx):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"api_c" is just a dir name in our tests :wink: 

I'd re-write this e.g. like this: "Validate passed values to public/API functions"
</blockquote></details>

Done.
___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/pmem/pmemstream/140#-MxFKq9d9tkFVVNEXk-0):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this is just an internal function, so you can drop the part "Add function" - just "Check if ..."
</blockquote></details>

Done.
___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/pmem/pmemstream/140#-MxFKTSc3U__ZCXWDcZ5):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

the line is still too long
</blockquote></details>

Done.
___
*[src/iterator.c, line 13 at r2](https://reviewable.io/reviews/pmem/pmemstream/140#-MxFOyhM9tB_P_VopNWc:-MxfQ0Ls0woL4cyYyJVa:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/315914cdccb5188bbdadb1817ecd4b96323cb255/src/iterator.c#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Please check for null here as well

and please make sure we check for null-ed stream in all public functions :)
</blockquote></details>

Done.
___
*[tests/api_c/append_entry.c, line 17 at r1](https://reviewable.io/reviews/pmem/pmemstream/140#-Mx9RSIm0qSriTBBr0j1:-MxemQGz5i9vK_K_v0tR:b-fmzth6) ([raw file](https://github.com/pmem/pmemstream/blob/0d29bf96dd671ae83cd7e4237f4c14848473e7b5/tests/api_c/append_entry.c#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm nope...? the name is still changed
</blockquote></details>

The other PR was merged, so it changed again,

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/140)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @karczex, @Karolina002, and @lukaszstolarczuk)

___
*[src/iterator.c, line 34 at r4](https://reviewable.io/reviews/pmem/pmemstream/140#-Mxhjw340lryXGij6gtz:-Mxhjw340lryXGij6gu-:b854h46) ([raw file](https://github.com/pmem/pmemstream/blob/0f4c6c27d30c7a647c287ea0538ff45826bd5e97/src/iterator.c#L34)):*
> ```C
> int pmemstream_region_iterator_next(struct pmemstream_region_iterator *it, struct pmemstream_region *region)
> {
> 	if (it) {
> ```

I think it's better readability if you check this, the other way around

`if (!it) return -1`

the rest of the code will have one less indentation
___
*[src/iterator.c, line 34 at r4](https://reviewable.io/reviews/pmem/pmemstream/140#-MxhkxEC04ZwTcb94dU7:-MxhkxEC04ZwTcb94dU8:bq5r1ov) ([raw file](https://github.com/pmem/pmemstream/blob/0f4c6c27d30c7a647c287ea0538ff45826bd5e97/src/iterator.c#L34)):*
> ```C
> int pmemstream_region_iterator_next(struct pmemstream_region_iterator *it, struct pmemstream_region *region)
> {
> 	if (it) {
> ```

since you're checking also iterators for nulls, please update the commit message
___
*[src/libpmemstream.c, line 183 at r2](https://reviewable.io/reviews/pmem/pmemstream/140#-MxFJwRp01na8MQDNfG2:-MxhlQfY51EssyYBKvvf:bb7dx2z) ([raw file](https://github.com/pmem/pmemstream/blob/315914cdccb5188bbdadb1817ecd4b96323cb255/src/libpmemstream.c#L183)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think, what @karczex suggested is to just avoid setting this var when is not delivered by the user - meaning - check if not null and only then assign the offset
</blockquote></details>

bump
___
*[tests/api_c/region_iterator.c, line 78 at r4](https://reviewable.io/reviews/pmem/pmemstream/140#-MxhmUo5-SVQ804OxRt7:-MxhmUo5-SVQ804OxRt8:b3poex8) ([raw file](https://github.com/pmem/pmemstream/blob/0f4c6c27d30c7a647c287ea0538ff45826bd5e97/tests/api_c/region_iterator.c#L78)):*
> ```C
> 	pmemstream_region_iterator_delete(&riter);
> }
> ```

you should now also add a test for calls like:

`pmemstream_region_iterator_new(NULL, proper_stream)`
and
`pmemstream_region_iterator_next(NULL, proper_region)`

and probably something similar for entry_iterator (if we don't have such tests yet)

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/140)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @karczex, @Karolina002, and @lukaszstolarczuk)

___
*[src/iterator.c, line 34 at r4](https://reviewable.io/reviews/pmem/pmemstream/140#-MxhkxEC04ZwTcb94dU7:-MxjDQak9E4X8ewZwZ6z:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0f4c6c27d30c7a647c287ea0538ff45826bd5e97/src/iterator.c#L34)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

since you're checking also iterators for nulls, please update the commit message
</blockquote></details>

Done.
___
*[src/iterator.c, line 34 at r4](https://reviewable.io/reviews/pmem/pmemstream/140#-Mxhjw340lryXGij6gtz:-MxjDSRWDpUKRgSVLFZf:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0f4c6c27d30c7a647c287ea0538ff45826bd5e97/src/iterator.c#L34)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think it's better readability if you check this, the other way around

`if (!it) return -1`

the rest of the code will have one less indentation
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 183 at r2](https://reviewable.io/reviews/pmem/pmemstream/140#-MxFJwRp01na8MQDNfG2:-MxjDUkbE11d892WWWLh:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/315914cdccb5188bbdadb1817ecd4b96323cb255/src/libpmemstream.c#L183)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

bump
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/140#-:-MxjFpWtDADg1QvgBrzM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[tests/api_c/region_iterator.c, line 78 at r4](https://reviewable.io/reviews/pmem/pmemstream/140#-MxhmUo5-SVQ804OxRt7:-MxjFiwf74FVhn32TuEB:b-v777cm) ([raw file](https://github.com/pmem/pmemstream/blob/0f4c6c27d30c7a647c287ea0538ff45826bd5e97/tests/api_c/region_iterator.c#L78)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you should now also add a test for calls like:

`pmemstream_region_iterator_new(NULL, proper_stream)`
and
`pmemstream_region_iterator_next(NULL, proper_region)`

and probably something similar for entry_iterator (if we don't have such tests yet)
</blockquote></details>

new tests will be added in sep. PR

**Review by karczex — APPROVED** [review]
> Reviewed 2 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/140)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/140#-:-MxnBDda8XCpljjBjHlR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)

**Review by KFilipek — APPROVED** [review]
:lgtm:
Tripple c-c-c-c-combo

> Reviewed 1 of 8 files at r2, 3 of 5 files at r3, 2 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/140#-:-MxnFZRi5wZutnGPX6ov:bq4vamp)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)

**Review by lukaszstolarczuk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/140)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)

**Pull request merged**
