### PR TITLE
Update compare bench runner

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/264)

### CODE REVIEW

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/264#-:-NAn68T78xUxgFBZPkos:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by KFilipek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/264)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`utils/docker/run-compare-bench.sh` line 32 at r1](https://reviewable.io/reviews/pmem/pmemstream/264#-NBBaSdC1y9OlzF0LuSX:-NBBaSdC1y9OlzF0LuSY:bw874yx) ([raw file](https://github.com/pmem/pmemstream/blob/cfab6ca852be445d3f11a186bf6daefa66892e44/utils/docker/run-compare-bench.sh#L32)):*
> ```Shell
> 	echo "Usage: $(basename ${1}) [-h|--help] [-q|--quiet] [-p|--pr] [-r|--ref] [--compare_repo] [--baseline_ref] [--baseline_repo]"
> 	echo "-h, --help       Print help and exit"
> 	echo "-q, --quiet      Hide some (rather redundant) output, to make it more readable"
> ```

`some` -> `informational`
`Some` suggest that random output will be hidden.



_Code quote:_
```Shell
some
```

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/264)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[`utils/docker/run-compare-bench.sh` line 32 at r1](https://reviewable.io/reviews/pmem/pmemstream/264#-NBBaSdC1y9OlzF0LuSX:-NBCGRHQ1C_3VJVte1FO:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cfab6ca852be445d3f11a186bf6daefa66892e44/utils/docker/run-compare-bench.sh#L32)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

`some` -> `informational`
`Some` suggest that random output will be hidden.
</blockquote></details>

Done.

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/264#-:-NBRoZoJ9ChOXw8LS89R:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
