### PR TITLE
Add tests for NULL stream/iterator

### PR DESCRIPTION
**Pull request by Karolina002**
in public/API functions

- [x] wait for https://github.com/pmem/pmemstream/pull/140

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/144)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/144)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @Karolina002 and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/144#-MxmicEg6CZxcMjEH9g1:-MxmicEg6CZxcMjEH9g2:buxpwp2) (no related file):*
please don't duplicate code from another PR (https://github.com/pmem/pmemstream/pull/140).

If you depend on that code you can easily start from that branch (or now, rebase to it) and just told us (in comment) which commits belong to the current change (and which are from mentioned PR).

---
___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/pmem/pmemstream/144#-Mxmjogv3Gh-U9sxmAml):*
if you want to break the first line in the commit message, you have to add an empty line between... but in this case you can easily fit the whole heading in the first line - it's below 72 chars.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/144)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @Karolina002 and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/144#-MxmicEg6CZxcMjEH9g1:-MxnIiTUCh_Y-P1QyC4a:b-fxidn1) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please don't duplicate code from another PR (https://github.com/pmem/pmemstream/pull/140).

If you depend on that code you can easily start from that branch (or now, rebase to it) and just told us (in comment) which commits belong to the current change (and which are from mentioned PR).
</blockquote></details>

we've merged that PR, so now just please rebase :)

---

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/144)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/pmem/pmemstream/144#-Mxmjogv3Gh-U9sxmAml):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if you want to break the first line in the commit message, you have to add an empty line between... but in this case you can easily fit the whole heading in the first line - it's below 72 chars.
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/144)* status: all files reviewed, 4 unresolved discussions (waiting on @Karolina002)

___
*[tests/api_c/append_entry.c, line 23 at r2](https://reviewable.io/reviews/pmem/pmemstream/144#-Mxspn4g4dPDydR9sfLH:-Mxspn4g4dPDydR9sfLI:bv3032f) ([raw file](https://github.com/pmem/pmemstream/blob/f02edf16f95451bc794781889d57d599565a78f7/tests/api_c/append_entry.c#L23)):*
> ```C
> 
> 	int ret;
> 	struct entry_data data = {.data = UINT16_MAX};
> ```

why `UINT16_`? (in all affected places)
___
*[tests/api_c/region_create.c, line 43 at r2](https://reviewable.io/reviews/pmem/pmemstream/144#-Mxt3L5e10JMHquQ1bcL:-Mxt3L5e10JMHquQ1bcM:bdkcfed) ([raw file](https://github.com/pmem/pmemstream/blob/f02edf16f95451bc794781889d57d599565a78f7/tests/api_c/region_create.c#L43)):*
> ```C
> 	ret = pmemstream_region_allocate(env.stream, TEST_DEFAULT_REGION_SIZE, &region);
> 	UT_ASSERTeq(ret, 0);
> ```

shouldn't we also check null stream in `pmemstream_region_allocate`?
___
*[tests/api_c/region_create.c, line 44 at r2](https://reviewable.io/reviews/pmem/pmemstream/144#-Mxt3RZoA6ws5hIi1hCa:-Mxt3RZoA6ws5hIi1hCb:b7ow47b) ([raw file](https://github.com/pmem/pmemstream/blob/f02edf16f95451bc794781889d57d599565a78f7/tests/api_c/region_create.c#L44)):*
> ```C
> 	UT_ASSERTeq(ret, 0);
> 
> 	UT_ASSERTeq(pmemstream_region_size(NULL, region), 0);
> ```

shouldn't this also return `-1`?
___
*[tests/api_c/region_iterator.c, line 56 at r2](https://reviewable.io/reviews/pmem/pmemstream/144#-Mxt5DohCK_n5UWxaTPA:-Mxt5DohCK_n5UWxaTPB:bbstetg) ([raw file](https://github.com/pmem/pmemstream/blob/f02edf16f95451bc794781889d57d599565a78f7/tests/api_c/region_iterator.c#L56)):*
> ```C
> 	UT_ASSERTeq(ret, -1);
> 
> 	ret = pmemstream_region_iterator_next(NULL, &region);
> ```

why 2 times?

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/144)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[tests/api_c/append_entry.c, line 23 at r2](https://reviewable.io/reviews/pmem/pmemstream/144#-Mxspn4g4dPDydR9sfLH:-My3ic-u8Z8HqBYW4-2V:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f02edf16f95451bc794781889d57d599565a78f7/tests/api_c/append_entry.c#L23)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why `UINT16_`? (in all affected places)
</blockquote></details>

Done.
___
*[tests/api_c/region_create.c, line 43 at r2](https://reviewable.io/reviews/pmem/pmemstream/144#-Mxt3L5e10JMHquQ1bcL:-My3ifTk42bJ2f0skb9V:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f02edf16f95451bc794781889d57d599565a78f7/tests/api_c/region_create.c#L43)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

shouldn't we also check null stream in `pmemstream_region_allocate`?
</blockquote></details>

Done.
___
*[tests/api_c/region_create.c, line 44 at r2](https://reviewable.io/reviews/pmem/pmemstream/144#-Mxt3RZoA6ws5hIi1hCa:-My3gGrQ8MhrZ1YX-EPl:bfmzs38) ([raw file](https://github.com/pmem/pmemstream/blob/f02edf16f95451bc794781889d57d599565a78f7/tests/api_c/region_create.c#L44)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

shouldn't this also return `-1`?
</blockquote></details>

Isn't size_t unsigned?
___
*[tests/api_c/region_iterator.c, line 56 at r2](https://reviewable.io/reviews/pmem/pmemstream/144#-Mxt5DohCK_n5UWxaTPA:-My3ih-B9RszJ-MWgE94:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f02edf16f95451bc794781889d57d599565a78f7/tests/api_c/region_iterator.c#L56)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why 2 times?
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/144)* status: all files reviewed, 1 unresolved discussion (waiting on @Karolina002)

___
*[src/iterator.c, line 92 at r3](https://reviewable.io/reviews/pmem/pmemstream/144#-My6Vir8CDuL0JN3Kx38:-My6Vir94iqxyanMgPY8:btqoqhr) ([raw file](https://github.com/pmem/pmemstream/blob/ed03d36daf8bac23e227eb51c27d58dafdbdff33/src/iterator.c#L92)):*
> ```C
> 				  struct pmemstream_region region)
> {
> 	if (!iterator) {
> ```

you could move this change into sep. commit
___
*[tests/api_c/region_create.c, line 44 at r2](https://reviewable.io/reviews/pmem/pmemstream/144#-Mxt3RZoA6ws5hIi1hCa:-My6Vtg87_sDryTg33ik:b-8fx2u7) ([raw file](https://github.com/pmem/pmemstream/blob/f02edf16f95451bc794781889d57d599565a78f7/tests/api_c/region_create.c#L44)):*
<details><summary><i>Previously, Karolina002 (Karolina Bober) wrote…</i></summary><blockquote>

Isn't size_t unsigned?
</blockquote></details>

:+1:

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/144)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[src/iterator.c, line 92 at r3](https://reviewable.io/reviews/pmem/pmemstream/144#-My6Vir8CDuL0JN3Kx38:-MyIigLtC8JW-qv4pxbU:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ed03d36daf8bac23e227eb51c27d58dafdbdff33/src/iterator.c#L92)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you could move this change into sep. commit
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/144#-:-MyLudnZ5LSJoTNCyaLO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Karolina002)

**Pull request merged**
