### PR TITLE
pmreorder region allocator test

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- [x] add commands generation

for this test to work I had to omit stores within "libpmem2" marker - these lots of stores appear due to memsetting region (with 0's) while allocating that region.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/164)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/164)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/common/random_helpers.hpp, line 32 at r2](https://reviewable.io/reviews/pmem/pmemstream/164#-N-7sX3tCnG_f02TX5RD:-N-7sX3u70QNLgsQVqiR:bdudvjx) ([raw file](https://github.com/pmem/pmemstream/blob/b88e4b3f61750e95432020794432d06c3a974b4e/tests/common/random_helpers.hpp#L32)):*
> ```cpp
> /* generates sequence of n commands out of 'commands' list */
> template <typename T>
> static inline std::vector<T> generate_commands(size_t n, std::initializer_list<T> commands)
> ```

initializer_list? vector would be more generic?
___
*[tests/integrity/multi_region_pmreorder.cpp, line 46 at r2](https://reviewable.io/reviews/pmem/pmemstream/164#-N-7t9h2D_dA7yg77eyI:-N-7t9h38oI9lw-Qyzvy:b-4vrlnh) ([raw file](https://github.com/pmem/pmemstream/blob/b88e4b3f61750e95432020794432d06c3a974b4e/tests/integrity/multi_region_pmreorder.cpp#L46)):*
> ```cpp
> 	}
> }
> ```

why not put it to the helpers also?
___
*[tests/integrity/multi_region_pmreorder.cpp, line 67 at r2](https://reviewable.io/reviews/pmem/pmemstream/164#-N-7tUGl9xoPYMrcbfq-:-N-7tUGl9xoPYMrcbfq0:b-ufnrge) ([raw file](https://github.com/pmem/pmemstream/blob/b88e4b3f61750e95432020794432d06c3a974b4e/tests/integrity/multi_region_pmreorder.cpp#L67)):*
> ```cpp
> 	do {
> 		struct pmemstream_region region;
> 		ret = pmemstream_region_iterator_next(riter.get(), &region);
> ```

How about trying to allocate/free some regions in check_consistency?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/164)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @igchor)

___
*[tests/common/random_helpers.hpp, line 32 at r2](https://reviewable.io/reviews/pmem/pmemstream/164#-N-7sX3tCnG_f02TX5RD:-N-7uduC0DHcbxAOXLPN:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/b88e4b3f61750e95432020794432d06c3a974b4e/tests/common/random_helpers.hpp#L32)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

initializer_list? vector would be more generic?
</blockquote></details>

Done.
___
*[tests/integrity/multi_region_pmreorder.cpp, line 46 at r2](https://reviewable.io/reviews/pmem/pmemstream/164#-N-7t9h2D_dA7yg77eyI:-N-7wFMQCzI8GB5w0Eao:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/b88e4b3f61750e95432020794432d06c3a974b4e/tests/integrity/multi_region_pmreorder.cpp#L46)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why not put it to the helpers also?
</blockquote></details>

Done.
___
*[tests/integrity/multi_region_pmreorder.cpp, line 67 at r2](https://reviewable.io/reviews/pmem/pmemstream/164#-N-7tUGl9xoPYMrcbfq-:-N-7wH1p8Kz1J3QlOsYC:bpru2qg) ([raw file](https://github.com/pmem/pmemstream/blob/b88e4b3f61750e95432020794432d06c3a974b4e/tests/integrity/multi_region_pmreorder.cpp#L67)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

How about trying to allocate/free some regions in check_consistency?
</blockquote></details>

hmm good idea, I think we may have caught some issue here. I've left this commented out for later debugging (by someone else :smile: )

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/164)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/common/random_helpers.hpp, line 24 at r4](https://reviewable.io/reviews/pmem/pmemstream/164#-N-8-hA2Dgqdimx2OqXe:-N-8-hA2Dgqdimx2OqXf:bu28rzy) ([raw file](https://github.com/pmem/pmemstream/blob/8be22d8b843c8e70279a3ce6d75fd29fc03c6bc6/tests/common/random_helpers.hpp#L24)):*
> ```cpp
> 	} else {
> 		seed = std::stoull(seed_env);
> 		std::cout << "Running with TEST_SEED=" << seed << std::endl;
> ```

lack of `<iostream>` header



_Code quote:_
```cpp
std::cout << "Running with TEST_SEED=" << seed << std::endl;
```
___
*[tests/integrity/multi_region_pmreorder.cpp, line 39 at r4](https://reviewable.io/reviews/pmem/pmemstream/164#-N-80Z6K--nk7IZWNskI:-N-80Z6K--nk7IZWNskJ:b-aq9c79) ([raw file](https://github.com/pmem/pmemstream/blob/8be22d8b843c8e70279a3ce6d75fd29fc03c6bc6/tests/integrity/multi_region_pmreorder.cpp#L39)):*
> ```cpp
> 
> 			size_t region_pos = rnd_generator() % regions.size();
> 			auto region = regions[region_pos];
> ```

dead code?



_Code quote:_
```cpp
			size_t region_pos = rnd_generator() % regions.size();
			auto region = regions[region_pos];
			int ret = pmemstream_region_free(stream.get(), region);
			UT_ASSERTeq(ret, 0);
			regions.erase(regions.begin() + static_cast<long>(region_pos));
```

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/164)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[tests/common/random_helpers.hpp, line 24 at r4](https://reviewable.io/reviews/pmem/pmemstream/164#-N-8-hA2Dgqdimx2OqXe:-N-838FT5zVrNZKj2N3W:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/8be22d8b843c8e70279a3ce6d75fd29fc03c6bc6/tests/common/random_helpers.hpp#L24)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

lack of `<iostream>` header
</blockquote></details>

Done.
___
*[tests/integrity/multi_region_pmreorder.cpp, line 39 at r4](https://reviewable.io/reviews/pmem/pmemstream/164#-N-80Z6K--nk7IZWNskI:-N-83IdW5tkIffogpUzN:bwagtsz) ([raw file](https://github.com/pmem/pmemstream/blob/8be22d8b843c8e70279a3ce6d75fd29fc03c6bc6/tests/integrity/multi_region_pmreorder.cpp#L39)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

dead code?
</blockquote></details>

lol, yes. Please read the comment above. To be updated with `region_free` fix.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/164#-:-N-84lVK5rdeN-HUvdoQ:bnfp4nl)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @KFilipek)

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 1 of 8 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/164#-:-N-8K3j13ZzSZgGGoYfQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
