### PR TITLE
Fix race in region_runtime_initialize

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/94)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/94)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[src/region.h, line 30 at r1](https://reviewable.io/reviews/pmem/pmemstream/94#-MuR1GYf2o2Q4I1_5KXz:-MuUwVvCA0CGJaCC2H3K:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/4f8764574d75dc884e5ad1f229f972c2d5b9218a/src/region.h#L30)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

all function**s**
</blockquote></details>

Done.
___
*[src/region.h, line 51 at r1](https://reviewable.io/reviews/pmem/pmemstream/94#-MuR1YSxB3vWzqyE5uUS:-MuUwVO--6UbQPFr91Su:b-rb6td) ([raw file](https://github.com/pmem/pmemstream/blob/4f8764574d75dc884e5ad1f229f972c2d5b9218a/src/region.h#L51)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Return**s**
</blockquote></details>

Done. kind of ;d

**Review by karczex — COMMENTED** [review]
> Reviewed 2 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/94)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

**Comment by karczex** [comment]
___
*[src/region.c, line 217 at r6](https://reviewable.io/reviews/pmem/pmemstream/94#-Muo_Ov79Ksf2WVuMyR3:-Muo_Ov79Ksf2WVuMyR4:bbl7rrp) ([raw file](https://github.com/pmem/pmemstream/blob/3da55f41276ad60affbc9f3c0ed1a9c61562c15d/src/region.c#L217)):*
> ```C
> 	assert(pthread_mutex_trylock(&region_runtime->region_lock) != 0);
> 
> 	struct pmemstream_entry_iterator iter;
> ```

nit: 
In a subtle way, naming this variable `iter` is little confusing. iterator would be much better here. 

When you look in function `entry_iterator_initialize()` variable named `iter` represents different object than `iter` in `region_iterate_and_initialize_dirty()`

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 7 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 13 of 13 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/94)* status: 15 of 16 files reviewed, 5 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[src/region.c, line 231 at r6](https://reviewable.io/reviews/pmem/pmemstream/94#-MuokCju6Ahw9tRuFVND:-MuokCjv-qPeJLqdkMtZ:bsyo465) ([raw file](https://github.com/pmem/pmemstream/blob/3da55f41276ad60affbc9f3c0ed1a9c61562c15d/src/region.c#L231)):*
> ```C
> }
> 
> static void region_runtime_clear_from_tail(struct pmemstream *stream, struct pmemstream_region region,
> ```

now we don't have 'tail' offset param, so perhaps rename to `region_runtime_clear_tail`
___
*[src/region.c, line 277 at r6](https://reviewable.io/reviews/pmem/pmemstream/94#-Muotshw4PkE1x8KWG-F:-Muotshw4PkE1x8KWG-G:boigtg6) ([raw file](https://github.com/pmem/pmemstream/blob/3da55f41276ad60affbc9f3c0ed1a9c61562c15d/src/region.c#L277)):*
> ```C
> 	pthread_mutex_unlock(&region_runtime->region_lock);
> 
> 	assert(region_runtime_get_state(region_runtime) == REGION_RUNTIME_STATE_CLEAR);
> ```

these asserts happen after the lock... so potentially they may differ...?
___
*[src/region.c, line 185 at r7](https://reviewable.io/reviews/pmem/pmemstream/94#-MupA88DBPpZb4lOqMX5:-MupA88DBPpZb4lOqMX6:b-pz8dy1) ([raw file](https://github.com/pmem/pmemstream/blob/8425b1dcd72f0d8d9cdb7aefbc79b881d43e3d64/src/region.c#L185)):*
> ```C
> 					    struct pmemstream_entry tail)
> {
> 	/* invariant, region_initialization should always happend under a lock. */
> ```

happen
___
*[tests/unittest/region_initialize.cpp, line 46 at r6](https://reviewable.io/reviews/pmem/pmemstream/94#-Muou9OfCGhnas4JuM3i:-Muou9OfCGhnas4JuM3j:b8ekdd8) ([raw file](https://github.com/pmem/pmemstream/blob/3da55f41276ad60affbc9f3c0ed1a9c61562c15d/tests/unittest/region_initialize.cpp#L46)):*
> ```cpp
> 					syncthreads();
> 
> 					region_runtime_initialize_dirty_locked(region_runtime, entry);
> ```

this test will work quite similarly with _clear_locked, isn't it?
___
*[tests/unittest/region_runtime_initialize.cpp, line 49 at r6](https://reviewable.io/reviews/pmem/pmemstream/94#-Mup9FQYE1qVxgOGn6Dy:-Mup9FQYE1qVxgOGn6Dz:bqd2nfc) ([raw file](https://github.com/pmem/pmemstream/blob/3da55f41276ad60affbc9f3c0ed1a9c61562c15d/tests/unittest/region_runtime_initialize.cpp#L49)):*
> ```cpp
> 		ret += rc::check("verify that pmemstream_region_runtime_initialize clears region after last entry",
> 				 [&](const std::vector<std::string> &data, const std::string &garbage) {
> 					 RC_PRE(data.size() > 0);
> ```

can't we test clearing garbage with no entries? We'd simulate e.g. garbage produced by the very first append being torn(?)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/94)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor)

___
*[src/region.h, line 25 at r8](https://reviewable.io/reviews/pmem/pmemstream/94#-Mupsl6D96iz8hgmsV-b:-Mupsl6D96iz8hgmsV-c:b-gczh3p) ([raw file](https://github.com/pmem/pmemstream/blob/a85973a087f809343665ade6fa73007ec73b9b3d/src/region.h#L25)):*
> ```objc
>  */
> 
> enum region_runtime_state {
> ```

pls describe it's a one-way street :wink: 
___
*[src/region.c, line 231 at r6](https://reviewable.io/reviews/pmem/pmemstream/94#-MuokCju6Ahw9tRuFVND:-Muq0Da44x0uh4UqvA62:b-93jarj) ([raw file](https://github.com/pmem/pmemstream/blob/3da55f41276ad60affbc9f3c0ed1a9c61562c15d/src/region.c#L231)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I actually prefer it this way - it still does the same thing - loads tail and clears data **from** that tail to the end of region. The name of the argument might not been the best - it was only output parameter.
</blockquote></details>

yeah, actually I agree now, it makes more sense.
___
*[src/region.c, line 165 at r8](https://reviewable.io/reviews/pmem/pmemstream/94#-Muq-UOK3zg-CdxLnH5I:-Muq-UOK3zg-CdxLnH5J:b-nolw7u) ([raw file](https://github.com/pmem/pmemstream/blob/a85973a087f809343665ade6fa73007ec73b9b3d/src/region.c#L165)):*
> ```C
> }
> 
> enum region_runtime_state region_runtime_get_state(const struct pmemstream_region_runtime *region_runtime)
> ```

_get_state_acquire (?) :wink: 
___
*[src/region.c, line 214 at r8](https://reviewable.io/reviews/pmem/pmemstream/94#-Muq-ko7DZzpfq3ViEMN:-Muq-ko7DZzpfq3ViEMO:bfoorj1) ([raw file](https://github.com/pmem/pmemstream/blob/a85973a087f809343665ade6fa73007ec73b9b3d/src/region.c#L214)):*
> ```C
> 					       struct pmemstream_region_runtime *region_runtime)
> {
> 	/* invariant, region_initialization should always happend under a lock. */
> ```

`happen` as well (I missed that one, previously)
___
*[src/region.c, line 219 at r8](https://reviewable.io/reviews/pmem/pmemstream/94#-Muq-v6T1i2AsOQDwpE6:-Muq-v6UBrLeYQdfUHPE:b-x7xvko) ([raw file](https://github.com/pmem/pmemstream/blob/a85973a087f809343665ade6fa73007ec73b9b3d/src/region.c#L219)):*
> ```C
> 	struct pmemstream_entry_iterator iterator;
> 	int ret = entry_iterator_initialize(&iterator, stream, region,
> 		&region_runtime_initialize_dirty /* do not use _locked_ version - this function is already executing under a region_lock. */);
> ```

perhaps move this comment above the call, now it looks a bit weird
___
*[src/region.c, line 260 at r8](https://reviewable.io/reviews/pmem/pmemstream/94#-MuprQoZAJa_6EgowoJ6:-MuprQoZAJa_6EgowoJ7:b-1gj870) ([raw file](https://github.com/pmem/pmemstream/blob/a85973a087f809343665ade6fa73007ec73b9b3d/src/region.c#L260)):*
> ```C
> 	if (region_runtime_get_state(region_runtime) == REGION_RUNTIME_STATE_CLEAR) {
> 		/* Nothing to do . */
> 		return false;
> ```

return int
___
*[tests/unittest/region_initialize.cpp, line 46 at r6](https://reviewable.io/reviews/pmem/pmemstream/94#-Muou9OfCGhnas4JuM3i:-Muq0SHJA03N6ck1_9pi:b-vaguzr) ([raw file](https://github.com/pmem/pmemstream/blob/3da55f41276ad60affbc9f3c0ed1a9c61562c15d/tests/unittest/region_initialize.cpp#L46)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Not quite, the clear version needs stream as parameter which makes it much more difficult to unittest. I'll think about how to test it but probably on separate PR.

It might require changing signature of the clear version a bit (adding some abstraction layer).
</blockquote></details>

perhaps make it an XXX comment then, pls

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/94)* status: 12 of 16 files reviewed, 4 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[src/region.h, line 25 at r8](https://reviewable.io/reviews/pmem/pmemstream/94#-Mupsl6D96iz8hgmsV-b:-Muq9WlR1J6kyBSru2yI:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/a85973a087f809343665ade6fa73007ec73b9b3d/src/region.h#L25)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls describe it's a one-way street :wink: 
</blockquote></details>

Done.
___
*[src/region.c, line 214 at r8](https://reviewable.io/reviews/pmem/pmemstream/94#-Muq-ko7DZzpfq3ViEMN:-Muq9hDK-jB89gXdeGQZ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/a85973a087f809343665ade6fa73007ec73b9b3d/src/region.c#L214)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`happen` as well (I missed that one, previously)
</blockquote></details>

Done.
___
*[src/region.c, line 219 at r8](https://reviewable.io/reviews/pmem/pmemstream/94#-Muq-v6T1i2AsOQDwpE6:-Muq9mAV9Te5_lRPD51W:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/a85973a087f809343665ade6fa73007ec73b9b3d/src/region.c#L219)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps move this comment above the call, now it looks a bit weird
</blockquote></details>

Done.
___
*[src/region.c, line 260 at r8](https://reviewable.io/reviews/pmem/pmemstream/94#-MuprQoZAJa_6EgowoJ6:-Muq9pXHCYulCZ7eJyRB:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/a85973a087f809343665ade6fa73007ec73b9b3d/src/region.c#L260)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

return int
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/94)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[src/region.c, line 219 at r9](https://reviewable.io/reviews/pmem/pmemstream/94#-MuqSReiD0o3vkqwgICx:-MuqSReiD0o3vkqwgICy:b4n3xt4) ([raw file](https://github.com/pmem/pmemstream/blob/ec68800d5f4f199e7fc964a1d8df77bf6a0b3158/src/region.c#L219)):*
> ```C
> 	struct pmemstream_entry_iterator iterator;
> 
> 	/* do not use region_runtime_initialize_dirty - this function is already executing under a region_lock. */
> ```

did you mean `region_runtime_initialize_dirty_locked`

and perhaps `this function` -> `current function` ("this" may be misleading)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/94#-:-MutaCi40YrBU-Tx0V7M:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/94#-:-Mutdush1qXqWExkzS63:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
