### PR TITLE
Entry iterator api refactor

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/198)

### CODE REVIEW

**Comment by karczex** [comment]
*[`tests/unittest/concurrent_iterate_with_append.cpp` line 32 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34WPyD-Gt-NWpPE1CR:-N34WPyE089nSABZRHx0:b9dohb5) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/tests/unittest/concurrent_iterate_with_append.cpp#L32)):*
> ```cpp
> 	/* Loop until all entries are found. */
> 	while (result.size() < data.size() + extra_data.size()) {
> 		if (pmemstream_entry_iterator_is_valid(eiter.get()) == 0) {
> ```

For some reason, iterator sometimes finds old entries when `pmemstream_is_valid()` is called concurrently with `pmemstream_append()`

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/198)* status: 3 of 13 files reviewed, 10 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[`src/iterator.c` line 172 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34fHas39Nj9xPq9Qp0:-N34fHas39Nj9xPq9Qp1:bzbkqzm) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/src/iterator.c#L172)):*
> ```C
> 
> 	if (check_entry_and_maybe_recover_region(iterator)) {
> 		pmemstream_entry_iterator_advance(iterator);
> ```

I wonder:
when region_iter_next is called at the last region we move into INVALID region
here, if we call it on the last entry (or 1 after committed) we do nothing or recover...?
___
*[`src/iterator.c` line 185 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34dCLx58DRMzSC-X97:-N34dCLx58DRMzSC-X98:botled1) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/src/iterator.c#L185)):*
> ```C
> 
> 	tmp_iterator.offset = first_entry_offset(iterator->region);
> 	if (!check_entry_consistency(&tmp_iterator)) {
> ```

I think `seek_*` function should not be calling any validation - this is why we have `is_valid` function
___
*[`src/libpmemstream.map` line 16 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34gB1zD1T3RQQvyq-x:-N34gB1zD1T3RQQvyq-y:b-cnad9k) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/src/libpmemstream.map#L16)):*
> ```
> 		pmemstream_entry_iterator_delete;
> 		pmemstream_entry_iterator_new;
> 		pmemstream_entry_iterator_is_valid;
> ```

pls sort A-Z :stuck_out_tongue_winking_eye: 
___
*[`src/region.c` line 271 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34gsPY95UtydpnWn7l:-N34gsPY95UtydpnWn7m:b-sn308) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/src/region.c#L271)):*
> ```C
> 	}
> 
> 	iterator.offset = first_entry_offset(region);
> ```

use `seek_first` instead..?
___
*[`tests/api_c/entry_iterator.c` line 37 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34mW4BDtv5SfX-V9Ov:-N34mW4CB7i43NY0Eazk:bjh184s) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/tests/api_c/entry_iterator.c#L37)):*
> ```C
> 	ret = pmemstream_entry_iterator_is_valid(eiter);
> 	UT_ASSERTeq(ret, -1);
> ```

pls test here next and get as well
___
*[`tests/api_c/entry_iterator.c` line 103 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34oNI14qafhWnvyPlF:-N34oNI24LX9K-iPzq_z:b2ni3ap) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/tests/api_c/entry_iterator.c#L103)):*
> ```C
> 
> 	ret = pmemstream_entry_iterator_is_valid(NULL);
> ```

get
___
*[`tests/common/stream_helpers.hpp` line 376 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34pNfM2JIDRiPzLWZp:-N34pNfM2JIDRiPzLWZq:b-hqurnh) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/tests/common/stream_helpers.hpp#L376)):*
> ```cpp
> 
> 		struct pmemstream_entry last_entry = {0};
> 		struct pmemstream_entry tmp_entry;
> ```

you can drop this variable
___
*[`tests/common/stream_helpers.hpp` line 386 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34pd-16xgCQgof_p1N:-N34pd-16xgCQgof_p1O:bazedq9) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/tests/common/stream_helpers.hpp#L386)):*
> ```cpp
> 			throw std::runtime_error("No elements in this region.");
> 
> 		UT_ASSERTeq(last_entry.offset, tmp_entry.offset);
> ```

redundant check...?
___
*[`tests/unittest/concurrent_iterate_with_append.cpp` line 36 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34qilG3S0Qdbe2GM1l:-N34qilG3S0Qdbe2GM1m:badmi1w) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/tests/unittest/concurrent_iterate_with_append.cpp#L36)):*
> ```cpp
> 			result.emplace_back(stream.sut.get_entry(entry));
> 		}
> 		pmemstream_entry_iterator_next(eiter.get());
> ```

actually, what's the point of calling next if is_valid return -1?

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/198)* status: 4 of 13 files reviewed, 14 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[`src/iterator.c` line 137 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N3IeQfsETvP2GASr3CK:-N3IeQfsETvP2GASr3CL:blmd127) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/src/iterator.c#L137)):*
> ```C
> 		return -1;
> 	}
> 	if (check_entry_consistency(iterator)) {
> ```

I would suggest changing this check to comparing entry offset with committed_offset. I will perform better (no read from PMEM) and avoid potential races which can happen during append and check_consistency. However, to do this, you also need to change order of recovery as I mentioned in pmemstream_entry_iterator_next comment.
___
*[`src/iterator.c` line 171 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N3IdpL01akg4OZ6_dpX:-N3IdpL01akg4OZ6_dpY:b-v931hl) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/src/iterator.c#L171)):*
> ```C
> 	}
> 
> 	if (check_entry_and_maybe_recover_region(iterator)) {
> ```

I would suggest chaning the order of those functions: call check_entry_and_maybe_recover_region AFTER advancing the iterator. I would also add check_entry_and_maybe_recover_region  to seek_first function. This way, the entry will always be recovered when user calls get or is_valid. Because of this, you can also change implementation of is_valid to just comparing entry offset with committed_offset.
___
*[`src/iterator.c` line 185 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34dCLx58DRMzSC-X97:-N3Ibuzg97TzaPRgMeye:b-fgzxpg) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/src/iterator.c#L185)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think `seek_*` function should not be calling any validation - this is why we have `is_valid` function
</blockquote></details>

As I mentioned above, I think it might be good to call recovery in seek and next.
___
*[`src/region.c` line 251 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N3IcUAw3oQrNbEeWTAY:-N3IcUAw3oQrNbEeWTAZ:b-w0g1ee) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/src/region.c#L251)):*
> ```C
> }
> 
> uint64_t first_entry_offset(struct pmemstream_region region)
> ```

please add prefix to this function, as in other in this file (or make this function static inside iterator.c)
___
*[`src/region.c` line 271 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34gsPY95UtydpnWn7l:-N3IceuQE3Bh2Q1YARiV:b2ngthx) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/src/region.c#L271)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

use `seek_first` instead..?
</blockquote></details>

+1 
___
*[`src/include/libpmemstream.h` line 192 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N3IdA4O2u6TF0mxl0Oo:-N3IdA4O2u6TF0mxl0Op:b-vbzy0n) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/src/include/libpmemstream.h#L192)):*
> ```objc
> int pmemstream_entry_iterator_is_valid(struct pmemstream_entry_iterator *iterator);
> 
> // if this function succeeds, entry points to a valid element in the stream, otherwise, it points to a memory
> ```

Please use `/*` comments.
___
*[`tests/unittest/concurrent_iterate_with_append.cpp` line 32 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34WPyD-Gt-NWpPE1CR:-N3Ien-f8DwzgUrlTgXA:b6oqdml) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/tests/unittest/concurrent_iterate_with_append.cpp#L32)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

For some reason, iterator sometimes finds old entries when `pmemstream_is_valid()` is called concurrently with `pmemstream_append()` 
</blockquote></details>

I belive this is race in check_consistency, please see if my idea with changing order of recovery in next() solves the issue.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/198)* status: 0 of 15 files reviewed, 13 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[`src/iterator.c` line 171 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N3IdpL01akg4OZ6_dpX:-N3ZMqOa8k3K2L9caWz7:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/src/iterator.c#L171)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I would suggest chaning the order of those functions: call check_entry_and_maybe_recover_region AFTER advancing the iterator. I would also add check_entry_and_maybe_recover_region  to seek_first function. This way, the entry will always be recovered when user calls get or is_valid. Because of this, you can also change implementation of is_valid to just comparing entry offset with committed_offset.
</blockquote></details>

Done.
___
*[`src/iterator.c` line 185 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34dCLx58DRMzSC-X97:-N3ZN5u44Hr_-zdRVMUv:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/src/iterator.c#L185)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

As I mentioned above, I think it might be good to call recovery in seek and next.
</blockquote></details>

Done.
___
*[`src/libpmemstream.map` line 16 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34gB1zD1T3RQQvyq-x:-N3ZNa1544w_Ts4jiVnW:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/src/libpmemstream.map#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls sort A-Z :stuck_out_tongue_winking_eye: 
</blockquote></details>

Done.
___
*[`src/region.c` line 251 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N3IcUAw3oQrNbEeWTAY:-N3ZQD_x0yLOwVinJkCI:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/src/region.c#L251)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

please add prefix to this function, as in other in this file (or make this function static inside iterator.c)
</blockquote></details>

Done.
___
*[`src/region.c` line 271 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34gsPY95UtydpnWn7l:-N3dFzC42oyaKbiXhppk:buzveu1) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/src/region.c#L271)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

+1 
</blockquote></details>

Seek first return PMEMSTREAM_INVALID_OFFSET (for consistency with region_iterator) when entry is not valid, so region_first_entry_offset have to be called directly. 
___
*[`src/include/libpmemstream.h` line 192 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N3IdA4O2u6TF0mxl0Oo:-N3ZO0YR3Sbv-odyLfeS:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/src/include/libpmemstream.h#L192)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please use `/*` comments.
</blockquote></details>

Done.
___
*[`tests/api_c/entry_iterator.c` line 37 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34mW4BDtv5SfX-V9Ov:-N3dGVKvA_Nxg9z5h-qa:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/tests/api_c/entry_iterator.c#L37)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls test here next and get as well
</blockquote></details>

Done.
___
*[`tests/api_c/entry_iterator.c` line 103 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34oNI14qafhWnvyPlF:-N3ZSQlh9VcnOvrCHAiS:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/tests/api_c/entry_iterator.c#L103)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

get
</blockquote></details>

Done.
___
*[`tests/common/stream_helpers.hpp` line 376 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34pNfM2JIDRiPzLWZp:-N3ZOMbK5uGDfOsQ10Ww:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/tests/common/stream_helpers.hpp#L376)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can drop this variable
</blockquote></details>

Done.
___
*[`tests/common/stream_helpers.hpp` line 386 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34pd-16xgCQgof_p1N:-N3ZON8q66RIw0dZJWAq:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/tests/common/stream_helpers.hpp#L386)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant check...?
</blockquote></details>

Done.
___
*[`tests/unittest/concurrent_iterate_with_append.cpp` line 36 at r1](https://reviewable.io/reviews/pmem/pmemstream/198#-N34qilG3S0Qdbe2GM1l:-N3ZOeQWB1oUmBbUlVX_:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/0732f993c9171d9d79b2164190db2a9728540402/tests/unittest/concurrent_iterate_with_append.cpp#L36)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

actually, what's the point of calling next if is_valid return -1?
</blockquote></details>

Done.

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 1 of 13 files at r1, 11 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/198)* status: 12 of 15 files reviewed, 12 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[`src/iterator.c` line 170 at r3](https://reviewable.io/reviews/pmem/pmemstream/198#-N3dOfvH2kTJFoKyc3L3:-N3dOfvH2kTJFoKyc3L4:b-iiztch) ([raw file](https://github.com/pmem/pmemstream/blob/43ef17f79dfffd856af4e1f2ec80da2dce2525cc/src/iterator.c#L170)):*
> ```C
> 	}
> 
> 	if (iterator->offset == PMEMSTREAM_INVALID_OFFSET) {
> ```

maybe replace this with checking pmemstream_entry_iterator_is_valid? Or assert(pmemstream_entry_iterator_is_valid) if entry being valid is our precondition?
___
*[`src/iterator.c` line 187 at r3](https://reviewable.io/reviews/pmem/pmemstream/198#-N3dP-P10_y8RUzd8eS0:-N3dP-P10_y8RUzd8eS1:b-iiztch) ([raw file](https://github.com/pmem/pmemstream/blob/43ef17f79dfffd856af4e1f2ec80da2dce2525cc/src/iterator.c#L187)):*
> ```C
> void pmemstream_entry_iterator_seek_first(struct pmemstream_entry_iterator *iterator)
> {
> 	if (!iterator) {
> ```

maybe replace this with checking pmemstream_entry_iterator_is_valid? Or assert(pmemstream_entry_iterator_is_valid) if entry being valid is our precondition?
___
*[`src/iterator.c` line 203 at r3](https://reviewable.io/reviews/pmem/pmemstream/198#-N3dPE-O0dIUcnNDGml7:-N3dPE-O0dIUcnNDGml8:b-iiztch) ([raw file](https://github.com/pmem/pmemstream/blob/43ef17f79dfffd856af4e1f2ec80da2dce2525cc/src/iterator.c#L203)):*
> ```C
> {
> 	struct pmemstream_entry entry;
> 	if (!iterator) {
> ```

maybe replace this with checking pmemstream_entry_iterator_is_valid? Or assert(pmemstream_entry_iterator_is_valid) if entry being valid is our precondition?
___
*[`src/include/libpmemstream.h` line 205 at r3](https://reviewable.io/reviews/pmem/pmemstream/198#-N3dP_8OEV6FqSOYYsDM:-N3dP_8OEV6FqSOYYsDN:b-xzn48l) ([raw file](https://github.com/pmem/pmemstream/blob/43ef17f79dfffd856af4e1f2ec80da2dce2525cc/src/include/libpmemstream.h#L205)):*
> ```objc
>  *
>  * Moves to next entry if possible.
>  */
> ```

Please add preconditions

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/198)* status: 11 of 15 files reviewed, 10 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[`src/iterator.c` line 187 at r3](https://reviewable.io/reviews/pmem/pmemstream/198#-N3dP-P10_y8RUzd8eS0:-N3dS_fx9CQunQa1ePDd:b-l7j40h) ([raw file](https://github.com/pmem/pmemstream/blob/43ef17f79dfffd856af4e1f2ec80da2dce2525cc/src/iterator.c#L187)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

maybe replace this with checking pmemstream_entry_iterator_is_valid? Or assert(pmemstream_entry_iterator_is_valid) if entry being valid is our precondition?
</blockquote></details>

New iterator returned by `pmemstream_entry_iterator_new()` is invalid until `seek_first()` succeed.   
___
*[`src/include/libpmemstream.h` line 205 at r3](https://reviewable.io/reviews/pmem/pmemstream/198#-N3dP_8OEV6FqSOYYsDM:-N3dWn-95TG4PloMEzGN:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/43ef17f79dfffd856af4e1f2ec80da2dce2525cc/src/include/libpmemstream.h#L205)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please add preconditions
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/198)* status: 11 of 15 files reviewed, 8 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[`src/iterator.c` line 187 at r3](https://reviewable.io/reviews/pmem/pmemstream/198#-N3dP-P10_y8RUzd8eS0:-N3d_6il9sB8MH7nTymX:b-1wsq91) ([raw file](https://github.com/pmem/pmemstream/blob/43ef17f79dfffd856af4e1f2ec80da2dce2525cc/src/iterator.c#L187)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

New iterator returned by `pmemstream_entry_iterator_new()` is invalid until `seek_first()` succeed.   
</blockquote></details>

Right. How about nex() and get()?

**Review by igchor — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/198#-:-N3xLIgjB9woSOpxETFZ:bnfp4nl)* status: 10 of 15 files reviewed, 8 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 13 files at r1, 8 of 14 files at r2, 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/198)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex)

___
*[`src/span.c` line 69 at r7](https://reviewable.io/reviews/pmem/pmemstream/198#-N3xgv9p9f5phAwp9TAr:-N3xgv9p9f5phAwp9TAs:b-yhk7ne) ([raw file](https://github.com/pmem/pmemstream/blob/f3d6c08799f4c84d47458c5c027dff585f0dde3c/src/span.c#L69)):*
> ```C
> 
> 	__atomic_store_n(&dst->timestamp, entry.timestamp, __ATOMIC_RELAXED);
> 	__atomic_store_n(&dst->span_base.size_and_type, entry.span_base.size_and_type, __ATOMIC_RELAXED);
> ```

why did you switch the order of these 2 lines?
___
*[`src/include/libpmemstream.h` line 205 at r7](https://reviewable.io/reviews/pmem/pmemstream/198#-N3xboIp2lF448QmrD0E:-N3xboIp2lF448QmrD0F:b-15qlyu) ([raw file](https://github.com/pmem/pmemstream/blob/f3d6c08799f4c84d47458c5c027dff585f0dde3c/src/include/libpmemstream.h#L205)):*
> ```objc
> int pmemstream_entry_iterator_is_valid(struct pmemstream_entry_iterator *iterator);
> 
> /* Moves iterator to next region.
> ```

region -> entry
___
*[`src/include/libpmemstream.h` line 229 at r7](https://reviewable.io/reviews/pmem/pmemstream/198#-N3xblJUBSusvqyQTmXN:-N3xblJUBSusvqyQTmXO:b-15qlyu) ([raw file](https://github.com/pmem/pmemstream/blob/f3d6c08799f4c84d47458c5c027dff585f0dde3c/src/include/libpmemstream.h#L229)):*
> ```objc
> struct pmemstream_entry pmemstream_entry_iterator_get(struct pmemstream_entry_iterator *iterator);
> 
> /* Release region iterator resources. */
> ```

region -> entry
___
*[`tests/unittest/concurrent_iterate_with_append.cpp` line 28 at r7](https://reviewable.io/reviews/pmem/pmemstream/198#-N3xcL_vBWhAxkomCUm1:-N3xcL_vBWhAxkomCUm2:b7enfly) ([raw file](https://github.com/pmem/pmemstream/blob/f3d6c08799f4c84d47458c5c027dff585f0dde3c/tests/unittest/concurrent_iterate_with_append.cpp#L28)):*
> ```cpp
> 	auto eiter = stream.sut.entry_iterator(region);
> 
> 	while (pmemstream_entry_iterator_is_valid(eiter.get()) != 0)
> ```

why do we have this `while` loop?

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/198)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[`tests/unittest/concurrent_iterate_with_append.cpp` line 28 at r7](https://reviewable.io/reviews/pmem/pmemstream/198#-N3xcL_vBWhAxkomCUm1:-N3xhvig2SNsCofAEUfZ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/f3d6c08799f4c84d47458c5c027dff585f0dde3c/tests/unittest/concurrent_iterate_with_append.cpp#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why do we have this `while` loop?
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/198#-:-N3xjZJR7GYXy44YrRR9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
