### PR TITLE
Enable docs

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/11)

### CODE REVIEW

**Review by karczex — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/11)* status: 4 of 10 files reviewed, 2 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[INSTALL.md, line 19 at r1](https://reviewable.io/reviews/pmem/pmemstream/11#-MpGKeac5RKJCacH9lud:-MpGKead-67MXFDvQWdl:b-zhzzz1) ([raw file](https://github.com/pmem/pmemstream/blob/944358c895ab72592d8878cc16276964a44c2c90/INSTALL.md#L19)):*
> ```Markdown
>     - [CMake](http://www.cmake.org) >= 3.16
> * **libpmem2**, which is part of [PMDK](https://github.com/pmem/pmdk) - Persistent Memory Development Kit 1.10
> * Used only for **testing**:
> ```

C++ compiler for tests.
___
*[doc/libpmemstream.7.md, line 15 at r1](https://reviewable.io/reviews/pmem/pmemstream/11#-MpGL1_S4lFmFZWhBR_b:-MpGL1_T7a-zJQeRFror:brrrqmj) ([raw file](https://github.com/pmem/pmemstream/blob/944358c895ab72592d8878cc16276964a44c2c90/doc/libpmemstream.7.md#L15)):*
> ```Markdown
> [comment]: <> (libpmemstream.7 -- man page for libpmemstream API)
> 
> [NAME](#name)<br />
> ```

Are those html tags really needed?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/11)* status: 4 of 10 files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[INSTALL.md, line 19 at r1](https://reviewable.io/reviews/pmem/pmemstream/11#-MpGKeac5RKJCacH9lud:-MpGYvPy5_4tEWlgFOUc:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/944358c895ab72592d8878cc16276964a44c2c90/INSTALL.md#L19)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

C++ compiler for tests.
</blockquote></details>

Done.
___
*[doc/libpmemstream.7.md, line 15 at r1](https://reviewable.io/reviews/pmem/pmemstream/11#-MpGL1_S4lFmFZWhBR_b:-MpGYwSm8Dcb0pyqwgJb:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/944358c895ab72592d8878cc16276964a44c2c90/doc/libpmemstream.7.md#L15)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Are those html tags really needed?
</blockquote></details>

Done.

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/11#-:-MpH4nse2mqOHyXvo--c:bnfp4nl)* status: 4 of 10 files reviewed, all discussions resolved (waiting on @karczex)

**Review by KFilipek — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
