### PR TITLE
More tests

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/237)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/237)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[`tests/api_c/async.c` line 16 at r1](https://reviewable.io/reviews/pmem/pmemstream/237#-N6DVsnm1rv1s5w9alVX:-N6DVsnn7mtVXO6XPdvc:b-r7rmll) ([raw file](https://github.com/pmem/pmemstream/blob/ca45531cf3dc4e3c2ed1459334aa1bceb83e4ddc/tests/api_c/async.c#L16)):*
> ```C
> 		UT_FATAL("usage: %s file-name", argv[0]);
> 	}
> ```

empty?
___
*[`tests/api_c/entry_iterator.c` line 172 at r1](https://reviewable.io/reviews/pmem/pmemstream/237#-N6DWSAv1wt1DgYdPIlE:-N6DWSAv1wt1DgYdPIlF:b-oh6q77) ([raw file](https://github.com/pmem/pmemstream/blob/ca45531cf3dc4e3c2ed1459334aa1bceb83e4ddc/tests/api_c/entry_iterator.c#L172)):*
> ```C
> 
> 	/*
> 	 * XXX: shouldn't this test also work if this re-allocation didn't happen?
> ```

Yes, we should probably extend `pmemstream_entry_iterator_offset_is_inside_region` to check if region is allocated and use this function in pmemstream_entry_iterator_is_valid
___
*[`tests/common/rapidcheck_helpers.hpp` line 79 at r1](https://reviewable.io/reviews/pmem/pmemstream/237#-N6DWsK00XobHLABtKf8:-N6DWsK00XobHLABtKf9:b-zggd7z) ([raw file](https://github.com/pmem/pmemstream/blob/ca45531cf3dc4e3c2ed1459334aa1bceb83e4ddc/tests/common/rapidcheck_helpers.hpp#L79)):*
> ```cpp
> 		}
> 
> 		UT_ASSERTeq(s.sut.persisted_timestamp(), total_entries_count);
> ```

How about calling timestamp_validate method here as well?
___
*[`tests/unittest/append.cpp` line 39 at r1](https://reviewable.io/reviews/pmem/pmemstream/237#-N6DWwBv6HP6fjRZUZfO:-N6DWwBwEGuKfmsBjcit:b-k9go1m) ([raw file](https://github.com/pmem/pmemstream/blob/ca45531cf3dc4e3c2ed1459334aa1bceb83e4ddc/tests/unittest/append.cpp#L39)):*
> ```cpp
> 
> 					 auto total_entries_count = data.size() + extra_data.size();
> 					 UT_ASSERTeq(total_entries_count, stream.sut.persisted_timestamp());
> ```

How about calling timestamp_validate method here as well?

Or perhaps, we should check it in stream dtor?

**Comment by lukaszstolarczuk** [comment]
> > Reviewed 10 of 11 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/237)_ status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)
> 
> _[`tests/api_c/async.c` line 16 at r1](https://reviewable.io/reviews/pmem/pmemstream/237#-N6DVsnm1rv1s5w9alVX:-N6DVsnn7mtVXO6XPdvc:b-r7rmll) ([raw file](https://github.com/pmem/pmemstream/blob/ca45531cf3dc4e3c2ed1459334aa1bceb83e4ddc/tests/api_c/async.c#L16)):_
> 
> > ```c
> > 		UT_FATAL("usage: %s file-name", argv[0]);
> > 	}
> > ```
> 
> empty?
> 
> _[`tests/api_c/entry_iterator.c` line 172 at r1](https://reviewable.io/reviews/pmem/pmemstream/237#-N6DWSAv1wt1DgYdPIlE:-N6DWSAv1wt1DgYdPIlF:b-oh6q77) ([raw file](https://github.com/pmem/pmemstream/blob/ca45531cf3dc4e3c2ed1459334aa1bceb83e4ddc/tests/api_c/entry_iterator.c#L172)):_
> 
> > ```c
> > 	/*
> > 	 * XXX: shouldn't this test also work if this re-allocation didn't happen?
> > ```
> 
> Yes, we should probably extend `pmemstream_entry_iterator_offset_is_inside_region` to check if region is allocated and use this function in pmemstream_entry_iterator_is_valid
> 
> _[`tests/common/rapidcheck_helpers.hpp` line 79 at r1](https://reviewable.io/reviews/pmem/pmemstream/237#-N6DWsK00XobHLABtKf8:-N6DWsK00XobHLABtKf9:b-zggd7z) ([raw file](https://github.com/pmem/pmemstream/blob/ca45531cf3dc4e3c2ed1459334aa1bceb83e4ddc/tests/common/rapidcheck_helpers.hpp#L79)):_
> 
> > ```c++
> > 		}
> > 
> > 		UT_ASSERTeq(s.sut.persisted_timestamp(), total_entries_count);
> > ```
> 
> How about calling timestamp_validate method here as well?
> 
> _[`tests/unittest/append.cpp` line 39 at r1](https://reviewable.io/reviews/pmem/pmemstream/237#-N6DWwBv6HP6fjRZUZfO:-N6DWwBwEGuKfmsBjcit:b-k9go1m) ([raw file](https://github.com/pmem/pmemstream/blob/ca45531cf3dc4e3c2ed1459334aa1bceb83e4ddc/tests/unittest/append.cpp#L39)):_
> 
> > ```c++
> > 					 auto total_entries_count = data.size() + extra_data.size();
> > 					 UT_ASSERTeq(total_entries_count, stream.sut.persisted_timestamp());
> > ```
> 
> How about calling timestamp_validate method here as well?
> 
> Or perhaps, we should check it in stream dtor?

I can't see your issues on reviewable, all done.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/237#-:-N6IYc190MUt2JB6HLwC:bnfp4nl)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[`src/libpmemstream.c` line 776 at r2](https://reviewable.io/reviews/pmem/pmemstream/237#-N6IYWai1WpnM5t7f-cs:-N6IYWai1WpnM5t7f-ct:b1fipga) ([raw file](https://github.com/pmem/pmemstream/blob/a80556ebfafc91ec7bf1d8c9589f4248295a322b/src/libpmemstream.c#L776)):*
> ```C
> 
> 	if (!stream) {
> 		future.output.error_code = -1;
> ```

should we also mention in manpage/comment that user should check this value ?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/237)* status: 10 of 15 files reviewed, all discussions resolved (waiting on @igchor)

___
*[`src/libpmemstream.c` line 776 at r2](https://reviewable.io/reviews/pmem/pmemstream/237#-N6IYWai1WpnM5t7f-cs:-N6NVPpp-wH2boTfdU-d:bnm6yqy) ([raw file](https://github.com/pmem/pmemstream/blob/a80556ebfafc91ec7bf1d8c9589f4248295a322b/src/libpmemstream.c#L776)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

should we also mention in manpage/comment that user should check this value ?
</blockquote></details>

I've added info about it only to docs, we may update examples as well if there are more "interesting" issues there - for now it can only fail due to NULL stream.
___
*[`tests/CMakeLists.txt` line 81 at r3](https://reviewable.io/reviews/pmem/pmemstream/237#-N6NVkVp3Po8vgtImMI8:-N6NVkVp3Po8vgtImMI9:bv9rt2q) ([raw file](https://github.com/pmem/pmemstream/blob/29764f15f4e75c7e7ada15053e427db551dbecdd/tests/CMakeLists.txt#L81)):*
> ```CMake
> # ----------------------------------------------------------------- #
> build_test_ext(NAME async SRC_FILES api_c/async.c LIBS miniasync)
> # XXX: add drd and helgrind, when miniasync's fix or suppress is delivered
> ```

ref. https://github.com/pmem/miniasync/pull/101

**Review by igchor — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/237#-:-N6NZ89C5zyEAh1rIRbs:bnfp4nl)* status: 13 of 15 files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
