### PR TITLE
Add more tests

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- cleanup in tests,
- testing creation of stream/region with various params,
- add check for initializing stream with block_size == 0,
- and add check for region size > empty.size

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/54)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/54)* status: 2 of 10 files reviewed, 5 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/common/unittest.h, line 26 at r1](https://reviewable.io/reviews/pmem/pmemstream/54#-Ms_3i2E9w9qSKDWrbxl:-Ms_3i2E9w9qSKDWrbxm:b-i6cu9p) ([raw file](https://github.com/pmem/pmemstream/blob/1456d83788208b8046bd2630a092d72b7859b81f/tests/common/unittest.h#L26)):*
> ```objc
> #define START() test_register_sighandlers()
> 
> static const size_t STREAM_METADATA_SIZE = 16ULL * 1024;
> ```

I would change it to define (to be able to use as array size for example).

Also please add some "DEFAULAT" or "TEST_DEFAULT" prefix like "TEST_DEFAULT_STREAM_SIZE" .
___
*[tests/common/unittest.h, line 26 at r1](https://reviewable.io/reviews/pmem/pmemstream/54#-Ms_4E_FE3ypRFT_d-UC:-Ms_4E_FE3ypRFT_d-UD:b-3vajmr) ([raw file](https://github.com/pmem/pmemstream/blob/1456d83788208b8046bd2630a092d72b7859b81f/tests/common/unittest.h#L26)):*
> ```objc
> #define START() test_register_sighandlers()
> 
> static const size_t STREAM_METADATA_SIZE = 16ULL * 1024;
> ```

Please add some todo here to maybe expose usable size from pmemstream (at least internally) - or you can implement this ;d
___
*[tests/unittest/create.cpp, line 31 at r1](https://reviewable.io/reviews/pmem/pmemstream/54#-Ms_50TWDzGkLLn5R-3q:-Ms_50TWDzGkLLn5R-3r:be9h5c4) ([raw file](https://github.com/pmem/pmemstream/blob/1456d83788208b8046bd2630a092d72b7859b81f/tests/unittest/create.cpp#L31)):*
> ```cpp
> 			/* append a single value of size = generated region_size */
> 			std::vector<std::string> data;
> 			const auto c = *rc::gen::character<char>();
> ```

nit: I belive you can just generate string directly: https://github.com/emil-e/rapidcheck/blob/master/doc/generators.md

Probably by something like *rc::gen::arbitrary<std::string>(size); Btw, `size` of the string can also be random (perhaps there's a way to tell rapidcheck to generate string of random size...)
___
*[tests/unittest/create.cpp, line 42 at r1](https://reviewable.io/reviews/pmem/pmemstream/54#-Ms_4iNy2tMC72rP9g2N:-Ms_4iNy2tMC72rP9g2O:bxxw12y) ([raw file](https://github.com/pmem/pmemstream/blob/1456d83788208b8046bd2630a092d72b7859b81f/tests/unittest/create.cpp#L42)):*
> ```cpp
> 		});
> 
> 		ret += rc::check("verify if a single region of size = 0 can be created", [&]() {
> ```

By default rc::check runs each test 100 times and there's no point in running this one multiple times. Could you see how we could limit number of test runs?
___
*[tests/unittest/create.cpp, line 56 at r1](https://reviewable.io/reviews/pmem/pmemstream/54#-Ms_6VYr6MrGHWb1JYvh:-Ms_6VYs8r8PzHGqiFjd:bxp6dqw) ([raw file](https://github.com/pmem/pmemstream/blob/1456d83788208b8046bd2630a092d72b7859b81f/tests/unittest/create.cpp#L56)):*
> ```cpp
> 		});
> 
> 		/* XXX: we don't check neither return any valuable return code for this case */
> ```

Why this is XXX?

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/54#-:-Ms_HNsd-Vd_l9evX813:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/common/unittest.h, line 26 at r1](https://reviewable.io/reviews/pmem/pmemstream/54#-Ms_3i2E9w9qSKDWrbxl:-Ms_GLRP1EeeRLOBKPXi:b6r3mmw) ([raw file](https://github.com/pmem/pmemstream/blob/1456d83788208b8046bd2630a092d72b7859b81f/tests/common/unittest.h#L26)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I would change it to define (to be able to use as array size for example).

Also please add some "DEFAULAT" or "TEST_DEFAULT" prefix like "TEST_DEFAULT_STREAM_SIZE" .
</blockquote></details>

const value can be passed as array size, I'm against putting macros in every part of C++ code.

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/54)* status: all files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[tests/common/unittest.h, line 26 at r1](https://reviewable.io/reviews/pmem/pmemstream/54#-Ms_3i2E9w9qSKDWrbxl:-Ms_Ha7w7WQC_z_vwSF9:b-tibwk7) ([raw file](https://github.com/pmem/pmemstream/blob/1456d83788208b8046bd2630a092d72b7859b81f/tests/common/unittest.h#L26)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

const value can be passed as array size, I'm against putting macros in every part of C++ code.
</blockquote></details>

Not in standard C

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/54)* status: all files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[tests/common/unittest.h, line 26 at r1](https://reviewable.io/reviews/pmem/pmemstream/54#-Ms_3i2E9w9qSKDWrbxl:-Ms_IJfv8cEyyzHOHNlW:b-e95uii) ([raw file](https://github.com/pmem/pmemstream/blob/1456d83788208b8046bd2630a092d72b7859b81f/tests/common/unittest.h#L26)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Not in standard C
</blockquote></details>

Or rather - if you talk about VLA - it might not be supported by all compilers

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/54)* status: all files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[tests/common/unittest.h, line 26 at r1](https://reviewable.io/reviews/pmem/pmemstream/54#-Ms_3i2E9w9qSKDWrbxl:-Ms_KRN5C6NCPKbQ0FZr:b-rvokb9) ([raw file](https://github.com/pmem/pmemstream/blob/1456d83788208b8046bd2630a092d72b7859b81f/tests/common/unittest.h#L26)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Or rather - if you talk about VLA - it might not be supported by all compilers
</blockquote></details>

And you can't use VLA in all context (like in structuts, etc.)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/54)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor)

___
*[tests/common/unittest.h, line 26 at r1](https://reviewable.io/reviews/pmem/pmemstream/54#-Ms_3i2E9w9qSKDWrbxl:-Ms_VTu01J1OsUc22NxM:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1456d83788208b8046bd2630a092d72b7859b81f/tests/common/unittest.h#L26)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

And you can't use VLA in all context (like in structuts, etc.)
</blockquote></details>

Done.
___
*[tests/common/unittest.h, line 26 at r1](https://reviewable.io/reviews/pmem/pmemstream/54#-Ms_4E_FE3ypRFT_d-UC:-Ms_VUKK5pGeFXt-A_nO:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1456d83788208b8046bd2630a092d72b7859b81f/tests/common/unittest.h#L26)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please add some todo here to maybe expose usable size from pmemstream (at least internally) - or you can implement this ;d
</blockquote></details>

Done.
___
*[tests/unittest/create.cpp, line 31 at r1](https://reviewable.io/reviews/pmem/pmemstream/54#-Ms_50TWDzGkLLn5R-3q:-Ms_VYy7D4hbX2NsKNYC:b6bgnmo) ([raw file](https://github.com/pmem/pmemstream/blob/1456d83788208b8046bd2630a092d72b7859b81f/tests/unittest/create.cpp#L31)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

nit: I belive you can just generate string directly: https://github.com/emil-e/rapidcheck/blob/master/doc/generators.md

Probably by something like *rc::gen::arbitrary<std::string>(size); Btw, `size` of the string can also be random (perhaps there's a way to tell rapidcheck to generate string of random size...)
</blockquote></details>

tbh, I didn't want to overthink this test, we have a separate test for appending random entries.

anyway, I couldn't find a good working solution for generating string with a fixed size, maybe it's just me :wink: 
___
*[tests/unittest/create.cpp, line 42 at r1](https://reviewable.io/reviews/pmem/pmemstream/54#-Ms_4iNy2tMC72rP9g2N:-Ms_r2M73B8M-4Iq1I26:b69kh72) ([raw file](https://github.com/pmem/pmemstream/blob/1456d83788208b8046bd2630a092d72b7859b81f/tests/unittest/create.cpp#L42)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

By default rc::check runs each test 100 times and there's no point in running this one multiple times. Could you see how we could limit number of test runs?
</blockquote></details>

`max_success` configuration is done by env_var (https://github.com/emil-e/rapidcheck/blob/master/doc/configuration.md), so I just switched back to our regular approach for 2 tests
___
*[tests/unittest/create.cpp, line 56 at r1](https://reviewable.io/reviews/pmem/pmemstream/54#-Ms_6VYr6MrGHWb1JYvh:-Ms_rE9VDYeneXVtsy_E:bgp52eu) ([raw file](https://github.com/pmem/pmemstream/blob/1456d83788208b8046bd2630a092d72b7859b81f/tests/unittest/create.cpp#L56)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Why this is XXX?
</blockquote></details>

tbh, I didn't find a good solution, how to check this and return a proper error code from pmemstream_region_allocate

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/54)* status: 3 of 13 files reviewed, 4 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[tests/unittest/create.cpp, line 56 at r1](https://reviewable.io/reviews/pmem/pmemstream/54#-Ms_6VYr6MrGHWb1JYvh:-MsdcaSt37a8RJMBPKda:b-opji4t) ([raw file](https://github.com/pmem/pmemstream/blob/1456d83788208b8046bd2630a092d72b7859b81f/tests/unittest/create.cpp#L56)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

tbh, I didn't find a good solution, how to check this and return a proper error code from pmemstream_region_allocate
</blockquote></details>

Done, now.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/54#-:-Mt2TxUp2mH8y2fV9Ukw:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @igchor)

___
*[tests/unittest/create.cpp, line 31 at r1](https://reviewable.io/reviews/pmem/pmemstream/54#-Ms_50TWDzGkLLn5R-3q:-Mt2TXkB9WVT8gOx5tUX:b-5oj6qy) ([raw file](https://github.com/pmem/pmemstream/blob/1456d83788208b8046bd2630a092d72b7859b81f/tests/unittest/create.cpp#L31)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

tbh, I didn't want to overthink this test, we have a separate test for appending random entries.

anyway, I couldn't find a good working solution for generating string with a fixed size, maybe it's just me :wink: 
</blockquote></details>

I think you can just pass size as an argument to the generator, like here: https://github.com/pmem/pmemstream/blob/master/tests/unittest/popcount.cpp#L63

**Pull request merged**
