### PR TITLE
Make SLIST crash-consistent

### PR DESCRIPTION
**Pull request by igchor**
Add persists and recovery code.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/151)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/151)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[src/singly_linked_list.h, line 34 at r1](https://reviewable.io/reviews/pmem/pmemstream/151#-MyqjtFmEAdNDQ11VO0g:-Myr3rGc0QyZF5kDgBg-:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/7ac82a1f1fd8c5c31dd230d68becfa6196c248f4/src/singly_linked_list.h#L34)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I would say it's `dest` 
```
Built-in Function: void __atomic_store_n (type *ptr, type val, int memorder)

   (...) It writes val into *ptr. 
```


</blockquote></details>

Done.

**Review by karczex — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/151)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @igchor and @karczex)

___
*[src/singly_linked_list.h, line 66 at r2](https://reviewable.io/reviews/pmem/pmemstream/151#-MyrGil20RbLw2U4g4wb:-MyrGil20RbLw2U4g4wc:b-hblj2h) ([raw file](https://github.com/pmem/pmemstream/blob/d123dffdfe19eff421a41e4f31f41d5d3791415d/src/singly_linked_list.h#L66)):*
> ```objc
> 		    (list)->head != (list)->tail) {                                                                    \
> 			SLIST_INIT(runtime, list);                                                                     \
> 		} else if (SLIST_NEXT(type, runtime, (list)->tail, field) != SLIST_INVALID_OFFSET) {                   \
> ```

`if( list->head == SLIST_INVALID_OFFSET && list->tail == SLIST_INVALID_OFFSET)`, which is state after SLIST_INIT , you call SLIST_NEXT()

SLIST_NEXT dereference ptr to get next element, but in this moment  the ptr == runtime->data->spans + SLIST_INVALID_OFFSET (UINT64_MAX).

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/151)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[src/singly_linked_list.h, line 66 at r2](https://reviewable.io/reviews/pmem/pmemstream/151#-MyrGil20RbLw2U4g4wb:-MyrQEOf5KDEPQPw13L5:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/d123dffdfe19eff421a41e4f31f41d5d3791415d/src/singly_linked_list.h#L66)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

`if( list->head == SLIST_INVALID_OFFSET && list->tail == SLIST_INVALID_OFFSET)`, which is state after SLIST_INIT , you call SLIST_NEXT()

SLIST_NEXT dereference ptr to get next element, but in this moment  the ptr == runtime->data->spans + SLIST_INVALID_OFFSET (UINT64_MAX). 

</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/151)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[src/singly_linked_list.h, line 74 at r3](https://reviewable.io/reviews/pmem/pmemstream/151#-MyrcSPC-CIqDvt2bZt7:-MyvDt32-hyEltmmRCu4:b-1jlnif) ([raw file](https://github.com/pmem/pmemstream/blob/cb8cd2660f51f78358112cfcc7e4e3b92d06bb05/src/singly_linked_list.h#L74)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

points? (all cases)
</blockquote></details>

Where? I don't see any error in this comment.

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/151#-:-MzEo_cv7TG39RjsKMfn:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/151)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor and @karczex)

___
*[src/singly_linked_list.h, line 131 at r3](https://reviewable.io/reviews/pmem/pmemstream/151#-MyvICQMCurBSB7McK9w:-MyvICQMCurBSB7McK9x:bwbg1zl) ([raw file](https://github.com/pmem/pmemstream/blob/c11c335e01c367db36e04dc423427c427aea1e06/src/singly_linked_list.h#L131)):*
> ```objc
> /* Invariants after crash for removing non-head 'node':
>  * If node->next was modified: list is consistent (tail had been updated if necessary)
>  * If node->next was not modified: tail might point element previous to last (it will be recovered on runtime init,
> ```

`might point to`
___
*[src/singly_linked_list.h, line 149 at r4](https://reviewable.io/reviews/pmem/pmemstream/151#-MzF4eEB5h99BQ0_1avX:-MzF4eEB5h99BQ0_1avY:bu3zmku) ([raw file](https://github.com/pmem/pmemstream/blob/e6bb9f3382dba75d2a3539f60462eccc8909d669/src/singly_linked_list.h#L149)):*
> ```objc
> 	for ((it) = (list)->head; (it) != SLIST_INVALID_OFFSET; (it) = SLIST_NEXT(type, runtime, it, field))
> 
> #define SLIST_REMOVE_HEAD(type, runtime, list, field)                                                                  \
> ```

pls add here "invariants" comment (for consistency with other macros)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/151)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[src/singly_linked_list.h, line 131 at r3](https://reviewable.io/reviews/pmem/pmemstream/151#-MyvICQMCurBSB7McK9w:-MzF6OeGAYGeZ4fZgAJv:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c11c335e01c367db36e04dc423427c427aea1e06/src/singly_linked_list.h#L131)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`might point to`
</blockquote></details>

Done.
___
*[src/singly_linked_list.h, line 149 at r4](https://reviewable.io/reviews/pmem/pmemstream/151#-MzF4eEB5h99BQ0_1avX:-MzF6JRrDARHfiYPMb7a:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/e6bb9f3382dba75d2a3539f60462eccc8909d669/src/singly_linked_list.h#L149)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add here "invariants" comment (for consistency with other macros)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:+1: 

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/151#-:-MzFKT0i85XST7JtKFYm:b-8fx2u7)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/151#-:-MzFf7XE5dlJDWBQ9exs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/151)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
