### PR TITLE
common:add GHA pmemstream workflow for self-hosted runners

### PR DESCRIPTION
**Pull request by tszczyp**
Added GHA workflow to build pmemstream and run tests

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/184)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
Besides the minor changes proposed I like it!

@tszczyp, do we have to update anything within our repo settings...?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/184#-:-N1xavsk3iNcvyfANK1P:b-heqwse)* status: all files reviewed, 5 unresolved discussions (waiting on @tszczyp)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/184#-N1xaSwG2XnwKR_oyJxp):*
please replace `common:` with `CI: `
___
*[`.github/workflows/unittest.yml` line 1 at r1](https://reviewable.io/reviews/pmem/pmemstream/184#-N1xZH2eBLkECCbB9o2y:-N1xZH2eBLkECCbB9o2z:bnuvqjw) ([raw file](https://github.com/pmem/pmemstream/blob/c8476a33edb41efea49a585ab35bb2d1be091e81/.github/workflows/unittest.yml#L1)):*
> ```YAML
> name: pmemstream_runners
> ```

please rename it to "Self Hosted" (along with the filename, e.g. `self_hosted.yml`)
___
*[`.github/workflows/unittest.yml` line 7 at r1](https://reviewable.io/reviews/pmem/pmemstream/184#-N1xak_e1Qh-BC_OQ03q:-N1xak_e1Qh-BC_OQ03r:be1pl0e) ([raw file](https://github.com/pmem/pmemstream/blob/c8476a33edb41efea49a585ab35bb2d1be091e81/.github/workflows/unittest.yml#L7)):*
> ```YAML
> jobs:
>   linux:
>     name: pmemstream_runners
> ```

please rename it to `Linux-Self_Hosted`
___
*[`.github/workflows/unittest.yml` line 23 at r1](https://reviewable.io/reviews/pmem/pmemstream/184#-N1xZa7w-KfZo_Nt3bpV:-N1xZa7w-KfZo_Nt3bpW:b-638bls) ([raw file](https://github.com/pmem/pmemstream/blob/c8476a33edb41efea49a585ab35bb2d1be091e81/.github/workflows/unittest.yml#L23)):*
> ```YAML
>         - name: Build pmemstream and run basic tests
>           run: |
>             ./$WORKDIR/build_and_run-pmemstream.sh
> ```

you can easily use our build/test running script: `utils/docker/run-build.sh tests_gcc_debug_cpp17_no_valgrind` (the param is to specify a type of the build, and for now it's ok to use just one of our pre-defines)

TEST_DIR path has to be then specified using env var: `PMEMSTREAM_TEST_DIR`
___
*[`utils/gha-runners/build_and_run-pmemstream.sh` line 6 at r1](https://reviewable.io/reviews/pmem/pmemstream/184#-N1x_XaI0J64_EX0qJ5L:-N1x_XaI0J64_EX0qJ5M:bygvt34) ([raw file](https://github.com/pmem/pmemstream/blob/c8476a33edb41efea49a585ab35bb2d1be091e81/utils/gha-runners/build_and_run-pmemstream.sh#L6)):*
> ```Shell
> 
> #
> # build_and_run-pmemstream.sh - Script for building pmemstream and running basic tests.
> ```

this file will be then redundant

**Review by tszczyp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/184)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/184#-N1xaSwG2XnwKR_oyJxp):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please replace `common:` with `CI: `
</blockquote></details>

Done.
___
*[`utils/gha-runners/build_and_run-pmemstream.sh` line 6 at r1](https://reviewable.io/reviews/pmem/pmemstream/184#-N1x_XaI0J64_EX0qJ5L:-N2kcP3CCfpzBjNODgwU:bqjp36p) ([raw file](https://github.com/pmem/pmemstream/blob/c8476a33edb41efea49a585ab35bb2d1be091e81/utils/gha-runners/build_and_run-pmemstream.sh#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this file will be then redundant
</blockquote></details>

File removed
___
*[`.github/workflows/unittest.yml` line 1 at r1](https://reviewable.io/reviews/pmem/pmemstream/184#-N1xZH2eBLkECCbB9o2y:-N2kbxWx-S7PhV9NMMca:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c8476a33edb41efea49a585ab35bb2d1be091e81/.github/workflows/unittest.yml#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please rename it to "Self Hosted" (along with the filename, e.g. `self_hosted.yml`)
</blockquote></details>

Done.
___
*[`.github/workflows/unittest.yml` line 7 at r1](https://reviewable.io/reviews/pmem/pmemstream/184#-N1xak_e1Qh-BC_OQ03q:-N2kbycKDKg-v-bxso40:bt1b19p) ([raw file](https://github.com/pmem/pmemstream/blob/c8476a33edb41efea49a585ab35bb2d1be091e81/.github/workflows/unittest.yml#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please rename it to `Linux-Self_Hosted`
</blockquote></details>

Renamed.
___
*[`.github/workflows/unittest.yml` line 23 at r1](https://reviewable.io/reviews/pmem/pmemstream/184#-N1xZa7w-KfZo_Nt3bpV:-N2kc-3O-WwjUhrvcebF:b4pqrny) ([raw file](https://github.com/pmem/pmemstream/blob/c8476a33edb41efea49a585ab35bb2d1be091e81/.github/workflows/unittest.yml#L23)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can easily use our build/test running script: `utils/docker/run-build.sh tests_gcc_debug_cpp17_no_valgrind` (the param is to specify a type of the build, and for now it's ok to use just one of our pre-defines)

TEST_DIR path has to be then specified using env var: `PMEMSTREAM_TEST_DIR`
</blockquote></details>

Script used as requested, in the future, please let me know beforehand if you have created scripts which'd fasten the development process

**Review by tszczyp — COMMENTED** [review]
Nothing I'm aware of right now.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/184#-:-N2kcWi_1Dti4SdOb1Gt:b-w4omkm)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/184)* status: all files reviewed, 1 unresolved discussion (waiting on @tszczyp)

___
*[`.github/workflows/unittest.yml` line 23 at r1](https://reviewable.io/reviews/pmem/pmemstream/184#-N1xZa7w-KfZo_Nt3bpV:-N2kecWq1BXU5pU3Az0y:b-9bg4bu) ([raw file](https://github.com/pmem/pmemstream/blob/c8476a33edb41efea49a585ab35bb2d1be091e81/.github/workflows/unittest.yml#L23)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Script used as requested, in the future, please let me know beforehand if you have created scripts which'd fasten the development process
</blockquote></details>

:+1: sure thing

test dir is not set, so it will be running on a default path (`.` here, meaning regular drive, I believe)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/184)* status: all files reviewed, 1 unresolved discussion (waiting on @tszczyp)

___
*[`.github/workflows/unittest.yml` line 23 at r1](https://reviewable.io/reviews/pmem/pmemstream/184#-N1xZa7w-KfZo_Nt3bpV:-N2kfBv93Z35kteKc0ht:b-mndk9n) ([raw file](https://github.com/pmem/pmemstream/blob/c8476a33edb41efea49a585ab35bb2d1be091e81/.github/workflows/unittest.yml#L23)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

:+1: sure thing

test dir is not set, so it will be running on a default path (`.` here, meaning regular drive, I believe)
</blockquote></details>

hmm actually, I can see in the logs:
```
TEST_DIR set to: "/tmp/"
```
is it expected?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/184)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk and @tszczyp)

___
*[`.github/workflows/unittest.yml` line 23 at r1](https://reviewable.io/reviews/pmem/pmemstream/184#-N1xZa7w-KfZo_Nt3bpV:-N2kox7O1u4g_DHtwiLr:b-4kyrrv) ([raw file](https://github.com/pmem/pmemstream/blob/c8476a33edb41efea49a585ab35bb2d1be091e81/.github/workflows/unittest.yml#L23)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm actually, I can see in the logs:
```
TEST_DIR set to: "/tmp/"
```
is it expected?
</blockquote></details>

as stated in the original comment - you have to set up `PMEMSTREAM_TEST_DIR` env var

I can also see in logs, it's failing because it's missing `CHECK_CPP_STYLE=OFF` env var, as well

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/184#-:-N2kvhpoAsWUjInKaTUI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tszczyp)

___
*[`.github/workflows/unittest.yml` line 23 at r1](https://reviewable.io/reviews/pmem/pmemstream/184#-N1xZa7w-KfZo_Nt3bpV:-N2kvdanBrQlzei9FTrb:b-pa6hn0) ([raw file](https://github.com/pmem/pmemstream/blob/c8476a33edb41efea49a585ab35bb2d1be091e81/.github/workflows/unittest.yml#L23)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

My mistake, vars added and fixed
</blockquote></details>

no worries, it looks good. Thx!

**Review by karczex — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/184)* status: all files reviewed, 1 unresolved discussion (waiting on @tszczyp)

___
*[`.github/workflows/self_hosted.yml` line 14 at r4](https://reviewable.io/reviews/pmem/pmemstream/184#-N2kzkV57tMt-DCsOh2_:-N2kzkV63PFC9gGOeM3L:b-85qwll) ([raw file](https://github.com/pmem/pmemstream/blob/8016cdf37ca7473f4da14b84de3c60f904e7a453/.github/workflows/self_hosted.yml#L14)):*
> ```YAML
>         os: [[self-hosted, ubuntu]]
>     env:
>       PMEMSTREAM_TEST_DIR: /mnt/pmem0
> ```

It seems `PMEMSTREAM_TEST_DIR` is never cleaned up, which may cause builds interference. 
And TEST_DIR probably should be configurable.  I suggest to add secret variable `SELF_HOSTED_RUNNERS_TEST_DIR` and add per-job directory 

```
PMEMSTREAM_TEST_DIR:  ${{ secrets.SELF_HOSTED_RUNNERS_TEST_DIR }}/${{ github.job}} 
```
 
And you may add cleanup step to remove PMEMSTREAM_TEST_DIR (https://stackoverflow.com/questions/58858429/how-to-run-a-github-actions-step-even-if-the-previous-step-fails-while-still-f)

``` 
- name: Test dir cleanup
  if: always()
  run: rm -rf ${{ env.PMEMSTREAM_TEST_DIR }} 
```

(My code snippets are not tested, but I hope it would be useful)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/184)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[`.github/workflows/self_hosted.yml` line 14 at r4](https://reviewable.io/reviews/pmem/pmemstream/184#-N2kzkV57tMt-DCsOh2_:-N2lC-HyDJrVHNT3pg7d:bpyfnng) ([raw file](https://github.com/pmem/pmemstream/blob/8016cdf37ca7473f4da14b84de3c60f904e7a453/.github/workflows/self_hosted.yml#L14)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

I'm not sure what do you mean, each job does clean up after itself, all the files created during the execution are removed at the end of the process, both in the repository and in the PMEMSTREAM_TEST_DIR directory.
</blockquote></details>

if your build was fine, then it should not leave anything within `TEST_DIR`, but if e.g. some tests failed, they will leave at least some directories e.g. with logs.



As for a separate directory for each GHA job - this may be a problem when we execute (concurrently) 2 independent pmemstream jobs on our machine.

Anyway, I believe we'd have to ask for help from one of our admins (and they are not around, right now), so we may leave the directory as is; if needed (as a workaround) we may manually add some dub-directory to the path for each job `/mnt/pmem0/...`.

**Review by tszczyp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/184)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[`.github/workflows/self_hosted.yml` line 14 at r4](https://reviewable.io/reviews/pmem/pmemstream/184#-N2kzkV57tMt-DCsOh2_:-N2lE9wwEeTXGOSWk9fS:b23wjzu) ([raw file](https://github.com/pmem/pmemstream/blob/8016cdf37ca7473f4da14b84de3c60f904e7a453/.github/workflows/self_hosted.yml#L14)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if your build was fine, then it should not leave anything within `TEST_DIR`, but if e.g. some tests failed, they will leave at least some directories e.g. with logs.



As for a separate directory for each GHA job - this may be a problem when we execute (concurrently) 2 independent pmemstream jobs on our machine.

Anyway, I believe we'd have to ask for help from one of our admins (and they are not around, right now), so we may leave the directory as is; if needed (as a workaround) we may manually add some dub-directory to the path for each job `/mnt/pmem0/...`.
</blockquote></details>

Then I assume it'd be for the best, to leave this PR in its current state as a base and modify/add features to it later, to not prolong the review process. If you agree of course.

**Comment by karczex** [comment]
*[`.github/workflows/self_hosted.yml` line 14 at r4](https://reviewable.io/reviews/pmem/pmemstream/184#-N2kzkV57tMt-DCsOh2_:-N2lF2by08zDDvvve9GK:b32w0x) ([raw file](https://github.com/pmem/pmemstream/blob/8016cdf37ca7473f4da14b84de3c60f904e7a453/.github/workflows/self_hosted.yml#L14)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Then I assume it'd be for the best, to leave this PR in its current state as a base and modify/add features to it later, to not prolong the review process. If you agree of course. 
</blockquote></details>

OK

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/184#-:-N2lFHp6Cy0Ed2r40BuO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tszczyp)

**Pull request merged**
