### PR TITLE
use pmemstream_publish in pmemstream_append again

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
in some refactoring we did, we stopped using _publish in _append,
which seems unnecessary copy-paste of the same code.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/128)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/128#-:-Mw6C3yD1MYy6sI-rHNl:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/128#-:-MwBP36sAlrC3XuGD5kB:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by igchor — CHANGES_REQUESTED** [review]
Actually please, wait with merging this - it's easier to make experiments with memcpy in this implementation

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/128#-:-MwBPziT0V1JnplVvv8s:bqbsq5w)* status: 0 of 1 files reviewed, all discussions resolved

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/128#-:-MzEpzWLD7LkrXbe7K2z:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Pull request merged**
