### PR TITLE
Update examples and compile them in CI

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/52)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/52)* status: 6 of 11 files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[examples/visual_iterator/main.cpp, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/52#-MsAYNh1D0yH7aJCp6Sm:-MsAYNh1D0yH7aJCp6Sn:b-wuup3v) ([raw file](https://github.com/pmem/pmemstream/blob/5c8851d3f8e52f755055cba8584d96b4f18f489d/examples/visual_iterator/main.cpp#L4)):*
> ```cpp
> /* Copyright 2021, Intel Corporation */
> 
> #include "../examples_helpers.h"
> ```

How this works with standalone examples? What if the example dir is moved to some other location?
___
*[examples/visual_iterator/main.cpp, line 31 at r1](https://reviewable.io/reviews/pmem/pmemstream/52#-MsAY6b0AKbitF0m9HZJ:-MsAY6b0AKbitF0m9HZK:b-o64p9p) ([raw file](https://github.com/pmem/pmemstream/blob/5c8851d3f8e52f755055cba8584d96b4f18f489d/examples/visual_iterator/main.cpp#L31)):*
> ```cpp
>  *
>  * Possible usage:
>  * ./example-basic_iterate existing_file
> ```

To be honest, I prefer having numbering in the example dir - this makes it obvious which example you should look at first. I took this from rpma repo.

**Comment by lukaszstolarczuk** [comment]
> > Reviewed 6 of 11 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/52)_ status: 6 of 11 files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)
> 
> _[examples/visual_iterator/main.cpp, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/52#-MsAYNh1D0yH7aJCp6Sm:-MsAYNh1D0yH7aJCp6Sn:b-wuup3v) ([raw file](https://github.com/pmem/pmemstream/blob/5c8851d3f8e52f755055cba8584d96b4f18f489d/examples/visual_iterator/main.cpp#L4)):_
> 
> > ```c++
> > /* Copyright 2021, Intel Corporation */
> > 
> > #include "../examples_helpers.h"
> > ```
> 
> How this works with standalone examples? What if the example dir is moved to some other location?
> 
> _[examples/visual_iterator/main.cpp, line 31 at r1](https://reviewable.io/reviews/pmem/pmemstream/52#-MsAY6b0AKbitF0m9HZJ:-MsAY6b0AKbitF0m9HZK:b-o64p9p) ([raw file](https://github.com/pmem/pmemstream/blob/5c8851d3f8e52f755055cba8584d96b4f18f489d/examples/visual_iterator/main.cpp#L31)):_
> 
> > ```c++
> >  *
> >  * Possible usage:
> >  * ./example-basic_iterate existing_file
> > ```
> 
> To be honest, I prefer having numbering in the example dir - this makes it obvious which example you should look at first. I took this from rpma repo.

Done and done (I can't access your issue on revieawble).

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/52)* status: 1 of 11 files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[examples/README.md, line 40 at r2](https://reviewable.io/reviews/pmem/pmemstream/52#-MsFHbqa2oZ7H7wOCt2V:-MsFHbqa2oZ7H7wOCt2W:b2ngx95) ([raw file](https://github.com/pmem/pmemstream/blob/444df507d8a8908fde659d77b714e1390f8a71c2/examples/README.md#L40)):*
> ```Markdown
> ## Descriptions and additional dependencies:
> 
> * basic_iterate/main.c -- contains basic example workflow of C application.
> ```

01_
___
*[examples/README.md, line 42 at r2](https://reviewable.io/reviews/pmem/pmemstream/52#-MsFHd198ksqA0JgN79M:-MsFHd198ksqA0JgN79N:b2ngxa0) ([raw file](https://github.com/pmem/pmemstream/blob/444df507d8a8908fde659d77b714e1390f8a71c2/examples/README.md#L42)):*
> ```Markdown
> * basic_iterate/main.c -- contains basic example workflow of C application.
> 
> * visual_iterator/main.cpp -- it iterates over all entries, on previously
> ```

02_

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/52)* status: 1 of 11 files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[examples/README.md, line 40 at r2](https://reviewable.io/reviews/pmem/pmemstream/52#-MsFHbqa2oZ7H7wOCt2V:-MsGFyqm3mlf61iiNy23:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/444df507d8a8908fde659d77b714e1390f8a71c2/examples/README.md#L40)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

01_
</blockquote></details>

Done.
___
*[examples/README.md, line 42 at r2](https://reviewable.io/reviews/pmem/pmemstream/52#-MsFHd198ksqA0JgN79M:-MsGFz3H9fvsPJIfqZ5z:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/444df507d8a8908fde659d77b714e1390f8a71c2/examples/README.md#L42)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

02_
</blockquote></details>

Done.

**Review by karczex — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, 3 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/52)* status: 5 of 11 files reviewed, 4 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[utils/docker/prepare-for-build.sh, line 87 at r3](https://reviewable.io/reviews/pmem/pmemstream/52#-MsUNhFq3ObQ5eXZ5DVB:-MsUNhFq3ObQ5eXZ5DVC:bzbuz25) ([raw file](https://github.com/pmem/pmemstream/blob/d1c874b549e8a462dad27306761cb67d53e9e110/utils/docker/prepare-for-build.sh#L87)):*
> ```Shell
> 	PMEM_IS_PMEM_FORCE=${TESTS_USE_FORCED_PMEM} ./${example_name} ${file_path} ${optional_args}
> 
> 	# exit on error
> ```

In this file `set -e` is already set. What's the point of this additional error handling?



_Code quote:_
```Shell
	# exit on error
	if [[ $? != 0 ]]; then
		popd
		return 1
	fi
```
___
*[examples/02_visual_iterator/main.cpp, line 8 at r3](https://reviewable.io/reviews/pmem/pmemstream/52#-MsUMM0822h18vSnYJcs:-MsUMM0822h18vSnYJct:bwy19my) ([raw file](https://github.com/pmem/pmemstream/blob/d1c874b549e8a462dad27306761cb67d53e9e110/examples/02_visual_iterator/main.cpp#L8)):*
> ```cpp
> 
> #include <libpmem2.h>
> #include <stdio.h>
> ```

As this file is C++, What's wrong with cstdio?

**Review by karczex — COMMENTED** [review]
> Reviewed 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/52)* status: 7 of 11 files reviewed, 4 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/52)* status: 6 of 11 files reviewed, 3 unresolved discussions (waiting on @igchor and @karczex)

___
*[utils/docker/prepare-for-build.sh, line 87 at r3](https://reviewable.io/reviews/pmem/pmemstream/52#-MsUNhFq3ObQ5eXZ5DVB:-MsUcY7c3ZlD0c65bnPt:b-gxnz0d) ([raw file](https://github.com/pmem/pmemstream/blob/d1c874b549e8a462dad27306761cb67d53e9e110/utils/docker/prepare-for-build.sh#L87)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

In this file `set -e` is already set. What's the point of this additional error handling?
</blockquote></details>

we want to always return `1`, because we count on this in run-build.sh - `compile_example_standalone 01_basic_iterate && exit 1`
___
*[examples/02_visual_iterator/main.cpp, line 8 at r3](https://reviewable.io/reviews/pmem/pmemstream/52#-MsUMM0822h18vSnYJcs:-MsUcPcW3S84Z7vlikOF:b-pr8kvo) ([raw file](https://github.com/pmem/pmemstream/blob/d1c874b549e8a462dad27306761cb67d53e9e110/examples/02_visual_iterator/main.cpp#L8)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

As this file is C++, What's wrong with cstdio? 
</blockquote></details>

a copy-paste from C example. Done

**Review by karczex — APPROVED** [review]
> Reviewed 2 of 11 files at r1, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/52)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/52#-:-Mt2Wv0I9fXDXoqxkN86:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
