### PR TITLE
Fix coverity issues

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/51)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/51)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[src/iterator.c, line 73 at r1](https://reviewable.io/reviews/pmem/pmemstream/51#-MsAEK-J16NC9vAM9a9L:-MsAEK-J16NC9vAM9a9M:b-39wcf1) ([raw file](https://github.com/pmem/pmemstream/blob/874d141a9bef23cf3aab3dcbbec6065a271d917a/src/iterator.c#L73)):*
> ```C
> 				  struct pmemstream_region region)
> {
> 	struct pmemstream_entry_iterator *iter = malloc(sizeof(*iter));
> ```

perhaps handle also bad mallocs

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/51)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[src/iterator.c, line 73 at r1](https://reviewable.io/reviews/pmem/pmemstream/51#-MsAEK-J16NC9vAM9a9L:-MsAXSNs3-aAtvOXCi8o:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/874d141a9bef23cf3aab3dcbbec6065a271d917a/src/iterator.c#L73)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps handle also bad mallocs
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/51)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[-- commits, line 9 at r3](https://reviewable.io/reviews/pmem/pmemstream/51#-MsAkwj45GXPp-VKw3fM):*
hmm so should we also check `pmemstream_delete` if `*s` is not null and critnib is initialized...?
___
*[src/region.c, line 39 at r3](https://reviewable.io/reviews/pmem/pmemstream/51#-MsAjck08vhKY5drUqhN:-MsAjck08vhKY5drUqhO:b-n5bcj6) ([raw file](https://github.com/pmem/pmemstream/blob/84accd9696797995e80cf908855641a93c4f4009/src/region.c#L39)):*
> ```C
> err_region_lock:
> 	pthread_mutex_destroy(&map->container_lock);
> 	free(map);
> ```

this should be one level below

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/51)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[src/region.c, line 39 at r3](https://reviewable.io/reviews/pmem/pmemstream/51#-MsAjck08vhKY5drUqhN:-MsEtJx99xryrZelVzGH:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/84accd9696797995e80cf908855641a93c4f4009/src/region.c#L39)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this should be one level below
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/51#-:-MsEwhQD8Unq9QGoohRt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
