### PR TITLE
Add example for timestamp based persistency

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/171)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/171#-:-N-hok5KC7yAL6s-cBLL:bnfp4nl)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @igchor)

___
*[examples/CMakeLists.txt, line 55 at r1](https://reviewable.io/reviews/pmem/pmemstream/171#-N-hns8j14x9wFTQPgmH:-N-hns8j14x9wFTQPgmI:bhee5h9) ([raw file](https://github.com/pmem/pmemstream/blob/9fca79a0f4256b4786e31e37a53fa85b1b5552a6/examples/CMakeLists.txt#L55)):*
> ```CMake
> 
> add_example(05_timestamp_based_order 05_timestamp_based_order/main.cpp)
> target_link_libraries(example-05_timestamp_based_order ${LIBPMEM2_LIBRARIES} ${MINIASYNC_LIBRARIES} pthread)
> ```

 ${CMAKE_THREAD_LIBS_INIT} and call find_threads first
___
*[examples/05_timestamp_based_order/CMakeLists.txt, line 5 at r1](https://reviewable.io/reviews/pmem/pmemstream/171#-N-ho1NhCV3iMpUq-RWi:-N-ho1NhCV3iMpUq-RWj:b-k8vd3x) ([raw file](https://github.com/pmem/pmemstream/blob/9fca79a0f4256b4786e31e37a53fa85b1b5552a6/examples/05_timestamp_based_order/CMakeLists.txt#L5)):*
> ```CMake
> 
> cmake_minimum_required(VERSION 3.3)
> project(03_reserve_publish CXX)
> ```

wrong name
___
*[examples/05_timestamp_based_order/CMakeLists.txt, line 14 at r1](https://reviewable.io/reviews/pmem/pmemstream/171#-N-ho3I_0Fr6lz3IpAq8:-N-ho3Ia8wGu1euMGzPZ:b-e9aj4f) ([raw file](https://github.com/pmem/pmemstream/blob/9fca79a0f4256b4786e31e37a53fa85b1b5552a6/examples/05_timestamp_based_order/CMakeLists.txt#L14)):*
> ```CMake
> 
> add_executable(05_timestamp_based_order main.cpp)
> target_link_libraries(05_timestamp_based_order ${LIBPMEMSTREAM_LIBRARIES} pthread)
> ```

 ${CMAKE_THREAD_LIBS_INIT}
___
*[examples/05_timestamp_based_order/main.cpp, line 160 at r1](https://reviewable.io/reviews/pmem/pmemstream/171#-N-hoCCV3RyDUlmXaVaX:-N-hoCCV3RyDUlmXaVaY:bqkfl5v) ([raw file](https://github.com/pmem/pmemstream/blob/9fca79a0f4256b4786e31e37a53fa85b1b5552a6/examples/05_timestamp_based_order/main.cpp#L160)):*
> ```cpp
> 		auto oldest_data = std::min_element(entry_iterators.begin(), entry_iterators.end());
> 		timestamped_entry entry = (*oldest_data).get_data();
> 		std::cout << "entry timestamp: " << entry.timestamp << " produced by thread: " << entry.data.produced_by
> ```

You could hide it under operator<< for entry perhaps?

**Review by igchor — COMMENTED** [review]
If this is called "timestamp based persistency" then you could somehow show (or just comment) that if element with timestamp X is committed then all elements with timestamp < X are also committed and accessible after crash

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/171#-:-N-hp3WK8rEwyc1SvpsX:b-asn2im)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @igchor)

**Review by igchor — COMMENTED** [review]
@karczex could you also paste a sample output of this example here (in a PR comment)?

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/171#-:-N0Uo6NaBdldFZ6x7oG-:b-trioun)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @igchor)

**Review by lukaszstolarczuk — COMMENTED** [review]
@igchor, FYI, there's output in the CI: https://github.com/pmem/pmemstream/runs/6040168699?check_suite_focus=true#step:6:632

> Reviewed 3 of 6 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/171#-:-N0UyxRw9vLmOMuxNQWH:bt328nc)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[`examples/CMakeLists.txt` line 57 at r2](https://reviewable.io/reviews/pmem/pmemstream/171#-N0Uu_p37gSbdeE_H6w1:-N0Uu_p37gSbdeE_H6w2:b5e0jto) ([raw file](https://github.com/pmem/pmemstream/blob/ba8fea4bc183f1621ac28a9356b98927a7a01007/examples/CMakeLists.txt#L57)):*
> ```CMake
> 
> add_example(05_timestamp_based_order 05_timestamp_based_order/main.cpp)
> target_link_libraries(example-05_timestamp_based_order ${LIBPMEM2_LIBRARIES} ${MINIASYNC_LIBRARIES} ${CMAKE_THREAD_LIBS_INIT})
> ```

do you need to include miniasync libs here?
___
*[`examples/05_timestamp_based_order/main.cpp` line 16 at r2](https://reviewable.io/reviews/pmem/pmemstream/171#-N0Uv8Xk0jK_8Kj24Wq2:-N0Uv8Xk0jK_8Kj24Wq3:b-9qtpxz) ([raw file](https://github.com/pmem/pmemstream/blob/ba8fea4bc183f1621ac28a9356b98927a7a01007/examples/05_timestamp_based_order/main.cpp#L16)):*
> ```cpp
> 
> #include <libpmem2.h>
> ```

you could add a general description for this example;

as well as some comments for structs/classes defined in this file
___
*[`examples/05_timestamp_based_order/main.cpp` line 56 at r2](https://reviewable.io/reviews/pmem/pmemstream/171#-N0UyTznBT9xv4t4shUj:-N0UyTznBT9xv4t4shUk:bej0jys) ([raw file](https://github.com/pmem/pmemstream/blob/ba8fea4bc183f1621ac28a9356b98927a7a01007/examples/05_timestamp_based_order/main.cpp#L56)):*
> ```cpp
> std::ostream &operator<<(std::ostream &os, const timestamped_entry &entry)
> {
> 	os << "entry timestamp " << entry.timestamp << " with data " << entry.data;
> ```

pls make it e.g.: `" with data: "` or `" with data (" << entry.data << ")";`
___
*[`examples/05_timestamp_based_order/main.cpp` line 134 at r2](https://reviewable.io/reviews/pmem/pmemstream/171#-N0Uxj9wD4syLH_TbLR5:-N0Uxj9wD4syLH_TbLR6:b-nsqcu9) ([raw file](https://github.com/pmem/pmemstream/blob/ba8fea4bc183f1621ac28a9356b98927a7a01007/examples/05_timestamp_based_order/main.cpp#L134)):*
> ```cpp
> 	std::vector<entry_iterator> entry_iterators;
> 	for (auto &region : regions) {
> ```

redundant empty line
___
*[`examples/05_timestamp_based_order/main.cpp` line 152 at r2](https://reviewable.io/reviews/pmem/pmemstream/171#-N0UuzTTE47cW8s1LAvE:-N0UuzTTE47cW8s1LAvF:b-wa8h23) ([raw file](https://github.com/pmem/pmemstream/blob/ba8fea4bc183f1621ac28a9356b98927a7a01007/examples/05_timestamp_based_order/main.cpp#L152)):*
> ```cpp
> 	constexpr size_t samples_per_thread = 10;
> 
> 	/* We initialize stream with a single region */
> ```

`a single region`?

// BTW: this is a good comment, you could add similar ones below, for other parts of this example

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/171)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[`examples/CMakeLists.txt` line 57 at r2](https://reviewable.io/reviews/pmem/pmemstream/171#-N0Uu_p37gSbdeE_H6w1:-N0ervk_3_fDAkIpxQkn:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ba8fea4bc183f1621ac28a9356b98927a7a01007/examples/CMakeLists.txt#L57)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do you need to include miniasync libs here?
</blockquote></details>

Done.
___
*[`examples/05_timestamp_based_order/main.cpp` line 16 at r2](https://reviewable.io/reviews/pmem/pmemstream/171#-N0Uv8Xk0jK_8Kj24Wq2:-N0f288F1Vl3Qy_H7UNT:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ba8fea4bc183f1621ac28a9356b98927a7a01007/examples/05_timestamp_based_order/main.cpp#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you could add a general description for this example;

as well as some comments for structs/classes defined in this file
</blockquote></details>

Done.
___
*[`examples/05_timestamp_based_order/main.cpp` line 56 at r2](https://reviewable.io/reviews/pmem/pmemstream/171#-N0UyTznBT9xv4t4shUj:-N0esE7A-BpVswfAV51o:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ba8fea4bc183f1621ac28a9356b98927a7a01007/examples/05_timestamp_based_order/main.cpp#L56)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls make it e.g.: `" with data: "` or `" with data (" << entry.data << ")";`
</blockquote></details>

Done.
___
*[`examples/05_timestamp_based_order/main.cpp` line 134 at r2](https://reviewable.io/reviews/pmem/pmemstream/171#-N0Uxj9wD4syLH_TbLR5:-N0esGYE3y7XViUC0-d2:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ba8fea4bc183f1621ac28a9356b98927a7a01007/examples/05_timestamp_based_order/main.cpp#L134)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done.
___
*[`examples/05_timestamp_based_order/main.cpp` line 152 at r2](https://reviewable.io/reviews/pmem/pmemstream/171#-N0UuzTTE47cW8s1LAvE:-N0esz04B5KAlZtWkXkR:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ba8fea4bc183f1621ac28a9356b98927a7a01007/examples/05_timestamp_based_order/main.cpp#L152)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`a single region`?

// BTW: this is a good comment, you could add similar ones below, for other parts of this example
</blockquote></details>

Done.

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/171)* status: all files reviewed, 8 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[`examples/05_timestamp_based_order/main.cpp` line 75 at r4](https://reviewable.io/reviews/pmem/pmemstream/171#-N0f9lX-9LGvxbKPHFL0:-N0f9lX-9LGvxbKPHFL1:b-4zvo16) ([raw file](https://github.com/pmem/pmemstream/blob/bee78bfecbc1528f10fb61afec0436cdabdff37d/examples/05_timestamp_based_order/main.cpp#L75)):*
> ```cpp
> 	void append(struct pmemstream_region region, payload &data)
> 	{
> 		/* Acquire lock to simulate atomicity of append with timestamp*/
> ```

`timestamp */`



_Code quote:_
```cpp
timestamp*/
```
___
*[`examples/05_timestamp_based_order/main.cpp` line 148 at r4](https://reviewable.io/reviews/pmem/pmemstream/171#-N0fALmP3ZcGLqcPgqb8:-N0fALmP3ZcGLqcPgqb9:b1ruuu9) ([raw file](https://github.com/pmem/pmemstream/blob/bee78bfecbc1528f10fb61afec0436cdabdff37d/examples/05_timestamp_based_order/main.cpp#L148)):*
> ```cpp
> {
> 	if (argc < 2) {
> 		printf("Usage: %s file\n", argv[0]);
> ```

Can be replaced with `std::cout` or add missing header `<cstdio>`



_Code quote:_
```cpp
printf("Usage: %s file\n", argv[0]);
```
___
*[`examples/05_timestamp_based_order/main.cpp` line 178 at r4](https://reviewable.io/reviews/pmem/pmemstream/171#-N0fAc8b93J4RYANmf6u:-N0fAc8b93J4RYANmf6v:bh9bxxt) ([raw file](https://github.com/pmem/pmemstream/blob/bee78bfecbc1528f10fb61afec0436cdabdff37d/examples/05_timestamp_based_order/main.cpp#L178)):*
> ```cpp
> 	for (size_t i = 0; i < concurrency * samples_per_thread; i++) {
> 		auto oldest_data = std::min_element(entry_iterators.begin(), entry_iterators.end());
> 		timestamped_entry entry = (*oldest_data).get_data();
> ```

oldest_data->get_data();



_Code quote:_
```cpp
(*oldest_data).get_data();
```

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/171)* status: 5 of 7 files reviewed, 8 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[`examples/05_timestamp_based_order/main.cpp` line 75 at r4](https://reviewable.io/reviews/pmem/pmemstream/171#-N0f9lX-9LGvxbKPHFL0:-N0ittnEA6MbTutaFAtB:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/bee78bfecbc1528f10fb61afec0436cdabdff37d/examples/05_timestamp_based_order/main.cpp#L75)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

`timestamp */`
</blockquote></details>

Done.
___
*[`examples/05_timestamp_based_order/main.cpp` line 81 at r4](https://reviewable.io/reviews/pmem/pmemstream/171#-N0fNAYhBkFdc1KwpLJ4:-N0itk7T4tFy0XoDcwzE:b-u02tng) ([raw file](https://github.com/pmem/pmemstream/blob/bee78bfecbc1528f10fb61afec0436cdabdff37d/examples/05_timestamp_based_order/main.cpp#L81)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can pass NULL as the last param
</blockquote></details>

Good catch, thx :) 
___
*[`examples/05_timestamp_based_order/main.cpp` line 82 at r4](https://reviewable.io/reviews/pmem/pmemstream/171#-N0fR1X_9RL1nee_0yjO:-N0itXOq6kYJ0P_Yvd7e:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/bee78bfecbc1528f10fb61afec0436cdabdff37d/examples/05_timestamp_based_order/main.cpp#L82)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe `!= 0` as you have below
</blockquote></details>

Done.
___
*[`examples/05_timestamp_based_order/main.cpp` line 120 at r4](https://reviewable.io/reviews/pmem/pmemstream/171#-N0fSY6y1stgKbTeBoLa:-N0itPE38IhWdI6ewWK9:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/bee78bfecbc1528f10fb61afec0436cdabdff37d/examples/05_timestamp_based_order/main.cpp#L120)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`->`
</blockquote></details>

Done.
___
*[`examples/05_timestamp_based_order/main.cpp` line 148 at r4](https://reviewable.io/reviews/pmem/pmemstream/171#-N0fALmP3ZcGLqcPgqb8:-N0j1krM1P-4AP1djzDr:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/bee78bfecbc1528f10fb61afec0436cdabdff37d/examples/05_timestamp_based_order/main.cpp#L148)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Can be replaced with `std::cout` or add missing header `<cstdio>`
</blockquote></details>

Done.
___
*[`examples/05_timestamp_based_order/main.cpp` line 178 at r4](https://reviewable.io/reviews/pmem/pmemstream/171#-N0fAc8b93J4RYANmf6u:-N0irlT-CyZTfYNKRfKW:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/bee78bfecbc1528f10fb61afec0436cdabdff37d/examples/05_timestamp_based_order/main.cpp#L178)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

oldest_data->get_data();
</blockquote></details>

Done.
___
*[`examples/05_timestamp_based_order/README.md` line 3 at r4](https://reviewable.io/reviews/pmem/pmemstream/171#-N0fA5AUAAM9MI-QGGcA:-N0j1pea5TvSQIaEPMW6:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/bee78bfecbc1528f10fb61afec0436cdabdff37d/examples/05_timestamp_based_order/README.md#L3)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add a full stop (`.`) at the end.
</blockquote></details>

Done.
___
*[`examples/05_timestamp_based_order/README.md` line 11 at r4](https://reviewable.io/reviews/pmem/pmemstream/171#-N0f9dRiCWCYLznFLoPD:-N0io5EL9ssTao6n5N5T:b-fht3ke) ([raw file](https://github.com/pmem/pmemstream/blob/bee78bfecbc1528f10fb61afec0436cdabdff37d/examples/05_timestamp_based_order/README.md#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

is this section needed?
</blockquote></details>

No, but @igchor asked for it :)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/171)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[`examples/05_timestamp_based_order/README.md` line 11 at r4](https://reviewable.io/reviews/pmem/pmemstream/171#-N0f9dRiCWCYLznFLoPD:-N0j7ViA9W-gzvUp1uXM:b-mdgww2) ([raw file](https://github.com/pmem/pmemstream/blob/bee78bfecbc1528f10fb61afec0436cdabdff37d/examples/05_timestamp_based_order/README.md#L11)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

No, but @igchor asked for it :)
</blockquote></details>

hah, but he asked for that `(in a PR comment)` :smile:

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/171)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[`examples/05_timestamp_based_order/README.md` line 11 at r4](https://reviewable.io/reviews/pmem/pmemstream/171#-N0f9dRiCWCYLznFLoPD:-N0jTRDeCwXnx4LET3v4:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/bee78bfecbc1528f10fb61afec0436cdabdff37d/examples/05_timestamp_based_order/README.md#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hah, but he asked for that `(in a PR comment)` :smile: 
</blockquote></details>

Done.

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/171#-:-N0jVuiL5GmCbaYNaDj6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/171#-:-N0j_M9K8AHy0BqCzqxc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
