### PR TITLE
Region allocator

### PR DESCRIPTION
**Pull request by KFilipek**
It's very initial draft with support for splitting
﻿
- [ ] move allocator to separate file
- [ ] iterate through free list
- [ ] iterate through allocated list
- [ ] layout tests

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/134)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/134)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[tests/unittest/region_allocator.cpp, line 51 at r1](https://reviewable.io/reviews/pmem/pmemstream/134#-Mwan-B97NqhYKtIRye7:-Mwan-B97NqhYKtIRye8:bmsmpfn) ([raw file](https://github.com/pmem/pmemstream/blob/224208a550f3d7836f3bb1e2d624c4bb3dca0b07/tests/unittest/region_allocator.cpp#L51)):*
> ```cpp
> }
> 
> uint64_t split(uint64_t *ptr, size_t size)
> ```

what is ptr? shouldn;t this function accept allocator_header and pointer to span which we want to split?
___
*[tests/unittest/region_allocator.cpp, line 66 at r1](https://reviewable.io/reviews/pmem/pmemstream/134#-Mwam63SCqNrSdeGc_oa:-Mwam63SCqNrSdeGc_ob:b-wo865c) ([raw file](https://github.com/pmem/pmemstream/blob/224208a550f3d7836f3bb1e2d624c4bb3dca0b07/tests/unittest/region_allocator.cpp#L66)):*
> ```cpp
> 	memcpy(pointer_to_offset(header->data, header->first_free), &sr, sizeof(sr));	     // create region
> 	memcpy(pointer_to_offset(header->data, header->first_free + size), &se, sizeof(se)); // create empty space
> 	header->first_allocated = header->first_free;
> ```

Why does split changes both allocated and free variables?
Wasn't split supposed to just split one empty span into two (and insert one extra element to the free_list)?
___
*[tests/unittest/region_allocator.cpp, line 90 at r1](https://reviewable.io/reviews/pmem/pmemstream/134#-MwamWUf4Xdjfn8BwtdT:-MwamWUf4Xdjfn8BwtdU:b-hfa74r) ([raw file](https://github.com/pmem/pmemstream/blob/224208a550f3d7836f3bb1e2d624c4bb3dca0b07/tests/unittest/region_allocator.cpp#L90)):*
> ```cpp
> 	}
> 
> 	struct pmemstream *stream;
> ```

you don't have to use stream/pmem2 for this test - you can use DRAM buffers for spans

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/134)* status: 0 of 7 files reviewed, 9 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[src/region_allocator.h, line 17 at r2](https://reviewable.io/reviews/pmem/pmemstream/134#-MwkNvHE15IViaDIS9m8:-MwkNvHE15IViaDIS9m9:bggo1bt) ([raw file](https://github.com/pmem/pmemstream/blob/f0d96d7e82cd5f83db7c807e4b4d90f4860c5dd9/src/region_allocator.h#L17)):*
> ```objc
> 
> /* API */
> uint64_t allocate_region(uint64_t region_size);
> ```

please add proper parameters to those functions
___
*[src/region_allocator.c, line 19 at r2](https://reviewable.io/reviews/pmem/pmemstream/134#-MwkNBQZ1CMSof3eKKYg:-MwkNBQZ1CMSof3eKKYh:bfvsvi7) ([raw file](https://github.com/pmem/pmemstream/blob/f0d96d7e82cd5f83db7c807e4b4d90f4860c5dd9/src/region_allocator.c#L19)):*
> ```C
> 	uint64_t first_allocated; // first allocated region offset
> 	uint64_t padding[5];
> 	uint64_t data[];
> ```

why do you have data in the header?
___
*[src/region_allocator.c, line 38 at r2](https://reviewable.io/reviews/pmem/pmemstream/134#-MwkMlEbEOHoamy8gn0y:-MwkMlEbEOHoamy8gn0z:b-pmj57a) ([raw file](https://github.com/pmem/pmemstream/blob/f0d96d7e82cd5f83db7c807e4b4d90f4860c5dd9/src/region_allocator.c#L38)):*
> ```C
> }
> 
> uint64_t *pointer_to_offset(uint64_t *base, uint64_t offset)
> ```

isn't this offset to pointer? anyway, there is such function already implemented: `pmemstream_offset_to_ptr`
___
*[src/region_allocator.c, line 43 at r2](https://reviewable.io/reviews/pmem/pmemstream/134#-MwkMulg0iQ_HoP3UsjO:-MwkMulg0iQ_HoP3UsjP:blral9d) ([raw file](https://github.com/pmem/pmemstream/blob/f0d96d7e82cd5f83db7c807e4b4d90f4860c5dd9/src/region_allocator.c#L43)):*
> ```C
> }
> 
> int is_free_empty(uint64_t *ptr)
> ```

free empty? what does it suppose to mean?
___
*[src/region_allocator.c, line 58 at r2](https://reviewable.io/reviews/pmem/pmemstream/134#-MwkNfXX2N_A5GHX2Vvo:-MwkNfXX2N_A5GHX2Vvp:b9st4ks) ([raw file](https://github.com/pmem/pmemstream/blob/f0d96d7e82cd5f83db7c807e4b4d90f4860c5dd9/src/region_allocator.c#L58)):*
> ```C
> 	uint64_t free_size = span_get_total_size(
> 		(struct span_base *)pointer_to_offset(alloc_header->data, alloc_header->first_free));
> 	if (size > free_size + sizeof(struct span_empty)) {
> ```

total_size already includes the metadata
___
*[src/region_allocator.c, line 67 at r2](https://reviewable.io/reviews/pmem/pmemstream/134#-MwkNki76h7_ux9-92hY:-MwkNki76h7_ux9-92hZ:b-ojoi8a) ([raw file](https://github.com/pmem/pmemstream/blob/f0d96d7e82cd5f83db7c807e4b4d90f4860c5dd9/src/region_allocator.c#L67)):*
> ```C
> 	se[1].span_base = span_base_create(target_size[1], SPAN_EMPTY);
> 	se[0].next = target_offset[1];
> 	memcpy(pointer_to_offset(alloc_header->data, target_offset[0]), &se[0], sizeof(struct span_empty));
> ```

why do you create two empty spans? shouldn't split assume there is already one existing?

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/134)* status: 0 of 7 files reviewed, 10 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[src/region_allocator.h, line 19 at r2](https://reviewable.io/reviews/pmem/pmemstream/134#-MwkSxsg3mCr-YKktQbq:-MwkOILB2AL11e8q7H7W:b-zgngo4) ([raw file](https://github.com/pmem/pmemstream/blob/f0d96d7e82cd5f83db7c807e4b4d90f4860c5dd9/src/region_allocator.h#L19)):*
> ```objc
> uint64_t allocate_region(uint64_t region_size);
> void free_region(uint64_t region_offset);
> uint64_t get_region_iterator();
> ```

Is there any specific reason for implementing different functions for region/empty iterators? Why not have  a generic implementation for iterating over a list?

You can literally just take some existing implementation for a single-linked list, e.g. from PMDK: 
https://github.com/pmem/pmdk/blob/master/src/common/queue.h#L173-L231

Just replace pointer type with uint64_t (store next offset instead of next pointer).

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/134)* status: 1 of 7 files reviewed, 12 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemstream.map, line 26 at r5](https://reviewable.io/reviews/pmem/pmemstream/134#-MxDyHWrBUHfWgHig3uf:-MxDyHWs3gsVsjun-bYc:bsc0ar2) ([raw file](https://github.com/pmem/pmemstream/blob/82e0aa15805d3db3b2906307f2310e3140e7440b/src/libpmemstream.map#L26)):*
> ```
> 		pmemstream_region_free;
> 		initialize_memory;
> 		is_free_empty;
> ```

these 2 should be just static I guess, and not be here...? 
___
*[tests/unittest/region_allocator.cpp, line 7 at r5](https://reviewable.io/reviews/pmem/pmemstream/134#-MxDwc6-6KscMJzfYLxm:-MxDwc6-6KscMJzfYLxn:b-gyqbov) ([raw file](https://github.com/pmem/pmemstream/blob/82e0aa15805d3db3b2906307f2310e3140e7440b/tests/unittest/region_allocator.cpp#L7)):*
> ```cpp
> 
> #include "region_allocator.h"
> #include "../examples/examples_helpers.h"
> ```

examples_helpers seems redundant; it's better to use unittest's functions in tests

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/134)* status: 1 of 7 files reviewed, 13 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/region_allocator.c, line 31 at r5](https://reviewable.io/reviews/pmem/pmemstream/134#-MxKGkT-90z7ho71_H6R:-MxKGkT-90z7ho71_H6S:b-mjjm10) ([raw file](https://github.com/pmem/pmemstream/blob/82e0aa15805d3db3b2906307f2310e3140e7440b/src/region_allocator.c#L31)):*
> ```C
> }
> 
> uint64_t next(struct allocator_header *alloc_header, uint64_t it)
> ```

Can you please make the list implementation (insertion, deletion, iteration) generic (no switches, etc.)? As I mentioned in last comment, you can just use the implementation from PMDK (with small changes).

**Review by karczex — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/134)* status: 2 of 7 files reviewed, 19 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/region_allocator.c, line 40 at r8](https://reviewable.io/reviews/pmem/pmemstream/134#-My6YcjrCXZSs72XMUJa:-My6YcjrCXZSs72XMUJb:b-tgl1u8) ([raw file](https://github.com/pmem/pmemstream/blob/562779747121bd12a672817cf27dfc3eba280bf9/src/region_allocator.c#L40)):*
> ```C
> }
> 
> uint64_t next(struct allocator_header *alloc_header, uint64_t it)
> ```

IMHO this function is rather `get_next()` than `next()`.
___
*[src/region_allocator.c, line 83 at r8](https://reviewable.io/reviews/pmem/pmemstream/134#-My6VIxr1HfS8JWn-8m-:-My6VIxr1HfS8JWn-8m0:b-3fv2oz) ([raw file](https://github.com/pmem/pmemstream/blob/562779747121bd12a672817cf27dfc3eba280bf9/src/region_allocator.c#L83)):*
> ```C
> }
> 
> void remove_elem(struct allocator_header *alloc_header, struct singly_linked_list *list, uint64_t it)
> ```

Please name somehow this type in the header. 



_Code quote:_
```C
uint64_t it
```
___
*[src/region_allocator.c, line 120 at r8](https://reviewable.io/reviews/pmem/pmemstream/134#-My6tSiN4_p3Cz2MKdXi:-My6tSiO3nEMP_vvJd7i:bns0w1o) ([raw file](https://github.com/pmem/pmemstream/blob/562779747121bd12a672817cf27dfc3eba280bf9/src/region_allocator.c#L120)):*
> ```C
> void region_allocator_new(struct allocator_header **alloc_header, uint64_t *ptr, size_t size)
> {
> 	const uint64_t header_id = 26985;
> ```

heh :) 
Anyway, I don't get the point of magic_number in header. Memory pointed by *ptr may have some random content with your value at the beginning or may be initialized with pattern similar to header_id. In  such case  this function would succeed with garbage in alloc_header. If you want to do such check, you should count and check crc of header. 
___
*[src/region_allocator.c, line 136 at r8](https://reviewable.io/reviews/pmem/pmemstream/134#-My6ahU8DmCVyy6C2-9r:-My6ahU8DmCVyy6C2-9s:b-mnba06) ([raw file](https://github.com/pmem/pmemstream/blob/562779747121bd12a672817cf27dfc3eba280bf9/src/region_allocator.c#L136)):*
> ```C
> }
> 
> uint64_t split(struct allocator_header *alloc_header, uint64_t it, size_t size)
> ```

If I understand correctly, for fixed size regions split may be called only for free_list (I would even say it shouldn't be possible to call it for alloc_list) so `it` parameter is redundant in function signature.



_Code quote:_
```C
uint64_t it,
```
___
*[src/region_allocator.c, line 179 at r8](https://reviewable.io/reviews/pmem/pmemstream/134#-My6Sd8VDpx8Snbi07nN:-My6Sd8VDpx8Snbi07nO:b-t4hbyq) ([raw file](https://github.com/pmem/pmemstream/blob/562779747121bd12a672817cf27dfc3eba280bf9/src/region_allocator.c#L179)):*
> ```C
> 	size = ALIGN_UP(size, alignment);
> 	uint64_t free_block_size = span_get_total_size(
> 		(struct span_base *)pointer_to_offset(alloc_header->data, alloc_header->free_list.head));
> ```

please wrap it into `size_t get_free_block_size(...)` helper



_Code quote:_
```C
	uint64_t free_block_size = span_get_total_size(
		(struct span_base *)pointer_to_offset(alloc_header->data, alloc_header->free_list.head));
```
___
*[src/region_allocator.c, line 180 at r8](https://reviewable.io/reviews/pmem/pmemstream/134#-My6TLEc095kauykqbRT:-My6TLEc095kauykqbRU:bvfvwaj) ([raw file](https://github.com/pmem/pmemstream/blob/562779747121bd12a672817cf27dfc3eba280bf9/src/region_allocator.c#L180)):*
> ```C
> 	uint64_t free_block_size = span_get_total_size(
> 		(struct span_base *)pointer_to_offset(alloc_header->data, alloc_header->free_list.head));
> 	if (size != free_block_size && size < free_block_size) {
> ```

`size != free_block_size` is redundant in this statement

**Pull request closed without merging**
