### PR TITLE
tests: RC stateful test for region allocator

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- [x] wait for https://github.com/pmem/pmemstream/pull/154
- [x] wait for helper function implemented in #161

only the last commit belongs to this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/160)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/160)* status: 0 of 14 files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/160#-MzQVS9j3LlrvQpZksB1:-MzQVS9j3LlrvQpZksB2:b9lxmci) (no related file):*
Please also extend the append test - just initialize multiple regions instead of just one (in the stateful test) and this will test appending data to multiple regions I belive

---

**Review by Karolina002 — COMMENTED** [review]
> Reviewed 8 of 9 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/160)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/160)* status: 1 of 18 files reviewed, 1 unresolved discussion (waiting on @igchor and @Karolina002)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/160#-MzQVS9j3LlrvQpZksB1:-MzVRg8M1to6cTOtzXht:b-896fix) (no related file):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please also extend the append test - just initialize multiple regions instead of just one (in the stateful test) and this will test appending data to multiple regions I belive
</blockquote></details>

Done.

---
___
*[tests/unittest/regions_state.cpp, line 24 at r3](https://reviewable.io/reviews/pmem/pmemstream/160#-MzQ0y4M6I2uSqcnzD8E:-MzVRihm6IvmnzMDOBL8:b-7rl0jd) ([raw file](https://github.com/pmem/pmemstream/blob/8cdb2e4185adb6a7006b5f0fa05dcdb9698d111d/tests/unittest/regions_state.cpp#L24)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think it would be better to hold a list here. This list could contain some unique ids (generated from a counter). Those ids could also be inserted as entry to each region. Then on iterate we can verify if the ids inside list and in stream are in the same order.
</blockquote></details>

done.
___
*[tests/unittest/regions_state.cpp, line 29 at r3](https://reviewable.io/reviews/pmem/pmemstream/160#-MzQ0ptYDCCW-WszEjL7:-MzQD0LUA6XFePeBeOWj:b-dpv1ji) ([raw file](https://github.com/pmem/pmemstream/blob/8cdb2e4185adb6a7006b5f0fa05dcdb9698d111d/tests/unittest/regions_state.cpp#L29)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Is this struct needed? perhaps you could just pass pmemstream_test_base as param to rc::state::Command directly? or use std::reference_wrapper?
</blockquote></details>

works like a charm

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/160)* status: 6 of 18 files reviewed, all discussions resolved (waiting on @igchor and @Karolina002)

___
*[tests/common/stream_helpers.hpp, line 266 at r4](https://reviewable.io/reviews/pmem/pmemstream/160#-MzVnbpO3SRnpN8yIZln:-MzZBmN85eRbHAmtTYEU:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/573d7d3f3e6a1b12a04ac580b72f8bbc5e266d39/tests/common/stream_helpers.hpp#L266)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why not just `get_region?` ;d
</blockquote></details>

Done.
___
*[tests/unittest/multi_region_state.cpp, line 99 at r4](https://reviewable.io/reviews/pmem/pmemstream/160#-MzVoX91Bnh0C3o3s4Ht:-MzZEORvE5ZH1sozBbae:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/573d7d3f3e6a1b12a04ac580b72f8bbc5e266d39/tests/unittest/multi_region_state.cpp#L99)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

please use static_casts where possible
</blockquote></details>

Done.
___
*[tests/unittest/multi_region_state.cpp, line 113 at r4](https://reviewable.io/reviews/pmem/pmemstream/160#-MzVog6X0XszXhR0vazk:-MzZC1_Z-030sg_ZL1je:bartveb) ([raw file](https://github.com/pmem/pmemstream/blob/573d7d3f3e6a1b12a04ac580b72f8bbc5e266d39/tests/unittest/multi_region_state.cpp#L113)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I guess the offset can also be gerated - just make sure that it's not present in the model's list.
</blockquote></details>

unfortunately we have no info in this model about offsets
___
*[tests/unittest/multi_region_state.cpp, line 177 at r4](https://reviewable.io/reviews/pmem/pmemstream/160#-MzVpHqe-7-cytg0fwDP:-MzZCgrz-evFNBD9XKn-:b-dku9zs) ([raw file](https://github.com/pmem/pmemstream/blob/573d7d3f3e6a1b12a04ac580b72f8bbc5e266d39/tests/unittest/multi_region_state.cpp#L177)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Can't we just check how many regions we have instead of relying on out_of_bound exception?
</blockquote></details>

tbh, I was waiting for Krzysiek's helper... sooo I stole it :wink: We can wait for merging his PR first.
Done.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/160)* status: 6 of 18 files reviewed, all discussions resolved (waiting on @igchor and @Karolina002)

___
*[tests/unittest/multi_region_state.cpp, line 113 at r4](https://reviewable.io/reviews/pmem/pmemstream/160#-MzVog6X0XszXhR0vazk:-MzZHMWb-QbTBX0Liuy3:bdx92xc) ([raw file](https://github.com/pmem/pmemstream/blob/573d7d3f3e6a1b12a04ac580b72f8bbc5e266d39/tests/unittest/multi_region_state.cpp#L113)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

unfortunately we have no info in this model about offsets
</blockquote></details>

Can't we then just generate some random offset and iterate over all regions ins stream (not model) to verify there is no region with such offset?

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/160#-:-MzZNtx6BwitelvrSGJg:bnfp4nl)* status: 6 of 18 files reviewed, all discussions resolved (waiting on @igchor and @Karolina002)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/160)* status: 6 of 18 files reviewed, all discussions resolved (waiting on @igchor and @Karolina002)

___
*[tests/unittest/multi_region_state.cpp, line 113 at r4](https://reviewable.io/reviews/pmem/pmemstream/160#-MzVog6X0XszXhR0vazk:-MzZPEEA9F4lwdK0cyuv:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/573d7d3f3e6a1b12a04ac580b72f8bbc5e266d39/tests/unittest/multi_region_state.cpp#L113)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Can't we then just generate some random offset and iterate over all regions ins stream (not model) to verify there is no region with such offset?
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/160)* status: 5 of 19 files reviewed, all discussions resolved (waiting on @igchor and @Karolina002)

___
*[tests/common/unittest.h, line 61 at r8](https://reviewable.io/reviews/pmem/pmemstream/160#-N-2sDyOAhBZI-CfS3OJ:-N-3YZ8p9C1xjbD5oT-b:bg0zent) ([raw file](https://github.com/pmem/pmemstream/blob/4c5d4d08a6f3e230186c06d201a9ca01237a75b2/tests/common/unittest.h#L61)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

perhpas add those to test_config also?
</blockquote></details>

tbh, I'd have to re-think how to use it properly; perhaps when we add some more multi-regions & multi-appends tests we'll come with some good idea how to handle these region sizes/count/... (and I guess it will change, when/if we add regions of different sizes :wink: )
___
*[tests/unittest/multi_region.cpp, line 47 at r8](https://reviewable.io/reviews/pmem/pmemstream/160#-N-2sY178yjaxnFQosfF:-N-3_4Ex1VYd7bjEB3gf:b-cc3nga) ([raw file](https://github.com/pmem/pmemstream/blob/4c5d4d08a6f3e230186c06d201a9ca01237a75b2/tests/unittest/multi_region.cpp#L47)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

remove this comment or uncomment?
</blockquote></details>

ups, forgot about it. Done.

**Review by igchor — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/160#-:-N-7sNpNANSzPmJXoyPM:bnfp4nl)* status: 7 of 19 files reviewed, all discussions resolved (waiting on @igchor and @Karolina002)

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 11 of 17 files at r4, 1 of 1 files at r6, 1 of 4 files at r7, 2 of 4 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/160)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[tests/common/stream_helpers.hpp, line 269 at r9](https://reviewable.io/reviews/pmem/pmemstream/160#-N-7nZTM6mArIHqs2ymF:-N-7nZTM6mArIHqs2ymG:b-34vro1) ([raw file](https://github.com/pmem/pmemstream/blob/6361042cddc2095a85ed3272816775d0aa0928d5/tests/common/stream_helpers.hpp#L269)):*
> ```cpp
> 				      const std::vector<std::string> &data)
> 	{
> 		auto regions = std::vector<struct pmemstream_region>();
> ```

```cpp
std::vector<struct pmemstream_region> regions;
```



_Code quote:_
```cpp
auto regions = std::vector<struct pmemstream_region>();
```
___
*[tests/unittest/multi_region.cpp, line 84 at r9](https://reviewable.io/reviews/pmem/pmemstream/160#-N-7zD5wC-ttYo4iFdzG:-N-7zD5wC-ttYo4iFdzH:bffqlg0) ([raw file](https://github.com/pmem/pmemstream/blob/6361042cddc2095a85ed3272816775d0aa0928d5/tests/unittest/multi_region.cpp#L84)):*
> ```cpp
> 
> 			stream.helpers.remove_region(stream.helpers.get_region(to_delete_pos).offset);
> 			RC_ASSERT(no_regions - 1 == regions.size() - 1);
> ```

```cpp
RC_ASSERT(no_regions == regions.size());
```



_Code quote:_
```cpp
RC_ASSERT(no_regions - 1 == regions.size() - 1);
```
___
*[tests/unittest/multi_region.cpp, line 94 at r9](https://reviewable.io/reviews/pmem/pmemstream/160#-N-7zYqv72pNgVehaE-3:-N-7zYqv72pNgVehaE-4:bp6764j) ([raw file](https://github.com/pmem/pmemstream/blob/6361042cddc2095a85ed3272816775d0aa0928d5/tests/unittest/multi_region.cpp#L94)):*
> ```cpp
> 
> 			/* remove random (unique) regions */
> 			auto to_delete_poss =
> ```

why not?
```cpp
auto to_delete_poss = *rc::gen::unique<std::vector<size_t>>(rc::gen::inRange<size_t>(1, no_regions));
// RC_PRE(to_delete_poss.size() > 0);
```



_Code quote:_
```cpp
			auto to_delete_poss =
				*rc::gen::unique<std::vector<size_t>>(rc::gen::inRange<size_t>(0, no_regions));
			RC_PRE(to_delete_poss.size() > 0);
```

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/160)* status: 17 of 19 files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[tests/common/stream_helpers.hpp, line 269 at r9](https://reviewable.io/reviews/pmem/pmemstream/160#-N-7nZTM6mArIHqs2ymF:-N-80BII2EQq6LCIGMMv:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/6361042cddc2095a85ed3272816775d0aa0928d5/tests/common/stream_helpers.hpp#L269)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

```cpp
std::vector<struct pmemstream_region> regions;
```
</blockquote></details>

Done.
___
*[tests/unittest/multi_region.cpp, line 84 at r9](https://reviewable.io/reviews/pmem/pmemstream/160#-N-7zD5wC-ttYo4iFdzG:-N-82Iwe-o6GPVzAaJS3:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/6361042cddc2095a85ed3272816775d0aa0928d5/tests/unittest/multi_region.cpp#L84)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

```cpp
RC_ASSERT(no_regions == regions.size());
```
</blockquote></details>

Done.
___
*[tests/unittest/multi_region.cpp, line 94 at r9](https://reviewable.io/reviews/pmem/pmemstream/160#-N-7zYqv72pNgVehaE-3:-N-80E8T0rp7DwEUUmV3:b-px4yti) ([raw file](https://github.com/pmem/pmemstream/blob/6361042cddc2095a85ed3272816775d0aa0928d5/tests/unittest/multi_region.cpp#L94)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

why not?
```cpp
auto to_delete_poss = *rc::gen::unique<std::vector<size_t>>(rc::gen::inRange<size_t>(1, no_regions));
// RC_PRE(to_delete_poss.size() > 0);
```
</blockquote></details>

That is not the same. It's vector's size check, not the numbers within that vector.

**Pull request merged**
