### PR TITLE
Multithreaded benchmark

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/117)

### CODE REVIEW

**Comment by karczex** [comment]
___
*[benchmarks/measure.hpp, line 85 at r1](https://reviewable.io/reviews/pmem/pmemstream/117#-MvY1sPG3nM1XB9R-RJ8:-MvY1sPG3nM1XB9R-RJ9:bmt4uac) ([raw file](https://github.com/pmem/pmemstream/blob/e1763131234d0b2fe64a5e8189e9557d13e16d45/benchmarks/measure.hpp#L85)):*
> ```cpp
> 		workload->initialize();
> 		parallel_xexec(concurency, [&](size_t id, std::function<void(void)> syncthreads) {
> 			std::vector<ResultsType> thread_results;
> ```

As @kfilipek said, this vector is not needed.

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/117)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[benchmarks/measure.hpp, line 88 at r1](https://reviewable.io/reviews/pmem/pmemstream/117#-MvYGA3k-bNU69Kig7Cj:-MvYGA3k-bNU69Kig7Ck:b-trhfb) ([raw file](https://github.com/pmem/pmemstream/blob/e1763131234d0b2fe64a5e8189e9557d13e16d45/benchmarks/measure.hpp#L88)):*
> ```cpp
> 			syncthreads();
> 
> 			thread_results.push_back(measure<TimeUnit>([&]() { workload->perform(); }));
> ```

push back is not thread safe - this will crash. Instead, you should preallocate the vector with size 'concurrency' and then, here just do: thread_results[id] = ...;
___
*[benchmarks/measure.hpp, line 90 at r1](https://reviewable.io/reviews/pmem/pmemstream/117#-MvYGNof7xfcDFHRAGSV:-MvYGNof7xfcDFHRAGSW:be7uip7) ([raw file](https://github.com/pmem/pmemstream/blob/e1763131234d0b2fe64a5e8189e9557d13e16d45/benchmarks/measure.hpp#L90)):*
> ```cpp
> 			thread_results.push_back(measure<TimeUnit>([&]() { workload->perform(); }));
> 
> 			merge_results(thread_results);
> ```

You can do:

```
syncthreads();
if (id == 0) {
 merge_results(...);
}
```

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/117)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor and @KFilipek)

___
*[benchmarks/CMakeLists.txt, line 20 at r1](https://reviewable.io/reviews/pmem/pmemstream/117#-MvYCG9nCAolS9vd85qE:-MvYmmC79qJbVs7QLel5:b-xd7kex) ([raw file](https://github.com/pmem/pmemstream/blob/e1763131234d0b2fe64a5e8189e9557d13e16d45/benchmarks/CMakeLists.txt#L20)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

https://stackoverflow.com/questions/39598323/how-to-properly-link-libraries-with-cmake
</blockquote></details>

It seems I'm properly linking pthread.

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/117)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[benchmarks/CMakeLists.txt, line 20 at r2](https://reviewable.io/reviews/pmem/pmemstream/117#-MvYtG6GAVGiEDnal2TJ:-MvYtG6GAVGiEDnal2TK:b-aiirpd) ([raw file](https://github.com/pmem/pmemstream/blob/2d7a52f6dc45ce81fd33081c9226890e33add34a/benchmarks/CMakeLists.txt#L20)):*
> ```CMake
> 	add_executable(benchmark-${name} ${srcs})
> 	add_dependencies(benchmarks benchmark-${name})
> 	target_link_libraries(benchmark-${name} ${LIBPMEM2_LIBRARIES} ${LIBPMEMLOG_LIBRARIES} pmemstream pthread)
> ```

Use "${CMAKE_THREAD_LIBS_INIT}" instead of hardcoding pthreads
___
*[benchmarks/append/CMakeLists.txt, line 17 at r2](https://reviewable.io/reviews/pmem/pmemstream/117#-MvYtTFY6CTf1LmyDMSh:-MvYtTFY6CTf1LmyDMSi:b-aiirpd) ([raw file](https://github.com/pmem/pmemstream/blob/2d7a52f6dc45ce81fd33081c9226890e33add34a/benchmarks/append/CMakeLists.txt#L17)):*
> ```CMake
> 
> add_executable(benchmark-append main.cpp)
> target_link_libraries(benchmark-append ${LIBPMEMSTREAM_LIBRARIES} ${LIBPMEMLOG_LIBRARIES} pthread)
> ```

Use "${CMAKE_THREAD_LIBS_INIT}" instead of hardcoding pthreads

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/117#-:-MvZ0d_e2cjmf_iT2CFR:bnfp4nl)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor and @KFilipek)

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/117)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[benchmarks/measure.hpp, line 77 at r3](https://reviewable.io/reviews/pmem/pmemstream/117#-MvZCPYCEIBT0NHV1FBY:-MvZCPYD-IZA7WbfGN7q:bt06x4h) ([raw file](https://github.com/pmem/pmemstream/blob/2f21c6b8048d59c5fa2c6a1bb634a861a33afa77/benchmarks/measure.hpp#L77)):*
> ```cpp
> 		workload->initialize();
> 		std::vector<ResultsType> iteration_results(concurency);
> 		parallel_xexec(concurency, [&](size_t id, std::function<void(void)> syncthreads) {
> ```

please rebase and add synchthreads also after assigning to iterator_results

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/117)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[benchmarks/append/main.cpp, line 83 at r3](https://reviewable.io/reviews/pmem/pmemstream/117#-MvZGuLl-4ztbwYHECc9:-MvZGuLl-4ztbwYHECcA:bobqek7) ([raw file](https://github.com/pmem/pmemstream/blob/2f21c6b8048d59c5fa2c6a1bb634a861a33afa77/benchmarks/append/main.cpp#L83)):*
> ```cpp
> 		app_name = std::string(argv[0]);
> 		int ch;
> 		while ((ch = getopt_long(argc, argv, "e:p:x:b:r:c:s:i:nt:h", long_options, NULL)) != -1) {
> ```

why is it together with "n" (like ":nt:")?

**Comment by karczex** [comment]
___
*[benchmarks/append/main.cpp, line 83 at r3](https://reviewable.io/reviews/pmem/pmemstream/117#-MvZGuLl-4ztbwYHECc9:-MvbvZzV4_08f-tmb43A:bmt75wp) ([raw file](https://github.com/pmem/pmemstream/blob/2f21c6b8048d59c5fa2c6a1bb634a861a33afa77/benchmarks/append/main.cpp#L83)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why is it together with "n" (like ":nt:")?
</blockquote></details>

it's not together, it's bizarre notation of getopt :) `:` means, argument is not a flag
```
i:nt:h == i<with parameter>n<just a flag>t<withparameter>h<just a flag>
```

however, as I sad, getopt is really tricky, please make double check with documentation https://linux.die.net/man/3/getopt_long

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/117)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[benchmarks/measure.hpp, line 77 at r3](https://reviewable.io/reviews/pmem/pmemstream/117#-MvZCPYCEIBT0NHV1FBY:-MvcCqZ6B6grCK9A_JKm:b-1nqv4e) ([raw file](https://github.com/pmem/pmemstream/blob/2f21c6b8048d59c5fa2c6a1bb634a861a33afa77/benchmarks/measure.hpp#L77)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

please rebase and add synchthreads also after assigning to iterator_results
</blockquote></details>

and I believe Igor asked also for the extra syncthreads after the 'measure'
___
*[benchmarks/measure.hpp, line 68 at r4](https://reviewable.io/reviews/pmem/pmemstream/117#-MvcCfBk2UIBpvfPHM1e:-MvcCfBk2UIBpvfPHM1f:brbvm6e) ([raw file](https://github.com/pmem/pmemstream/blob/c2379d089a9aab8119e652fea214f1b5f7dcae21/benchmarks/measure.hpp#L68)):*
> ```cpp
>  * functions are executed respectively before and after each iteration */
> template <typename TimeUnit>
> auto measure(size_t iterations, workload_base *workload, size_t concurency = 1)
> ```

hah, pls rename to `concurrency` (CI found you a typo :smile: )
___
*[benchmarks/append/main.cpp, line 83 at r3](https://reviewable.io/reviews/pmem/pmemstream/117#-MvZGuLl-4ztbwYHECc9:-MvcAu549FabCzM6W93Z:b414wfp) ([raw file](https://github.com/pmem/pmemstream/blob/2f21c6b8048d59c5fa2c6a1bb634a861a33afa77/benchmarks/append/main.cpp#L83)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

it's not together, it's bizarre notation of getopt :) `:` means, argument is not a flag
```
i:nt:h == i<with parameter>n<just a flag>t<withparameter>h<just a flag>
```

however, as I sad, getopt is really tricky, please make double check with documentation https://linux.die.net/man/3/getopt_long 
</blockquote></details>

haha, ok, mea culpa :smile: 

I believe you're absolutely correct

**Comment by karczex** [comment]
___
*[benchmarks/measure.hpp, line 77 at r3](https://reviewable.io/reviews/pmem/pmemstream/117#-MvZCPYCEIBT0NHV1FBY:-MvcFVCG5cTVtYSvsYvy:be27f99) ([raw file](https://github.com/pmem/pmemstream/blob/2f21c6b8048d59c5fa2c6a1bb634a861a33afa77/benchmarks/measure.hpp#L77)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

and I believe Igor asked also for the extra syncthreads after the 'measure'
</blockquote></details>

It's not needed. There is `join()` at the end of `parallel_exec()` so merge of the data is done when all measurements are already done.

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/117)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[benchmarks/measure.hpp, line 77 at r3](https://reviewable.io/reviews/pmem/pmemstream/117#-MvZCPYCEIBT0NHV1FBY:-MvcGy4F4hxaIHxMYu0q:b-n8nhj8) ([raw file](https://github.com/pmem/pmemstream/blob/2f21c6b8048d59c5fa2c6a1bb634a861a33afa77/benchmarks/measure.hpp#L77)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It's not needed. There is `join()` at the end of `parallel_exec()` so merge of the data is done when all measurements are already done.
</blockquote></details>

Not necessarily. join wait for a thread to finish - however, it's possible for that thread to finish sooner.

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/117)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[benchmarks/measure.hpp, line 77 at r3](https://reviewable.io/reviews/pmem/pmemstream/117#-MvZCPYCEIBT0NHV1FBY:-MvcHApG3JiYsbeW19fJ:b-cv16dm) ([raw file](https://github.com/pmem/pmemstream/blob/2f21c6b8048d59c5fa2c6a1bb634a861a33afa77/benchmarks/measure.hpp#L77)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Not necessarily. join wait for a thread to finish - however, it's possible for that thread to finish sooner.
</blockquote></details>

I mean, you are true regarding merging of data but the fact that some threads have finished sooner might impact performance

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/117#-:-MvcIPBU2eE-9TBPyGW5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Pull request merged**
