### PR TITLE
CI:add TEST_DIR removal to self-hosted workflow

### PR DESCRIPTION
**Pull request by tszczyp**
Added secret variable for TEST_DIR

Added step to remove TEST_DIR at the end of job

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/209)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/209)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @igchor and @tszczyp)

___
*[`.github/workflows/self_hosted.yml` line 28 at r1](https://reviewable.io/reviews/pmem/pmemstream/209#-N3dQXbE9s0B_YM2VelR:-N3dQXbE9s0B_YM2VelS:b-8nrn57) ([raw file](https://github.com/pmem/pmemstream/blob/43a916c893eee3f65bd87935c9bc161e5e8d0698/.github/workflows/self_hosted.yml#L28)):*
> ```YAML
> 
>         - name: Test dir cleanup
>           if: always()
> ```

you don't need this `if` I belive
___
*[`.github/workflows/self_hosted.yml` line 29 at r1](https://reviewable.io/reviews/pmem/pmemstream/209#-N3dQUh17R5EKUF1wfGk:-N3dQUh17R5EKUF1wfGl:bcbc7ao) ([raw file](https://github.com/pmem/pmemstream/blob/43a916c893eee3f65bd87935c9bc161e5e8d0698/.github/workflows/self_hosted.yml#L29)):*
> ```YAML
>         - name: Test dir cleanup
>           if: always()
>           run: rm -rf ${{ env.PMEMSTREAM_TEST_DIR }}
> ```

missing endline

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/209)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @igchor, @karczex, and @tszczyp)

___
*[`.github/workflows/self_hosted.yml` line 28 at r1](https://reviewable.io/reviews/pmem/pmemstream/209#-N3dQXbE9s0B_YM2VelR:-N3dZL2M6puIVoCmnfaT:b95nmnc) ([raw file](https://github.com/pmem/pmemstream/blob/43a916c893eee3f65bd87935c9bc161e5e8d0698/.github/workflows/self_hosted.yml#L28)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

you don't need this `if` I belive
</blockquote></details>

You definitely need it :) 
https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs

**Review by tszczyp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/209)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @igchor and @karczex)

___
*[`.github/workflows/self_hosted.yml` line 28 at r1](https://reviewable.io/reviews/pmem/pmemstream/209#-N3dQXbE9s0B_YM2VelR:-N3xlr3H-BspYdDR2ISt:b-mv95ro) ([raw file](https://github.com/pmem/pmemstream/blob/43a916c893eee3f65bd87935c9bc161e5e8d0698/.github/workflows/self_hosted.yml#L28)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

You definitely need it :) 
https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs
</blockquote></details>

That's right it is needed.
___
*[`.github/workflows/self_hosted.yml` line 29 at r1](https://reviewable.io/reviews/pmem/pmemstream/209#-N3dQUh17R5EKUF1wfGk:-N3xlp-u8tLAVlt25WvR:bo5dlyc) ([raw file](https://github.com/pmem/pmemstream/blob/43a916c893eee3f65bd87935c9bc161e5e8d0698/.github/workflows/self_hosted.yml#L29)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

missing endline
</blockquote></details>

endline added.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/209#-:-N416m3M4EQ8UXYDVlNI:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @karczex)

**Comment by karczex** [comment]
*[`.github/workflows/self_hosted.yml` line 15 at r3](https://reviewable.io/reviews/pmem/pmemstream/209#-N41fOPI1IP0tqa34Kfl:-N41fOPI1IP0tqa34Kfm:b-jtsd1g) ([raw file](https://github.com/pmem/pmemstream/blob/c2a6f3ed252b80c96fffe9b191827eb71b57b1c5/.github/workflows/self_hosted.yml#L15)):*
> ```YAML
>         os: [[self-hosted, ubuntu]]
>     env:
>       PMEMSTREAM_TEST_DIR: ${{ secrets.SELF_HOSTED_RUNNERS_TEST_DIR }}/${{ github.job }}
> ```

It seems secrets doesn't work on PRs :/  
So you have to change to partially hardcoded `/mnt/pmem0/${{github.job }} 



_Code quote:_
```YAML
 ${{ secrets.SELF_HOSTED_RUNNERS_TEST_DIR }}
```

**Review by tszczyp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/209)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @karczex)

___
*[`.github/workflows/self_hosted.yml` line 15 at r3](https://reviewable.io/reviews/pmem/pmemstream/209#-N41fOPI1IP0tqa34Kfl:-N46TmnXBgOaw5pWfFP8:b40i7rt) ([raw file](https://github.com/pmem/pmemstream/blob/c2a6f3ed252b80c96fffe9b191827eb71b57b1c5/.github/workflows/self_hosted.yml#L15)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It seems secrets doesn't work on PRs :/  
So you have to change to partially hardcoded `/mnt/pmem0/${{github.job }} 
</blockquote></details>

Well yes but since they does work when migrated, maybe we could leave it as it is :) 
I had no issues in my fork when I was testing this.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/209)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @karczex)

___
*[`.github/workflows/self_hosted.yml` line 15 at r3](https://reviewable.io/reviews/pmem/pmemstream/209#-N41fOPI1IP0tqa34Kfl:-N4QfXt1E4yuN3vqEiuZ:bn9ltyn) ([raw file](https://github.com/pmem/pmemstream/blob/c2a6f3ed252b80c96fffe9b191827eb71b57b1c5/.github/workflows/self_hosted.yml#L15)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Well yes but since they does work when migrated, maybe we could leave it as it is :) 
I had no issues in my fork when I was testing this. 
</blockquote></details>

we discussed it later on, that it will not work on PRs (after merging this).
I'm guessing, you've tested only push events on your fork and did not test PR on your own fork, that's why it worked :wink: 

I believe, we have to drop this idea and not use secrets here.

**Review by tszczyp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/209)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[`.github/workflows/self_hosted.yml` line 15 at r3](https://reviewable.io/reviews/pmem/pmemstream/209#-N41fOPI1IP0tqa34Kfl:-N4WXEqP2vuuSpwjDifU:b9xa8h8) ([raw file](https://github.com/pmem/pmemstream/blob/c2a6f3ed252b80c96fffe9b191827eb71b57b1c5/.github/workflows/self_hosted.yml#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we discussed it later on, that it will not work on PRs (after merging this).
I'm guessing, you've tested only push events on your fork and did not test PR on your own fork, that's why it worked :wink: 

I believe, we have to drop this idea and not use secrets here.
</blockquote></details>

Alright, done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/209)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor, @karczex, and @tszczyp)

___
*[`-- commits` line 4 at r4](https://reviewable.io/reviews/pmem/pmemstream/209#-N4WmNTC8XIDnetuFQvh):*
pls update

**Review by tszczyp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/209)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[`-- commits` line 4 at r4](https://reviewable.io/reviews/pmem/pmemstream/209#-N4WmNTC8XIDnetuFQvh):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls update
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/209#-:-N4WpfdW3iYQQ9C6t7jM:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @karczex)

___
*[`-- commits` line 4 at r4](https://reviewable.io/reviews/pmem/pmemstream/209#-N4WmNTC8XIDnetuFQvh):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx!

**Pull request merged**
