### PR TITLE
Size checks

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/88)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/88#-:-MuF_umyDoFLxt0I63U0:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[src/libpmemstream.c, line 44 at r1](https://reviewable.io/reviews/pmem/pmemstream/88#-MuFZvEz8Qe36mRLOUMS:-MuFZvF-4N193WSLVBlU:b-grifba) ([raw file](https://github.com/pmem/pmemstream/blob/cc361fb47d0c6da3f6107b797b2500687d1096dc/src/libpmemstream.c#L44)):*
> ```C
> 
> static size_t pmemstream_usable_size(size_t stream_size, size_t block_size)
> {
> ```

nit: maybe add assert(stream_size >= sizeof(pmemstream_data)?
___
*[src/libpmemstream.c, line 130 at r1](https://reviewable.io/reviews/pmem/pmemstream/88#-MuF_70p4RDMT-jsUFAv:-MuF_70p4RDMT-jsUFAw:bg1k7kz) ([raw file](https://github.com/pmem/pmemstream/blob/cc361fb47d0c6da3f6107b797b2500687d1096dc/src/libpmemstream.c#L130)):*
> ```C
> 	size = ALIGN_UP(size, stream->block_size);
> 
> 	if (size > stream->usable_size) {
> ```

hm, actually isn't this check basically the same (even less specific) as the one below? (with srt.empty.size)?
___
*[tests/unittest/create.cpp, line 68 at r1](https://reviewable.io/reviews/pmem/pmemstream/88#-MuF_XQ89Fryf3PG0V7y:-MuF_XQ89Fryf3PG0V7z:b-8lxxyv) ([raw file](https://github.com/pmem/pmemstream/blob/cc361fb47d0c6da3f6107b797b2500687d1096dc/tests/unittest/create.cpp#L68)):*
> ```cpp
> 			});
> 
> 		ret += rc::check("verify if region of region_size = 0 cannot be created", [&]() {
> ```

This does not have to be a rapidhcheck test anymore (with rapidcheck it will be repeated 100 times).

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/88)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor and @karczex)

___
*[src/libpmemstream.c, line 44 at r1](https://reviewable.io/reviews/pmem/pmemstream/88#-MuFZvEz8Qe36mRLOUMS:-MuFvTnl7b_p_DwjkGVb:bh9c7se) ([raw file](https://github.com/pmem/pmemstream/blob/cc361fb47d0c6da3f6107b797b2500687d1096dc/src/libpmemstream.c#L44)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

nit: maybe add assert(stream_size >= sizeof(pmemstream_data)?
</blockquote></details>

as discussed - even more - we may check `- size of (empty) entry`

... and at best, we may set up a public variable/define for minimal stream size (something like `PMEMOBJ_MIN_POOL`) 
___
*[tests/unittest/create.cpp, line 68 at r1](https://reviewable.io/reviews/pmem/pmemstream/88#-MuF_XQ89Fryf3PG0V7y:-MuG0Wis9bPoxh7uVo_K:b-bcepld) ([raw file](https://github.com/pmem/pmemstream/blob/cc361fb47d0c6da3f6107b797b2500687d1096dc/tests/unittest/create.cpp#L68)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This does not have to be a rapidhcheck test anymore (with rapidcheck it will be repeated 100 times).
</blockquote></details>

yeah, that's why it wasn't an RC test :wink: 
___
*[tests/unittest/create.cpp, line 102 at r1](https://reviewable.io/reviews/pmem/pmemstream/88#-MuG3cSw-jo99pVr78M3:-MuG3cSw-jo99pVr78M4:b-35ie07) ([raw file](https://github.com/pmem/pmemstream/blob/cc361fb47d0c6da3f6107b797b2500687d1096dc/tests/unittest/create.cpp#L102)):*
> ```cpp
> 				1UL, TEST_DEFAULT_STREAM_SIZE / 2UL - STREAM_METADATA_SIZE);
> 
> 			auto region_size = block_size / 10UL;
> ```

Now, using this `RC_PRE` we are not tied to this `/ 10UL` part. Right now we're probably not testing the small block sizes

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/88#-:-MvP0cIP-vtQhygIyR7i:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor and @karczex)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/88)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 130 at r1](https://reviewable.io/reviews/pmem/pmemstream/88#-MuF_70p4RDMT-jsUFAv:-MuFx15h0MPtEJGymW4a:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cc361fb47d0c6da3f6107b797b2500687d1096dc/src/libpmemstream.c#L130)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

hm, actually isn't this check basically the same (even less specific) as the one below? (with srt.empty.size)?
</blockquote></details>

Done.
___
*[tests/unittest/create.cpp, line 68 at r1](https://reviewable.io/reviews/pmem/pmemstream/88#-MuF_XQ89Fryf3PG0V7y:-MuFjyg-A58wn_qq9vqK:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cc361fb47d0c6da3f6107b797b2500687d1096dc/tests/unittest/create.cpp#L68)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

yeah, that's why it wasn't an RC test :wink: 
</blockquote></details>

Done.
___
*[tests/unittest/create.cpp, line 102 at r1](https://reviewable.io/reviews/pmem/pmemstream/88#-MuG3cSw-jo99pVr78M3:-MvYckkd0PKIsBf5Q-pl:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/cc361fb47d0c6da3f6107b797b2500687d1096dc/tests/unittest/create.cpp#L102)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Now, using this `RC_PRE` we are not tied to this `/ 10UL` part. Right now we're probably not testing the small block sizes
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/88)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Pull request merged**
