### PR TITLE
Region allocator

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/154)

### CODE REVIEW

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 9 of 10 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/154#-:-MzFZ7oZBol0M8UVaXWG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by karczex — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/154)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[src/iterator.c, line 45 at r2](https://reviewable.io/reviews/pmem/pmemstream/154#-MzFmNuT4MsXsSjFgSlA:-MzFmNuT4MsXsSjFgSlB:b2nign6) ([raw file](https://github.com/pmem/pmemstream/blob/c616de962f1dddf321587cfb5644e22bf0f06851/src/iterator.c#L45)):*
> ```C
> 	*region = it->region;
> 
> 	/* XXX: hide this in allocator? */
> ```

yes

**Comment by KFilipek** [comment]
> > Reviewed 1 of 3 files at r2.
> > _[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/154)_ status: all files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)
> 
> _[src/iterator.c, line 45 at r2](https://reviewable.io/reviews/pmem/pmemstream/154#-MzFmNuT4MsXsSjFgSlA:-MzFmNuT4MsXsSjFgSlB:b2nign6) ([raw file](https://github.com/pmem/pmemstream/blob/c616de962f1dddf321587cfb5644e22bf0f06851/src/iterator.c#L45)):_
> 
> > ```c
> > 	*region = it->region;
> > 
> > 	/* XXX: hide this in allocator? */
> > ```
> 
> yes

As we talked earlier, I will push it to separate PR

**Review by KFilipek — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/154)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex and @lukaszstolarczuk)

**Review by KFilipek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/154)* status: all files reviewed, 10 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[src/iterator.c, line 45 at r2](https://reviewable.io/reviews/pmem/pmemstream/154#-MzFmNuT4MsXsSjFgSlA:-MzGQiXTCfRMP4gdb604:b49wi0h) ([raw file](https://github.com/pmem/pmemstream/blob/c616de962f1dddf321587cfb5644e22bf0f06851/src/iterator.c#L45)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Igor can drop `?` in this comment then :smile:
</blockquote></details>

I think it doesn't matter, this comment will die in 1 day xD
___
*[src/iterator.c, line 27 at r4](https://reviewable.io/reviews/pmem/pmemstream/154#-MzG5vOMEdPUsXMktWQk:-MzGQLOy8QbZWAZyJaF0:b-19cfdd) ([raw file](https://github.com/pmem/pmemstream/blob/c398d20755d0f1bb32a0297a994876c2c9f102d1/src/iterator.c#L27)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`.tail`?
</blockquote></details>

Here, we create forward iterator to iterate from the beginning, so it have to start from the head, not tail.
___
*[src/region.c, line 248 at r4](https://reviewable.io/reviews/pmem/pmemstream/154#-MzG6miJ6XvyTqXN1kd8:-MzGRDX15FzLmeAzS305:b-7b0gst) ([raw file](https://github.com/pmem/pmemstream/blob/c398d20755d0f1bb32a0297a994876c2c9f102d1/src/region.c#L248)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you deleted lots of "SPAN_EMPTY" usage due to usage of region allocator - do we still need it? // not necessarily to be done now
</blockquote></details>

In this file there is no changes compared base to actual state :)

**Comment by karczex** [comment]
___
*[src/span.h, line 42 at r4](https://reviewable.io/reviews/pmem/pmemstream/154#-MzLVSLo2N89tvWowxlB:-MzLVSLo2N89tvWowxlC:b-80ythm) ([raw file](https://github.com/pmem/pmemstream/blob/c398d20755d0f1bb32a0297a994876c2c9f102d1/src/span.h#L42)):*
> ```objc
> 
> 	/* XXX: CACHELINE_SIZE */
> 	uint64_t padding[(64 - sizeof(struct span_base) - sizeof(struct allocator_metadata)) / 8];
> ```

You may add to util.h generic facility  for  padding computation

```C
#define CACHELINE 64

typedef struct empty{
} empty;

#define SIZES_SUM(...) (SIZES_SUM_I(__VA_ARGS__, empty, empty, empty, empty, empty, empty, empty, empty))
#define SIZES_SUM_I(a, b, c, d, e, f, g, h, ...) (sizeof(a) + sizeof(b) + sizeof(c) + sizeof(d) + sizeof(e) + sizeof(f) + sizeof(g) + sizeof(h))
#define CACHELINE_PADDING_SIZE(...) ((CACHELINE  - (SIZES_SUM(__VA_ARGS__) % CACHELINE) )  / 8)
```

and use it 
```
uint64_t padding[CACHELINE_PADDING_SIZE(struct span_base, struct allocator_metadata)];
```



_Code quote:_
```objc
(64 - sizeof(struct span_base) - sizeof(struct allocator_metadata)) / 8
```

**Comment by karczex** [comment]
___
*[src/span.h, line 42 at r4](https://reviewable.io/reviews/pmem/pmemstream/154#-MzLVSLo2N89tvWowxlB:-MzOVLhJ0aK3TZPKwvOP:bzetlp1) ([raw file](https://github.com/pmem/pmemstream/blob/c398d20755d0f1bb32a0297a994876c2c9f102d1/src/span.h#L42)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

You may add to util.h generic facility  for  padding computation

```C
#define CACHELINE 64

typedef struct empty{
} empty;

#define SIZES_SUM(...) (SIZES_SUM_I(__VA_ARGS__, empty, empty, empty, empty, empty, empty, empty, empty))
#define SIZES_SUM_I(a, b, c, d, e, f, g, h, ...) (sizeof(a) + sizeof(b) + sizeof(c) + sizeof(d) + sizeof(e) + sizeof(f) + sizeof(g) + sizeof(h))
#define CACHELINE_PADDING_SIZE(...) ((CACHELINE  - (SIZES_SUM(__VA_ARGS__) % CACHELINE) )  / 8)
```

and use it 
```
uint64_t padding[CACHELINE_PADDING_SIZE(struct span_base, struct allocator_metadata)];
```
</blockquote></details>

It seems my proposal is gcc specific, so please ignore it.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/154)* status: all files reviewed, 9 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[src/region_allocator/allocator_base.h, line 21 at r2](https://reviewable.io/reviews/pmem/pmemstream/154#-MzFgpzaAeR4pL8I3nQa:-MzPA-W-5pXS5VeqKr-z:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c616de962f1dddf321587cfb5644e22bf0f06851/src/region_allocator/allocator_base.h#L21)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

at the first glimpse, I'm not sure why there are `free_offset` and `offset_to_free` :smile: 

maybe `next/last_free_offset` & `current_free_offset` (+ info why is it current/temporarily stored)... or maybe just rename to the second one to `recovery_free_offset`
</blockquote></details>

Done.
___
*[src/region_allocator/allocator_base.h, line 24 at r2](https://reviewable.io/reviews/pmem/pmemstream/154#-MzFg1keCYiyzI0lqud4:-MzPAJIm-1dZudhldqfU:bb6un1j) ([raw file](https://github.com/pmem/pmemstream/blob/c616de962f1dddf321587cfb5644e22bf0f06851/src/region_allocator/allocator_base.h#L24)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you could add some/any comments in this PR, pls :wink: 
</blockquote></details>

Done
___
*[src/region_allocator/allocator_base.h, line 48 at r2](https://reviewable.io/reviews/pmem/pmemstream/154#-MzFU9Gd6P_wFc3uNQny:-MzPAWZ99vladpLUDPC2:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c616de962f1dddf321587cfb5644e22bf0f06851/src/region_allocator/allocator_base.h#L48)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

\+ ` /* LIBPMEMSTREAM_ALLOCATOR_BASE_H */`
</blockquote></details>

Done.
___
*[src/region_allocator/region_allocator.h, line 21 at r2](https://reviewable.io/reviews/pmem/pmemstream/154#-MzFUSen34ZXAjMEoPZA:-MzPAX2DBfeA5BxIhOC8:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c616de962f1dddf321587cfb5644e22bf0f06851/src/region_allocator/region_allocator.h#L21)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/region_allocator/region_allocator.c, line 55 at r2](https://reviewable.io/reviews/pmem/pmemstream/154#-MzFWdHV8FJy9KUPMmXc:-MzPAeYI8rwGQeJhL9GD:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c616de962f1dddf321587cfb5644e22bf0f06851/src/region_allocator/region_allocator.c#L55)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's `allocated_list` actually
</blockquote></details>

Done.
___
*[src/region_allocator/region_allocator.c, line 69 at r4](https://reviewable.io/reviews/pmem/pmemstream/154#-MzG5ebGExScksT_tILd:-MzPAezcCxs4XYUMcP0r:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c398d20755d0f1bb32a0297a994876c2c9f102d1/src/region_allocator/region_allocator.c#L69)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/154)* status: 5 of 12 files reviewed, 9 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[-- commits, line 11 at r2](https://reviewable.io/reviews/pmem/pmemstream/154#-MzFJHAgCaom-H-eUpp1):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`to singly linked` (misspell and no "-")
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/154)* status: 5 of 12 files reviewed, 10 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/154#-MzPQm8b266ikAkXvUcA:-MzPQm8cCW5hTboRwoio:b-pf1u28) (no related file):*
@karczex I've improved the alignement code here: https://github.com/pmem/pmemstream/pull/158/files

---

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 7 files at r5, 1 of 4 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/154)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 164 at r8](https://reviewable.io/reviews/pmem/pmemstream/154#-MzPj7ZO5uyRhC3Jac96:-MzPj7ZO5uyRhC3Jac97:bmk5nu6) ([raw file](https://github.com/pmem/pmemstream/blob/c34b5c543daf38166bd27d23f09318f5c1365c75/src/libpmemstream.c#L164)):*
> ```C
> // necessary to hold on to it and explicitly delete it.
> /* XXX: add test for multiple regions, when supported */
> int pmemstream_region_allocate(struct pmemstream *stream, size_t size, struct pmemstream_region *region)
> ```

pls add info that for now we require regions of a constant size
___
*[src/region_allocator/allocator_base.h, line 28 at r8](https://reviewable.io/reviews/pmem/pmemstream/154#-MzPCg_364n_1wOc2_Qx:-MzPCg_364n_1wOc2_Qy:bp7l9js) ([raw file](https://github.com/pmem/pmemstream/blob/c34b5c543daf38166bd27d23f09318f5c1365c75/src/region_allocator/allocator_base.h#L28)):*
> ```objc
> };
> 
> struct allocator_entry_metadata {
> ```

`entry`? perhaps `span`...?
___
*[src/region_allocator/region_allocator.c, line 101 at r8](https://reviewable.io/reviews/pmem/pmemstream/154#-MzPlMYF2eh9oSYtoqip:-MzPlMYG971YXpP50laD:b-qp4mxb) ([raw file](https://github.com/pmem/pmemstream/blob/c34b5c543daf38166bd27d23f09318f5c1365c75/src/region_allocator/region_allocator.c#L101)):*
> ```C
> 	}
> 
> 	struct span_region *allocator_region_free_span =
> ```

it's a local variable, I guess you can drop `allocator_region_`
___
*[src/region_allocator/region_allocator.c, line 125 at r8](https://reviewable.io/reviews/pmem/pmemstream/154#-MzPlPyy9ArhSPvcftEQ:-MzPlPyy9ArhSPvcftER:b-plr3os) ([raw file](https://github.com/pmem/pmemstream/blob/c34b5c543daf38166bd27d23f09318f5c1365c75/src/region_allocator/region_allocator.c#L125)):*
> ```C
> 				   size_t size)
> {
> 	uint64_t allocator_region_free = header->free_list.head;
> ```

. (just `free_region` ?)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/154)* status: 8 of 13 files reviewed, 5 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 164 at r8](https://reviewable.io/reviews/pmem/pmemstream/154#-MzPj7ZO5uyRhC3Jac96:-MzPofoPCf4Mxb-EjT6S:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c34b5c543daf38166bd27d23f09318f5c1365c75/src/libpmemstream.c#L164)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add info that for now we require regions of a constant size
</blockquote></details>

Done.
___
*[src/region_allocator/allocator_base.h, line 28 at r8](https://reviewable.io/reviews/pmem/pmemstream/154#-MzPCg_364n_1wOc2_Qx:-MzPoga33Ny-FD4K-etd:b-pux9r4) ([raw file](https://github.com/pmem/pmemstream/blob/c34b5c543daf38166bd27d23f09318f5c1365c75/src/region_allocator/allocator_base.h#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`entry`? perhaps `span`...?
</blockquote></details>

Allocator base does not know anything about spans.
___
*[src/region_allocator/region_allocator.c, line 101 at r8](https://reviewable.io/reviews/pmem/pmemstream/154#-MzPlMYF2eh9oSYtoqip:-MzPoxji4ZLaeC6__tVn:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c34b5c543daf38166bd27d23f09318f5c1365c75/src/region_allocator/region_allocator.c#L101)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's a local variable, I guess you can drop `allocator_region_`
</blockquote></details>

Done.
___
*[src/region_allocator/region_allocator.c, line 125 at r8](https://reviewable.io/reviews/pmem/pmemstream/154#-MzPlPyy9ArhSPvcftEQ:-MzPoxuj7pdiz0QB8x6i:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c34b5c543daf38166bd27d23f09318f5c1365c75/src/region_allocator/region_allocator.c#L125)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

. (just `free_region` ?)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 5 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/154#-:-MzPuUTd3unfIE980jw7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/region_allocator/allocator_base.h, line 28 at r8](https://reviewable.io/reviews/pmem/pmemstream/154#-MzPCg_364n_1wOc2_Qx:-MzPuK1e9kGlJzcFIhxs:b1g9tpw) ([raw file](https://github.com/pmem/pmemstream/blob/c34b5c543daf38166bd27d23f09318f5c1365c75/src/region_allocator/allocator_base.h#L28)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Allocator base does not know anything about spans.
</blockquote></details>

this `entry` just sounds weird :wink: but I guess it can stay...

**Comment by karczex** [comment]
*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/154#-MzPQm8b266ikAkXvUcA:-MzUUpsu6EnKo8GmjKtM:b-a6p6f0) (no related file):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

@karczex I've improved the alignement code here: https://github.com/pmem/pmemstream/pull/158/files
</blockquote></details>

That's really good change, thx.

---

**Review by KFilipek — APPROVED** [review]
> Reviewed 2 of 7 files at r5, 2 of 5 files at r9, 1 of 4 files at r11, 1 of 4 files at r13, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/154)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Review by karczex — COMMENTED** [review]
> Reviewed 2 of 10 files at r1, 1 of 5 files at r3, 1 of 5 files at r9, 1 of 4 files at r13, 2 of 3 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/154)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Review by karczex — COMMENTED** [review]
Except that, some  of XXXs are super important :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/154#-:-MzUlgnK87xwSOJhua2c:b-e6ngjs)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Pull request merged**
