### PR TITLE
add basic CMake functionalities

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
**Disclaimer:** I'm not 100% sure if everything works perfectly, but this will be a base for our next changes

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/3)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/3)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 288 at r1](https://reviewable.io/reviews/pmem/pmemstream/3#-Mnz-Lm2A9YA1iF8qyJt:-Mnz-Lm2A9YA1iF8qyJu:bl3qazh) ([raw file](https://github.com/pmem/pmemstream/blob/da192ddf5126b6a5ae8703c2b4cb6a12ecdd60bf/CMakeLists.txt#L288)):*
> ```CMake
> # XXX: set it up within the source dir (and its own CMake file) ? do we need this?
> # set up project's include dir (our source 'include' dir)
> # include_directories(include)
> ```

I think this is not needed, similar as in pmemkv, right?
___
*[cmake/functions.cmake, line 81 at r1](https://reviewable.io/reviews/pmem/pmemstream/3#-Mnz-XkQ1C368DAgc8Aw:-Mnz-XkQ1C368DAgc8Ax:btqu8k5) ([raw file](https://github.com/pmem/pmemstream/blob/da192ddf5126b6a5ae8703c2b4cb6a12ecdd60bf/cmake/functions.cmake#L81)):*
> ```CMake
> endmacro()
> 
> macro(add_sanitizer_flag flag)
> ```

Maybe a comment that this works for C compiler? Or maybe make it a parameter?

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/3)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[cmake/functions.cmake, line 81 at r1](https://reviewable.io/reviews/pmem/pmemstream/3#-Mnz-XkQ1C368DAgc8Aw:-MnzTHWN5MANQea6r1pt:b-1c7rpn) ([raw file](https://github.com/pmem/pmemstream/blob/da192ddf5126b6a5ae8703c2b4cb6a12ecdd60bf/cmake/functions.cmake#L81)):*
> Maybe a comment that this works for C compiler? Or maybe make it a parameter?

As I see it's for gcc, not only g++, but some options are available only in C++ like: -fsanitize=return
https://gcc.gnu.org/onlinedocs/gcc-7.3.0/gcc/Instrumentation-Options.html
___
*[cmake/libpmemstream.pc.in, line 10 at r1](https://reviewable.io/reviews/pmem/pmemstream/3#-MnzUMvbCf6KwKmRp3XT:-MnzUMvbCf6KwKmRp3XU:bo0wqwr) ([raw file](https://github.com/pmem/pmemstream/blob/da192ddf5126b6a5ae8703c2b4cb6a12ecdd60bf/cmake/libpmemstream.pc.in#L10)):*
> ```
> ··
> ```
two spaces at the end

**Review by karczex — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/3)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[cmake/functions.cmake, line 34 at r1](https://reviewable.io/reviews/pmem/pmemstream/3#-Mnz4pwnBhD3x3tXT2k6:-Mnz4pwnBhD3x3tXT2k7:be1crws) ([raw file](https://github.com/pmem/pmemstream/blob/da192ddf5126b6a5ae8703c2b4cb6a12ecdd60bf/cmake/functions.cmake#L34)):*
> ```CMake
> # 1st: a compiler flag to add
> # 2nd: (optional) a build type (DEBUG, RELEASE, ...), by default appends to common variable
> macro(add_c_flag flag)
> ```

Does it have to be macro? Cmake macros seems to be tricky monsters. 
___
*[src/CMakeLists.txt, line 5 at r1](https://reviewable.io/reviews/pmem/pmemstream/3#-Mnzno-6BOEblI3sWstF:-MnznlXF4TcQNTUReIc2:b-c35vaz) ([raw file](https://github.com/pmem/pmemstream/blob/da192ddf5126b6a5ae8703c2b4cb6a12ecdd60bf/src/CMakeLists.txt#L5)):*
> ```
> *.[ch]
> ```
we probably want to mach also cpp and hpp files
___
*[src/CMakeLists.txt, line 9 at r1](https://reviewable.io/reviews/pmem/pmemstream/3#-MnznugI6_J1SwZ_pNzh:-MnznugI6_J1SwZ_pNzi:b3kqx) ([raw file](https://github.com/pmem/pmemstream/blob/da192ddf5126b6a5ae8703c2b4cb6a12ecdd60bf/src/CMakeLists.txt#L9)):*
> ```CMake
> 
> add_check_whitespace(src
> 	${CMAKE_CURRENT_SOURCE_DIR}/*.[ch]
> ```

.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/3)* status: 3 of 7 files reviewed, 4 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[CMakeLists.txt, line 288 at r1](https://reviewable.io/reviews/pmem/pmemstream/3#-Mnz-Lm2A9YA1iF8qyJt:-MnzZl9i4ZaFi_i4e7L9:b-z982gn) ([raw file](https://github.com/pmem/pmemstream/blob/da192ddf5126b6a5ae8703c2b4cb6a12ecdd60bf/CMakeLists.txt#L288)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think this is not needed, similar as in pmemkv, right?
</blockquote></details>

it seems so, done
___
*[cmake/functions.cmake, line 34 at r1](https://reviewable.io/reviews/pmem/pmemstream/3#-Mnz4pwnBhD3x3tXT2k6:-MnzrHjYATGVxlLixG9E:b4i99l8) ([raw file](https://github.com/pmem/pmemstream/blob/da192ddf5126b6a5ae8703c2b4cb6a12ecdd60bf/cmake/functions.cmake#L34)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Does it have to be macro? Cmake macros seems to be tricky monsters. 
</blockquote></details>

tbh, I'm not sure, but I personally, wouldn't change it right now, since I can't test it properly. There is some trickery (I'm not fully familiar with) on how macros setup variables (here we don't see any "global scope" usage and probably it would be required in function).
___
*[cmake/functions.cmake, line 81 at r1](https://reviewable.io/reviews/pmem/pmemstream/3#-Mnz-XkQ1C368DAgc8Aw:-MnzZjz18LQk7hVfmm5X:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/da192ddf5126b6a5ae8703c2b4cb6a12ecdd60bf/cmake/functions.cmake#L81)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> Maybe a comment that this works for C compiler? Or maybe make it a parameter?

As I see it's for gcc, not only g++, but some options are available only in C++ like: -fsanitize=return
https://gcc.gnu.org/onlinedocs/gcc-7.3.0/gcc/Instrumentation-Options.html
</blockquote></details>

Done.
___
*[cmake/libpmemstream.pc.in, line 10 at r1](https://reviewable.io/reviews/pmem/pmemstream/3#-MnzUMvbCf6KwKmRp3XT:-MnzYrRFC-FN9l0WKI4w:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/da192ddf5126b6a5ae8703c2b4cb6a12ecdd60bf/cmake/libpmemstream.pc.in#L10)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> ··
> ```
two spaces at the end
</blockquote></details>

Done.
___
*[src/CMakeLists.txt, line 5 at r1](https://reviewable.io/reviews/pmem/pmemstream/3#-Mnzno-6BOEblI3sWstF:-MnzriEmA7ueCrUniBca:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/da192ddf5126b6a5ae8703c2b4cb6a12ecdd60bf/src/CMakeLists.txt#L5)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

> ```
> *.[ch]
> ```
we probably want to mach also cpp and hpp files
</blockquote></details>

Done.
___
*[src/CMakeLists.txt, line 9 at r1](https://reviewable.io/reviews/pmem/pmemstream/3#-MnznugI6_J1SwZ_pNzh:-MnzritC4QVUpZBCN2Jj:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/da192ddf5126b6a5ae8703c2b4cb6a12ecdd60bf/src/CMakeLists.txt#L9)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/3#-:-MnztNKj6oksePqj8JCK:bnfp4nl)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @karczex and @KFilipek)

**Review by KFilipek — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/3)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/3#-:-Mo--j309-yrNolLvW3H:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
