### PR TITLE
Fix SLIST_REMOVE while remove nonexisting offset

### PR DESCRIPTION
**Pull request by KFilipek**
Since this PR removing nonexisting element takes no effect.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/162)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/162)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/singly_linked_list.h, line 181 at r1](https://reviewable.io/reviews/pmem/pmemstream/162#-MzzN0Ht71Ik0fLA1FQy:-MzzN0Hu9L5S7kreK6cG:b822nxu) ([raw file](https://github.com/pmem/pmemstream/blob/e69ee3e4c1a9b8568effd4204a30dfa614019d5a/src/singly_linked_list.h#L181)):*
> ```objc
> 			uint64_t curelm = (list)->head;                                                                \
> 			uint64_t next;                                                                                 \
> 			while ((next = SLIST_NEXT(type, runtime, curelm, field)) != offset) {                          \
> ```

why not just:

```
while (SLIST_NEXT(type, runtime, curelm, field) != offset && SLIST_NEXT(type, runtime, curelm, field) != SLIST_INVALID_OFFSET) {
    curelm = SLIST_NEXT(type, runtime, curelm, field);
}
if (curelm == SLIST_INVALID_OFFSET) break;
...
```

?

It would be a bit simpler I think

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/162)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[-- commits, line 3 at r2](https://reviewable.io/reviews/pmem/pmemstream/162#-N--HPFWCLh2rmghbqeR):*
FYI, `nonexistent` is the correct form :wink: 
___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/pmem/pmemstream/162#-N--H1DMBLUAGpd8nbUb):*
pls drop `Since this commit` (perhaps add "now" somewhere here)
___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/pmem/pmemstream/162#-N--AWeq8xG-Ch0kVe0n):*
?
___
*[tests/unittest/singly_linked_list.cpp, line 205 at r2](https://reviewable.io/reviews/pmem/pmemstream/162#-N--I56Y83F3Z5XBZdgB:-N--I56Y83F3Z5XBZdgC:b-f3qmve) ([raw file](https://github.com/pmem/pmemstream/blob/edaf09d6a8f0b59a4b6fa78e1d6fe0215d8df72d/tests/unittest/singly_linked_list.cpp#L205)):*
> ```cpp
> 	});
> 
> 	rc::check("Remove nonexisting element don't change list", [](const std::vector<struct node> &data) {
> ```

1. Removing
2. nonexistent
3. doesn't
4. a/the list
___
*[tests/unittest/singly_linked_list.cpp, line 224 at r2](https://reviewable.io/reviews/pmem/pmemstream/162#-N--IYtX43nFFho5FP7l:-N--IYtX43nFFho5FP7m:bybrlt4) ([raw file](https://github.com/pmem/pmemstream/blob/edaf09d6a8f0b59a4b6fa78e1d6fe0215d8df72d/tests/unittest/singly_linked_list.cpp#L224)):*
> ```cpp
> 		}
> 
> 		uint64_t out_of_bound_offset = offset + sizeof(struct node);
> ```

FYI, I think `offset` should be already out-of-bound
___
*[tests/unittest/singly_linked_list.cpp, line 225 at r2](https://reviewable.io/reviews/pmem/pmemstream/162#-N--JWWC9kGDJCnglIrW:-N--JWWDEIDtjszIOHaA:bgy2b66) ([raw file](https://github.com/pmem/pmemstream/blob/edaf09d6a8f0b59a4b6fa78e1d6fe0215d8df72d/tests/unittest/singly_linked_list.cpp#L225)):*
> ```cpp
> 
> 		uint64_t out_of_bound_offset = offset + sizeof(struct node);
> 		SLIST_REMOVE(struct node, &runtime, &list, out_of_bound_offset, next);
> ```

1. you can randomize this removal (any random offset "after" the list)
2. you can try this in a loop = remove more than one value

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/162)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/singly_linked_list.h, line 181 at r1](https://reviewable.io/reviews/pmem/pmemstream/162#-MzzN0Ht71Ik0fLA1FQy:-N-1ieFcCM4QBCMzHqMY:b-l8i8t9) ([raw file](https://github.com/pmem/pmemstream/blob/e69ee3e4c1a9b8568effd4204a30dfa614019d5a/src/singly_linked_list.h#L181)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why not just:

```
while (SLIST_NEXT(type, runtime, curelm, field) != offset && SLIST_NEXT(type, runtime, curelm, field) != SLIST_INVALID_OFFSET) {
    curelm = SLIST_NEXT(type, runtime, curelm, field);
}
if (curelm == SLIST_INVALID_OFFSET) break;
...
```

?

It would be a bit simpler I think
</blockquote></details>

@igchor  I'm not sure. It's probably better to dereference this ptr only once. Compiler probably may optimize it, but you never know :)  

And both are equally unreadable/undebugable :) 
___
*[tests/unittest/singly_linked_list.cpp, line 225 at r2](https://reviewable.io/reviews/pmem/pmemstream/162#-N--JWWC9kGDJCnglIrW:-N-1klmDDc_rR-zvyS0s:b-j1ok07) ([raw file](https://github.com/pmem/pmemstream/blob/edaf09d6a8f0b59a4b6fa78e1d6fe0215d8df72d/tests/unittest/singly_linked_list.cpp#L225)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. you can randomize this removal (any random offset "after" the list)
2. you can try this in a loop = remove more than one value
</blockquote></details>

1st option seems to be reasonable.
___
*[tests/unittest/singly_linked_list.cpp, line 227 at r2](https://reviewable.io/reviews/pmem/pmemstream/162#-N-1m0ht0JcPEstkOhan:-N-1m0ht0JcPEstkOhao:b-43y11) ([raw file](https://github.com/pmem/pmemstream/blob/edaf09d6a8f0b59a4b6fa78e1d6fe0215d8df72d/tests/unittest/singly_linked_list.cpp#L227)):*
> ```cpp
> 		SLIST_REMOVE(struct node, &runtime, &list, out_of_bound_offset, next);
> 
> 		/* Check correctness */
> ```

You may move this check to function, as it's copied from another test.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/162)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[src/singly_linked_list.h, line 181 at r1](https://reviewable.io/reviews/pmem/pmemstream/162#-MzzN0Ht71Ik0fLA1FQy:-N-1qi47B40cTLOzzNBY:b-i2kk64) ([raw file](https://github.com/pmem/pmemstream/blob/e69ee3e4c1a9b8568effd4204a30dfa614019d5a/src/singly_linked_list.h#L181)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

@igchor  I'm not sure. It's probably better to dereference this ptr only once. Compiler probably may optimize it, but you never know :)  

And both are equally unreadable/undebugable :) 
</blockquote></details>

heh, @karczex - I think it's already done :wink (see previous, slightly different version)
___
*[tests/unittest/singly_linked_list.cpp, line 225 at r2](https://reviewable.io/reviews/pmem/pmemstream/162#-N--JWWC9kGDJCnglIrW:-N-1qIBj744l1aMSuHL5:b-relhvb) ([raw file](https://github.com/pmem/pmemstream/blob/edaf09d6a8f0b59a4b6fa78e1d6fe0215d8df72d/tests/unittest/singly_linked_list.cpp#L225)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

1st option seems to be reasonable.
</blockquote></details>

actually, yeah, scratch the second option; it'll be covered by rapidcheck's 100 TCs

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/162)* status: all files reviewed, 7 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/162#-N-1zaQp4xjV_UY8jW0I:-N-1zaQp4xjV_UY8jW0J:bdraj68) (no related file):*
there's an "XXX" comment in the `region_allocator.c`, that you're fixing - please remove that comment

---

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/162)* status: all files reviewed, 8 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[src/singly_linked_list.h, line 173 at r2](https://reviewable.io/reviews/pmem/pmemstream/162#-N-29sz6DrTZeBcwmjho:-N-29sz6DrTZeBcwmjhp:b-1b3t8i) ([raw file](https://github.com/pmem/pmemstream/blob/edaf09d6a8f0b59a4b6fa78e1d6fe0215d8df72d/src/singly_linked_list.h#L173)):*
> ```objc
>  * remove will be rolled back).
>  */
> #define SLIST_REMOVE(type, runtime, list, offset, field)                                                               \
> ```

How about empty list? We should either check it here or fix it inside region_allocator

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/162)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/pmem/pmemstream/162#-N--H1DMBLUAGpd8nbUb):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls drop `Since this commit` (perhaps add "now" somewhere here)
</blockquote></details>

Done.
___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/pmem/pmemstream/162#-N--AWeq8xG-Ch0kVe0n):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[src/singly_linked_list.h, line 173 at r2](https://reviewable.io/reviews/pmem/pmemstream/162#-N-29sz6DrTZeBcwmjho:-N-99C6C3kLHvXP22zRK:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/edaf09d6a8f0b59a4b6fa78e1d6fe0215d8df72d/src/singly_linked_list.h#L173)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

How about empty list? We should either check it here or fix it inside region_allocator
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 205 at r2](https://reviewable.io/reviews/pmem/pmemstream/162#-N--I56Y83F3Z5XBZdgB:-N-9A2ua2q469gHLXIsS:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/edaf09d6a8f0b59a4b6fa78e1d6fe0215d8df72d/tests/unittest/singly_linked_list.cpp#L205)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. Removing
2. nonexistent
3. doesn't
4. a/the list
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list.cpp, line 225 at r2](https://reviewable.io/reviews/pmem/pmemstream/162#-N--JWWC9kGDJCnglIrW:-N-9F_mS1wWMzDPNAmww:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/edaf09d6a8f0b59a4b6fa78e1d6fe0215d8df72d/tests/unittest/singly_linked_list.cpp#L225)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

actually, yeah, scratch the second option; it'll be covered by rapidcheck's 100 TCs
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/162#-:-N-MlM3S7pfLsr2hpt-C:bnfp4nl)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/162#-:-N-Mvnp42YFkB-r1lWwU:bnfp4nl)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

**Pull request merged**
