### PR TITLE
Code fixes

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/56)

### CODE REVIEW

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/56#-:-MseFUG_CycpQ_I5SDBW:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/56)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/pmem/pmemstream/56#-MseYcCT2vmZ7maCcWqJ):*
typo: succeeded



_Code quote:_
```
suceeded
```
___
*[-- commits, line 9 at r1](https://reviewable.io/reviews/pmem/pmemstream/56#-MseZ_OG52r3QsykWUoX):*
drop it, it's not necessary to describe such small change, also it isn't true



_Code quote:_
```
return -1 if stream is not initialized.
```
___
*[src/libpmemstream.c, line 47 at r1](https://reviewable.io/reviews/pmem/pmemstream/56#-Mse_inFB08bxKnr_rwT:-Mse_inFB08bxKnr_rwU:bxh6uqa) ([raw file](https://github.com/pmem/pmemstream/blob/9d915fcc431235940e526ce26dd8c252079fa6b8/src/libpmemstream.c#L47)):*
also possible: `goto err;`
because of:
7.20.3.2:
>The free function causes the space pointed to by ptr to be deallocated, that is, made
>available for further allocation. If ptr is a null pointer, no action occurs.
But it's just informative.



_Code quote:_
```C
return -1;
```

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/56)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/pmem/pmemstream/56#-MseYcCT2vmZ7maCcWqJ):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

typo: succeeded
</blockquote></details>

Done.
___
*[-- commits, line 9 at r1](https://reviewable.io/reviews/pmem/pmemstream/56#-MseZ_OG52r3QsykWUoX):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

drop it, it's not necessary to describe such small change, also it isn't true
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/56#-:-Mt2WT8IDNrUdHFyxYzm:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/56#-:-MtCpd-FA1e_-8t1_NY_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
