### PR TITLE
Add test for recovery during recovery

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/228)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/228)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/228#-N5dOcEB6apT7Hq-nM78:-N5dOcEB6apT7Hq-nM79:bmzm1p4) (no related file):*
pls enable e.g. PMREORDER_STACKTRACE_DEPTH=20

___
___
*[`tests/cmake/exec_functions.cmake` line 303 at r1](https://reviewable.io/reviews/pmem/pmemstream/228#-N5dD8CBExdNUmCLyzH8:-N5dD8CBExdNUmCLyzH9:b-vq8yja) ([raw file](https://github.com/pmem/pmemstream/blob/1a38613abb6406e98b6ab232efbad1f9a32694ae/tests/cmake/exec_functions.cmake#L303)):*
> ```CMake
> # the command.
> function(pmreorder_execute expect_success engine conf_file name)
> 	#	check_target(${name})
> ```

you can add extra param "executable" (beside "name"), like e.g. here: https://github.com/pmem/pmemstream/blob/master/tests/cmake/functions.cmake#L203
___
*[`tests/integrity/crash_during_recovery.cmake` line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/228#-N5dMqh-3ygxQkXzRdHd:-N5dMqh-3ygxQkXzRdHe:br06351) ([raw file](https://github.com/pmem/pmemstream/blob/1a38613abb6406e98b6ab232efbad1f9a32694ae/tests/integrity/crash_during_recovery.cmake#L4)):*
> ```CMake
> # Copyright 2022, Intel Corporation
> 
> # XXX: In this script is some problem with SIGINT propagation, so after CTRL-C subtest's pmreorder is still
> ```

fix this comments pls and add more comments :-D
___
*[`tests/integrity/crash_during_recovery.cmake` line 9 at r1](https://reviewable.io/reviews/pmem/pmemstream/228#-N5dDvje2p8Ng2yjrcrE:-N5dDvje2p8Ng2yjrcrF:bis0foe) ([raw file](https://github.com/pmem/pmemstream/blob/1a38613abb6406e98b6ab232efbad1f9a32694ae/tests/integrity/crash_during_recovery.cmake#L9)):*
> ```CMake
> 
> # Run binary under pmreorder under pmreorder. ReorderPartial is used because ReorderAccumulative
> # would take to much time
> ```

too much
___
*[`tests/integrity/crash_during_recovery_subtest.cmake` line 12 at r1](https://reviewable.io/reviews/pmem/pmemstream/228#-N5dO_Ei9n_ddPzxWVfv:-N5dO_Ei9n_ddPzxWVfw:b4d9rio) ([raw file](https://github.com/pmem/pmemstream/blob/1a38613abb6406e98b6ab232efbad1f9a32694ae/tests/integrity/crash_during_recovery_subtest.cmake#L12)):*
> ```CMake
> message(STATUS "Running Subtest")
> 
> configure_file(${TEST_FILE} ${SUBTEST_FILE} COPYONLY)
> ```

not sure if needed...?

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/228)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[`tests/integrity/crash_during_recovery.cmake` line 1 at r1](https://reviewable.io/reviews/pmem/pmemstream/228#-N5dPxK-1XiE9bvs1cm0:-N5dPxK-1XiE9bvs1cm1:bojb8ri) ([raw file](https://github.com/pmem/pmemstream/blob/1a38613abb6406e98b6ab232efbad1f9a32694ae/tests/integrity/crash_during_recovery.cmake#L1)):*
> ```CMake
> # SPDX-License-Identifier: BSD-3-Clause
> ```

This tests only tests allocator, not per-region recovery (there are no appends in the test). I thought we wanted to test: https://github.com/pmem/pmemstream/blob/master/src/libpmemstream.c#L98
___
*[`tests/integrity/crash_during_recovery.cmake` line 2 at r1](https://reviewable.io/reviews/pmem/pmemstream/228#-N5dQ2gt42HLhFF5EJV1:-N5dQ2gt42HLhFF5EJV2:b79z8hn) ([raw file](https://github.com/pmem/pmemstream/blob/1a38613abb6406e98b6ab232efbad1f9a32694ae/tests/integrity/crash_during_recovery.cmake#L2)):*
> ```CMake
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2022, Intel Corporation
> ```

Also, this test performs pmemstream_region_free() inside check_consistency which makes this test not idempotent. The assumption is that you only call check_consistency once.

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/228)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[`tests/integrity/append_pmreorder.cpp` line 45 at r2](https://reviewable.io/reviews/pmem/pmemstream/228#-N6wHhv33Rp1G-63Ti6c:-N6wHhv33Rp1G-63Ti6d:bscb69p) ([raw file](https://github.com/pmem/pmemstream/blob/9a5ddd410c2ff190b0bce859339d3e7a3b63c42a/tests/integrity/append_pmreorder.cpp#L45)):*
> ```cpp
> 	struct pmemstream_test_base stream(copy_path, test_config.block_size, test_config.stream_size, no_truncate,
> 					   no_init);
> 	for (auto &region : stream.helpers.get_regions()) {
> ```

There should also be a testcase where we are allocating new region and appending to it (instead of appending to existing regions). This is because appending to existing will trigger per-region recovery. (possibly we would need to limit number of regions somehow or do free and allocate).

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/228)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[`tests/integrity/crash_during_recovery.cmake` line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/228#-N5dMqh-3ygxQkXzRdHd:-N70lLEi4wc2qWZBe3wj:b3t5wow) ([raw file](https://github.com/pmem/pmemstream/blob/1a38613abb6406e98b6ab232efbad1f9a32694ae/tests/integrity/crash_during_recovery.cmake#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

fix this comments pls and add more comments :-D
</blockquote></details>

fixed ;) https://github.com/pmem/pmdk/pull/5467
___
*[`tests/integrity/crash_during_recovery.cmake` line 9 at r1](https://reviewable.io/reviews/pmem/pmemstream/228#-N5dDvje2p8Ng2yjrcrE:-N70lA586GWAyDZsEjRJ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/1a38613abb6406e98b6ab232efbad1f9a32694ae/tests/integrity/crash_during_recovery.cmake#L9)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

too much
</blockquote></details>

Done.
___
*[`tests/integrity/crash_during_recovery_subtest.cmake` line 7 at r2](https://reviewable.io/reviews/pmem/pmemstream/228#-N6s7yru6jcg6_JtxjwA:-N70i5OY-gfw3KaGkXkU:b-x6yllg) ([raw file](https://github.com/pmem/pmemstream/blob/9a5ddd410c2ff190b0bce859339d3e7a3b63c42a/tests/integrity/crash_during_recovery_subtest.cmake#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do you need this?
</blockquote></details>

yes, it's needed by `pmreorder_create_store_log()`
___
*[`tests/integrity/append_pmreorder.cpp` line 45 at r2](https://reviewable.io/reviews/pmem/pmemstream/228#-N6wHhv33Rp1G-63Ti6c:-N71-LsR3ujmtc0bd8Vd:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/9a5ddd410c2ff190b0bce859339d3e7a3b63c42a/tests/integrity/append_pmreorder.cpp#L45)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

There should also be a testcase where we are allocating new region and appending to it (instead of appending to existing regions). This is because appending to existing will trigger per-region recovery. (possibly we would need to limit number of regions somehow or do free and allocate).
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/228)* status: 2 of 7 files reviewed, 6 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[`tests/integrity/crash_during_recovery_subtest.cmake` line 7 at r2](https://reviewable.io/reviews/pmem/pmemstream/228#-N6s7yru6jcg6_JtxjwA:-N7Ga83hEZOVKPV1f1Dk:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/9a5ddd410c2ff190b0bce859339d3e7a3b63c42a/tests/integrity/crash_during_recovery_subtest.cmake#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe just extend the check in that function `or ${tracer} STREQUAL ""`.

In our tests `""` and `none` are treated the same.
</blockquote></details>

Done.
___
*[`tests/integrity/append_to_new_region_pmreorder.cpp` line 49 at r4](https://reviewable.io/reviews/pmem/pmemstream/228#-N71Ghl38HkbvuqJNTOs:-N7Gsn9f1aRzaLViABKO:b5s85zr) ([raw file](https://github.com/pmem/pmemstream/blob/c39b1e7bd387d2831bfcee2ca53ea203f009ddbb/tests/integrity/append_to_new_region_pmreorder.cpp#L49)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

I removed this test for now.
___
*[`tests/integrity/append_pmreorder.cpp` line 45 at r2](https://reviewable.io/reviews/pmem/pmemstream/228#-N6wHhv33Rp1G-63Ti6c:-N7GsTnt2HhKRB6sXaVd:bpwr5p4) ([raw file](https://github.com/pmem/pmemstream/blob/9a5ddd410c2ff190b0bce859339d3e7a3b63c42a/tests/integrity/append_pmreorder.cpp#L45)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I implemented this test, but it needs some additional investigation, so I removed it from this PR. 
___
*[`tests/integrity/append_to_existing_region_pmreorder.cpp` line 12 at r4](https://reviewable.io/reviews/pmem/pmemstream/228#-N71HSiOE3uGMLpM9fF0:-N7GRKuQ8AS305AmVbn5:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c39b1e7bd387d2831bfcee2ca53ea203f009ddbb/tests/integrity/append_to_existing_region_pmreorder.cpp#L12)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess you can clean some of these up
</blockquote></details>

Done.
___
*[`tests/integrity/append_to_existing_region_pmreorder.cpp` line 13 at r4](https://reviewable.io/reviews/pmem/pmemstream/228#-N71I1e3DV6ktFgJxTPl:-N7Gb2N9-F4WpydEM0lU:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c39b1e7bd387d2831bfcee2ca53ea203f009ddbb/tests/integrity/append_to_existing_region_pmreorder.cpp#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add a short description for both of these tests (on top of the file), also with a clear difference between these two tests :wink: 
</blockquote></details>

Done.
___
*[`tests/integrity/append_to_existing_region_pmreorder.cpp` line 46 at r4](https://reviewable.io/reviews/pmem/pmemstream/228#-N71GVu-D0bfbZM_sjME:-N7Gb6kABdlyfYTBG7AZ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c39b1e7bd387d2831bfcee2ca53ea203f009ddbb/tests/integrity/append_to_existing_region_pmreorder.cpp#L46)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm region size is set to `TEST_DEFAULT_REGION_MULTI_SIZE` in these tests, I believe - pls make sure the calculations are proper and pls fix the comment, I guess :wink: 
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/228#-:-N7Kq_KuBs0yEa-WXBVU:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Review by igchor — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/228)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
