### PR TITLE
Change UT_ASSERT to UT_ASSERTeq where needed

### PR DESCRIPTION
**Pull request by karczex**
Change was done with little bit of regex engineering.
```
find -iname "*.cpp" | xargs sed -ri 's/UT_ASSERT\((.+)==(.+)\)/UT_ASSERTeq(\1,\2)/g'
```

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/119)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/119)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/pmem/pmemstream/119#-MvdBda44BRtRiDiTBHu):*
you should also grep .hpp and .c files

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/119)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/pmem/pmemstream/119#-MvdBda44BRtRiDiTBHu):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you should also grep .hpp and .c files
</blockquote></details>

still .c, I believe

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/119)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/pmem/pmemstream/119#-MvdBda44BRtRiDiTBHu):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

still .c, I believe
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/119#-:-MvdNGF0CxoDh5796_8s:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
