### PR TITLE
Add RC stateful singly linked list tests

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- [x] wait for merge of #145 
- [x] fix issue reported by UBSAN ( https://github.com/pmem/pmemstream/runs/5650629391?check_suite_focus=true#step:6:705 )

It's the first stateful test for singly linked list; more to come.
Please review only `unittest/singly_linked_list_ls.cpp` file.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/148)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/148)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/unittest/singly_linked_list_ls.cpp, line 47 at r2](https://reviewable.io/reviews/pmem/pmemstream/148#-MygMSjj8QGnhh9Xu-lb:-MygMSjj8QGnhh9Xu-lc:b-py039o) ([raw file](https://github.com/pmem/pmemstream/blob/00bc548d3545af8fc728c3a6b257badbfcc5b93f/tests/unittest/singly_linked_list_ls.cpp#L47)):*
> ```cpp
> }
> 
> struct singly_linked_list_model {
> ```

Couldn't we use just std::vector<struct node> as model?

then, apply for insert_tail is just `list.push_back(node)` where node can be generated in ctor and `run` can be `SLIST_INSERT_TAIL(..., TO_OFFSET(&m.back()), ...);

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/148)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/unittest/singly_linked_list_ls.cpp, line 47 at r2](https://reviewable.io/reviews/pmem/pmemstream/148#-MygMSjj8QGnhh9Xu-lb:-MygO5V45w2kgtKl_zp7:b-y91ule) ([raw file](https://github.com/pmem/pmemstream/blob/00bc548d3545af8fc728c3a6b257badbfcc5b93f/tests/unittest/singly_linked_list_ls.cpp#L47)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Couldn't we use just std::vector<struct node> as model?

then, apply for insert_tail is just `list.push_back(node)` where node can be generated in ctor and `run` can be `SLIST_INSERT_TAIL(..., TO_OFFSET(&m.back()), ...);
</blockquote></details>

Ok, nevermind, this can be problematic for inserting new items in the middle (offsets will change). But... how about just using normal., runtime pointers as offsets and normal std::list for model? You can the rely on 'data' field for checking list correctness. For example:

`runtime = {.spans = NULL, ...};

...

struct rc_insert_tail {
struct node node;

rc_insert_tail() {
     node = {.data = model.list.size() };
}

apply() {
     model.list.push_back(node);
}

run() {
   SLIST_INSERT_TAIL(..., (uint64_t) &model.back(), ...);
}
}
`

This should work because converting offset back to pointer will just subtract .span (which is 0) giving original pointer.

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/148)* status: all files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[tests/unittest/singly_linked_list_ls.cpp, line 50 at r2](https://reviewable.io/reviews/pmem/pmemstream/148#-MygiY_R0qFDdYcvfdTh:-MygiY_S41RvokcKoD7V:bsjy6xq) ([raw file](https://github.com/pmem/pmemstream/blob/00bc548d3545af8fc728c3a6b257badbfcc5b93f/tests/unittest/singly_linked_list_ls.cpp#L50)):*
> ```cpp
> 	singly_linked_list_model(std::vector<struct node> data)
> 	{
> 		offsets = {};
> ```

You can do that only in such way, using initializer list:
```cpp
	singly_linked_list_model(std::vector<struct node> data) : data(data)
	{
		offsets = {};
        }
```
It should do what you want and looks clean, also you can initialize std::list in the same way.



_Code quote:_
```cpp
	singly_linked_list_model(std::vector<struct node> data)
	{
		offsets = {};
		data = data;
```
___
*[tests/unittest/singly_linked_list_ls.cpp, line 75 at r2](https://reviewable.io/reviews/pmem/pmemstream/148#-Mygkr2d4oIzyAV92LvH:-Mygkr2d4oIzyAV92LvI:b-an5q5c) ([raw file](https://github.com/pmem/pmemstream/blob/00bc548d3545af8fc728c3a6b257badbfcc5b93f/tests/unittest/singly_linked_list_ls.cpp#L75)):*
> ```cpp
> using singly_linked_list_command = rc::state::Command<singly_linked_list_model, singly_linked_list_test>;
> 
> struct rc_insert_tail_command : public singly_linked_list_command {
> ```

Default inheritance visibility for structure is public, so it's not necessary to put extra public specifier or you're going to change all structures to classes.
Classes should looks more natural in this case.



_Code quote:_
```cpp
struct rc_insert_tail_command : public singly_linked_list_command
```
___
*[tests/unittest/singly_linked_list_ls.cpp, line 97 at r2](https://reviewable.io/reviews/pmem/pmemstream/148#-MygmwI1AQ5Ca8BIVB6K:-MygmwI1AQ5Ca8BIVB6L:b-cm2ln1) ([raw file](https://github.com/pmem/pmemstream/blob/00bc548d3545af8fc728c3a6b257badbfcc5b93f/tests/unittest/singly_linked_list_ls.cpp#L97)):*
> ```cpp
> 	void checkPreconditions(const singly_linked_list_model &m) const override
> 	{
> 		RC_PRE(m.offsets.size() > 0);
> ```

wrong place I thing, here should be an assert



_Code quote:_
```cpp
RC_PRE(m.offsets.size() > 0);
```
___
*[tests/unittest/singly_linked_list_ls.cpp, line 133 at r2](https://reviewable.io/reviews/pmem/pmemstream/148#-Mygmpo54j981Ly3xk8j:-Mygmpo54j981Ly3xk8k:b89orzu) ([raw file](https://github.com/pmem/pmemstream/blob/00bc548d3545af8fc728c3a6b257badbfcc5b93f/tests/unittest/singly_linked_list_ls.cpp#L133)):*
> ```cpp
> 		rc::check("Random inserts and removes should not break a list",
> 			  [](const std::vector<struct node> &data) {
> 				  singly_linked_list_model model(data);
> ```

RC_PRE should be placed here, discard wrong data and to generate the new one then initialize model.



_Code quote:_
```cpp
singly_linked_list_model model(data);
```

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/148)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @Karolina002 and @KFilipek)

___
*[tests/unittest/singly_linked_list_ls.cpp, line 47 at r2](https://reviewable.io/reviews/pmem/pmemstream/148#-MygMSjj8QGnhh9Xu-lb:-Myn48lUEx3tlhnlVG0Z:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/00bc548d3545af8fc728c3a6b257badbfcc5b93f/tests/unittest/singly_linked_list_ls.cpp#L47)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Ok, nevermind, this can be problematic for inserting new items in the middle (offsets will change). But... how about just using normal., runtime pointers as offsets and normal std::list for model? You can the rely on 'data' field for checking list correctness. For example:

`runtime = {.spans = NULL, ...};

...

struct rc_insert_tail {
struct node node;

rc_insert_tail() {
     node = {.data = model.list.size() };
}

apply() {
     model.list.push_back(node);
}

run() {
   SLIST_INSERT_TAIL(..., (uint64_t) &model.back(), ...);
}
}
`

This should work because converting offset back to pointer will just subtract .span (which is 0) giving original pointer.
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list_ls.cpp, line 50 at r2](https://reviewable.io/reviews/pmem/pmemstream/148#-MygiY_R0qFDdYcvfdTh:-Myn4B8x7_XT1hEfHRO1:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/00bc548d3545af8fc728c3a6b257badbfcc5b93f/tests/unittest/singly_linked_list_ls.cpp#L50)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

You can do that only in such way, using initializer list:
```cpp
	singly_linked_list_model(std::vector<struct node> data) : data(data)
	{
		offsets = {};
        }
```
It should do what you want and looks clean, also you can initialize std::list in the same way.
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list_ls.cpp, line 75 at r2](https://reviewable.io/reviews/pmem/pmemstream/148#-Mygkr2d4oIzyAV92LvH:-MyhJDGQ-TLFcAJfcazm:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/00bc548d3545af8fc728c3a6b257badbfcc5b93f/tests/unittest/singly_linked_list_ls.cpp#L75)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Default inheritance visibility for structure is public, so it's not necessary to put extra public specifier or you're going to change all structures to classes.
Classes should looks more natural in this case.
</blockquote></details>

Done.
___
*[tests/unittest/singly_linked_list_ls.cpp, line 97 at r2](https://reviewable.io/reviews/pmem/pmemstream/148#-MygmwI1AQ5Ca8BIVB6K:-MyhBTjlCA98eaG9g98J:b-dtgokk) ([raw file](https://github.com/pmem/pmemstream/blob/00bc548d3545af8fc728c3a6b257badbfcc5b93f/tests/unittest/singly_linked_list_ls.cpp#L97)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

wrong place I thing, here should be an assert
</blockquote></details>

nope - in `checkPreconditions` you want to discard the test case if it's not a proper one (before it's run). In this case, it means we have anything to remove from the model (and from the list).

RC_ASSERT is supposed to be used within a running TC to assert the proper result.
___
*[tests/unittest/singly_linked_list_ls.cpp, line 133 at r2](https://reviewable.io/reviews/pmem/pmemstream/148#-Mygmpo54j981Ly3xk8j:-MyhBEgvBhoyZaoC1CWd:bx0o57r) ([raw file](https://github.com/pmem/pmemstream/blob/00bc548d3545af8fc728c3a6b257badbfcc5b93f/tests/unittest/singly_linked_list_ls.cpp#L133)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

RC_PRE should be placed here, discard wrong data and to generate the new one then initialize model.
</blockquote></details>

it'd be a good update, but the approach is changed now.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/148)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[tests/unittest/singly_linked_list_state.cpp, line 11 at r4](https://reviewable.io/reviews/pmem/pmemstream/148#-Myq2hJMB5iQR3dYUuab:-Myq2hJMB5iQR3dYUuac:bxa6c2c) ([raw file](https://github.com/pmem/pmemstream/blob/af0e7cda8283dbdaa34eb5824041fa2ab3033c53/tests/unittest/singly_linked_list_state.cpp#L11)):*
> ```cpp
> #include "unittest.hpp"
> 
> #define RC_SLIST_UNORDERED (0U)
> ```

why not enum?
___
*[tests/unittest/singly_linked_list_state.cpp, line 11 at r4](https://reviewable.io/reviews/pmem/pmemstream/148#-Myq2r9I9l_7_NTvp9go:-Myq2r9I9l_7_NTvp9gp:b-2j7veq) ([raw file](https://github.com/pmem/pmemstream/blob/af0e7cda8283dbdaa34eb5824041fa2ab3033c53/tests/unittest/singly_linked_list_state.cpp#L11)):*
> ```cpp
> #include "unittest.hpp"
> 
> #define RC_SLIST_UNORDERED (0U)
> ```

is this unordered used anywhere?
___
*[tests/unittest/singly_linked_list_state.cpp, line 84 at r4](https://reviewable.io/reviews/pmem/pmemstream/148#-Myq147i4MD6IcrwJJRb:-Myq147j4i4hg-pEp5Kb:b2caoen) ([raw file](https://github.com/pmem/pmemstream/blob/af0e7cda8283dbdaa34eb5824041fa2ab3033c53/tests/unittest/singly_linked_list_state.cpp#L84)):*
> ```cpp
> 
> struct singly_linked_list_insert_command : singly_linked_list_command {
> 	struct node *n = NULL;
> ```

why not shared/unique ptr?

Or pehaps, instead of holding `struct node *n` inside command structure, we could just do allocate it inside run?
```
	void run(const singly_linked_list_model &m, singly_linked_list_test &s) const override
	{
                auto n = new node(m.counter);
		SLIST_INSERT_HEAD(struct node, &s.runtime, &s.sut, (uint64_t)n, next);
	}
```

And then manually call free after inside *remove_comand::run methods and also we can have a destructor for struct singly_linked_list_test which clears the list.

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/148)* status: 3 of 5 files reviewed, 9 unresolved discussions (waiting on @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[tests/unittest/singly_linked_list_state.cpp, line 104 at r4](https://reviewable.io/reviews/pmem/pmemstream/148#-Myq3-0J3snlx-pRpywJ:-Myq3-0J3snlx-pRpywK:bizsiit) ([raw file](https://github.com/pmem/pmemstream/blob/af0e7cda8283dbdaa34eb5824041fa2ab3033c53/tests/unittest/singly_linked_list_state.cpp#L104)):*
> ```cpp
> 	void apply(singly_linked_list_model &m) const override
> 	{
> 		m.list.push_front(n->data);
> ```

Hm, shouldn't you push m.counter here instead of n->data?
___
*[tests/unittest/singly_linked_list_state.cpp, line 110 at r4](https://reviewable.io/reviews/pmem/pmemstream/148#-Myq3MF68o89dfaWp0le:-Myq3MF68o89dfaWp0lf:b-t85xvc) ([raw file](https://github.com/pmem/pmemstream/blob/af0e7cda8283dbdaa34eb5824041fa2ab3033c53/tests/unittest/singly_linked_list_state.cpp#L110)):*
> ```cpp
> 	void run(const singly_linked_list_model &m, singly_linked_list_test &s) const override
> 	{
> 		SLIST_INSERT_HEAD(struct node, &s.runtime, &s.sut, (uint64_t)n, next);
> ```

shoudln't you set n->data to m.counter here?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/148)* status: 1 of 6 files reviewed, 6 unresolved discussions (waiting on @igchor, @Karolina002, and @KFilipek)

___
*[tests/unittest/singly_linked_list_state.cpp, line 11 at r4](https://reviewable.io/reviews/pmem/pmemstream/148#-Myq2hJMB5iQR3dYUuab:-MyqA_wo9Hr05Zm088ek:bnh7hog) ([raw file](https://github.com/pmem/pmemstream/blob/af0e7cda8283dbdaa34eb5824041fa2ab3033c53/tests/unittest/singly_linked_list_state.cpp#L11)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why not enum?
</blockquote></details>

huh :smile: done
___
*[tests/unittest/singly_linked_list_state.cpp, line 11 at r4](https://reviewable.io/reviews/pmem/pmemstream/148#-Myq2r9I9l_7_NTvp9go:-Myq9aR7AIDQ7dpv8eXX:bltssmq) ([raw file](https://github.com/pmem/pmemstream/blob/af0e7cda8283dbdaa34eb5824041fa2ab3033c53/tests/unittest/singly_linked_list_state.cpp#L11)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

is this unordered used anywhere?
</blockquote></details>

yes, the first test is totally random. In the verification command we just don't check for any ordering, in that case.
___
*[tests/unittest/singly_linked_list_state.cpp, line 84 at r4](https://reviewable.io/reviews/pmem/pmemstream/148#-Myq147i4MD6IcrwJJRb:-MyqApxuDwCLLydwoMKA:bfv3cg) ([raw file](https://github.com/pmem/pmemstream/blob/af0e7cda8283dbdaa34eb5824041fa2ab3033c53/tests/unittest/singly_linked_list_state.cpp#L84)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why not shared/unique ptr?

Or pehaps, instead of holding `struct node *n` inside command structure, we could just do allocate it inside run?
```
	void run(const singly_linked_list_model &m, singly_linked_list_test &s) const override
	{
                auto n = new node(m.counter);
		SLIST_INSERT_HEAD(struct node, &s.runtime, &s.sut, (uint64_t)n, next);
	}
```

And then manually call free after inside *remove_comand::run methods and also we can have a destructor for struct singly_linked_list_test which clears the list.


</blockquote></details>

as for unique/shared ptr - I just couldn't make it work, not sure why, but there was a problem with casting I couldn't solve :/

hmm not sure if that solution would be cleaner - in this case, we know who is the owner of the allocated object and there's little room for mistakes...?
___
*[tests/unittest/singly_linked_list_state.cpp, line 104 at r4](https://reviewable.io/reviews/pmem/pmemstream/148#-Myq3-0J3snlx-pRpywJ:-MyqBNFe23t7eQuCkZ17:beodp2x) ([raw file](https://github.com/pmem/pmemstream/blob/af0e7cda8283dbdaa34eb5824041fa2ab3033c53/tests/unittest/singly_linked_list_state.cpp#L104)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, shouldn't you push m.counter here instead of n->data?
</blockquote></details>

node is constructed already with the proper data
`n = new struct node(m.counter);`

I'm just incrementing the counter here, because the ctor has `const` access to model. (and in case the command will be discarded we won't lose that value)
___
*[tests/unittest/singly_linked_list_state.cpp, line 110 at r4](https://reviewable.io/reviews/pmem/pmemstream/148#-Myq3MF68o89dfaWp0le:-MyqBv-33boVuaz0P33i:b-diqwvc) ([raw file](https://github.com/pmem/pmemstream/blob/af0e7cda8283dbdaa34eb5824041fa2ab3033c53/tests/unittest/singly_linked_list_state.cpp#L110)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

shoudln't you set n->data to m.counter here?
</blockquote></details>

similarly, done in ctor

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/148)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @igchor, @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[tests/unittest/singly_linked_list_state.cpp, line 11 at r4](https://reviewable.io/reviews/pmem/pmemstream/148#-Myq2r9I9l_7_NTvp9go:-Myw_xGo9R51O2E7meJK:b-s7ebyt) ([raw file](https://github.com/pmem/pmemstream/blob/af0e7cda8283dbdaa34eb5824041fa2ab3033c53/tests/unittest/singly_linked_list_state.cpp#L11)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I don;t understand how it works, you verify the data based on this value but where do you use it to generate the data?
</blockquote></details>

Ok, nevermind, I see, you run different commands for ascending/descending. But still, why this ordering is important to you? Why can't you just compare SLIST with model list inside foreach command?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/148)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @igchor, @Karolina002, and @KFilipek)

___
*[tests/unittest/singly_linked_list_state.cpp, line 11 at r4](https://reviewable.io/reviews/pmem/pmemstream/148#-Myq2r9I9l_7_NTvp9go:-Mz-w10M72j9EjAOP3Tu:bc6fxex) ([raw file](https://github.com/pmem/pmemstream/blob/af0e7cda8283dbdaa34eb5824041fa2ab3033c53/tests/unittest/singly_linked_list_state.cpp#L11)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Ok, nevermind, I see, you run different commands for ascending/descending. But still, why this ordering is important to you? Why can't you just compare SLIST with model list inside foreach command?
</blockquote></details>

I've added some comments, I hope to make things more clear
___
*[tests/unittest/singly_linked_list_state.cpp, line 84 at r4](https://reviewable.io/reviews/pmem/pmemstream/148#-Myq147i4MD6IcrwJJRb:-Mz-vlrM11nQ26WOrt__:b-nbkh8n) ([raw file](https://github.com/pmem/pmemstream/blob/af0e7cda8283dbdaa34eb5824041fa2ab3033c53/tests/unittest/singly_linked_list_state.cpp#L84)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Can you copy/paste the error you got for shared_ptr?
</blockquote></details>

huh, actually I added this today once more and there were no errors, soo I guess I was just tired or something :smile:

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/148#-:-Mz-zP5w9ErXmyEWadBS:bnfp4nl)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @igchor, @Karolina002, and @KFilipek)

**Comment by igchor** [comment]
@lukaszstolarczuk please push the code once again, the build didn't trigger I think

**Review by KFilipek — APPROVED** [review]
PR author can "re-run jobs" in Github Actions instead of pushing the same code

> Reviewed 1 of 5 files at r3, 4 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/148#-:-MzEoi12-0yXz4AASXSf:bpymg93)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Comment by lukaszstolarczuk** [comment]
> PR author can "re-run jobs" in Github Actions instead of pushing the same code
> 
> > Reviewed 1 of 5 files at r3, 4 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/148#-:-MzEoi12-0yXz4AASXSf:bpymg93)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

FYI, anyone with "write" access can re-run... but there was nothing to re-run since GHA failed to start anything.

**Pull request merged**
