### PR TITLE
Add truncate flag to map_open.

### PR DESCRIPTION
**Pull request by igchor**
It will be useful for testing pmemstream after reopen.

Also, remove run_with_file.cmake which is not necessary - we can just
pass truncate flag to open.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/35)

### CODE REVIEW

**Review by karczex — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/35)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)

___
*[tests/common/unittest.h, line 86 at r1](https://reviewable.io/reviews/pmem/pmemstream/35#-Mr6xr690l1FsWwi4fu8:-Mr6xr6A2f-UMCrBxkf7:b-tigoaw) ([raw file](https://github.com/pmem/pmemstream/blob/65ef1052723c7e2fba45f27867818fb3d7f6d188/tests/common/unittest.h#L86)):*
> ```objc
>  * XXX: add granularity (and FILE_MODE?) as a param
>  */
> static inline struct pmem2_map *map_open(const char *file, size_t size, int truncate)
> ```

bool truncate?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/35)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[tests/common/unittest.h, line 86 at r1](https://reviewable.io/reviews/pmem/pmemstream/35#-Mr6xr690l1FsWwi4fu8:-Mr6ys40ELYqdakUw2iQ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/65ef1052723c7e2fba45f27867818fb3d7f6d188/tests/common/unittest.h#L86)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

bool truncate? 
</blockquote></details>

Done.

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/35#-:-Mr6z1_9C2vWpsGldsiJ:bnfp4nl)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @karczex)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/35#-:-Mr72oFDAysAoiABWzzi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
