### PR TITLE
Add more dockers

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
// preview with all builds: https://github.com/lukaszstolarczuk/pmemstream/actions/runs/1789531825
// one of the builds fail because of random fail (fixed after https://github.com/pmem/pmemstream/pull/88 )

- [x] at best, this should be merged after https://github.com/pmem/dev-utils-kit/pull/8 (TESTS_DEPS could be removed then)

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/108)

### CODE REVIEW

**Review by karczex — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/108)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[utils/docker/images/fedora-33.Dockerfile, line 10 at r1](https://reviewable.io/reviews/pmem/pmemstream/108#-MuznEOn4LwiijfbBUeP:-MuznEOn4LwiijfbBUeQ:bpj4lbp) ([raw file](https://github.com/pmem/pmemstream/blob/71b2f1ad650c8d46d00201b216a0910af0ac24aa/utils/docker/images/fedora-33.Dockerfile#L10)):*
> ```
> 
> # Pull base image
> FROM ghcr.io/pmem/dev-utils-kit:fedora-33-latest
> ```

fedora 33 is already eol, so I would rather not introduce it to pmemstream. 
___
*[utils/docker/images/ubuntu-21.10.Dockerfile, line 18 at r1](https://reviewable.io/reviews/pmem/pmemstream/108#-MuzoUea3FhbOkeStLgn:-MuzoUea3FhbOkeStLgo:bl1ucdj) ([raw file](https://github.com/pmem/pmemstream/blob/71b2f1ad650c8d46d00201b216a0910af0ac24aa/utils/docker/images/ubuntu-21.10.Dockerfile#L18)):*
> ```
> # Tests (optional)
> ARG TESTS_DEPS="\
> 	libc6-dbg"
> ```

why we need this dependency?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/108)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @igchor and @karczex)

___
*[utils/docker/images/fedora-33.Dockerfile, line 10 at r1](https://reviewable.io/reviews/pmem/pmemstream/108#-MuznEOn4LwiijfbBUeP:-MuzxxlMAHSuZg1iwsj2:b-ilk1ul) ([raw file](https://github.com/pmem/pmemstream/blob/71b2f1ad650c8d46d00201b216a0910af0ac24aa/utils/docker/images/fedora-33.Dockerfile#L10)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

fedora 33 is already eol, so I would rather not introduce it to pmemstream. 
</blockquote></details>

hah, distrowatch lied to me (it's not marked there as EOL yet) - good catch.
___
*[utils/docker/images/ubuntu-21.10.Dockerfile, line 18 at r1](https://reviewable.io/reviews/pmem/pmemstream/108#-MuzoUea3FhbOkeStLgn:-MuzymWHCM-M4QTr0BJv:b-r42adn) ([raw file](https://github.com/pmem/pmemstream/blob/71b2f1ad650c8d46d00201b216a0910af0ac24aa/utils/docker/images/ubuntu-21.10.Dockerfile#L18)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

why we need this dependency?
</blockquote></details>

I believe, we added it because it was useful with some additional debug info in case of failed tests...? @igchor, please correct me, if I'm wrong.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/108)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)

___
*[utils/docker/images/fedora-33.Dockerfile, line 10 at r1](https://reviewable.io/reviews/pmem/pmemstream/108#-MuznEOn4LwiijfbBUeP:-Mv3hOOSColn_7j5-OAg:b-kl9nyz) ([raw file](https://github.com/pmem/pmemstream/blob/71b2f1ad650c8d46d00201b216a0910af0ac24aa/utils/docker/images/fedora-33.Dockerfile#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hah, distrowatch lied to me (it's not marked there as EOL yet) - good catch.
</blockquote></details>

```
'Release N'' is supported until four weeks after the release of ''Release N+2''. 
```

**Review by KFilipek — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 1 of 7 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/108)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/108)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)

___
*[utils/docker/images/ubuntu-21.10.Dockerfile, line 18 at r1](https://reviewable.io/reviews/pmem/pmemstream/108#-MuzoUea3FhbOkeStLgn:-MvJL-Mc0gktjHacq1Sr:bpagful) ([raw file](https://github.com/pmem/pmemstream/blob/71b2f1ad650c8d46d00201b216a0910af0ac24aa/utils/docker/images/ubuntu-21.10.Dockerfile#L18)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe, we added it because it was useful with some additional debug info in case of failed tests...? @igchor, please correct me, if I'm wrong.
</blockquote></details>

No idea, probably we can do git blame to find out?

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/108#-:-MvJN6Tm2yT9-KjfUj6W:bnfp4nl)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)

**Pull request merged**
