### PR TITLE
[API] Add pmemstream_entry_timestamp()

### LINKED ISSUE #202: Expose `pmemstream_entry_timestamp(struct pmemstream_entry)`

### PR DESCRIPTION
**Pull request by KFilipek**
This function returns the timestamp assigned to the entry.

Closes #202.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/205)

### CODE REVIEW

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/205)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor and @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/205#-N3KPGWx0qdKK2bs-vdu:-N3KPGWx0qdKK2bs-vdv:b-118wjz) (no related file):*
please add tests

___
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/205#-N3KOE1eEKPMNRyVdBCC):*
It looks like this function's code is taken from Igor's PR, so please, at least, mention his name here :wink: 
___
*[`src/libpmemstream.c` line 320 at r1](https://reviewable.io/reviews/pmem/pmemstream/205#-N3KOcgS8XTus-nus4rb:-N3KOcgS8XTus-nus4rc:b-c7zc1j) ([raw file](https://github.com/pmem/pmemstream/blob/775af54292954092e88400363ede170213b6c3e5/src/libpmemstream.c#L320)):*
> ```C
> 	int ret = pmemstream_validate_stream_and_offset(stream, entry.offset);
> 	if (ret) {
> 		return 0;
> ```

@igchor, please see here - I think this is one of the reasons why `INVALID_TIMESTAMP=0` should be nice :wink: I know we should have here a proper error code and we don't use this function internally, but I believe in some situations such `0` might cause an issue, and be counted as a proper entry...
___
*[`src/include/libpmemstream.h` line 197 at r1](https://reviewable.io/reviews/pmem/pmemstream/205#-N3KPg4O8lumgTFHbaBj:-N3KPg4O8lumgTFHbaBk:bjmfngo) ([raw file](https://github.com/pmem/pmemstream/blob/775af54292954092e88400363ede170213b6c3e5/src/include/libpmemstream.h#L197)):*
> ```objc
> void pmemstream_entry_iterator_delete(struct pmemstream_entry_iterator **iterator);
> 
> uint64_t pmemstream_entry_timestamp(struct pmemstream *stream, struct pmemstream_entry entry);
> ```

pls move this up, to be next to `pmemstream_entry_length` (as you did in .c file)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/205)* status: all files reviewed, 4 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`src/libpmemstream.c` line 320 at r1](https://reviewable.io/reviews/pmem/pmemstream/205#-N3KOcgS8XTus-nus4rb:-N3KSB7X4jScDNeLCTAb:b3e8k4s) ([raw file](https://github.com/pmem/pmemstream/blob/775af54292954092e88400363ede170213b6c3e5/src/libpmemstream.c#L320)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

@igchor, please see here - I think this is one of the reasons why `INVALID_TIMESTAMP=0` should be nice :wink: I know we should have here a proper error code and we don't use this function internally, but I believe in some situations such `0` might cause an issue, and be counted as a proper entry...
</blockquote></details>

Hm, ok, so maybe let's keep PMEMSTREAM_INVALID_TIMESTAMP as 0, introduce PMEMSTREAM_FIRST_TIMESTAMP as 1 and add static_assert (PMEMSTREAM_FIRST_TIMESTAMP > PMEMSTREAM_INVALID_TIMESTAMP)? And then, from pmemstream_committed/persisted_timestamp we can return timestamp which is >= (instead of >) than max commited_timestamp.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/205)* status: all files reviewed, 3 unresolved discussions (waiting on @KFilipek)

___
*[`src/libpmemstream.c` line 320 at r1](https://reviewable.io/reviews/pmem/pmemstream/205#-N3KOcgS8XTus-nus4rb:-N3O5nDHEaxJ3QNaLPKT:b-hby4m1) ([raw file](https://github.com/pmem/pmemstream/blob/775af54292954092e88400363ede170213b6c3e5/src/libpmemstream.c#L320)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, ok, so maybe let's keep PMEMSTREAM_INVALID_TIMESTAMP as 0, introduce PMEMSTREAM_FIRST_TIMESTAMP as 1 and add static_assert (PMEMSTREAM_FIRST_TIMESTAMP > PMEMSTREAM_INVALID_TIMESTAMP)? And then, from pmemstream_committed/persisted_timestamp we can return timestamp which is >= (instead of >) than max commited_timestamp.
</blockquote></details>

I've added sine changes in https://github.com/pmem/pmemstream/pull/196 . Let's discuss more there if needed.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/205)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/205#-N3KOE1eEKPMNRyVdBCC):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

It looks like this function's code is taken from Igor's PR, so please, at least, mention his name here :wink: 
</blockquote></details>

Done.
___
*[`src/include/libpmemstream.h` line 197 at r1](https://reviewable.io/reviews/pmem/pmemstream/205#-N3KPg4O8lumgTFHbaBj:-N3OSH9J6fkCLG1kjIL0:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/775af54292954092e88400363ede170213b6c3e5/src/include/libpmemstream.h#L197)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls move this up, to be next to `pmemstream_entry_length` (as you did in .c file)
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/205)* status: 2 of 5 files reviewed, 8 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[`tests/api_c/timestamp.c` line 16 at r3](https://reviewable.io/reviews/pmem/pmemstream/205#-N3ZaMVE29edVczbEtAb:-N3ZlEcADWWo3hIhOyak:b210dwe) ([raw file](https://github.com/pmem/pmemstream/blob/c923bd409c76d2081613a597ef9c99cf11c7479d/tests/api_c/timestamp.c#L16)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Please initialize those variables. Coverity probably would scream anyway. 
</blockquote></details>

or just declare them when they are initialized (inside the loop)
___
*[`tests/api_c/timestamp.c` line 23 at r3](https://reviewable.io/reviews/pmem/pmemstream/205#-N3Zl6LY0C3Gshk2D3M2:-N3Zl6LY0C3Gshk2D3M3:b-ert70a) ([raw file](https://github.com/pmem/pmemstream/blob/c923bd409c76d2081613a597ef9c99cf11c7479d/tests/api_c/timestamp.c#L23)):*
> ```C
> 	ret = pmemstream_region_allocate(env.stream, TEST_DEFAULT_REGION_SIZE, &region);
> 	UT_ASSERTeq(ret, 0);
> 	for (int i = 0; i < 10; i++) {
> ```

magic value?
___
*[`tests/api_c/timestamp.c` line 28 at r3](https://reviewable.io/reviews/pmem/pmemstream/205#-N3ZlVncE24rubs2oImp:-N3ZlVncE24rubs2oImq:b-cbnqvp) ([raw file](https://github.com/pmem/pmemstream/blob/c923bd409c76d2081613a597ef9c99cf11c7479d/tests/api_c/timestamp.c#L28)):*
> ```C
> 
> 		timestamp = pmemstream_entry_timestamp(env.stream, entry);
> 		UT_ASSERTne(timestamp, PMEMSTREAM_INVALID_TIMESTAMP);
> ```

Can't you just compare timestamp to i + PMEMSTREAM_TIMESTAMP_BEGIN and get rid of prev_timestamp?
___
*[`tests/common/stream_helpers.hpp` line 404 at r3](https://reviewable.io/reviews/pmem/pmemstream/205#-N3ZZop63ZZ2RonyvhrM:-N3ZljVJEuBIztRkc3uM:bm2qh5i) ([raw file](https://github.com/pmem/pmemstream/blob/c923bd409c76d2081613a597ef9c99cf11c7479d/tests/common/stream_helpers.hpp#L404)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I would suggest to combine those two methods in one 
```
std::vector<std::pair<uint64_t, std::string> get_elements_in_region(pmemstream_region region)
```

And probably you should move it to separate commit. And probably  to seperate PR, where you use it. 
</blockquote></details>

THe most generic way would be to just return vector<pmemstream_entry> instead of vector<string> from get_elements_in_region() and then we can have something like:


```
auto entires = get_elements_in_region();
auto timestamps = foreach(entries, [](pmemsream_entry entry) {return pmemstream_entry_timestamp(entry); });
auto values = foreach(entries, [](pmemsream_entry entry) {return pmemstream_entry_value(entry); });
auto sizes = ...
```

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/205)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[`tests/api_c/timestamp.c` line 30 at r5](https://reviewable.io/reviews/pmem/pmemstream/205#-N3dVKKE4OGOcEZuiG6i:-N3dVKKE4OGOcEZuiG6j:b19g5sq) ([raw file](https://github.com/pmem/pmemstream/blob/26e6ecc570466652802a976c1ee2d944317e128d/tests/api_c/timestamp.c#L30)):*
> ```C
> 		timestamp = pmemstream_entry_timestamp(env.stream, entry);
> 		UT_ASSERTne(timestamp, PMEMSTREAM_INVALID_TIMESTAMP);
> 		if (i > 0) {
> ```

Why i > 0, it should also work for i == 0

**Review by KFilipek — COMMENTED** [review]
> Reviewed 3 of 4 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/205)* status: 5 of 6 files reviewed, 6 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[`src/libpmemstream.c` line 320 at r1](https://reviewable.io/reviews/pmem/pmemstream/205#-N3KOcgS8XTus-nus4rb:-N3P0BUS9U5BcWHY23rN:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/775af54292954092e88400363ede170213b6c3e5/src/libpmemstream.c#L320)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Since we want to merge Łukasz PR, please return INVALID_TIMESTAMP here.
</blockquote></details>

Done.
___
*[`tests/api_c/timestamp.c` line 30 at r5](https://reviewable.io/reviews/pmem/pmemstream/205#-N3dVKKE4OGOcEZuiG6i:-N3dVVvu6kUsvBx7LDzi:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/26e6ecc570466652802a976c1ee2d944317e128d/tests/api_c/timestamp.c#L30)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Why i > 0, it should also work for i == 0
</blockquote></details>

Done.
___
*[`tests/common/stream_helpers.hpp` line 404 at r3](https://reviewable.io/reviews/pmem/pmemstream/205#-N3ZZop63ZZ2RonyvhrM:-N3dUwfOBnRejakktgWq:b-4ewdjj) ([raw file](https://github.com/pmem/pmemstream/blob/c923bd409c76d2081613a597ef9c99cf11c7479d/tests/common/stream_helpers.hpp#L404)):*
> or just declare them when they are initialized (inside the loop)
We agreed that is better to remove this now and e.g. extend get_elements_in_region()

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/205)* status: 5 of 6 files reviewed, 6 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[`tests/api_c/timestamp.c` line 16 at r3](https://reviewable.io/reviews/pmem/pmemstream/205#-N3ZaMVE29edVczbEtAb:-N3dVbVo94A6z20OQgcz:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/c923bd409c76d2081613a597ef9c99cf11c7479d/tests/api_c/timestamp.c#L16)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

or just declare them when they are initialized (inside the loop)
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/205#-:-N3dcCnT5MacTToH9p6H:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

**Pull request merged**
