### PR TITLE
Extend decriptions of API functions

### PR DESCRIPTION
**Pull request by igchor**
and remove duplicated signatures.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/221)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/221)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[`src/include/libpmemstream.h` line 148 at r1](https://reviewable.io/reviews/pmem/pmemstream/221#-N59dmOEA528NQ-T7XJr:-N59dmOF4PWbK0R1MbM_:b-uj2yyg) ([raw file](https://github.com/pmem/pmemstream/blob/b4a7d42ca543f54389a36c65320a61593162609b/src/include/libpmemstream.h#L148)):*
> ```objc
> 			    struct pmemstream_entry *new_entry);
> 
> /* Return committed timestamp. All entries with timestamps less than that timestamp can be treated as committed. */
> ```

less or equal :wink:

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/221)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[`src/include/libpmemstream.h` line 148 at r1](https://reviewable.io/reviews/pmem/pmemstream/221#-N59dmOEA528NQ-T7XJr:-N59f1957MNJjsVT3_YN:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/b4a7d42ca543f54389a36c65320a61593162609b/src/include/libpmemstream.h#L148)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

less or equal :wink: 
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/221#-:-N59m6P34Rtk1ilZICSi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/221#-:-N59o-dXAdYP3JPpDM7s:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
