### PR TITLE
examples: show how to use reserve-publish instead of regular append

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/68)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/68)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[examples/03_reserve_publish/main.cpp, line 69 at r1](https://reviewable.io/reviews/pmem/pmemstream/68#-MtIgqL1DTUjkt8bZVo9:-MtN9zYb8BBruMnKhnvg:b-vx3gcd) ([raw file](https://github.com/pmem/pmemstream/blob/5b6f286d28b819983f545cbae2c84397f23b2d52/examples/03_reserve_publish/main.cpp#L69)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I just read I have to explicitly call dtor on this object - does it make sense here?
</blockquote></details>

Well, I guess it can be skipped in this example. In general, dtor can be called in different application instance.

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/68)* status: all files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[examples/03_reserve_publish/main.cpp, line 7 at r1](https://reviewable.io/reviews/pmem/pmemstream/68#-MtNpEkK78byzeEN6W5y:-MtNpEkK78byzeEN6W5z:b-1iivf) ([raw file](https://github.com/pmem/pmemstream/blob/5b6f286d28b819983f545cbae2c84397f23b2d52/examples/03_reserve_publish/main.cpp#L7)):*
> ```cpp
> #include "libpmemstream.h"
> 
> #include <assert.h>
> ```

#include <cassert> #if you are using C++
___
*[examples/03_reserve_publish/main.cpp, line 9 at r1](https://reviewable.io/reviews/pmem/pmemstream/68#-MtNp6kb1oZMxCWCDO_m:-MtNp6kb1oZMxCWCDO_n:b-kirz2s) ([raw file](https://github.com/pmem/pmemstream/blob/5b6f286d28b819983f545cbae2c84397f23b2d52/examples/03_reserve_publish/main.cpp#L9)):*
> ```cpp
> #include <assert.h>
> #include <cstring>
> #include <libpmem2.h>
> ```

regroup -> Google Coding Style



_Suggestion:_
```cpp
#include <assert.h>
#include <cstring>
#include <libpmem2.h> <- this shouldn't be here
#include <string>
#include <vector>
```
___
*[examples/03_reserve_publish/main.cpp, line 54 at r1](https://reviewable.io/reviews/pmem/pmemstream/68#-MtNrRm41r1SjhusfJ36:-MtNrRm57Q7KTlkc7o6f:b3kre) ([raw file](https://github.com/pmem/pmemstream/blob/5b6f286d28b819983f545cbae2c84397f23b2d52/examples/03_reserve_publish/main.cpp#L54)):*
> ```cpp
> 
> 	/* instead of doing regular append, we use reserve and publish */
> 	// pmemstream_append(stream, region, nullptr, my_entry.data(), my_entry.size(), nullptr);
> ```

?



_Code quote:_
```cpp
// pmemstream_append(stream, region, nullptr, my_entry.data(), my_entry.size(), nullptr);
```
___
*[examples/03_reserve_publish/main.cpp, line 66 at r1](https://reviewable.io/reviews/pmem/pmemstream/68#-MtNpkV_ByE51x3uMkKe:-MtNpkVa4XUfvhiR6ga1:b48octw) ([raw file](https://github.com/pmem/pmemstream/blob/5b6f286d28b819983f545cbae2c84397f23b2d52/examples/03_reserve_publish/main.cpp#L66)):*
> ```cpp
> 	/* write the data as required (with the size declared in pmemstream_reserve) */
> 	/* e.g. with memcpy: */
> 	// memcpy(reserved_data, &my_entry, sizeof(data_entry));
> ```

one comment block, please remove one line comment



_Code quote:_
```cpp
	/* write the data as required (with the size declared in pmemstream_reserve) */
	/* e.g. with memcpy: */
	// memcpy(reserved_data, &my_entry, sizeof(data_entry));
```
___
*[examples/03_reserve_publish/main.cpp, line 69 at r1](https://reviewable.io/reviews/pmem/pmemstream/68#-MtIgqL1DTUjkt8bZVo9:-MtNqd7cCD6lZ4_N_G2N:blcct9b) ([raw file](https://github.com/pmem/pmemstream/blob/5b6f286d28b819983f545cbae2c84397f23b2d52/examples/03_reserve_publish/main.cpp#L69)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Well, I guess it can be skipped in this example. In general, dtor can be called in different application instance.
</blockquote></details>

Why not put in `unique_ptr`?
___
*[examples/03_reserve_publish/main.cpp, line 93 at r1](https://reviewable.io/reviews/pmem/pmemstream/68#-MtNpXxL5UU5F-M_FxBq:-MtNpXxL5UU5F-M_FxBr:bkeao4r) ([raw file](https://github.com/pmem/pmemstream/blob/5b6f286d28b819983f545cbae2c84397f23b2d52/examples/03_reserve_publish/main.cpp#L93)):*
> ```cpp
> 		return -1;
> 	} else {
> 		printf("Hooray, everything works fine\n");
> ```

If you are using `printf()` you should include `cstdio`



_Code quote:_
```cpp
printf("Hooray, everything works fine\n");
```

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/68)* status: all files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[examples/03_reserve_publish/main.cpp, line 69 at r1](https://reviewable.io/reviews/pmem/pmemstream/68#-MtIgqL1DTUjkt8bZVo9:-MtOYRQaDQGbXgAakU29:b-rbf37c) ([raw file](https://github.com/pmem/pmemstream/blob/5b6f286d28b819983f545cbae2c84397f23b2d52/examples/03_reserve_publish/main.cpp#L69)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Why not put in `unique_ptr`?
</blockquote></details>

I don't understand. What would you like to put into unique_ptr?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/68)* status: all files reviewed, 6 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[examples/03_reserve_publish/main.cpp, line 7 at r1](https://reviewable.io/reviews/pmem/pmemstream/68#-MtNpEkK78byzeEN6W5y:-Mtmas5100AFTacLvhMn:b-s77hd2) ([raw file](https://github.com/pmem/pmemstream/blob/5b6f286d28b819983f545cbae2c84397f23b2d52/examples/03_reserve_publish/main.cpp#L7)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

#include <cassert> #if you are using C++
</blockquote></details>

Not sure if I got you correctly - Done.
___
*[examples/03_reserve_publish/main.cpp, line 9 at r1](https://reviewable.io/reviews/pmem/pmemstream/68#-MtNp6kb1oZMxCWCDO_m:-MtmazJP4grjoCfToDek:be08h8u) ([raw file](https://github.com/pmem/pmemstream/blob/5b6f286d28b819983f545cbae2c84397f23b2d52/examples/03_reserve_publish/main.cpp#L9)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

regroup -> Google Coding Style
</blockquote></details>

Done, but as I wrote previously - if you want to enforce some kind of includes style - please make a function/checker for that. There's little-to-no gain with this change.
___
*[examples/03_reserve_publish/main.cpp, line 54 at r1](https://reviewable.io/reviews/pmem/pmemstream/68#-MtNrRm41r1SjhusfJ36:-MtmbRe7A9_f4pHbR5uK:bngfa85) ([raw file](https://github.com/pmem/pmemstream/blob/5b6f286d28b819983f545cbae2c84397f23b2d52/examples/03_reserve_publish/main.cpp#L54)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

?
</blockquote></details>

`instead of doing regular append, we use reserve and publish` and here is the example, how this could look like



_Code quote:_
```cpp
instead of doing regular append, we use reserve and publish
```
___
*[examples/03_reserve_publish/main.cpp, line 66 at r1](https://reviewable.io/reviews/pmem/pmemstream/68#-MtNpkV_ByE51x3uMkKe:-MtmbZ4VAqgWxlGFUACp:b2zdpgy) ([raw file](https://github.com/pmem/pmemstream/blob/5b6f286d28b819983f545cbae2c84397f23b2d52/examples/03_reserve_publish/main.cpp#L66)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

one comment block, please remove one line comment
</blockquote></details>

the first two lines are separate comments, that happen to be right next to each other. Fixed by adding an empty line.
___
*[examples/03_reserve_publish/main.cpp, line 93 at r1](https://reviewable.io/reviews/pmem/pmemstream/68#-MtNpXxL5UU5F-M_FxBq:-MtmciCl12lwnT8rnHSU:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/5b6f286d28b819983f545cbae2c84397f23b2d52/examples/03_reserve_publish/main.cpp#L93)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

If you are using `printf()` you should include `cstdio`
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/68#-:-MtvvCIJAV99Vo7ihsAP:bnfp4nl)* status: 4 of 6 files reviewed, 7 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[examples/03_reserve_publish/main.cpp, line 50 at r2](https://reviewable.io/reviews/pmem/pmemstream/68#-Mtvv_pI-g912Xm5doDS:-Mtvv_pI-g912Xm5doDT:bfrkxrf) ([raw file](https://github.com/pmem/pmemstream/blob/345f186bf313999f4f7668a0d282d2522bfec397/examples/03_reserve_publish/main.cpp#L50)):*
> ```cpp
> 
> 	struct pmemstream_region region;
> 	ret = pmemstream_region_allocate(stream, 10240, &region);
> ```

nit: it might be good to split main into functions:
```
initialize() -> for creating stream and allocation entry

reserve + publish part (can be directly in main)

verify_stream() -> check written entry.
```

It will make reserve/publish part more visible.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/68)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[examples/03_reserve_publish/main.cpp, line 50 at r2](https://reviewable.io/reviews/pmem/pmemstream/68#-Mtvv_pI-g912Xm5doDS:-MtwviEY65-Refhz5bwZ:b-86mr6o) ([raw file](https://github.com/pmem/pmemstream/blob/345f186bf313999f4f7668a0d282d2522bfec397/examples/03_reserve_publish/main.cpp#L50)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

nit: it might be good to split main into functions:
```
initialize() -> for creating stream and allocation entry

reserve + publish part (can be directly in main)

verify_stream() -> check written entry.
```

It will make reserve/publish part more visible.
</blockquote></details>

I like it, done.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/68#-:-MtxK4_-4VExZzmvLG3i:bnfp4nl)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @igchor and @KFilipek)

**Review by karczex — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/68)* status: 5 of 6 files reviewed, 6 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[utils/docker/run-build.sh, line 251 at r3](https://reviewable.io/reviews/pmem/pmemstream/68#-MuFAP49Bh9JLyItlOGw:-MuFAP49Bh9JLyItlOGx:b-abc40y) ([raw file](https://github.com/pmem/pmemstream/blob/fe70275b13d47f565a5c907afdc5f8d7bcc26b70/utils/docker/run-build.sh#L251)):*
> ```Shell
> 	echo "C++ example using reserve-publish (with emplace new) instead of append:"
> 	compile_example_standalone 03_reserve_publish
> 	run_example_standalone 03_reserve_publish ${WORKDIR}/build/testfile2
> ```

It's `run_binary_standalone()` now

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/68)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[utils/docker/run-build.sh, line 251 at r3](https://reviewable.io/reviews/pmem/pmemstream/68#-MuFAP49Bh9JLyItlOGw:-MuFc4NY0vMGG8hlLZBx:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/fe70275b13d47f565a5c907afdc5f8d7bcc26b70/utils/docker/run-build.sh#L251)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It's `run_binary_standalone()` now 
</blockquote></details>

Done.

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/68#-:-MuGB9J01pnjnncSdVah:bnfp4nl)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @igchor and @KFilipek)

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/68)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[examples/03_reserve_publish/main.cpp, line 7 at r1](https://reviewable.io/reviews/pmem/pmemstream/68#-MtNpEkK78byzeEN6W5y:-MuGQ893A0tjqcI3KGW7:b-5f6zdo) ([raw file](https://github.com/pmem/pmemstream/blob/5b6f286d28b819983f545cbae2c84397f23b2d52/examples/03_reserve_publish/main.cpp#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Not sure if I got you correctly - Done.
</blockquote></details>

Perfecto, thanks
___
*[examples/03_reserve_publish/main.cpp, line 54 at r1](https://reviewable.io/reviews/pmem/pmemstream/68#-MtNrRm41r1SjhusfJ36:-MuGR8r86-U997P42Dbv:b-yyva1f) ([raw file](https://github.com/pmem/pmemstream/blob/5b6f286d28b819983f545cbae2c84397f23b2d52/examples/03_reserve_publish/main.cpp#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`instead of doing regular append, we use reserve and publish` and here is the example, how this could look like
</blockquote></details>

Oh, sorry, I missed this
___
*[examples/03_reserve_publish/main.cpp, line 69 at r1](https://reviewable.io/reviews/pmem/pmemstream/68#-MtIgqL1DTUjkt8bZVo9:-MuGRPUw1vI4w46WmKr6:b-sqgk5v) ([raw file](https://github.com/pmem/pmemstream/blob/5b6f286d28b819983f545cbae2c84397f23b2d52/examples/03_reserve_publish/main.cpp#L69)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I don't understand. What would you like to put into unique_ptr? 
</blockquote></details>

You've explained me why I was wrong
___
*[examples/03_reserve_publish/main.cpp, line 33 at r4](https://reviewable.io/reviews/pmem/pmemstream/68#-MuGQb792RRJ6L4-rSyR:-MuGQb792RRJ6L4-rSyS:bbp5hx) ([raw file](https://github.com/pmem/pmemstream/blob/86cd5dfc986496e037f3f794abcb1fc86f0aaccf/examples/03_reserve_publish/main.cpp#L33)):*
> ```cpp
> {
> 	*map = example_map_open(path, EXAMPLE_STREAM_SIZE);
> 	assert(map != NULL);
> ```

`*map != NULL`
map is address to pointer, otherwise this assert is always true



_Code quote:_
```cpp
map != NULL
```

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/68)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @igchor and @KFilipek)

___
*[examples/03_reserve_publish/main.cpp, line 33 at r4](https://reviewable.io/reviews/pmem/pmemstream/68#-MuGQb792RRJ6L4-rSyR:-MuGoPRt63FMdd5Nj9a9:bd30ifx) ([raw file](https://github.com/pmem/pmemstream/blob/86cd5dfc986496e037f3f794abcb1fc86f0aaccf/examples/03_reserve_publish/main.cpp#L33)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

`*map != NULL`
map is address to pointer, otherwise this assert is always true
</blockquote></details>

good catch

**Pull request merged**
