### PR TITLE
Refactor region_runtimes_map_get_or_create

### PR DESCRIPTION
**Pull request by igchor**
Split this function into multiple smaller functions for better
readability.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/80)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/80)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[src/region.c, line 72 at r1](https://reviewable.io/reviews/pmem/pmemstream/80#-Mthw4I01YKTEVje8X5Z:-Mthw4I01YKTEVje8X5_:b-sgfu9u) ([raw file](https://github.com/pmem/pmemstream/blob/ea5581f3f172d1871cf9e8b841a4a533e7da0dd8/src/region.c#L72)):*
> ```C
> 	{
> 		runtime = (struct pmemstream_region_runtime *)calloc(1, sizeof(*runtime));
> 		if (runtime) {
> ```

Does this `calloc` and `if` have to be under lock?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/80)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[src/region.c, line 72 at r1](https://reviewable.io/reviews/pmem/pmemstream/80#-Mthw4I01YKTEVje8X5Z:-MtiNpJK1b3X4_L_R9M2:bfbw1wg) ([raw file](https://github.com/pmem/pmemstream/blob/ea5581f3f172d1871cf9e8b841a4a533e7da0dd8/src/region.c#L72)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Does this `calloc` and `if` have to be under lock?
</blockquote></details>

That's a good question. And even a better one would be: do we need this lock at all? ;d And I think the answer is "no" so I removed it.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/80#-:-MtlsNP85RQK7axQFIaR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

___
*[src/region.c, line 72 at r1](https://reviewable.io/reviews/pmem/pmemstream/80#-Mthw4I01YKTEVje8X5Z:-Mtlrxxi4HbFnM2ej9C_:b21ua0g) ([raw file](https://github.com/pmem/pmemstream/blob/ea5581f3f172d1871cf9e8b841a4a533e7da0dd8/src/region.c#L72)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

That's a good question. And even a better one would be: do we need this lock at all? ;d And I think the answer is "no" so I removed it.
</blockquote></details>

hah, nice. It looks ok

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/80#-:-MtrMm2R0lvTEy5frohb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
