### PR TITLE
add memset in free span creation

### PR DESCRIPTION
**Pull request by Karolina002**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/24)

### CODE REVIEW

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/24)* status: all files reviewed, 1 unresolved discussion (waiting on @Karolina002)

___
*[src/libpmemstream.c, line 50 at r1](https://reviewable.io/reviews/pmem/pmemstream/24#-MqZD7wR72-vKFF-T8qx:-MqZD7wR72-vKFF-T8qy:bgrueg2) ([raw file](https://github.com/pmem/pmemstream/blob/ebdbed1c6b38caa53be6bf0f0bd72737c42b9e92/src/libpmemstream.c#L50)):*
> ```
> data_size-1
> ```
You need to add spaces around minus sign :) 
Build failed and you can view logs before fixing above.

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/24)* status: all files reviewed, 3 unresolved discussions (waiting on @Karolina002)

___
*[src/libpmemstream.c, line 50 at r1](https://reviewable.io/reviews/pmem/pmemstream/24#-Mq_BbJo8Z6FxJvqooXp:-Mq_BbJo8Z6FxJvqooXq:b2k80go) ([raw file](https://github.com/pmem/pmemstream/blob/ebdbed1c6b38caa53be6bf0f0bd72737c42b9e92/src/libpmemstream.c#L50)):*
> ```C
> 	assert((data_size & PMEMSTREAM_SPAN_TYPE_MASK) == 0);
> 	span[0] = data_size | PMEMSTREAM_SPAN_EMPTY;
> 	memset(&span[1], 0, data_size-1);
> ```

If you use regular memcpy it will not guarantee that data is actually written to pmem. Instead, you should use stream->memset with nontemporal flag - you can see the docs for memset here https://pmem.io/pmdk/manpages/linux/master/libpmem2/pmem2_get_memmove_fn.3

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/24)* status: all files reviewed, 3 unresolved discussions (waiting on @Karolina002)

___
*[src/libpmemstream.c, line 50 at r1](https://reviewable.io/reviews/pmem/pmemstream/24#-Mq_CC_cDtCB30xo0PtP:-Mq_CC_cDtCB30xo0PtQ:b-dik2xu) ([raw file](https://github.com/pmem/pmemstream/blob/ebdbed1c6b38caa53be6bf0f0bd72737c42b9e92/src/libpmemstream.c#L50)):*
> ```C
> 	assert((data_size & PMEMSTREAM_SPAN_TYPE_MASK) == 0);
> 	span[0] = data_size | PMEMSTREAM_SPAN_EMPTY;
> 	memset(&span[1], 0, data_size-1);
> ```

why -1?

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/24)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @igchor, @KFilipek, and @kilobyte)

*[a discussion](https://reviewable.io/reviews/pmem/pmemstream/24#-MqZDgRg1mCPXLIN1fDJ:-Mqz7YBH9-CMmvq14leB:b-896fix) (no related file):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

Could you please say what is done and why, instead of the function being used (as that's the diff)?

In this case, "what" would be "clear empty span's data during creation".

"Why", on an uneducated guess, could be "to placate valgrind" or "to make a checksum reproducible" (I don't know if a checksum/etc is used here, I don't know this code, and a reader two years in the future might now know either).
</blockquote></details>

Done.

---
___
*[src/libpmemstream.c, line 50 at r1](https://reviewable.io/reviews/pmem/pmemstream/24#-MqZD7wR72-vKFF-T8qx:-Mqz7dWV32FL1HgOD8o7:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ebdbed1c6b38caa53be6bf0f0bd72737c42b9e92/src/libpmemstream.c#L50)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> data_size-1
> ```
You need to add spaces around minus sign :) 
Build failed and you can view logs before fixing above.
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 50 at r1](https://reviewable.io/reviews/pmem/pmemstream/24#-Mq_BbJo8Z6FxJvqooXp:-Mqz7eZ3BJTFcriJox2-:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/ebdbed1c6b38caa53be6bf0f0bd72737c42b9e92/src/libpmemstream.c#L50)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

If you use regular memcpy it will not guarantee that data is actually written to pmem. Instead, you should use stream->memset with nontemporal flag - you can see the docs for memset here https://pmem.io/pmdk/manpages/linux/master/libpmem2/pmem2_get_memmove_fn.3
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/24)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor, @Karolina002, and @KFilipek)

___
*[src/libpmemstream.c, line 44 at r3](https://reviewable.io/reviews/pmem/pmemstream/24#-Mr1ARXq0v2_hxrQKs0W:-Mr1ARXq0v2_hxrQKs0X:blk2tzk) ([raw file](https://github.com/pmem/pmemstream/blob/73f60ec02ed5db7db24052d583f8d10386baacb6/src/libpmemstream.c#L44)):*
> ```C
> };
> 
> struct pmemstream {
> ```

moving this struct to the top should be done in the first commit (88fcd6e) along with the addition of the `stream` param in `pmemstream_span_create_empty`. Right now, if you take only the first commit the code will not compile :wink: 
___
*[src/libpmemstream.c, line 59 at r3](https://reviewable.io/reviews/pmem/pmemstream/24#-Mr1Autz67IlwaH3fDMK:-Mr1Autz67IlwaH3fDML:b-bhyx2v) ([raw file](https://github.com/pmem/pmemstream/blob/73f60ec02ed5db7db24052d583f8d10386baacb6/src/libpmemstream.c#L59)):*
> ```C
> typedef uint64_t pmemstream_span_bytes;
> 
> static void pmemstream_span_create_empty(pmemstream_span_bytes *span, size_t data_size, struct pmemstream *stream)
> ```

usually (if you see in our other functions) `struct pmemstream *stream` is the first param - pls move

**Review by igchor — APPROVED** [review]
:lgtm: (just please move the stream parameter to front)

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/24#-:-Mr24Q9TEP_3IAcoGsa8:b1aqtjl)* status: all files reviewed, 3 unresolved discussions (waiting on @Karolina002, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 59 at r3](https://reviewable.io/reviews/pmem/pmemstream/24#-Mr1Autz67IlwaH3fDMK:-Mr24IXg0fpaAUx0S0eJ:b32v57) ([raw file](https://github.com/pmem/pmemstream/blob/73f60ec02ed5db7db24052d583f8d10386baacb6/src/libpmemstream.c#L59)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

usually (if you see in our other functions) `struct pmemstream *stream` is the first param - pls move
</blockquote></details>

+1

**Comment by karczex** [comment]
___
*[src/libpmemstream.c, line 44 at r3](https://reviewable.io/reviews/pmem/pmemstream/24#-Mr1ARXq0v2_hxrQKs0W:-Mr2TjT06ubVRH96SjVf:bvhmbyz) ([raw file](https://github.com/pmem/pmemstream/blob/73f60ec02ed5db7db24052d583f8d10386baacb6/src/libpmemstream.c#L44)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

moving this struct to the top should be done in the first commit (88fcd6e) along with the addition of the `stream` param in `pmemstream_span_create_empty`. Right now, if you take only the first commit the code will not compile :wink: 
</blockquote></details>

This structure was moved to separate header.

**Review by Karolina002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/24)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/libpmemstream.c, line 44 at r3](https://reviewable.io/reviews/pmem/pmemstream/24#-Mr1ARXq0v2_hxrQKs0W:-Mr76qcx0EYNusjb836H:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/73f60ec02ed5db7db24052d583f8d10386baacb6/src/libpmemstream.c#L44)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

This structure was moved to separate header.
</blockquote></details>

Done.
___
*[src/libpmemstream.c, line 59 at r3](https://reviewable.io/reviews/pmem/pmemstream/24#-Mr1Autz67IlwaH3fDMK:-Mr76npu6Kj9LdMs8DD7:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/73f60ec02ed5db7db24052d583f8d10386baacb6/src/libpmemstream.c#L59)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/24#-:-Mr7OWFm4OQzLqUvyEK_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Review by KFilipek — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/24#-:-Mr7Q2H-AjCj4_tnVVs0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Karolina002)

___
*[src/libpmemstream.c, line 87 at r4](https://reviewable.io/reviews/pmem/pmemstream/24#-Mr7QDcj-03_ziRI-Gwo:-Mr7QDcl8nqvpvQaMuyC:b-89qzzp) ([raw file](https://github.com/pmem/pmemstream/blob/b1c0c71ab2bbeae5d551878d13dfb5736f777a31/src/libpmemstream.c#L87)):*
> ```C
> 
> 	size_t metadata_size = MEMBER_SIZE(pmemstream_span_runtime, empty);
> 	pmemstream_span_create_empty(stream, &stream->data->spans[0], stream->usable_size - metadata_size);
> ```

@igchor do we need `&stream->data->spans[0]` (equivalent `stream->data->spans`) if we have stream passed?



_Code quote:_
```C
stream, &stream->data->spans[0]
```

**Review by KFilipek — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/24#-:-Mr7S-vE9uug8oA-sT0n:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Karolina002)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/24)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[src/libpmemstream.c, line 87 at r4](https://reviewable.io/reviews/pmem/pmemstream/24#-Mr7QDcj-03_ziRI-Gwo:-Mr7Vjqb9UyjLDi2LCj3:b-yl3kgv) ([raw file](https://github.com/pmem/pmemstream/blob/b1c0c71ab2bbeae5d551878d13dfb5736f777a31/src/libpmemstream.c#L87)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

@igchor do we need `&stream->data->spans[0]` (equivalent `stream->data->spans`) if we have stream passed?
</blockquote></details>

I think it's not always a case to start at[0] with empty'ing :wink:

**Pull request merged**
