### PR TITLE
Collaborative commit

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/210)

### CODE REVIEW

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/210#-:-N4XOhly8-lZlMJn-rCb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/210)* status: all files reviewed, 8 unresolved discussions (waiting on @igchor)

___
*[`src/libpmemstream.c` line 543 at r3](https://reviewable.io/reviews/pmem/pmemstream/210#-N4XelxsDgE4jKfzLacY:-N4XelxsDgE4jKfzLacZ:b-ouveee) ([raw file](https://github.com/pmem/pmemstream/blob/8b4fa0602e8238ff25a021a236fb8c5659f2621f/src/libpmemstream.c#L543)):*
> ```C
> 	size_t entry_total_size_span_aligned = pmemstream_entry_total_size_aligned(size);
> 
> 	async_op->future = *future;
> ```

you've missed setting a `timestamp`
___
*[`src/libpmemstream.c` line 653 at r3](https://reviewable.io/reviews/pmem/pmemstream/210#-N4XhRZS5fRgPFQK-3GD:-N4XhRZS5fRgPFQK-3GE:b-q3tcj) ([raw file](https://github.com/pmem/pmemstream/blob/8b4fa0602e8238ff25a021a236fb8c5659f2621f/src/libpmemstream.c#L653)):*
> ```C
> }
> 
> static void pmemstream_increase_commited_timestamp(struct pmemstream_async_wait_data *data)
> ```

`commited` -> `committed` (in few places within this patch)
___
*[`src/libpmemstream.c` line 691 at r3](https://reviewable.io/reviews/pmem/pmemstream/210#-N4XiGBhCA58Dz1slk7A:-N4XiGBhCA58Dz1slk7B:bwvo8gw) ([raw file](https://github.com/pmem/pmemstream/blob/8b4fa0602e8238ff25a021a236fb8c5659f2621f/src/libpmemstream.c#L691)):*
> ```C
> 
> 	uint64_t committed_timestamp = __atomic_load_n(&data->stream->committed_timestamp, __ATOMIC_ACQUIRE);
> ```

you could add here short comments for these 'ifs' (to describe what are the cases)... I guess :wink: 
___
*[`src/include/libpmemstream.h` line 38 at r3](https://reviewable.io/reviews/pmem/pmemstream/210#-N4XpgqeCy9owvf4sKVo:-N4Xpgqf7rSa_dsOETEd:beulyix) ([raw file](https://github.com/pmem/pmemstream/blob/8b4fa0602e8238ff25a021a236fb8c5659f2621f/src/include/libpmemstream.h#L38)):*
> ```objc
> struct pmemstream_async_wait_data {
> 	struct pmemstream *stream;
> 	struct pmemstream_region_runtime *region_runtime;
> ```

did you mean to remove it...? (if not it's not initialized in `pmemstream_async_wait_*`
___
*[`src/include/libpmemstream.h` line 41 at r3](https://reviewable.io/reviews/pmem/pmemstream/210#-N4Xk8RI1ZzAhyI5IyEn:-N4Xk8RI1ZzAhyI5IyEo:b-x64szw) ([raw file](https://github.com/pmem/pmemstream/blob/8b4fa0602e8238ff25a021a236fb8c5659f2621f/src/include/libpmemstream.h#L41)):*
> ```objc
> 	uint64_t timestamp;
> 
> 	uint64_t first_timestamp;
> ```

you could describe these 4 timestamp variables
___
*[`tests/unittest/concurrent_iterate_with_append.cpp` line 16 at r3](https://reviewable.io/reviews/pmem/pmemstream/210#-N4XmH8s5ZBLeHgTOZio:-N4XmH8s5ZBLeHgTOZip:b-ekim70) ([raw file](https://github.com/pmem/pmemstream/blob/8b4fa0602e8238ff25a021a236fb8c5659f2621f/tests/unittest/concurrent_iterate_with_append.cpp#L16)):*
> ```cpp
> static constexpr size_t min_write_concurrency = 1;
> static constexpr size_t max_write_concurrency = 4;
> static constexpr size_t read_concurrency = 8;
> ```

this could be equal to `max_write * 2` so each thread will have always at least 2 readers (just to be safe, if we change the max_write_conc.)
___
*[`tests/unittest/concurrent_iterate_with_append.cpp` line 18 at r3](https://reviewable.io/reviews/pmem/pmemstream/210#-N4XkyRd2aJAFwWt-qVP:-N4XkyRd2aJAFwWt-qVQ:b-u9d4ty) ([raw file](https://github.com/pmem/pmemstream/blob/8b4fa0602e8238ff25a021a236fb8c5659f2621f/tests/unittest/concurrent_iterate_with_append.cpp#L18)):*
> ```cpp
> static constexpr size_t read_concurrency = 8;
> static constexpr size_t max_size = 1024; /* Max number of elements in stream and max size of single entry. */
> static constexpr size_t region_size = ALIGN_UP(max_size * max_size * 10, 4096ULL); /* 10x-margin */
> ```

perhaps 4096 -> TEST_DEFAULT_BLOCK_SIZE
___
*[`tests/unittest/concurrent_iterate_with_append.cpp` line 18 at r3](https://reviewable.io/reviews/pmem/pmemstream/210#-N4XlQhlAPOlcHJZtt32:-N4XlQhlAPOlcHJZtt33:bi2m1me) ([raw file](https://github.com/pmem/pmemstream/blob/8b4fa0602e8238ff25a021a236fb8c5659f2621f/tests/unittest/concurrent_iterate_with_append.cpp#L18)):*
> ```cpp
> static constexpr size_t read_concurrency = 8;
> static constexpr size_t max_size = 1024; /* Max number of elements in stream and max size of single entry. */
> static constexpr size_t region_size = ALIGN_UP(max_size * max_size * 10, 4096ULL); /* 10x-margin */
> ```

shouldn't this region_size be already aligned up along with metadata?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/210)* status: 1 of 4 files reviewed, 8 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`src/libpmemstream.c` line 543 at r3](https://reviewable.io/reviews/pmem/pmemstream/210#-N4XelxsDgE4jKfzLacY:-N4Y5zv23xv1_VSua_Sx:b-hao5kc) ([raw file](https://github.com/pmem/pmemstream/blob/8b4fa0602e8238ff25a021a236fb8c5659f2621f/src/libpmemstream.c#L543)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you've missed setting a `timestamp`
</blockquote></details>

nope, this is intentional
___
*[`src/libpmemstream.c` line 653 at r3](https://reviewable.io/reviews/pmem/pmemstream/210#-N4XhRZS5fRgPFQK-3GD:-N4Y6AO2-IfIJciEl9vb:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/8b4fa0602e8238ff25a021a236fb8c5659f2621f/src/libpmemstream.c#L653)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`commited` -> `committed` (in few places within this patch)
</blockquote></details>

Done.
___
*[`src/libpmemstream.c` line 691 at r3](https://reviewable.io/reviews/pmem/pmemstream/210#-N4XiGBhCA58Dz1slk7A:-N4Y6L_y2l5tzA3Z0Fmw:bodid78) ([raw file](https://github.com/pmem/pmemstream/blob/8b4fa0602e8238ff25a021a236fb8c5659f2621f/src/libpmemstream.c#L691)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you could add here short comments for these 'ifs' (to describe what are the cases)... I guess :wink: 
</blockquote></details>

This was supposed to be self-describing - the only place where it's not so obvious is check last_timestamp. Done.
___
*[`src/include/libpmemstream.h` line 38 at r3](https://reviewable.io/reviews/pmem/pmemstream/210#-N4XpgqeCy9owvf4sKVo:-N4Y6iC55b-EZkIGw5o7:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/8b4fa0602e8238ff25a021a236fb8c5659f2621f/src/include/libpmemstream.h#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

did you mean to remove it...? (if not it's not initialized in `pmemstream_async_wait_*`
</blockquote></details>

Done.
___
*[`src/include/libpmemstream.h` line 41 at r3](https://reviewable.io/reviews/pmem/pmemstream/210#-N4Xk8RI1ZzAhyI5IyEn:-N4Y6jHl-Lq2CuoI7ruQ:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/8b4fa0602e8238ff25a021a236fb8c5659f2621f/src/include/libpmemstream.h#L41)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you could describe these 4 timestamp variables
</blockquote></details>

Done.
___
*[`tests/unittest/concurrent_iterate_with_append.cpp` line 16 at r3](https://reviewable.io/reviews/pmem/pmemstream/210#-N4XmH8s5ZBLeHgTOZio:-N4Y7NY00uW1lsFSf_lW:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/8b4fa0602e8238ff25a021a236fb8c5659f2621f/tests/unittest/concurrent_iterate_with_append.cpp#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this could be equal to `max_write * 2` so each thread will have always at least 2 readers (just to be safe, if we change the max_write_conc.)
</blockquote></details>

Done.
___
*[`tests/unittest/concurrent_iterate_with_append.cpp` line 18 at r3](https://reviewable.io/reviews/pmem/pmemstream/210#-N4XkyRd2aJAFwWt-qVP:-N4Y7QGI-VX6w5T9f4y1:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/8b4fa0602e8238ff25a021a236fb8c5659f2621f/tests/unittest/concurrent_iterate_with_append.cpp#L18)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps 4096 -> TEST_DEFAULT_BLOCK_SIZE
</blockquote></details>

Done.
___
*[`tests/unittest/concurrent_iterate_with_append.cpp` line 18 at r3](https://reviewable.io/reviews/pmem/pmemstream/210#-N4XlQhlAPOlcHJZtt32:-N4Y7TVv0GNCezoCXdZo:b-xlsoc) ([raw file](https://github.com/pmem/pmemstream/blob/8b4fa0602e8238ff25a021a236fb8c5659f2621f/tests/unittest/concurrent_iterate_with_append.cpp#L18)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

shouldn't this region_size be already aligned up along with metadata?
</blockquote></details>

Whatever, this is just an approximate calculation anyway

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/210)* status: 1 of 4 files reviewed, 8 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`tests/unittest/concurrent_iterate_with_append.cpp` line 18 at r3](https://reviewable.io/reviews/pmem/pmemstream/210#-N4XlQhlAPOlcHJZtt32:-N4YAPPS1Ff_sA8r4MB3:b-8dxfrt) ([raw file](https://github.com/pmem/pmemstream/blob/8b4fa0602e8238ff25a021a236fb8c5659f2621f/tests/unittest/concurrent_iterate_with_append.cpp#L18)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Whatever, this is just an approximate calculation anyway
</blockquote></details>

Actually it matters, region_size should only have size of user data and then we just need to reserve more space for metadata

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/210)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[`src/libpmemstream.c` line 543 at r3](https://reviewable.io/reviews/pmem/pmemstream/210#-N4XelxsDgE4jKfzLacY:-N4YKLL58uEHAfkf91cY:bwma4pl) ([raw file](https://github.com/pmem/pmemstream/blob/8b4fa0602e8238ff25a021a236fb8c5659f2621f/src/libpmemstream.c#L543)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

nope, this is intentional
</blockquote></details>

och, right
___
*[`src/libpmemstream.c` line 691 at r3](https://reviewable.io/reviews/pmem/pmemstream/210#-N4XiGBhCA58Dz1slk7A:-N4YKZl7ErYxZfsmXXj9:b-ao8ijx) ([raw file](https://github.com/pmem/pmemstream/blob/8b4fa0602e8238ff25a021a236fb8c5659f2621f/src/libpmemstream.c#L691)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This was supposed to be self-describing - the only place where it's not so obvious is check last_timestamp. Done.
</blockquote></details>

that place was my favorite, thx! :-)
___
*[`src/libpmemstream.c` line 546 at r4](https://reviewable.io/reviews/pmem/pmemstream/210#-N4YKO5f1r3lMwMhS51_:-N4YKO5f1r3lMwMhS51a:b-7mmvxt) ([raw file](https://github.com/pmem/pmemstream/blob/44f465733588915b8cbc683bc2460cf7be0cba23/src/libpmemstream.c#L546)):*
> ```C
> 	async_op->entry = entry;
> 	async_op->size = entry_total_size_span_aligned;
> 	/* o not set timestamp here, this is done in publish. */
> ```

"o not"? :wink:
___
*[`tests/unittest/concurrent_iterate_with_append.cpp` line 18 at r3](https://reviewable.io/reviews/pmem/pmemstream/210#-N4XlQhlAPOlcHJZtt32:-N4YL-Oc8s9W7oPEWyIM:b-eussr) ([raw file](https://github.com/pmem/pmemstream/blob/8b4fa0602e8238ff25a021a236fb8c5659f2621f/tests/unittest/concurrent_iterate_with_append.cpp#L18)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Actually it matters, region_size should only have size of user data and then we just need to reserve more space for metadata
</blockquote></details>

ochh, yeah! that's actually a lot better
___
*[`tests/unittest/concurrent_iterate_with_append.cpp` line 15 at r4](https://reviewable.io/reviews/pmem/pmemstream/210#-N4YLbNL3DtB2q0wxtAK:-N4YLbNL3DtB2q0wxtAL:bd243ca) ([raw file](https://github.com/pmem/pmemstream/blob/44f465733588915b8cbc683bc2460cf7be0cba23/tests/unittest/concurrent_iterate_with_append.cpp#L15)):*
> ```cpp
> 
> static constexpr size_t min_write_concurrency = 1;
> static constexpr size_t max_write_concurrency = 4;
> ```

ech... it timed out with pmemcheck tracer :/

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/210)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`src/libpmemstream.c` line 546 at r4](https://reviewable.io/reviews/pmem/pmemstream/210#-N4YKO5f1r3lMwMhS51_:-N4YXD3f2aKfYOcn6YGa:b-896fix) ([raw file](https://github.com/pmem/pmemstream/blob/44f465733588915b8cbc683bc2460cf7be0cba23/src/libpmemstream.c#L546)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"o not"? :wink:
</blockquote></details>

Done.
___
*[`tests/unittest/concurrent_iterate_with_append.cpp` line 15 at r4](https://reviewable.io/reviews/pmem/pmemstream/210#-N4YLbNL3DtB2q0wxtAK:-N4YXDos9B69ZGIspw56:bhka8t) ([raw file](https://github.com/pmem/pmemstream/blob/44f465733588915b8cbc683bc2460cf7be0cba23/tests/unittest/concurrent_iterate_with_append.cpp#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

ech... it timed out with pmemcheck tracer :/
</blockquote></details>

Rerun might fix it ;d

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/210#-:-N4aC8Uh3Cwm_qa1xWrs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

___
*[`tests/unittest/concurrent_iterate_with_append.cpp` line 15 at r4](https://reviewable.io/reviews/pmem/pmemstream/210#-N4YLbNL3DtB2q0wxtAK:-N4aBPTU2V5Kzia90qj1:bpjt7b2) ([raw file](https://github.com/pmem/pmemstream/blob/44f465733588915b8cbc683bc2460cf7be0cba23/tests/unittest/concurrent_iterate_with_append.cpp#L15)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Rerun might fix it ;d
</blockquote></details>

hmm.. I don't like this one bit :stuck_out_tongue: buuut, CI is green now, I give you that :smile:

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/210)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

___
*[`tests/unittest/concurrent_iterate_with_append.cpp` line 15 at r4](https://reviewable.io/reviews/pmem/pmemstream/210#-N4YLbNL3DtB2q0wxtAK:-N4aHgvbDly36fIKiujV:b79ds5h) ([raw file](https://github.com/pmem/pmemstream/blob/44f465733588915b8cbc683bc2460cf7be0cba23/tests/unittest/concurrent_iterate_with_append.cpp#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm.. I don't like this one bit :stuck_out_tongue: buuut, CI is green now, I give you that :smile: 
</blockquote></details>

I got the same timeout on our current master branch - I think we should fix it separately

**Pull request merged**
