### PR TITLE
docker: enable auto doc updates already to pmem.io

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/239)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by karczex — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/239)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`utils/docker/run-doc-update.sh` line 35 at r1](https://reviewable.io/reviews/pmem/pmemstream/239#-N6SGJz78pDORTVi9qhY:-N6SGJz89V31_oOG1OJ-:bkm7zkp) ([raw file](https://github.com/pmem/pmemstream/blob/391a28cfb514f795d8272056417c50b1962f4b5b/utils/docker/run-doc-update.sh#L35)):*
> ```Shell
> 
> # Only 'master' or 'stable-*' branches are valid; determine docs location dir on 'docs' branch
> if [[ "${CI_BRANCH}" == "master" ]]; then
> ```

This check is already done in github workflow. Also, when removed, this script (after env variables setup) would be better for manual usage (in scenario: push from local machine to user owned pmem.github.io fork).



_Code quote:_
```Shell
if [[ "${CI_BRANCH}" == "master" ]]; then
	DOCS_TARGET_DIR="master"
elif [[ ${CI_BRANCH} == stable-* ]]; then
	DOCS_TARGET_DIR=v$(echo ${CI_BRANCH} | cut -d"-" -f2 -s)
else
	echo "Skipping docs build, this script should be run only on master or stable-* branches."
	echo "CI_BRANCH is set to: \'${CI_BRANCH}\'."
	exit 0
fi
```
___
*[`utils/docker/run-doc-update.sh` line 64 at r1](https://reviewable.io/reviews/pmem/pmemstream/239#-N6SJQcM-RfmNLTMmGNQ:-N6SJQcM-RfmNLTMmGNR:b-g4vrn1) ([raw file](https://github.com/pmem/pmemstream/blob/391a28cfb514f795d8272056417c50b1962f4b5b/utils/docker/run-doc-update.sh#L64)):*
> ```Shell
> 
> echo "Clone pmem.io repo (with web content and our docs):"
> git clone ${ORIGIN} ${DOC_REPO_DIR}
> ```

shallow clone?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/239)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[`utils/docker/run-doc-update.sh` line 35 at r1](https://reviewable.io/reviews/pmem/pmemstream/239#-N6SGJz78pDORTVi9qhY:-N6ScSUc3YT9kYjiXTBC:b-ruetqj) ([raw file](https://github.com/pmem/pmemstream/blob/391a28cfb514f795d8272056417c50b1962f4b5b/utils/docker/run-doc-update.sh#L35)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

This check is already done in github workflow. Also, when removed, this script (after env variables setup) would be better for manual usage (in scenario: push from local machine to user owned pmem.github.io fork).
</blockquote></details>

Done. Set "devel" dir for other branches.
___
*[`utils/docker/run-doc-update.sh` line 64 at r1](https://reviewable.io/reviews/pmem/pmemstream/239#-N6SJQcM-RfmNLTMmGNQ:-N6ScJR28NtJHudpICMF:bcgyv7x) ([raw file](https://github.com/pmem/pmemstream/blob/391a28cfb514f795d8272056417c50b1962f4b5b/utils/docker/run-doc-update.sh#L64)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

shallow clone?
</blockquote></details>

yes and no - origin can be shallow, but you just made me think, that we never fetch upstream

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/239)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[`utils/docker/run-doc-update.sh` line 35 at r2](https://reviewable.io/reviews/pmem/pmemstream/239#-N6gjDzuEm0IbieuW0-g:-N6gjDzuEm0IbieuW0-h:biadv81) ([raw file](https://github.com/pmem/pmemstream/blob/4eb14cb6fccc0760a2ca1ff3d772a47792089249/utils/docker/run-doc-update.sh#L35)):*
> ```Shell
> 
> # Determine docs location directory, based on the branch
> if [[ "${CI_BRANCH}" == "master" ]]; then
> ```

It may be simplified to 
```
if [[ ${CI_BRANCH} == stable-* ]]; then
	DOCS_TARGET_DIR=v$(echo ${CI_BRANCH} | cut -d"-" -f2 -s)
else 
         DOCS_TARGET_DIR=${CI_BRANCH}
fi
```

or even to 
```
DOCS_TARGET_DIR=$(echo ${CI_BRANCH} |  awk -F '-' '{print $(NF)}'
``` 
If you may skip `v` at the beginning 



_Code quote:_
```Shell
if [[ "${CI_BRANCH}" == "master" ]]; then
	DOCS_TARGET_DIR="master"
elif [[ ${CI_BRANCH} == stable-* ]]; then
	DOCS_TARGET_DIR=v$(echo ${CI_BRANCH} | cut -d"-" -f2 -s)
else
	DOCS_TARGET_DIR="devel"






fi
```

**Comment by karczex** [comment]
*[`utils/docker/run-doc-update.sh` line 35 at r2](https://reviewable.io/reviews/pmem/pmemstream/239#-N6gjDzuEm0IbieuW0-g:-N6gkQWU1n_sCYuf7XkO:b3qoda8) ([raw file](https://github.com/pmem/pmemstream/blob/4eb14cb6fccc0760a2ca1ff3d772a47792089249/utils/docker/run-doc-update.sh#L35)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It may be simplified to 
```
if [[ ${CI_BRANCH} == stable-* ]]; then
	DOCS_TARGET_DIR=v$(echo ${CI_BRANCH} | cut -d"-" -f2 -s)
else 
         DOCS_TARGET_DIR=${CI_BRANCH}
fi
```

or even to 
```
DOCS_TARGET_DIR=$(echo ${CI_BRANCH} |  awk -F '-' '{print $(NF)}'
``` 
If you may skip `v` at the beginning 

</blockquote></details>

with 
```
awk -F 'stable-' '/stable/{printf "v"} {print $(NF)}'
``` 
we may preserve `v`

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/239#-:-N6h42KsEafKN7-Owkof:bnfp4nl)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @igchor and @karczex)

**Pull request merged**
