### PR TITLE
Add coverage and Coverity GHA jobs

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemstream/8)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> Reviewed 9 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/8)* status: 9 of 13 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[utils/docker/0001-travis-fix-travisci_build_coverity_scan.sh.patch, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/8#-Mp73FlM80gutcM0sVMA:-Mp73FlM80gutcM0sVMB:b-qdi1sv) ([raw file](https://github.com/pmem/pmemstream/blob/61ee0d417189f186e5cb7e6e2ae97af89137dfd8/utils/docker/0001-travis-fix-travisci_build_coverity_scan.sh.patch#L4)):*
> ```Diff
> From: Lukasz Dorau <lukasz.dorau@intel.com>
> Date: Mon, 7 May 2018 12:05:40 +0200
> Subject: [PATCH] travis: fix travisci_build_coverity_scan.sh
> ```

Is this still needed?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/8)* status: 9 of 13 files reviewed, all discussions resolved (waiting on @igchor)

___
*[utils/docker/0001-travis-fix-travisci_build_coverity_scan.sh.patch, line 4 at r1](https://reviewable.io/reviews/pmem/pmemstream/8#-Mp73FlM80gutcM0sVMA:-Mp74tEF3NuXZO-7OvUj:b-ljsol9) ([raw file](https://github.com/pmem/pmemstream/blob/61ee0d417189f186e5cb7e6e2ae97af89137dfd8/utils/docker/0001-travis-fix-travisci_build_coverity_scan.sh.patch#L4)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Is this still needed?
</blockquote></details>

the script we download still looks the same, and we use this patch on other repos with success, so I'm afraid it's still required

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/8#-:-Mp790Q58P6uctpfX4D9:bnfp4nl)* status: 9 of 13 files reviewed, all discussions resolved (waiting on @igchor)

**Review by KFilipek — APPROVED** [review]
> Reviewed 10 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by karczex — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/8)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/docker/run-build.sh, line 51 at r1](https://reviewable.io/reviews/pmem/pmemstream/8#-MpAmQuJ1HtCDn_74CDy:-MpAmQuJ1HtCDn_74CDz:b-nyz5t6) ([raw file](https://github.com/pmem/pmemstream/blob/61ee0d417189f186e5cb7e6e2ae97af89137dfd8/utils/docker/run-build.sh#L51)):*
nit:

> ```
> 	if [ "${COVERAGE}" == "1" ]; then
> 		upload_codecov tests_clang_debug_cpp17
> 	fi
> ```

To get stuff more generic we probably should have wrapper script `run_coverage.sh` which handle coverage related stuff, and call `run_build.sh` underneath. As such, it may be separate build type in `build.sh`, which would be more consistent with rest of the build system. 

With little bit of ${@} magic `run_coverage.sh` may be very simple and even share help message with `run_build.sh`. 
 
___
*[utils/docker/images/download-scripts.sh, line 24 at r1](https://reviewable.io/reviews/pmem/pmemstream/8#-MpAtjPG5v9FB50GHX4l:-MpAtjPH6lNFSKN-lgyr:b-y0o9c4) ([raw file](https://github.com/pmem/pmemstream/blob/61ee0d417189f186e5cb7e6e2ae97af89137dfd8/utils/docker/images/download-scripts.sh#L24)):*


> ```
> https://github.com/codecov/codecov-bash
> ```

Nope. 

```
Deprecation Warning warning

On February 1, 2022, this uploader will be fully sunset and no longer function

We recommend all users migrate to the uploader to prevent any breakages in usage. You can learn more about our deprecation plan and the new uploader on our blog.
```

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/8)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[utils/docker/run-build.sh, line 51 at r1](https://reviewable.io/reviews/pmem/pmemstream/8#-MpAmQuJ1HtCDn_74CDy:-MpAzItq0nReNoukcO_n:bl26iyu) ([raw file](https://github.com/pmem/pmemstream/blob/61ee0d417189f186e5cb7e6e2ae97af89137dfd8/utils/docker/run-build.sh#L51)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

nit:

> ```
> 	if [ "${COVERAGE}" == "1" ]; then
> 		upload_codecov tests_clang_debug_cpp17
> 	fi
> ```

To get stuff more generic we probably should have wrapper script `run_coverage.sh` which handle coverage related stuff, and call `run_build.sh` underneath. As such, it may be separate build type in `build.sh`, which would be more consistent with rest of the build system. 

With little bit of ${@} magic `run_coverage.sh` may be very simple and even share help message with `run_build.sh`. 
 
</blockquote></details>

but the trick is, that we can run `COVERAGE=1` with any other type of build. We'll most likely run it with "debug" type, but e.g. in pmemkv we run two different coverage builds.

I'd leave it as-is now and we'll see how we'll use coverage build in this repo.
___
*[utils/docker/images/download-scripts.sh, line 24 at r1](https://reviewable.io/reviews/pmem/pmemstream/8#-MpAtjPG5v9FB50GHX4l:-MpB-Lm19s9oCnTuv77v:b-qfjqny) ([raw file](https://github.com/pmem/pmemstream/blob/61ee0d417189f186e5cb7e6e2ae97af89137dfd8/utils/docker/images/download-scripts.sh#L24)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>



> ```
> https://github.com/codecov/codecov-bash
> ```

Nope. 

```
Deprecation Warning warning

On February 1, 2022, this uploader will be fully sunset and no longer function

We recommend all users migrate to the uploader to prevent any breakages in usage. You can learn more about our deprecation plan and the new uploader on our blog.
```

</blockquote></details>

hah, good catch!
Nonetheless, on their readme file in the new suggested uploader, they say `This is a work in progress.` :smile: 

I'll file an issue for now. This way we'll wait until 1) the new uploader is polished and 2) we can make sure we didn't break anything in our coverage - while switching to the new uploader we still can use the old one (the one on this PR).

**Comment by karczex** [comment]
___
*[utils/docker/images/download-scripts.sh, line 24 at r1](https://reviewable.io/reviews/pmem/pmemstream/8#-MpAtjPG5v9FB50GHX4l:-MpB2Qos0bRJwJF05AsQ:b1cgl1m) ([raw file](https://github.com/pmem/pmemstream/blob/61ee0d417189f186e5cb7e6e2ae97af89137dfd8/utils/docker/images/download-scripts.sh#L24)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hah, good catch!
Nonetheless, on their readme file in the new suggested uploader, they say `This is a work in progress.` :smile: 

I'll file an issue for now. This way we'll wait until 1) the new uploader is polished and 2) we can make sure we didn't break anything in our coverage - while switching to the new uploader we still can use the old one (the one on this PR).


</blockquote></details>

3) Remove codecov for now, as we have very little test coverage and ongoing API refactors.

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemstream/8#-:-MpCDL9b0VclqKK_tZJ7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
